### ISSUE TITLE
[Bug]: FTB One - Server Crashes (World Gen Related)

### ISSUE THREAD

**Issue by AdamBundschuh** [FTBTeam/FTB-Modpack-Issues#1137]
### Modpack

FTB One

### Modpack version

1.30

### Log Files

https://pastebin.com/GJXkM8vG

### Describe the bug

This was a brand new server (hosted by CreeperHost). 

Server crashed multiple times within 10 minutes. Customer suppor said:

> Your server appears to have crashed due to a worldgen issue within Minecraft.
> 
> This may be caused by a mod.
> 
> I recommend reporting the issue to the Modpack author.
> 
> You can locate logs under the Files sub-menu in the 'screenlog.0' file, logs folder, or screenlogs folder.

### Steps to reproduce

I'm unsure of how to recreate, hopefully the log file has some helpful information.

### Expected behaviour

Stable server.

### Additional information

Thanks ahead of time!

**Comment by Raidobw2** [comment]
Looks like that maybe could be a bug from ItShallNotTick, on world gen indeed. Though unsure how that happened since it was apparently patched by Mojang https://bugs.mojang.com/browse/MC-249933
```
[Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.ReportedException: Accessing LegacyRandomSource from multiple threads
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:870) ~[server-1.19-20220607.102129-srg.jar%23258!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19-20220607.102129-srg.jar%23258!/:?] {re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19-20220607.102129-srg.jar%23258!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19-20220607.102129-srg.jar%23258!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:245) ~[server-1.19-20220607.102129-srg.jar%23258!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) [?:?] {}
Caused by: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
        at net.minecraft.util.ThreadingDetector.m_199417_(ThreadingDetector.java:84) ~[server-1.19-20220607.102129-srg.jar%23258!/:?] {re:classloading,pl:epic_rei_lmao:B}
        at net.minecraft.world.level.levelgen.LegacyRandomSource.m_64707_(LegacyRandomSource.java:49) ~[server-1.19-20220607.102129-srg.jar%23258!/:?] {re:classloading,pl:epic_rei_lmao:B}
        at net.minecraft.world.level.levelgen.BitRandomSource.m_188503_(BitRandomSource.java:33) ~[server-1.19-20220607.102129-srg.jar%23258!/:?] {re:classloading,pl:epic_rei_lmao:B}
        at net.minecraft.world.level.NaturalSpawner.m_47038_(NaturalSpawner.java:158) ~[server-1.19-20220607.102129-srg.jar%23258!/:?] {re:mixin,re:classloading,pl:epic_rei_lmao:B,pl:mixin:APP:itshallnottick.mixins.json:WorldEntitySpawnerOptimizationMixin,pl:mixin:A}
        at net.minecraft.world.level.NaturalSpawner.m_47045_(NaturalSpawner.java:127) ~[server-1.19-20220607.102129-srg.jar%23258!/:?] {re:mixin,re:classloading,pl:epic_rei_lmao:B,pl:mixin:APP:itshallnottick.mixins.json:WorldEntitySpawnerOptimizationMixin,pl:mixin:A}
        at net.minecraft.world.level.NaturalSpawner.m_47029_(NaturalSpawner.java:117) ~[server-1.19-20220607.102129-srg.jar%23258!/:?] {re:mixin,re:classloading,pl:epic_rei_lmao:B,pl:mixin:APP:itshallnottick.mixins.json:WorldEntitySpawnerOptimizationMixin,pl:mixin:A}
        at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:356) ~[server-1.19-20220607.102129-srg.jar%23258!/:?] {re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:310) ~[server-1.19-20220607.102129-srg.jar%23258!/:?] {re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:284) ~[server-1.19-20220607.102129-srg.jar%23258!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19-20220607.102129-srg.jar%23258!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        ... 5 more
```
```at net.minecraft.world.level.NaturalSpawner.m_47038_(NaturalSpawner.java:158) ~[server-1.19-20220607.102129-srg.jar%23258!/:?] {re:mixin,re:classloading,pl:epic_rei_lmao:B,pl:mixin:APP:itshallnottick.mixins.json:WorldEntitySpawnerOptimizationMixin,pl:mixin:A}```
The `WorldEntitySpawnerOptimizationMixin` mixin is present in the stacktrace when mentioning the spawners, from ISNT (ItShallNotTick), we'll investigate

**Comment by SeubertE** [comment]
Wanted to bump this issue and see if there was a fix. I'm experiencing something similar when players are exploring and thus generating a lot of chunks pretty quickly. Here are some logs:

[crash-2022-09-14_05.18.29-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9563091/crash-2022-09-14_05.18.29-server.txt)

[crash-2022-09-14_04.44.37-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9563096/crash-2022-09-14_04.44.37-server.txt)

**Comment by Raidobw2** [comment]
Actually this issue might be the same as https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1298.

What I wrote in https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1275#issuecomment-1241450918 should mitigate the crashes? Let me know if you do try it and thanks

**Comment by SeubertE** [comment]
You are absolutely right! Sorry, I didn't see there was a fix and that the issue was not a hardware issue in #1275. I'll update if it crashes again after the fix!

Thanks! You can close this ticket and merge it with #1275 I think!
