### ISSUE TITLE
[Bug]: Cyclic Fishing Block not working

### ISSUE THREAD

**Issue by Chocorean** [FTBTeam/FTB-Modpack-Issues#1252]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.9.0

### Log Files

https://drive.proton.me/urls/E8BJ176NKC#UuhAGuJNslkk
Password: ftb_rocks_!

### Describe the bug

Just noticed this block is not working; Took a look at the logs and noticed something's wrong with bloodmagic loot tables ?

Useful piece of logs:

```plain
[10Aug2022 21:41:30.161] [Server thread/ERROR] [com.lothrazar.cyclic.ModCyclic/]: Fishing Block: Loot table failed
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.state.BlockState.m_60734_()" because the return value of "net.minecraft.world.level.storage.loot.LootContext.m_78953_(net.minecraft.world.level.storage.loot.parameters.LootContextParam)" is null
	at wayoftime.bloodmagic.loot.GlobalLootModifier$VoidingModifier.doApply(GlobalLootModifier.java:319) ~[BloodMagic-1.18.2-3.2.4-39.jar%2380!/:1.18.2-3.2.4-39]
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:39) ~[forge-1.18.2-40.1.69-universal.jar%23330!/:?]
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1244) ~[forge-1.18.2-40.1.69-universal.jar%23330!/:?]
	at net.minecraft.world.level.storage.loot.LootTable.m_79129_(LootTable.java:89) ~[client-1.18.2-20220404.173914-srg.jar%23325!/:?]
	at com.lothrazar.cyclic.block.fishing.TileFisher.doFishing(TileFisher.java:151) ~[Cyclic-1.18.2-1.7.6.jar%23123!/:1.18.2-1.7.6]
	at com.lothrazar.cyclic.block.fishing.TileFisher.tick(TileFisher.java:119) ~[Cyclic-1.18.2-1.7.6.jar%23123!/:1.18.2-1.7.6]
	at com.lothrazar.cyclic.block.fishing.TileFisher.serverTick(TileFisher.java:63) ~[Cyclic-1.18.2-1.7.6.jar%23123!/:1.18.2-1.7.6]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[client-1.18.2-20220404.173914-srg.jar%23325!/:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[client-1.18.2-20220404.173914-srg.jar%23325!/:?]
	at net.minecraft.world.level.Level.m_46463_(Level.java:476) ~[client-1.18.2-20220404.173914-srg.jar%23325!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:327) ~[client-1.18.2-20220404.173914-srg.jar%23325!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%23325!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%23325!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23325!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23325!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23325!/:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

### Steps to reproduce

1. Craft a Fishing Block
2. Craft a vanilla Fishing  Rod
3. Place the Fishing Block and put the rod inside
4. Wait and notice the logs

### Expected behaviour

Spawn fish I guess ?

**Comment by Chocorean** [comment]
It also breaks vanilla fishing as a side effect

**Comment by TheonlyTazz** [comment]
Updating Bloodmagic will fix this issue, Bloodmagic got updated a few hours after we released our v1.9.0
I'll make sure to add this in our 1.9.1 hotfix

**Comment by Chocorean** [comment]
That's awesome, thank for very much!

**Comment by TheonlyTazz** [comment]
That is because the vanilla loot table got borked by blood magic....

This will be fixed by updating blood magic, or wait till the hotfix is up
