### ISSUE TITLE
[Bug]: Loot Crate Opener and Translocators Freeze

### ISSUE THREAD

**Issue by AxelTheModder** [FTBTeam/FTB-Modpack-Issues#1469]
### Modpack

FTB Sky Odyssey

### Modpack version

1.4.1

### Describe the bug

Loot crate openers freeze a world when you try to link it with a storage block using translocators

### Steps to reproduce

1. Place a storage block
2. Place a loot crate opener
3. (Optional) Place another storage block as output
4. Place translocators on all blocks (storage block) to loot crate opener) then use glowstone on input translocators
5. Add loot crates on the storage block
6. Click on translocator on loot crate opener

### Expected behaviour

Loot crate openers should open crates when using translocators with glowstone

### Screenshots

https://user-images.githubusercontent.com/80662822/196914976-a910b676-da7b-44b6-b301-75a503b0c373.mp4

**Comment by Raidobw2** [comment]
I'd recommend using a hopper on top and a hopper on the bottom. Chests above and below as well. If your input of loot crate is very high, load balance it through multiple of these setups.

It seems like Translocators (even without glowstone) will cause the world to lock in place until closed externally. I don't know how to solve this or work around it and I'll likely require help from a mod developer at FTB, if this is meant to be fixed (unsure if 1.12.2 development is still something we will be looking into). As of now the only good solution is to not use Translocators for this task.

Here's a jstack of the locked process, this is for me to check for later:
```
"Server thread" #436 prio=5 os_prio=0 tid=0x000001d8369af000 nid=0x3630 runnable [0x000000ab1e5fe000]
   java.lang.Thread.State: RUNNABLE
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
        at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:691)
        at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:673)
        at net.minecraft.item.ItemStack.forgeInit(ItemStack.java:1217)
        at net.minecraft.item.ItemStack.<init>(ItemStack.java:112)
        at net.minecraft.item.ItemStack.func_77946_l(ItemStack.java:396)
        at net.minecraftforge.items.ItemHandlerHelper.copyStackWithSize(ItemHandlerHelper.java:92)
        at com.feed_the_beast.ftbquests.quest.reward.ItemReward.automatedClaimPre(ItemReward.java:159)
        at com.feed_the_beast.ftbquests.tile.TileLootCrateOpener.insertItem(TileLootCrateOpener.java:146)
        at codechicken.lib.inventory.InventoryUtils.canInsertStack(InventoryUtils.java:359)
        at codechicken.lib.inventory.InventoryUtils.getInsertableQuantity(InventoryUtils.java:413)
        at codechicken.translocators.part.ItemTranslocatorPart.getInsertableAmount(ItemTranslocatorPart.java:313)
        at codechicken.translocators.part.ItemTranslocatorPart.getInsertableAmount(ItemTranslocatorPart.java:299)
        at codechicken.translocators.part.ItemTranslocatorPart.func_73660_a(ItemTranslocatorPart.java:124)
        at codechicken.multipart.scalatraits.TTickableTile$class.update(TTickableTile.scala:58)
        at codechicken.multipart.scalatraits.JTickableTile$class.func_73660_a(TTickableTile.scala:95)
        at TileMultipart_cmp$$0.func_73660_a(Unknown Source)
        at net.minecraft.world.World.func_72939_s(World.java:1838)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)


"Client thread" #1 prio=5 os_prio=0 tid=0x000001d869510800 nid=0x3930 runnable [0x000000ab191fe000]
   java.lang.Thread.State: RUNNABLE
        at codechicken.lib.render.CCRenderState.render(CCRenderState.java:168)
        at codechicken.lib.render.CCModel.render(CCModel.java:460)
        at codechicken.lib.render.CCModel.render(CCModel.java:448)
        at com.brandon3055.draconicevolution.client.render.tile.RenderTileReactorCore.renderCore(RenderTileReactorCore.java:163)
        at com.brandon3055.draconicevolution.client.render.tile.RenderTileReactorCore.renderItem(RenderTileReactorCore.java:123)
        at com.brandon3055.draconicevolution.client.render.item.RenderItemReactorComponent.renderItem(RenderItemReactorComponent.java:56)
        at codechicken.lib.render.item.CCRenderItem.func_180454_a(CCRenderItem.java:207)
        at codechicken.lib.render.item.CCRenderItem.func_191962_a(CCRenderItem.java:270)
        at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:337)
        at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:30)
        at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:23)
        at mezz.jei.render.IngredientRenderer.renderSlow(IngredientRenderer.java:69)
        at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:189)
        at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:99)
        at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:97)
        at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:161)
        at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:72)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2494_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
        at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:575)
        at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:615)
        at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
        at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
        at net.minecraft.client.main.Main.main(SourceFile:123)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
