### ISSUE TITLE
[Bug]: Apotheosis enchantmen libraryan filter crash the game "FTB Inferno" 

### ISSUE THREAD

**Issue by Yasserfate** [FTBTeam/FTB-Modpack-Issues#1639]
### Modpack

Inferno

### Modpack version

Apotheosis-1.18.2-5.7.6.jar%2359!/:5.7.6

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9941847/latest.log)
[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9941849/console.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9941848/debug.log)

[04Nov2022 14:29:48.727] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[04Nov2022 14:29:48.733] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[04Nov2022 14:29:48.848] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Roaroftime10 lost connection: Disconnected
[04Nov2022 14:29:48.848] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Roaroftime10 left the game
[04Nov2022 14:29:48.945] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Stopping singleplayer server as player logged out

[04Nov2022 14:29:48.945] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[04Nov2022 14:29:49.861] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[firestream]'/minecraft:overworld
[04Nov2022 14:29:49.942] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[firestream]'/minecraft:the_end
[04Nov2022 14:29:49.951] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[firestream]'/ae2:spatial_storage
[04Nov2022 14:29:49.960] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[firestream]'/bonsaitrees3:growtown
[04Nov2022 14:29:49.970] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[firestream]'/minecraft:the_nether
[04Nov2022 14:29:50.050] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[firestream]'/witherstormmod:bowels
[04Nov2022 14:29:50.058] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[firestream]'/bloodmagic:dungeon
[04Nov2022 14:29:50.140] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (firestream): All chunks are saved
[04Nov2022 14:29:50.140] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[04Nov2022 14:29:50.140] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (spatial_storage): All chunks are saved
[04Nov2022 14:29:50.140] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (growtown): All chunks are saved
[04Nov2022 14:29:50.140] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[04Nov2022 14:29:50.140] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (bowels): All chunks are saved
[04Nov2022 14:29:50.140] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (dungeon): All chunks are saved
[04Nov2022 14:29:50.140] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage: All dimensions are saved
[04Nov2022 14:29:54.020] [Server thread/INFO] [net.creeperhost.ftbbackups.org.quartz.core.QuartzScheduler/]: Scheduler ftbbackups2_$_NON_CLUSTERED shutting down.
[04Nov2022 14:29:54.020] [Server thread/INFO] [net.creeperhost.ftbbackups.org.quartz.core.QuartzScheduler/]: Scheduler ftbbackups2_$_NON_CLUSTERED paused.
[04Nov2022 14:29:54.020] [Server thread/INFO] [net.creeperhost.ftbbackups.org.quartz.core.QuartzScheduler/]: Scheduler ftbbackups2_$_NON_CLUSTERED shutdown complete.
[04Nov2022 14:29:54.030] [Server thread/INFO] [configured/]: Unloading server configs...
[04Nov2022 14:29:54.064] [Render thread/INFO] [FluxNetworks/]: Released client Flux Networks cache
[04Nov2022 14:29:54.064] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggedOutEvent
[04Nov2022 14:29:54.064] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver transitioning state from JEI_STARTED to DISABLED
[04Nov2022 14:29:54.064] [Render thread/INFO] [mezz.jei.forge.startup.ClientLifecycleHandler/]: Stopping JEI
[04Nov2022 14:29:54.068] [Sound engine/ERROR] [com.mojang.blaze3d.audio.OpenAlUtil/]: Stop: Invalid name parameter.
[04Nov2022 14:29:54.081] [Render thread/INFO] [minecolonies/]: Removed all colony views
[04Nov2022 14:29:54.091] [Render thread/INFO] [ChunkBuilder/]: Stopping worker threads
[04Nov2022 14:29:54.119] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: Container click
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:535) ~[client-1.18.2-20220404.173914-srg.jar%23311!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:93) ~[client-1.18.2-20220404.173914-srg.jar%23311!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.18.2-20220404.173914-srg.jar%23311!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.18.2-20220404.173914-srg.jar%23311!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.18.2-20220404.173914-srg.jar%23311!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar%2348!/:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%2344!/:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar%2348!/:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.18.2-20220404.173914-srg.jar%23311!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:333) ~[client-1.18.2-20220404.173914-srg.jar%23311!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1068) ~[client-1.18.2-20220404.173914-srg.jar%23311!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23311!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23311!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.80.jar%2317!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.enchantment.EnchantmentCategory.m_7454_(net.minecraft.world.item.Item)" because "enchantment.f_44672_" is null
	at net.minecraftforge.common.extensions.IForgeItem.canApplyAtEnchantingTable(IForgeItem.java:522) ~[forge-1.18.2-40.1.80-universal.jar%23316!/:?]
	at net.minecraftforge.common.extensions.IForgeItemStack.canApplyAtEnchantingTable(IForgeItemStack.java:159) ~[forge-1.18.2-40.1.80-universal.jar%23316!/:?]
	at shadows.apotheosis.ench.library.EnchLibraryScreen.isAllowedByItem(EnchLibraryScreen.java:240) ~[Apotheosis-1.18.2-5.7.6.jar%2359!/:5.7.6]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(Unknown Source) ~[?:?]
	at shadows.apotheosis.ench.library.EnchLibraryScreen.filter(EnchLibraryScreen.java:235) ~[Apotheosis-1.18.2-5.7.6.jar%2359!/:5.7.6]
	at shadows.apotheosis.ench.library.EnchLibraryScreen.containerChanged(EnchLibraryScreen.java:222) ~[Apotheosis-1.18.2-5.7.6.jar%2359!/:5.7.6]
	at shadows.apotheosis.ench.library.EnchLibraryContainer.onChanged(EnchLibraryContainer.java:125) ~[Apotheosis-1.18.2-5.7.6.jar%2359!/:5.7.6]
	at shadows.apotheosis.ench.library.EnchLibraryContainer$3.m_6654_(EnchLibraryContainer.java:87) ~[Apotheosis-1.18.2-5.7.6.jar%2359!/:5.7.6]
	at net.minecraft.world.inventory.Slot.m_5852_(Slot.java:60) ~[client-1.18.2-20220404.173914-srg.jar%23311!/:?]
	at net.minecraft.world.inventory.Slot.m_150656_(Slot.java:161) ~[client-1.18.2-20220404.173914-srg.jar%23311!/:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.m_150430_(AbstractContainerMenu.java:410) ~[client-1.18.2-20220404.173914-srg.jar%23311!/:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.m_150399_(AbstractContainerMenu.java:295) ~[client-1.18.2-20220404.173914-srg.jar%23311!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_171799_(MultiPlayerGameMode.java:392) ~[client-1.18.2-20220404.173914-srg.jar%23311!/:?]
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6597_(AbstractContainerScreen.java:550) ~[client-1.18.2-20220404.173914-srg.jar%23311!/:?]
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6348_(AbstractContainerScreen.java:520) ~[client-1.18.2-20220404.173914-srg.jar%23311!/:?]
	at net.minecraft.client.MouseHandler.m_168078_(MouseHandler.java:96) ~[client-1.18.2-20220404.173914-srg.jar%23311!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:528) ~[client-1.18.2-20220404.173914-srg.jar%23311!/:?]
	... 25 more
[04Nov2022 14:29:54.136] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 3b65d680-2146-4efb-90b4-627273434ec5
[04Nov2022 14:29:54.141] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID caa35396-0caf-4d47-b531-6824385c8e87
[04Nov2022 14:29:55.038] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 05b74dd2-0152-4f65-a88d-61c592d7d593
[04Nov2022 14:29:55.039] [Thread-22/INFO] [net.creeperhost.minetogether.MineTogetherCommon/]: Shutdown called, Stopping our threads
[04Nov2022 14:29:55.040] [Thread-22/ERROR] [net.creeperhost.minetogether.lib.chat.irc.IrcHandler/]: Socket error, Attempt stuff and things
[04Nov2022 14:29:55.040] [Thread-22/INFO] [net.creeperhost.minetogether.lib.chat.irc.IrcHandler/]: Stopping Reconnection thread
[04Nov2022 14:29:55.040] [Thread-22/INFO] [net.creeperhost.minetogether.lib.chat.irc.IrcHandler/]: Stopping IRC Socket
[04Nov2022 14:29:55.040] [Thread-22/ERROR] [net.creeperhost.minetogether.lib.chat.irc.IrcHandler/]: Socket is already null
[04Nov2022 14:29:55.040] [Thread-22/INFO] [net.creeperhost.minetogether.lib.chat.irc.IrcHandler/]: Force quitting chat thread

### Describe the bug

Using the "item" filter in the block that let you store all the enchantments, crash the game. even with vanilla items

### Steps to reproduce

1.- Put a "armor/weapon" item in your inventory
2.- Open Enchantment library's GUI
3.- Drop the listed Item into the "filter" slot
4.- Game crash and start saving your world and finally close at all

### Expected behaviour

The GUI show you the supported enchantments for the item you "filtered" for example smite for an iron sword

### Screenshots

![2022-11-04_14 56 10](https://user-images.githubusercontent.com/117484128/200073245-b856f7e0-df72-46d3-a75d-e81de64e7959.png)
![2022-11-04_14 56 27](https://user-images.githubusercontent.com/117484128/200073247-056a6ad0-73be-42dc-a1c4-160b0075cb20.png)

### Additional information

didnt try with the upgraded version "library of alexandría"
Even Vanilla items proc the crash.
Bug trugh almos all the modpack version. 
Modpack versión bug submition: 1.2.1

**Comment by Saereth** [comment]
Im speaking with shadows about this issue, will follwup when I know more

**Comment by orbidlo** [comment]
I think thr problem here is shift+click to put inside. When I just drag something there it's ok.
