### ISSUE TITLE
[Bug]: Crash when crafting framed drawers with some blocks

### ISSUE THREAD

**Issue by DarkBladeNemo** [FTBTeam/FTB-Modpack-Issues#1667]
### Modpack

Stoneblock 3

### Modpack version

1.0.2

### Log Files

[crash-2022-11-05_23.12.36-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9944791/crash-2022-11-05_23.12.36-client.txt)

### Describe the bug

The game crashes when trying to craft Framed compacting drawer with Stripped dark oak and stripped spruce. Also crashes when using some chipped blocks.

### Steps to reproduce

1. Craft Framed compacting drawer
2. Add stripped dark oak, stripped spruce and framed compacting drawer in crafting table.
3. cry

### Expected behaviour

Game crashes

**Comment by Sunekaer** [comment]
https://github.com/Buuz135/FunctionalStorage/issues/113

**Comment by tylerl** [comment]
This bug -- or a variant on this bug -- appears to be trivially reproducible with functionalstorage 1.0.7 (Stoneblock 3 1.4.1).  

Successfully (unexpectedly) reproduced this crash with `functionalstorage-1.18.2-1.0.7` as follows:

* Craft a framed compacting drawer
* Place in a crafting grid with stone block and gold block first (OK so far)
* Accidentally replace the gold block in the grid with a cobblestone slab.
* _Profit!!_  (...er... crash)

Crafting grid on crash:
```
S B D
- - -
- - -

S: Cobblestone Slab
B: Stone Block
D: Framed Compacting Drawer
-: Empty
```

The most important details of the stack trace remain unchanged as reported above -- the model has a *null* side.  Here's mine:

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.core.Direction.m_122421_()" because "side" is null
	at com.buuz135.functionalstorage.client.loader.FramedModel$Baked.getMinMaxPosition(FramedModel.java:228) ~[functionalstorage-1.18.2-1.0.7.jar%23142!/:1.18.2-1.0.7] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.buuz135.functionalstorage.client.loader.FramedModel$Baked.getSpriteData(FramedModel.java:203) ~[functionalstorage-1.18.2-1.0.7.jar%23142!/:1.18.2-1.0.7] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.buuz135.functionalstorage.client.loader.FramedModel$Baked.getQuadsUsingShape(FramedModel.java:183) ~[functionalstorage-1.18.2-1.0.7.jar%23142!/:1.18.2-1.0.7] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.buuz135.functionalstorage.client.loader.FramedModel$ItemModel.getQuads(FramedModel.java:582) ~[functionalstorage-1.18.2-1.0.7.jar%23142!/:1.18.2-1.0.7] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraftforge.client.model.data.IDynamicBakedModel.m_6840_(IDynamicBakedModel.java:27) ~[forge-1.18.2-40.1.84-universal.jar%23280!/:?] {re:classloading,pl:rei_plugin_compatibilities:B,re:mixin}

... etc.
```
