### ISSUE TITLE
[Bug]: Modpack crashes on launch.

### ISSUE THREAD

**Issue by Onikage056** [FTBTeam/FTB-Modpack-Issues#1716]
### Modpack

FTB Stoneblock 3

### Modpack version

1.1.0

### Log Files

[Stoneblock 3 crash log.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9948086/Stoneblock.3.crash.log.txt)

### Describe the bug

Admittedly, I had installed some extra mods, but the modpack simply fails to start at all.

### Steps to reproduce

1. Start FTB Stoneblock 3
2. Crashes without starting Minecraft.

### Expected behaviour

Stoneblock starts.

**Comment by Raidobw2** [comment]
For @Onikage056, have you tried using the FTB App and no additional mods? Did that work? This is present in the log you sent, can you check if you sent the Minecraft log/crash log and not the launcher log? Thanks `[06/11/2022 23:12:42 PM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.`

For @YuGnad, first try clearing the cache in the FTB App and reinstalling the modpack. That's done by clicking settings at the left, app info, refresh cache
![image](https://user-images.githubusercontent.com/17010632/200459964-f3316145-9fd6-4c84-9a69-80857d743a3d.png)
Once that's done before starting the pack put `-Duser.language=en -Duser.country=US` in your additional java arguments, then start it.
Let me know if that works

------

### For both of you, posting logs after those steps will help me further if the issue persists

**Comment by Onikage056** [comment]
> For @Onikage056, have you tried using the FTB App and no additional mods? Did that work? This is present in the log you sent, can you check if you sent the Minecraft log/crash log and not the launcher log? Thanks `[06/11/2022 23:12:42 PM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.`
> 
> For @YuGnad, first try clearing the cache in the FTB App and reinstalling the modpack. That's done by clicking settings at the left, app info, refresh cache ![image](https://user-images.githubusercontent.com/17010632/200459964-f3316145-9fd6-4c84-9a69-80857d743a3d.png) Once that's done before starting the pack put `-Duser.language=en -Duser.country=US` in your additional java arguments, then start it. Let me know if that works
> 
> ### For both of you, posting logs after those steps will help me further if the issue persists

I posted my issue with the AT Launcher due to the fact I literally cannot even install it using FTB App. I get a Fatal Exception error when I try, as posted by Danydew here: https://github.com/FTBTeam/FTB-App/issues/725

**Comment by Raidobw2** [comment]
In that case swing by the FTB Discord and use the debug tool in the ftb-app-support channel. It'll give you a code you can post there. You can ping me (`@R3GEN`) with it and I'll answer as soon as I'm available. Same goes for YuGnad if it's the same issue

Most of the times I've seen it's one of these things:

> - A VPN is active, or Hamachi is installed
> - The computer's firewall is blocking websites
> - Some antivirus controls the firewall and blocks websites
> - Your hosts file contains unwanted redirections (`c:\Windows\System32\Drivers\etc\hosts`)
> - The local DNS cache is broken somehow (type `ipconfig /flushdns` in a command prompt to flush & empty it)
> - The router requires a restart

**Comment by Raidobw2** [comment]
@YuhGnad Looks like Mojang is having issues for a while now, and from what I've tested and seen it's affecting launching the game and servers (even private ones or local ones on StoneBlock 3)
https://twitter.com/MojangStatus/status/1589822938995621888
I suggest waiting and trying again later for the FTB App, I can't launch modpacks either.
An offline mode for the app is planned eventually, but it's for after other bugs have been fixed.

If you really want to launch the game, using the stock MC Launcher with Forge installed probably would work in offline mode and singleplayer, right now with the FTB App it's not possible. The CurseForge App can help launching with the official MC launcher if you want to copy files there as well.

**Comment by Raidobw2** [comment]
@Onikage056 I've taken a look at the debug code you posted and one error is apparent:
```
[22:40:04] [main/ERROR] [net.creeperhost.creeperlauncher.Instances]: Failed to load instance: C:\Users\%username%\AppData\Local\.ftba\instances\e902ef42-91b7-4514-a3bd-66339e4c1c79\instance.json
java.lang.NumberFormatException: For input string: "1920`"
	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:?]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:?]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:?]
	at net.creeperhost.creeperlauncher.pack.LocalInstance.<init>(LocalInstance.java:86) ~[launcher-202211021238-4322c4d8d1-release-all.jar:?]
	at net.creeperhost.creeperlauncher.Instances.loadInstance(Instances.java:100) ~[launcher-202211021238-4322c4d8d1-release-all.jar:202211021238-4322c4d8d1-release]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.Nodes$CollectorTask.doLeaf(Unknown Source) ~[?:?]
	at java.util.stream.Nodes$CollectorTask.doLeaf(Unknown Source) ~[?:?]
	at java.util.stream.AbstractTask.compute(Unknown Source) ~[?:?]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[?:?]
	at java.util.stream.Nodes.collect(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.evaluateToNode(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(Unknown Source) ~[?:?]
	at net.creeperhost.creeperlauncher.Instances.refreshInstances(Instances.java:64) ~[launcher-202211021238-4322c4d8d1-release-all.jar:202211021238-4322c4d8d1-release]
	at net.creeperhost.creeperlauncher.CreeperLauncher.main(CreeperLauncher.java:130) ~[launcher-202211021238-4322c4d8d1-release-all.jar:202211021238-4322c4d8d1-release]
```

If you open the file `C:\Users\%username%\AppData\Local\.ftba\instances\e902ef42-91b7-4514-a3bd-66339e4c1c79\instance.json` and search for "1920`", I believe you might find it. Try removing that backtick and saving the file.

As mentioned to YuhGnad before about the FTB App though, you're bound to run into the same problem, so you will have to wait as well until Mojang can fix this, or move your instance to the stock MC Launcher / CurseForge App.
