### ISSUE TITLE
[Bug]: Ritual of Mother Silverfish crashes the game

### ISSUE THREAD

**Issue by SnowTimex** [FTBTeam/FTB-Modpack-Issues#1728]
### Modpack

Stoneblock 3

### Modpack version

1.0.2

### Log Files

```
07Nov2022 09:18:40.307] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking block entity
    at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:906) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?]
    at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?]
    at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?]
    at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?]
    at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?]
    at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoSuchMethodError: 'double java.util.Random.nextDouble(double, double)'
    at com.almostreliable.summoningrituals.recipe.component.RecipeOutputs$RecipeOutput.getRandomPos(RecipeOutputs.java:201) ~[summoningrituals-1.18.2-1.1.6.jar%23221!/:1.18.2-1.1.6]
    at com.almostreliable.summoningrituals.recipe.component.RecipeOutputs$MobOutput.spawn(RecipeOutputs.java:324) ~[summoningrituals-1.18.2-1.1.6.jar%23221!/:1.18.2-1.1.6]
    at com.almostreliable.summoningrituals.recipe.component.RecipeOutputs.handleRecipe(RecipeOutputs.java:83) ~[summoningrituals-1.18.2-1.1.6.jar%23221!/:1.18.2-1.1.6]
    at com.almostreliable.summoningrituals.altar.AltarEntity.tick(AltarEntity.java:160) ~[summoningrituals-1.18.2-1.1.6.jar%23221!/:1.18.2-1.1.6]
    at com.almostreliable.summoningrituals.altar.AltarBlock.lambda$getTicker$1(AltarBlock.java:86) ~[summoningrituals-1.18.2-1.1.6.jar%23221!/:1.18.2-1.1.6]
    ... 5 more
```

### Describe the bug

Ritual of Mother Silverfish crashes the Server

### Steps to reproduce

1.Put the items on the Altar 
2.Game Crashes before spawning the Mother Silverfish

### Expected behaviour

The Mother Silverfish should Spawn

**Comment by Sunekaer** [comment]
https://github.com/AlmostReliable/summoningrituals-forge/issues/9

**Comment by SnowTimex** [comment]
The Summon works in Singleplayer but not on the Multiplayer Server
