### ISSUE TITLE
[Bug]: Server wont start

### ISSUE THREAD

**Issue by itsjusttriz** [FTBTeam/FTB-Modpack-Issues#2116]
### Modpack

FTB Stoneblock 3

### Modpack version

1.4.0

### Log Files

```
[24Nov2022 20:20:04.924] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 40.1.84, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
[24Nov2022 20:20:04.930] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.1 by Oracle Corporation
[24Nov2022 20:20:05.043] [main/ERROR] [net.minecraftforge.fml.loading.ModDirTransformerDiscoverer/]: Zip Error when loading jar file /home/smpicnic/server/data/mods/ftb-stoneblock-companion-0.6.6+mc1.18.2.jar
java.util.zip.ZipException: zip END header not found
	at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469) ~[?:?]
	at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477) ~[?:?]
	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1277) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:243) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:172) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:186) ~[?:?]
	at net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.visitFile(ModDirTransformerDiscoverer.java:51) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:1.0]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.scan(ModDirTransformerDiscoverer.java:41) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:1.0]
	at net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.candidates(ModDirTransformerDiscoverer.java:24) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:1.0]
	at cpw.mods.modlauncher.serviceapi.ITransformerDiscoveryService.candidates(ITransformerDiscoveryService.java:48) ~[modlauncher-9.1.3.jar%235!/:9.1.3+9.1.3+main.9b69c82a]
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$discoverServices$14(TransformationServicesHandler.java:123) ~[modlauncher-9.1.3.jar%235!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) [?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) [?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) [?:?]
	at java.util.ServiceLoader$ProviderSpliterator.tryAdvance(ServiceLoader.java:1499) [?:?]
	at java.util.Spliterator.forEachRemaining(Spliterator.java:332) [?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) [?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) [?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) [?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) [?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) [?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) [?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) [?:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:125) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:86) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
[24Nov2022 20:20:05.273] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/smpicnic/server/data/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=SERVER
```

### Describe the bug

Server just wont start. Reinstalled and all. No proper crash log.

### Steps to reproduce

Load onto server.

### Expected behaviour

To work

### Additional information

Using serverminer.com as my server host. How they handle serverfiles, i dont know. I just used their one-click installer.

**Comment by manmaed** [comment]
dose this still happen on 1.4.1?

**Comment by itsjusttriz** [comment]
@manmaed Yes.

**Comment by itsjusttriz** [comment]
@manmaed any ideas i could try? I was thinking i could maybe install server files manually from the ftbapp, but then again i dont know how my host handles server files, so i wouldnt know if a start.sh would work, or even how to trigger it.

**Comment by itsjusttriz** [comment]
reverted back to 1.3.0 and it loaded perfectly. Guess i gotta stick with the FTBBackups issue for a bit longer xD

**Comment by itsjusttriz** [comment]
This has been fixed with the help of `@ukmcplyr#9736` in the FTB discord. They went through the byte-to-byte data of all the mods that were on my server, and had noticed that the ftb-stoneblock-companion's byte data was sus. So i copypasta'd the same mod jar from my client-side instance, and the server booted immediately.
