### ISSUE TITLE
Stoneblock 3 crashes on load

### ISSUE THREAD

**Issue by maksann69** [FTBTeam/FTB-Modpack-Issues#2228]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.2

### Log Files
<details>

<summary>Crash log</summary>

```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 12/3/22, 5:16 PM
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraftforge/resource/ResourceCacheManager
	at net.minecraft.server.packs.VanillaPackResources.<init>(VanillaPackResources.java:505) ~[client-1.18.2-20220404.173914-srg.jar%23275!/:?] {re:mixin,xf:OptiFine:default,re:classloading,pl:epic_rei_lmao:B,xf:OptiFine:default}
	at net.minecraft.client.resources.DefaultClientPackResources.<init>(DefaultClientPackResources.java:20) ~[client-1.18.2-20220404.173914-srg.jar%23275!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at net.minecraft.client.resources.ClientPackSource.<init>(ClientPackSource.java:77) ~[client-1.18.2-20220404.173914-srg.jar%23275!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:396) ~[client-1.18.2-20220404.173914-srg.jar%23275!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:traylauncher:loadingHookCoremod,pl:runtimedistcleaner:A,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,xf:fml:traylauncher:loadingHookCoremod,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:tklib.mixin.json:client.MinecraftMixin,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorMinecraft,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:mixin.dynamic_asset_generator.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.18.2-20220404.173914-srg.jar%23275!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.resource.ResourceCacheManager
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:138) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
	... 18 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.server.packs.VanillaPackResources.<init>(VanillaPackResources.java:505) ~[client-1.18.2-20220404.173914-srg.jar%23275!/:?] {re:mixin,xf:OptiFine:default,re:classloading,pl:epic_rei_lmao:B,xf:OptiFine:default}
	at net.minecraft.client.resources.DefaultClientPackResources.<init>(DefaultClientPackResources.java:20) ~[client-1.18.2-20220404.173914-srg.jar%23275!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at net.minecraft.client.resources.ClientPackSource.<init>(ClientPackSource.java:77) ~[client-1.18.2-20220404.173914-srg.jar%23275!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:396) ~[client-1.18.2-20220404.173914-srg.jar%23275!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:traylauncher:loadingHookCoremod,pl:runtimedistcleaner:A,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,xf:fml:traylauncher:loadingHookCoremod,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:tklib.mixin.json:client.MinecraftMixin,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorMinecraft,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:mixin.dynamic_asset_generator.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Расширенная библиотека API Windows 32:10.0.18362.2339 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:Библиотека элементов управления взаимодействия с пользователем:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.18362.1 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.18362.1 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:Динамическая библиотека API DNS-клиента:10.0.18362.2339 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.18362.1 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.18362.387 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:API вспомогательного приложения IP:10.0.18362.2339 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Библиотека клиента Windows NT BASE API:10.0.18362.329 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Библиотека клиента Windows NT BASE API:10.0.18362.329 (WinBuild.160101.0800):Microsoft Corporation
		NLAapi.dll:Network Location Awareness 2:10.0.18362.387 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.18362.449 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE для Windows:10.0.18362.1 (WinBuild.160101.0800):Microsoft Corporation
		OleAut32.dll:OLEAUT32.DLL:10.0.18362.535 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.18362.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Модуль поддержки данных производительности Windows:10.0.18362.2339 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Библиотека удаленного вызова процедур:10.0.18362.2339 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Общая библиотека оболочки Windows:10.0.18362.1 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll
		USER32.dll:Многопользовательская библиотека клиента USER API Windows:10.0.18362.2339 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.18362.2339 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.27.29016.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.18362.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Службы HTTP Windows:10.0.18362.2339 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.18362.2339 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:32-разрядная библиотека Windows Socket 2.0:10.0.18362.1 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.18362.2339 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.18362.1 (WinBuild.160101.0800):Microsoft Corporation
		aswAMSI.dll:AVG AMSI COM object:22.10.7633.0:AVG Technologies CZ, s.r.o.
		aswhook.dll:AVG Hook Library:22.10.7633.0:AVG Technologies CZ, s.r.o.
		bcrypt.dll:Библиотека криптографических примитивов Windows:10.0.18362.2339 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.18362.295 (WinBuild.160101.0800):Microsoft Corporation
		cfgmgr32.dll:Configuration Manager DLL:10.0.18362.387 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM для Windows:10.0.18362.1 (WinBuild.160101.0800):Microsoft Corporation
		cryptsp.dll:Cryptographic Service Provider API:10.0.18362.1 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.18362.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:Служба DHCP-клиента:10.0.18362.2339 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:Клиент DHCPv6:10.0.18362.2339 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:API пользовательского режима FWP/IPsec:10.0.18362.2339 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.18362.535 (WinBuild.160101.0800):Microsoft Corporation
		instrument.dll:OpenJDK Platform binary:17.0.2.0:Eclipse Adoptium
		java.dll:OpenJDK Platform binary:17.0.2.0:Eclipse Adoptium
		javaw.exe:OpenJDK Platform binary:17.0.2.0:Eclipse Adoptium
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:17.0.2.0:Eclipse Adoptium
		jli.dll:OpenJDK Platform binary:17.0.2.0:Eclipse Adoptium
		jna7027995222854676802.dll:JNA native library:6.1.2:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:17.0.2.0:Eclipse Adoptium
		jvm.dll:OpenJDK 64-Bit server VM:17.0.2.0:Eclipse Adoptium
		kernel.appcore.dll:AppModel API Host:10.0.18362.1 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:OpenJDK Platform binary:17.0.2.0:Eclipse Adoptium
		management_ext.dll:OpenJDK Platform binary:17.0.2.0:Eclipse Adoptium
		msvcp140.dll:Microsoft® C Runtime Library:14.27.29016.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.18362.387 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.18362.1 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Расширение поставщика службы API Microsoft Windows Sockets 2.0:10.0.18362.2339 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:Поставщик оболочки совместимости для имен электронной почты:10.0.18362.2339 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.2.0:Eclipse Adoptium
		nio.dll:OpenJDK Platform binary:17.0.2.0:Eclipse Adoptium
		ntdll.dll:Системная библиотека NT:10.0.18362.329 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Библиотека объектов производительности системы Windows:10.0.18362.2339 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:Поставщик пространства имен PNRP:10.0.18362.2339 (WinBuild.160101.0800):Microsoft Corporation
		powrprof.dll:DLL модуля поддержки профиля управления питанием:10.0.18362.2339 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.18362.1 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.18362.1 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.18362.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.18362.1 (WinBuild.160101.0800):Microsoft Corporation
		shcore.dll:SHCORE:10.0.18362.2339 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Библиотека небольших программ оболочки:10.0.18362.2339 (WinBuild.160101.0800):Microsoft Corporation
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.18362.387 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.27.29016.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.2.0:Eclipse Adoptium
		win32u.dll:Win32u:10.0.18362.628 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:API хранения Microsoft WinRT:10.0.18362.2339 (WinBuild.160101.0800):Microsoft Corporation
		winmmbase.dll:Base Multimedia Extension API DLL:10.0.18362.1 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.18362.1 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.18362.1 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.2.0:Eclipse Adoptium
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.18.2-20220404.173914-srg.jar%23275!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.2, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 5070886088 bytes (4835 MiB) / 6274678784 bytes (5984 MiB) up to 14898167808 bytes (14208 MiB)
	CPUs: 10
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E5-2689 0 @ 2.60GHz
	Identifier: Intel64 Family 6 Model 45 Stepping 7
	Microarchitecture: Sandy Bridge (Server)
	Frequency (GHz): 2.60
	Number of physical packages: 1
	Number of physical CPUs: 5
	Number of logical CPUs: 10
	Graphics card #0 name: Radeon (TM) RX 470 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=30.0.21017.1000
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 4096.00
	Memory slot #2 clockSpeed (GHz): 1.60
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 4096.00
	Memory slot #3 clockSpeed (GHz): 1.60
	Memory slot #3 type: DDR3
	Virtual memory max (MB): 21947.47
	Virtual memory used (MB): 11971.62
	Swap memory total (MB): 7680.00
	Swap memory used (MB): 54.24
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx14208M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.18.2-forge-40.1.84
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.18.2_HD_U_H9_pre1
	OptiFine Build: 20220823-161442
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 0
```

</details>

### Describe the bug

крашится при загрузке в лаунчере

### Steps to reproduce

1.Запустил через FTB лаунчер стоун блок 3. 2. идёт загрузка модов. 3. крашится загрузка.

### Expected behaviour

вход в игру

### Screenshots

![888](https://user-images.githubusercontent.com/119744599/205446133-f7debbc4-34c2-41a4-bc67-40c0477363c4.png)

**Comment by Raidobw2** [comment]
Try removing the Optifine mod, it causes crash.

Optifine alternative: [Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium) + [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus)
