### ISSUE TITLE
Server crash/hang on first start

### ISSUE THREAD

**Issue by ukmcplyr** [FTBTeam/FTB-Modpack-Issues#2258]
### Modpack

Other...

### Modpack version

1.0.0 (FTB Presents Direwolf20 1.19)

### Log Files

[latest.log](https://pste.ch/uqizirokan.md)

### Describe the bug

First time running `./start.sh` and the server was unresponsive following:

```
[07Dec2022 15:37:00.258] [main/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$4598/0x0000000801892b38@672175c1
java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:788)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:786)
	at java.base/java.util.Map.forEach(Map.java:703)
	at TRANSFORMER/resourcefulconfig@1.0.13/com.teamresourceful.resourcefulconfig.common.config.forge.ForgeConfigLoader.loadConfig(ForgeConfigLoader.java:87)
[...]
```

Hitting ^C and re-running `start.sh` worked as expected. Doesn't seem to be easily reproducable from a few attempts.

### Steps to reproduce

1. Start server with `start.sh`
2. Wait for hang

### Expected behaviour

No crash

### Screenshots

![Server console](https://gcdnb.pbrd.co/images/Ou52UJRFKoJm.png?o=1)

**Comment by Saereth** [comment]
cme due to resourceful config, got a mod update to address this, will be out for 1.0.1

**Comment by ukmcplyr** [comment]
Unsure if this is actually the same bug but I hit this on `1.0.1` with `resourcefulconfig-forge-1.19.2-1.0.14.jar`:

```
[09Dec2022 22:49:20.521] [main/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$4606/0x00000008018bec68@5f6b490f
java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:788)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:786)
	at java.base/java.util.Map.forEach(Map.java:703)
	at TRANSFORMER/resourcefulconfig@1.0.14/com.teamresourceful.resourcefulconfig.common.config.forge.ForgeConfigLoader.loadConfig(ForgeConfigLoader.java:88)
[...]
```

[latest.log](https://pste.ch/xubojeneru.md)
