### ISSUE TITLE
Game keeps crashing, after working like a charm yesterday

### ISSUE THREAD

**Issue by PBelerovon** [FTBTeam/FTB-Modpack-Issues#2270]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.10.2

### Log Files

Full Crash Report:
https://pastebin.com/kaULaCHn

### Describe the bug

Game worked till today. Now im getting this Error when launching:

Time: 12/9/22, 8:28 AM
Description: Rendering overlay

net.minecraftforge.fml.ModLoadingException: Better Than Llamas (betterthanllamas) encountered an error during the done event phase
§7java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.m_46658_()" because "p_21369_" is null
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:110) ~[javafmllanguage-1.18.2-40.1.84.jar%23327!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:285) ~[fmlcore-1.18.2-40.1.84.jar%23326!/:?] {}
	at java.util.HashMap.forEach(Unknown Source) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:219) ~[fmlcore-1.18.2-40.1.84.jar%23326!/:?] {}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:285) ~[fmlcore-1.18.2-40.1.84.jar%23326!/:?] {}

Here is a link to the crash report:
https://pastebin.com/kaULaCHn

Can you help me?

### Steps to reproduce

Start the game
Crash

**Comment by PBelerovon** [comment]
Error is related to the BetterThan Mods (EasterDay Error 1.April and 9.December). Fix is to delete both BetterThan mods from the client.
