### ISSUE TITLE
Carry-On Bonsai - Stuck / Duplication Possible

### ISSUE THREAD

**Issue by JasonBow42** [FTBTeam/FTB-Modpack-Issues#2323]
### Modpack

FTB Inferno

### Modpack version

1.3.0

### Describe the bug

Picked up an active bonsai (shift-right click) but when placed, it placed and got stuck in my hand. I can place it multiple times, but can't drop it, change the selected item (1-9), open inventory, or open another block such as a Chest. This is on a private multiplayer server, restart didn't fix it.

Testing in single player, I was unable to make it happen. After restoring playerdata on server, was able to easily pickup the bonsai and get stuck again.

### Steps to reproduce

1. Login to multiplayer server.
2. Find bonsai 
3. Shift-right click to pickup
4. Congratulations, you are now stuck! (But can also duplicate the bonsai w/ contents as much as you want)

### Expected behaviour

Not be able to pickup the bonsai, or be able to place it down.

### Screenshots

![CarryOnBonsaiStuck](https://user-images.githubusercontent.com/23586823/207176359-5996e1e4-9c0b-41bb-993a-d60ca5e776db.png)

### Additional information

This exception seemed to appear when I picked up the bonsai:

```
[18:04:09] [Server thread/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER
> java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER
        at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.80/net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at TRANSFORMER/bonsaitrees3@3.1.0/com.davenonymous.bonsaitrees3.blocks.BonsaiPotBlockEntity.onDataLoaded(BonsaiPotBlockEntity.java:473)
        at TRANSFORMER/libnonymous@2.1.0/com.davenonymous.libnonymous.base.BaseBlockEntity.m_142466_(BaseBlockEntity.java:107)
        at TRANSFORMER/carryon@1.17.0.8/tschipp.carryon.common.item.ItemCarryonBlock.m_6225_(ItemCarryonBlock.java:189)
        at TRANSFORMER/forge@40.1.80/net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:605)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:222)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:357)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:985)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:30)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.TickTask.run(TickTask.java:18)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:761)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261)
        at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by HumdrumPanic** [comment]
As a work around until fixed... I found that you can die, then grab your gravestone, then before doing anything else (don't mouse wheel your hot-bar or try to swap items) open the trashcan inventory then grab the invisible carry on "item" and drop it in there. That way you can keep playing.

**Comment by Saereth** [comment]
Pick up on bonsais is restricted so this appears to be a misconfiguration. updating the pack should force fix the configs, you can also grab them from the defaultconfigs folder and put them in your saves/savename/serverconfigs
