### ISSUE TITLE
Apotheosis Spawner No-AI upgrade causes crash

### ISSUE THREAD

**Issue by moneyblind** [FTBTeam/FTB-Modpack-Issues#2449]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Log Files

[crash-2023-01-03_14.06.49-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10339530/crash-2023-01-03_14.06.49-server.txt)

=-=--=--=-=--=-=
HEAD OF FILE
-=-=-=-=-=-=-=
Time: 2023-01-03 14:06:50
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getRight()" because "walkingSide" is null
	at net.minecraft.world.entity.monster.Spider.getStickingForce(Spider.java:1341) ~[client-1.19.2-20220805.130853-srg.jar%23422!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:spiderstpo.mixins.json:ClimberEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:BetterSpiderEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.monster.Spider.travelOnGround(Spider.java:1428) ~[client-1.19.2-20220805.130853-srg.jar%23422!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:spiderstpo.mixins.json:ClimberEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:BetterSpiderEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.monster.Spider.onTravel(Spider.java:1400) ~[client-1.19.2-20220805.130853-srg.jar%23422!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:spiderstpo.mixins.json:ClimberEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:BetterSpiderEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.handler$bhj000$onTravelPre(LivingEntity.java:12047) ~[client-1.19.2-20220805.130853-srg.jar%23422!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:LivingEntityInvoker,pl:mixin:APP:supplementaries-common.mixins.json:LivingEntityMixin,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:ars_nouveau.mixins.json:elytra.MixinLivingEntity,pl:mixin:APP:ars_nouveau.mixins.json:perks.PerkLivingEntity,pl:mixin:APP:whisperwoods.mixins.json:LivingEntityMixin,pl:mixin:APP:ad_astra-common.mixins.json:LivingEntityMixin,pl:mixin:APP:ad_astra-common.mixins.json:gravity.LivingEntityGravityMixin,pl:mixin:APP:netherportalfix.mixins.json:LivingEntityAccessor,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:entity.MixinLivingEntity,pl:mixin:APP:morefrogs.mixins.json:LivingEntityMixin,pl:mixin:APP:spirit.common.mixins.json:LivingEntityMixin,pl:mixin:APP:voidtotem.mixins.json:LivingEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityClientMixin,pl:mixin:APP:betterdeserttemples.mixins.json:PharaohKilledMixin,pl:mixin:APP:hexplat.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:quark.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:bettertridents.common.mixins.json:LivingEntityMixin,pl:mixin:APP:charmofundying.mixins.json:MixinLivingEntity,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:expandability-common.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_7023_(LivingEntity.java) ~[client-1.19.2-20220805.130853-srg.jar%23422!/:?] 

### Describe the bug

Apotheosis spawner with only a redstone control was placed down.
Spawns as expected.
Applying the chorus fruit for the No-AI effect is successful.
Upon spawning of the entity, in this case the spider, the game freezes, then crashes with a null pointer exception.

### Steps to reproduce

Spider spawner
Apply redstone control (unknown if needed, but its in my world)
Apply NO-AI modifier
Server Crash

### Expected behaviour

Lifeless zombie entities for easy killing.

**Comment by DizzyDJW** [comment]
This is to do with no AI and spider spawners specifically, as I made an issue about this myself. I have several spawners of every other vanilla mob and many modded mobs all with no ai upgrades and no crashes, yet the spider spawner with no ai will spawn the mob then freeze then crash and on next load the mob will be there but if you try to spawn another it will crash the same way again.

**Comment by DizzyDJW** [comment]
Duplicate issue: Issue #2447
