### ISSUE TITLE
[CRASH] "Cannot accept empty stack"

### ISSUE THREAD

**Issue by DizzyDJW** [FTBTeam/FTB-Modpack-Issues#2467]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Log Files

https://pste.ch/buqanutuyi.sql

### Describe the bug

Random crash while doing nothing at all.

### Steps to reproduce

No idea

### Expected behaviour

Not that

**Comment by DizzyDJW** [comment]
This is still an ongoing crash. Too common. Happens twice a day.

**Comment by DizzyDJW** [comment]
I hope an update fixes it at some point.

**Comment by DizzyDJW** [comment]
I hope an update comes at some point.

**Comment by TemporalWolf** [comment]
I had a nearly identical crash that I solved by removing the functional storage armory cabinet from my refined storage network.

Every time the game tried to do an automatic backup it would crash with this error.

```---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-01-13 16:17:09
Description: Exception in server tick loop

java.lang.IllegalArgumentException: Cannot accept empty stack
	at com.refinedmods.refinedstorage.apiimpl.util.ItemStackList.add(ItemStackList.java:35) ~[refinedstorage-1.11.4.jar%23633!/:1.11.4] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.util.ItemStackList.add(ItemStackList.java:19) ~[refinedstorage-1.11.4.jar%23633!/:1.11.4] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.storage.cache.ItemStorageCache.add(ItemStorageCache.java:76) ~[refinedstorage-1.11.4.jar%23633!/:1.11.4] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.storage.cache.ItemStorageCache.add(ItemStorageCache.java:26) ~[refinedstorage-1.11.4.jar%23633!/:1.11.4] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.storage.externalstorage.ItemExternalStorageCache.update(ItemExternalStorageCache.java:82) ~[refinedstorage-1.11.4.jar%23633!/:1.11.4] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.storage.externalstorage.ItemExternalStorage.update(ItemExternalStorage.java:43) ~[refinedstorage-1.11.4.jar%23633!/:1.11.4] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.node.ExternalStorageNetworkNode.update(ExternalStorageNetworkNode.java:98) ~[refinedstorage-1.11.4.jar%23633!/:1.11.4] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.NetworkListener.onLevelTick(NetworkListener.java:25) ~[refinedstorage-1.11.4.jar%23633!/:1.11.4] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.__NetworkListener_onLevelTick_LevelTickEvent.invoke(.dynamic) ~[refinedstorage-1.11.4.jar%23633!/:1.11.4] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactory.java:820) ~[forge-1.19.2-43.2.3-universal.jar%23724!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:minetogether-common.mixins.json:connect.IntegratedServerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:?] {re:mixin}```

**Comment by Saereth** [comment]
next update has an upate to functional storage that will hopefully resolve this, not using the armory until then is a good work around
