### ISSUE TITLE
Mekanism Anchor upgrade conflict with FTB Chunks

### ISSUE THREAD

**Issue by vedrit** [FTBTeam/FTB-Modpack-Issues#2471]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.1

### Log Files

https://pastebin.com/QfEPbMTi
[crash-2023-01-08_06.35.56-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10368719/crash-2023-01-08_06.35.56-server.txt)

### Describe the bug

Loading the Mekanism Anchor upgrade into a machine and then leaving the area causes the server to crash, and crash on startup. Disabling the FTB Chunks mod allows the server to start. Removing the Anchor upgrade, the server can be started normally with FTB Chunks enabled.

### Steps to reproduce

Install the Anchor upgrade into a Mekanism machine, such as the Miner.
Leave the area or change dimensions.

### Expected behaviour

Server to start and run without crashing

**Comment by vedrit** [comment]
Further testing, it seems the issue occurs with other chunk loaders as well, such as Flux Points/Plugs, and only seems to occur if that chunk is also set to be loaded with FTBChunks

**Comment by vedrit** [comment]
Looking at the logs, it seems to be an issue with non-player entities breaking blocks in an FTBChunk loaded chunk.

`[Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.m_46472_()" because "world" is null
	at dev.ftb.mods.ftblibrary.math.ChunkDimPos.<init>(ChunkDimPos.java:32) ~[ftb-library-forge-1902.3.10-build.162.jar%23198!/:1902.3.10-build.162]
	at dev.ftb.mods.ftbchunks.data.ClaimedChunkManager.protect(ClaimedChunkManager.java:199) ~[ftb-chunks-forge-1902.3.13-build.207.jar%23196!/:1902.3.13-build.207]
	at dev.ftb.mods.ftbchunks.FTBChunks.blockBreak(FTBChunks.java:280) ~[ftb-chunks-forge-1902.3.13-build.207.jar%23196!/:1902.3.13-build.207]
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source) ~[?:?]
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-6.3.56-forge.jar%23114!/:?]
	at dev.architectury.event.EventFactory$2.handleInvocation(EventFactory.java:81) ~[architectury-6.3.56-forge.jar%23114!/:?]
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89) ~[guava-31.0.1-jre.jar%2372!/:?]
	at jdk.proxy3.$Proxy137.breakBlock(Unknown Source) ~[?:?]
	at pro.mikey.accelerateddecay.AcceleratedDecay.levelTick(AcceleratedDecay.java:68) ~[accelerated-decay-forge-1.0.0+mc1.19.2.jar%2398!/:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source) ~[?:?]
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-6.3.56-forge.jar%23114!/:?]
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62) ~[architectury-6.3.56-forge.jar%23114!/:?]
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89) ~[guava-31.0.1-jre.jar%2372!/:?]
	at jdk.proxy3.$Proxy135.tick(Unknown Source) ~[?:?]
	at dev.architectury.event.forge.EventHandlerImplCommon.event(EventHandlerImplCommon.java:79) ~[architectury-6.3.56-forge.jar%23114!/:?]
	at dev.architectury.event.forge.__EventHandlerImplCommon_event_LevelTickEvent.invoke(.dynamic) ~[architectury-6.3.56-forge.jar%23114!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactory.java:820) ~[forge-1.19.2-43.1.57-universal.jar%23374!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872) ~[server-1.19.2-20220805.130853-srg.jar%23369!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23369!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23369!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23369!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23369!/:?]
	at java.lang.Thread.run(Unknown Source) [?:?]`

**Comment by vedrit** [comment]
Same crash in modpack v1.1.0

**Comment by xRiriq** [comment]
I do not have a released mod pack, but I was able to see the same issue on a homebrew 1.18.2 modpack. This is with the same Mekanism Digital Miner w/ Anchor Upgrade + FTB Chunks as described for the original issue. In our experimentation as long as it wasn't in an owned chunk it did not cause any problems.

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.m_46472_()" because "world" is null
	at dev.ftb.mods.ftblibrary.math.ChunkDimPos.<init>(ChunkDimPos.java:32) ~[ftb-library-forge-1802.3.9-build.167.jar%2373!/:1802.3.9-build.167] {re:classloading}
	at dev.ftb.mods.ftbchunks.data.ClaimedChunkManager.protect(ClaimedChunkManager.java:199) ~[ftb-chunks-forge-1802.3.12-build.217.jar%2371!/:1802.3.12-build.217] {re:mixin,re:classloading}
	at dev.ftb.mods.ftbchunks.FTBChunks.blockBreak(FTBChunks.java:279) ~[ftb-chunks-forge-1802.3.12-build.217.jar%2371!/:1802.3.12-build.217] {re:mixin,re:classloading}
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?] {re:mixin}
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-4.10.88-forge.jar%2344!/:?] {re:classloading}
	at dev.architectury.event.EventFactory$2.handleInvocation(EventFactory.java:81) ~[architectury-4.10.88-forge.jar%2344!/:?] {re:classloading}
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89) ~[guava-31.0.1-jre.jar%2322!/:?] {}
	at jdk.proxy3.$Proxy119.breakBlock(Unknown Source) ~[?:?] {}
	at pro.mikey.accelerateddecay.AcceleratedDecay.levelTick(AcceleratedDecay.java:68) ~[accelerated-decay-forge-0.1.1+mc1.18.2.jar%2339!/:?] {re:classloading}
	at dev.architectury.event.forge.EventHandlerImplCommon.event(EventHandlerImplCommon.java:81) ~[architectury-4.10.88-forge.jar%2344!/:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_233_EventHandlerImplCommon_event_WorldTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostWorldTick(ForgeEventFactory.java:911) ~[forge-1.18.2-40.1.93-universal.jar%23132!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:908) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

```
