### ISSUE TITLE
Dedicated server crash on load

### ISSUE THREAD

**Issue by sadovsf** [FTBTeam/FTB-Modpack-Issues#2472]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.10.3

### Log Files

[08Jan2023 11:04:25.874] [main/ERROR] [net.minecraft.server.Main/FATAL]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
MineTogether (minetogether) has failed to load correctly
ยง7java.lang.reflect.InvocationTargetException: null
]
at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:222) ~[fmlcore-1.18.2-40.1.84.jar%23307!/:?]
at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:187) ~[fmlcore-1.18.2-40.1.84.jar%23307!/:?]

### Describe the bug

Iam hosting server with g-portal hosting and for some time it fails to start. I opened ticked with them and aparently it could be modpack issue (see attached log section).

### Steps to reproduce

Start dedicated server, observe it does not start

### Expected behaviour

It should start :)

**Comment by sadovsf** [comment]
[crash-2023-01-23_08.58.24-fml.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10477762/crash-2023-01-23_08.58.24-fml.txt)
Here is crash report in case it helps

**Comment by Gaz492** [comment]
Closing this as the latest version of the modpack contains minetogether-forge-1.18.2-6.0.15
