### ISSUE TITLE
mini map disapeared and crashes if i try to open it

### ISSUE THREAD

**Issue by vandoor1** [FTBTeam/FTB-Modpack-Issues#2495]
### Modpack

FTB One

### Modpack version

1.3.0

### Log Files

	0: HIGH
		1: ASM: class dev.architectury.event.forge.EventHandlerImplClient eventMouseReleasedEvent(Lnet/minecraftforge/client/event/ScreenEvent$MouseReleasedEvent$Pre;)V
		2: NORMAL
		3: ASM: yalter.mousetweaks.forge.MouseTweaksForge@13d6c86e onGuiMouseReleasedPre(Lnet/minecraftforge/client/event/ScreenEvent$MouseReleasedEvent$Pre;)V
		4: net.minecraftforge.eventbus.EventBus$$Lambda$4684/0x0000000801946a80@4f16b8f2
		5: ASM: com.leobeliik.extremesoundmuffler.SoundMufflerForge@1c4f600 onMouseRelease(Lnet/minecraftforge/client/event/ScreenEvent$MouseReleasedEvent;)V
java.lang.NullPointerException: Cannot invoke "com.mojang.blaze3d.platform.Window.m_85445_()" because "this.screen" is null
	at TRANSFORMER/ftblibrary@1900.3.7-build.131/dev.ftb.mods.ftblibrary.ui.BaseScreen.setFullscreen(BaseScreen.java:123)
	at TRANSFORMER/ftbchunks@1900.3.7-build.154/dev.ftb.mods.ftbchunks.client.LargeMapScreen.onInit(LargeMapScreen.java:175)
	at TRANSFORMER/ftblibrary@1900.3.7-build.131/dev.ftb.mods.ftblibrary.ui.BaseScreen.closeContextMenu(BaseScreen.java:273)
	at TRANSFORMER/ftblibrary@1900.3.7-build.131/dev.ftb.mods.ftblibrary.ui.BaseScreen.onClosed(BaseScreen.java:279)
	at TRANSFORMER/ftblibrary@1900.3.7-build.131/dev.ftb.mods.ftblibrary.ui.BaseScreen.closeGui(BaseScreen.java:162)
	at TRANSFORMER/ftbchunks@1900.3.7-build.154/dev.ftb.mods.ftbchunks.client.LargeMapScreen.<init>(LargeMapScreen.java:69)
	at TRANSFORMER/ftbchunks@1900.3.7-build.154/dev.ftb.mods.ftbchunks.client.FTBChunksClient.openGui(FTBChunksClient.java:183)
	at TRANSFORMER/ftbchunks@1900.3.7-build.154/dev.ftb.mods.ftbchunks.client.FTBChunksClient.customClick(FTBChunksClient.java:369)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at TRANSFORMER/architectury@5.7.28/dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53)
	at TRANSFORMER/architectury@5.7.28/dev.architectury.event.EventFactory$5.handleInvocation(EventFactory.java:152)
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89)
	at TRANSFORMER/jdk.proxy3/jdk.proxy3.$Proxy133.act(Unknown Source)
	at TRANSFORMER/ftblibrary@1900.3.7-build.131/dev.ftb.mods.ftblibrary.util.ClientUtils.handleClick(ClientUtils.java:151)
	at TRANSFORMER/ftblibrary@1900.3.7-build.131/dev.ftb.mods.ftblibrary.ui.BaseScreen.handleClick(BaseScreen.java:387)
	at TRANSFORMER/ftblibrary@1900.3.7-build.131/dev.ftb.mods.ftblibrary.ui.Widget.handleClick(Widget.java:187)
	at TRANSFORMER/ftblibrary@1900.3.7-build.131/dev.ftb.mods.ftblibrary.sidebar.SidebarButton.onClicked(SidebarButton.java:158)
	at TRANSFORMER/ftblibrary@1900.3.7-build.131/dev.ftb.mods.ftblibrary.integration.REIIntegration$SidebarButtonEntry.doAction(REIIntegration.java:167)
	at TRANSFORMER/roughlyenoughitems@9.1.500/me.shedaniel.rei.impl.client.gui.widget.region.RegionEntryWidget.doAction(RegionEntryWidget.java:140)
	at TRANSFORMER/roughlyenoughitems@9.1.500/me.shedaniel.rei.impl.client.gui.widget.EntryWidget.m_6348_(EntryWidget.java:545)
	at TRANSFORMER/minecraft@1.19/net.minecraft.client.gui.components.events.ContainerEventHandler.m_94704_(ContainerEventHandler.java:41)
	at java.base/java.util.Optional.filter(Unknown Source)
	at TRANSFORMER/minecraft@1.19/net.minecraft.client.gui.components.events.ContainerEventHandler.m_6348_(ContainerEventHandler.java:41)
	at TRANSFORMER/roughlyenoughitems@9.1.500/me.shedaniel.rei.impl.client.gui.widget.favorites.FavoritesListWidget.m_6348_(FavoritesListWidget.java:310)
	at TRANSFORMER/minecraft@1.19/net.minecraft.client.gui.components.events.ContainerEventHandler.m_94704_(ContainerEventHandler.java:41)
	at java.base/java.util.Optional.filter(Unknown Source)
	at TRANSFORMER/minecraft@1.19/net.minecraft.client.gui.components.events.ContainerEventHandler.m_6348_(ContainerEventHandler.java:41)
	at TRANSFORMER/roughlyenoughitems@9.1.500/me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$18(RoughlyEnoughItemsCoreClient.java:383)
	at TRANSFORMER/architectury@5.7.28/dev.architectury.event.forge.EventHandlerImplClient.eventMouseReleasedEvent(EventHandlerImplClient.java:268)
	at TRANSFORMER/architectury@5.7.28/dev.architectury.event.forge.__EventHandlerImplClient_eventMouseReleasedEvent_Pre.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:93)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@41.0.63/net.minecraftforge.client.ForgeHooksClient.onScreenMouseReleasedPre(ForgeHooksClient.java:624)
	at TRANSFORMER/minecraft@1.19/net.minecraft.client.MouseHandler.m_168078_(MouseHandler.java:94)
	at TRANSFORMER/minecraft@1.19/net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:524)
	at TRANSFORMER/minecraft@1.19/net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:93)
	at TRANSFORMER/minecraft@1.19/net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185)
	at TRANSFORMER/minecraft@1.19/net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103)
	at TRANSFORMER/minecraft@1.19/net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184)
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.1+7/org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at MC-BOOTSTRAP/org.lwjgl@3.3.1+7/org.lwjgl.system.JNI.invokeV(Native Method)
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.1+7/org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at TRANSFORMER/minecraft@1.19/com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197)
	at TRANSFORMER/minecraft@1.19/com.mojang.blaze3d.platform.Window.m_85435_(Window.java:332)
	at TRANSFORMER/minecraft@1.19/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1098)
	at TRANSFORMER/minecraft@1.19/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660)
	at TRANSFORMER/minecraft@1.19/net.minecraft.client.main.Main.main(Main.java:205)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at MC-BOOTSTRAP/fmlloader@1.19-41.0.63/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.1/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.1/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.1/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.1/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.1/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.1/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.1/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.1/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

[11Jan2023 20:48:57.897] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: mouseReleased event handler
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:531) ~[client-1.19-20220607.102129-srg.jar%23305!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:93) ~[client-1.19-20220607.102129-srg.jar%23305!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.19-20220607.102129-srg.jar%23305!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19-20220607.102129-srg.jar%23305!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.19-20220607.102129-srg.jar%23305!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%23136!/:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23128!/:build 7]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23136!/:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.19-20220607.102129-srg.jar%23305!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:332) ~[client-1.19-20220607.102129-srg.jar%23305!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1098) ~[client-1.19-20220607.102129-srg.jar%23305!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.19-20220607.102129-srg.jar%23305!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.19-20220607.102129-srg.jar%23305!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.63.jar%2393!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.1.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.mojang.blaze3d.platform.Window.m_85445_()" because "this.screen" is null
	at dev.ftb.mods.ftblibrary.ui.BaseScreen.setFullscreen(BaseScreen.java:123) ~[ftb-library-forge-1900.3.7-build.131.jar%23204!/:1900.3.7-build.131]
	at dev.ftb.mods.ftbchunks.client.LargeMapScreen.onInit(LargeMapScreen.java:175) ~[ftb-chunks-forge-1900.3.7-build.154.jar%23201!/:1900.3.7-build.154]
	at dev.ftb.mods.ftblibrary.ui.BaseScreen.closeContextMenu(BaseScreen.java:273) ~[ftb-library-forge-1900.3.7-build.131.jar%23204!/:1900.3.7-build.131]
	at dev.ftb.mods.ftblibrary.ui.BaseScreen.onClosed(BaseScreen.java:279) ~[ftb-library-forge-1900.3.7-build.131.jar%23204!/:1900.3.7-build.131]
	at dev.ftb.mods.ftblibrary.ui.BaseScreen.closeGui(BaseScreen.java:162) ~[ftb-library-forge-1900.3.7-build.131.jar%23204!/:1900.3.7-build.131]
	at dev.ftb.mods.ftbchunks.client.LargeMapScreen.<init>(LargeMapScreen.java:69) ~[ftb-chunks-forge-1900.3.7-build.154.jar%23201!/:1900.3.7-build.154]
	at dev.ftb.mods.ftbchunks.client.FTBChunksClient.openGui(FTBChunksClient.java:183) ~[ftb-chunks-forge-1900.3.7-build.154.jar%23201!/:1900.3.7-build.154]
	at dev.ftb.mods.ftbchunks.client.FTBChunksClient.customClick(FTBChunksClient.java:369) ~[ftb-chunks-forge-1900.3.7-build.154.jar%23201!/:1900.3.7-build.154]
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source) ~[?:?]
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-5.7.28-forge.jar%23148!/:?]
	at dev.architectury.event.EventFactory$5.handleInvocation(EventFactory.java:152) ~[architectury-5.7.28-forge.jar%23148!/:?]
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89) ~[guava-31.0.1-jre.jar%23113!/:?]
	at jdk.proxy3.$Proxy133.act(Unknown Source) ~[?:?]
	at dev.ftb.mods.ftblibrary.util.ClientUtils.handleClick(ClientUtils.java:151) ~[ftb-library-forge-1900.3.7-build.131.jar%23204!/:1900.3.7-build.131]
	at dev.ftb.mods.ftblibrary.ui.BaseScreen.handleClick(BaseScreen.java:387) ~[ftb-library-forge-1900.3.7-build.131.jar%23204!/:1900.3.7-build.131]
	at dev.ftb.mods.ftblibrary.ui.Widget.handleClick(Widget.java:187) ~[ftb-library-forge-1900.3.7-build.131.jar%23204!/:1900.3.7-build.131]
	at dev.ftb.mods.ftblibrary.sidebar.SidebarButton.onClicked(SidebarButton.java:158) ~[ftb-library-forge-1900.3.7-build.131.jar%23204!/:1900.3.7-build.131]
	at dev.ftb.mods.ftblibrary.integration.REIIntegration$SidebarButtonEntry.doAction(REIIntegration.java:167) ~[ftb-library-forge-1900.3.7-build.131.jar%23204!/:1900.3.7-build.131]
	at me.shedaniel.rei.impl.client.gui.widget.region.RegionEntryWidget.doAction(RegionEntryWidget.java:140) ~[RoughlyEnoughItems-9.1.500.jar%23268!/:?]
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.m_6348_(EntryWidget.java:545) ~[RoughlyEnoughItems-9.1.500.jar%23268!/:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_94704_(ContainerEventHandler.java:41) ~[client-1.19-20220607.102129-srg.jar%23305!/:?]
	at java.util.Optional.filter(Unknown Source) ~[?:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6348_(ContainerEventHandler.java:41) ~[client-1.19-20220607.102129-srg.jar%23305!/:?]
	at me.shedaniel.rei.impl.client.gui.widget.favorites.FavoritesListWidget.m_6348_(FavoritesListWidget.java:310) ~[RoughlyEnoughItems-9.1.500.jar%23268!/:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_94704_(ContainerEventHandler.java:41) ~[client-1.19-20220607.102129-srg.jar%23305!/:?]
	at java.util.Optional.filter(Unknown Source) ~[?:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6348_(ContainerEventHandler.java:41) ~[client-1.19-20220607.102129-srg.jar%23305!/:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$18(RoughlyEnoughItemsCoreClient.java:383) ~[RoughlyEnoughItems-9.1.500.jar%23268!/:?]
	at dev.architectury.event.forge.EventHandlerImplClient.eventMouseReleasedEvent(EventHandlerImplClient.java:268) ~[architectury-5.7.28-forge.jar%23148!/:?]
	at dev.architectury.event.forge.__EventHandlerImplClient_eventMouseReleasedEvent_Pre.invoke(.dynamic) ~[architectury-5.7.28-forge.jar%23148!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:93) ~[eventbus-6.0.0.jar%2378!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-6.0.0.jar%2378!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-6.0.0.jar%2378!/:?]
	at net.minecraftforge.client.ForgeHooksClient.onScreenMouseReleasedPre(ForgeHooksClient.java:624) ~[forge-1.19-41.0.63-universal.jar%23310!/:?]
	at net.minecraft.client.MouseHandler.m_168078_(MouseHandler.java:94) ~[client-1.19-20220607.102129-srg.jar%23305!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:524) ~[client-1.19-20220607.102129-srg.jar%23305!/:?]
	... 25 more

### Describe the bug

game runs fine randomly started after tried opening the map

### Steps to reproduce

press m or click ftb chunks

### Expected behaviour

map to open

**Comment by vandoor1** [comment]
to add to this my friends maps/minimaps all work

**Comment by Saereth** [comment]
Ftb One 2.0 will be out this month and this issue should be resolved, please update once it's out.
