### ISSUE TITLE
Mods missing after update

### ISSUE THREAD

**Issue by imevul** [FTBTeam/FTB-Modpack-Issues#2630]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.2.1

### Describe the bug

Updated linux server from v1.1.1 to v1.2.1 using the installer. It reported that 7 files were changed (even though I hadn't changed any configs). Install completed successfully.
After the update the server crashed on startup with error:

Mod §exnetgases§r requires §6xnet§r §o1.18-4 or above§r

After closer inspection, I noticed that the xnet-1.19-5.1.0.jar file was missing. May have been more missing as well.
Re-ran the installer, and this time everything worked fine.

### Steps to reproduce

1. Have v1.1.1 of the modpack installed (linux server, x64)
2. Download and run serverinstall_101_2324
3. Answer "y" to all questions
4. Some mods are now missing and server crashes on startup
5. Re-run serverinstall_101_2324
6. Answer "y" to all questions
7. Everything works correctly

### Expected behaviour

I expected the mods to be installed on the first try

**Comment by MoonStalk** [comment]
I had the same issue with the server install.  I removed the mod directory and re-ran the installer, and it installed correctly

**Comment by FagSoft** [comment]
No need to delete the mod folder, just running the installer again should be enough.

I can confirm this issue, as I had the same problem with the 1.2.0 installer. Was missing the xnet mod after the first run with the installer, but with the second run it was downloaded properly.

Also had the same issue with a couple of other mods, with the 1.1.0 installer. Can't recall what mods that were missing, but it gave a server error when trying to download them the first time.

**Comment by MvanRietschoten** [comment]
I updated from 1.2.1 to 1.3.2 and had the same issue, running the update again fixed it for me.

**Comment by FagSoft** [comment]
Afraid this issue persists. Just updated from 1.2.1 to 1.4.0, and go the following error when trying to start the server afterwards.
`[17:51:51] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Mod ?exnetgases?r requires ?6xnet?r ?o1.18-4 or above?r
?7Currently, ?6xnet?r?7 is ?o?nnot installed
]
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:152) ~[fmlcore-1.19.2-43.2.3.jar%23662!/:?] {}
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[forge-1.19.2-43.2.3-universal.jar%23666!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19.2-20220805.130853-srg.jar%23661!/:?] {re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.2.3.jar%2367!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
`
I double-checked the download progress after running the installer the first time, to which it said 189 (out of 189) downloads completed. No other errors either, as I could see.

I can confirm that xnet was not in the mod folder after the first update run, only xnet-gases. Tried re-running the installer, and this time it downloaded 80 more files. After which the server did indeed start as normal.

Unfortunately I don't have a list of those 80 additional files, as I ran the update in a screen session. :\
