### ISSUE TITLE
Mekanism Digi Miner causes crash when finished Mining

### ISSUE THREAD

**Issue by Woodka7** [FTBTeam/FTB-Modpack-Issues#2728]
### Modpack

FTB Direwolf20 1.19.2 1.3.2

### Modpack version

1.3.2

### Log Files

---- Minecraft Crash Report ----
// You're mean.

Time: 2023-02-18 11:34:55
Description: Ticking block entity

java.lang.IllegalArgumentException: duplicate element: [83, -7]
	at java.util.ImmutableCollections$Set12.<init>(Unknown Source) ~[?:?] {}
	at java.util.Set.of(Unknown Source) ~[?:?] {re:computing_frames,re:mixin}
	at mekanism.common.tile.machine.TileEntityDigitalMiner.getChunkSet(TileEntityDigitalMiner.java:1029) ~[Mekanism-1.19.2-10.3.7.476.jar%23588!/:10.3.7] {re:classloading}
	at mekanism.common.tile.component.TileComponentChunkLoader.getTileChunks(TileComponentChunkLoader.java:220) ~[Mekanism-1.19.2-10.3.7.476.jar%23588!/:10.3.7] {re:classloading}
	at mekanism.common.tile.component.TileComponentChunkLoader.refreshChunkTickets(TileComponentChunkLoader.java:130) ~[Mekanism-1.19.2-10.3.7.476.jar%23588!/:10.3.7] {re:classloading}
	at mekanism.common.tile.component.TileComponentChunkLoader.refreshChunkTickets(TileComponentChunkLoader.java:96) ~[Mekanism-1.19.2-10.3.7.476.jar%23588!/:10.3.7] {re:classloading}
	at mekanism.common.tile.machine.TileEntityDigitalMiner.updateTargetChunk(TileEntityDigitalMiner.java:1012) ~[Mekanism-1.19.2-10.3.7.476.jar%23588!/:10.3.7] {re:classloading}
	at mekanism.common.tile.machine.TileEntityDigitalMiner.tryMineBlock(TileEntityDigitalMiner.java:438) ~[Mekanism-1.19.2-10.3.7.476.jar%23588!/:10.3.7] {re:classloading}
	at mekanism.common.tile.machine.TileEntityDigitalMiner.onUpdateServer(TileEntityDigitalMiner.java:229) ~[Mekanism-1.19.2-10.3.7.476.jar%23588!/:10.3.7] {re:classloading}
	at mekanism.common.tile.base.TileEntityMekanism.tickServer(TileEntityMekanism.java:574) ~[Mekanism-1.19.2-10.3.7.476.jar%23588!/:10.3.7] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:APP:itshallnottick.mixins.json:EntityTickMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:ars_elemental.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:?] {re:mixin}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.ImmutableCollections$Set12.<init>(Unknown Source) ~[?:?] {}
	at java.util.Set.of(Unknown Source) ~[?:?] {re:computing_frames,re:mixin}
	at mekanism.common.tile.machine.TileEntityDigitalMiner.getChunkSet(TileEntityDigitalMiner.java:1029) ~[Mekanism-1.19.2-10.3.7.476.jar%23588!/:10.3.7] {re:classloading}
	at mekanism.common.tile.component.TileComponentChunkLoader.getTileChunks(TileComponentChunkLoader.java:220) ~[Mekanism-1.19.2-10.3.7.476.jar%23588!/:10.3.7] {re:classloading}
	at mekanism.common.tile.component.TileComponentChunkLoader.refreshChunkTickets(TileComponentChunkLoader.java:130) ~[Mekanism-1.19.2-10.3.7.476.jar%23588!/:10.3.7] {re:classloading}
	at mekanism.common.tile.component.TileComponentChunkLoader.refreshChunkTickets(TileComponentChunkLoader.java:96) ~[Mekanism-1.19.2-10.3.7.476.jar%23588!/:10.3.7] {re:classloading}
	at mekanism.common.tile.machine.TileEntityDigitalMiner.updateTargetChunk(TileEntityDigitalMiner.java:1012) ~[Mekanism-1.19.2-10.3.7.476.jar%23588!/:10.3.7] {re:classloading}
	at mekanism.common.tile.machine.TileEntityDigitalMiner.tryMineBlock(TileEntityDigitalMiner.java:438) ~[Mekanism-1.19.2-10.3.7.476.jar%23588!/:10.3.7] {re:classloading}
	at mekanism.common.tile.machine.TileEntityDigitalMiner.onUpdateServer(TileEntityDigitalMiner.java:229) ~[Mekanism-1.19.2-10.3.7.476.jar%23588!/:10.3.7] {re:classloading}
	at mekanism.common.tile.base.TileEntityMekanism.tickServer(TileEntityMekanism.java:574) ~[Mekanism-1.19.2-10.3.7.476.jar%23588!/:10.3.7] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:APP:itshallnottick.mixins.json:EntityTickMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:ars_elemental.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
-- Block entity being ticked --
Details:
	Name: mekanism:digital_miner // mekanism.common.tile.machine.TileEntityDigitalMiner
	Block: Block{mekanism:digital_miner}[active=true,facing=west,fluid_logged=empty]
	Block location: World: (1340,69,-105), Section: (at 12,5,7 in 83,4,-7; chunk contains blocks 1328,-64,-112 to 1343,319,-97), Region: (2,-1; contains chunks 64,-32 to 95,-1, blocks 1024,-64,-512 to 1535,319,-1)
	Block: Block{mekanism:digital_miner}[active=true,facing=west,fluid_logged=empty]
	Block location: World: (1340,69,-105), Section: (at 12,5,7 in 83,4,-7; chunk contains blocks 1328,-64,-112 to 1343,319,-97), Region: (2,-1; contains chunks 64,-32 to 95,-1, blocks 1024,-64,-512 to 1535,319,-1)
Stacktrace:
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:APP:itshallnottick.mixins.json:EntityTickMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:ars_elemental.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:?] {re:mixin}

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 841
	Level dimension: jamd:mining
	Derived: true
	Level spawn location: World: (96,70,-352), Section: (at 0,6,0 in 6,4,-22; chunk contains blocks 96,-64,-352 to 111,319,-337), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 8815243 game time, 9486352 day time
	Level name: Hardcore #2
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 80003 (now: false), thunder time: 28598 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:?] {re:mixin}

### Describe the bug

I initially used the Digi miner in the overworld as a test and it crashed my world when finishing mining the iron I had filtered , luckily I did not have enough power to sustain it at this point so i was able to login to my world, I upgraded my power generation and was able to sustain it with 4 speed upgrades, so I decided to go into the mining dimension and have my mining set up there, thinking it was just a fluke crash, I decided to redo the process, it was going perfectly, until I was rudely interrupted in the middle building my Evaporation Plant, and it would auto crash every time I tried launching  reading the crash report it looks like it still registers blocks to mine even after the process is done I maybe wrong, I ended up fixing it by going into configs and deleting the mining dimension in the saves folder, I really want to use the Digi Miner one of my favorite Quarries, have to hold off for now

### Steps to reproduce

1. Have and A Good amount of power Generation From Extreme Reactors
2. Create the Digi Miner and 4 Speed Upgrades 8 Energy and an Anchor Upgrade
3. Power Directly with Flux Plug and Point
4. Have Iron Ore filtered and Run until process is complete, Do not turn off the system
5. Then it crashes My system

### Expected behaviour

I expect it to turn off after the Digi Miner is finished

**Comment by Woodka7** [comment]
How do you change the Label to DireWolf 1.19

**Comment by jondwaite** [comment]
I hit this earlier today in DW20 pack, manually upgrading to latest Mekanism .jar files (10.3.8) fixed it for me - same log entry regarding Ticking block entity and duplicate element. Appears to be a known bug in Mekanism 10.3.7 when using chunkloader.

**Comment by Woodka7** [comment]
Thanks that worked out!!
