### ISSUE TITLE
Server crashing on startup

### ISSUE THREAD

**Issue by gvillwrstlr** [FTBTeam/FTB-Modpack-Issues#2741]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.3.2

### Log Files

[crash-2023-02-22_12.22.28-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10806673/crash-2023-02-22_12.22.28-server.txt)
[crash-2023-02-22_06.00.56-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10806674/crash-2023-02-22_06.00.56-server.txt)

### Describe the bug

Ran a digital miner + excavator overnight, server crashed at 6am and crashes on startup

Edti: set max-tick to -1 in server.properties, now crashing with the following error
java.lang.IllegalArgumentException: duplicate element: [-41, -32]
	at java.util.ImmutableCollections$Set12.<init>(Unknown Source) ~[?:?] {}
	at java.util.Set.of(Unknown Source) ~[?:?] {re:mixin}
	at mekanism.common.tile.machine.TileEntityDigitalMiner.getChunkSet(TileEntityDigitalMiner.java:1029) ~[Mekanism-1.19.2-10.3.7.476.jar%23536!/:10.3.7] {re:classloading}
	at mekanism.common.tile.component.TileComponentChunkLoader.getTileChunks(TileComponentChunkLoader.java:220) ~[Mekanism-1.19.2-10.3.7.476.jar%23536!/:10.3.7] {re:classloading}
	at mekanism.common.tile.component.TileComponentChunkLoader.refreshChunkTickets(TileComponentChunkLoader.java:130) ~[Mekanism-1.19.2-10.3.7.476.jar%23536!/:10.3.7] {re:classloading}
	at mekanism.common.tile.component.TileComponentChunkLoader.refreshChunkTickets(TileComponentChunkLoader.java:96) ~[Mekanism-1.19.2-10.3.7.476.jar%23536!/:10.3.7] {re:classloading}
	at mekanism.common.tile.machine.TileEntityDigitalMiner.updateTargetChunk(TileEntityDigitalMiner.java:1012) ~[Mekanism-1.19.2-10.3.7.476.jar%23536!/:10.3.7] {re:classloading}
	at mekanism.common.tile.machine.TileEntityDigitalMiner.tryMineBlock(TileEntityDigitalMiner.java:438) ~[Mekanism-1.19.2-10.3.7.476.jar%23536!/:10.3.7] {re:classloading}
	at mekanism.common.tile.machine.TileEntityDigitalMiner.onUpdateServer(TileEntityDigitalMiner.java:229) ~[Mekanism-1.19.2-10.3.7.476.jar%23536!/:10.3.7] {re:classloading}
	at mekanism.common.tile.base.TileEntityMekanism.tickServer(TileEntityMekanism.java:574) ~[Mekanism-1.19.2-10.3.7.476.jar%23536!/:10.3.7] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[server-1.19.2-20220805.130853-srg.jar%23669!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[server-1.19.2-20220805.130853-srg.jar%23669!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[server-1.19.2-20220805.130853-srg.jar%23669!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:APP:itshallnottick.mixins.json:EntityTickMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[server-1.19.2-20220805.130853-srg.jar%23669!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:ars_elemental.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23669!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23669!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23669!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23669!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23669!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:?] {re:mixin}

### Steps to reproduce

Crashing on startup

### Expected behaviour

The server to actually run

**Comment by Saereth** [comment]
You should ugprade to 1.4.0 this was fixed on mekanism's side in the new update
