### ISSUE TITLE
Xaero Minimap Crash Null Pointer Exception FTB Interactions 

### ISSUE THREAD

**Issue by IronHide4** [FTBTeam/FTB-Modpack-Issues#2751]
### Modpack

FTB Interactions

### Modpack version

2.12.1

### Log Files

https://paste.ee/p/QQS7y

### Describe the bug

Sudden crash while playing.  I was enchanting some armor when the game shut down. Crash below, full pastebin attached. Crash at line 8447

[17:46:08] [Client thread/INFO] [xaero.common.MinimapLogs]: Exception when loading botania:specialflower texture, using material colour.
[17:46:08] [Client thread/INFO] [xaero.common.MinimapLogs]: Didn't pass the unlisted property check.
[SFM] Indexed 100000 items in 8197ms.
[17:46:09] [Client thread/INFO] [xaero.common.MinimapLogs]: Exception when loading gregtech:machine texture, using material colour.
[17:46:09] [Client thread/INFO] [xaero.common.MinimapLogs]: Didn't pass the unlisted property check.
[17:46:09] [Client thread/INFO] [xaero.common.MinimapLogs]: Exception when loading mekanism:transmitter texture, using material colour.
[17:46:09] [Client thread/INFO] [xaero.common.MinimapLogs]: Didn't pass the unlisted property check.
[17:46:09] [Client thread/INFO] [xaero.common.MinimapLogs]: Exception when loading gregtech:machine texture, using material colour.
[17:46:09] [Client thread/INFO] [xaero.common.MinimapLogs]: Didn't pass the unlisted property check.
[17:46:09] [Client thread/INFO] [xaero.common.MinimapLogs]: Exception when loading roost:roost texture, using material colour.
[17:46:09] [Client thread/INFO] [xaero.common.MinimapLogs]: Didn't pass the unlisted property check.
[17:46:09] [Client thread/INFO] [xaero.common.MinimapLogs]: Exception when loading thermalexpansion:device texture, using material colour.
[17:46:09] [Client thread/INFO] [xaero.common.MinimapLogs]: Didn't pass the unlisted property check.
[17:46:09] [Client thread/INFO] [xaero.common.MinimapLogs]: Exception when loading primal_tech:water_saw texture, using material colour.
[17:46:09] [Client thread/ERROR] [xaero.common.MinimapLogs]: suppressed exception
java.lang.NullPointerException: null
	at xaero.common.minimap.write.MinimapWriter.loadBlockColourFromTexture(MinimapWriter.java:1472) [MinimapWriter.class:?]
	at xaero.common.minimap.write.MinimapWriter.calculateBlockColors(MinimapWriter.java:1364) [MinimapWriter.class:?]
	at xaero.common.minimap.write.MinimapWriter.loadBlockColor(MinimapWriter.java:1005) [MinimapWriter.class:?]
	at xaero.common.minimap.write.MinimapWriter.writeTile(MinimapWriter.java:804) [MinimapWriter.class:?]
	at xaero.common.minimap.write.MinimapWriter.writeChunk(MinimapWriter.java:586) [MinimapWriter.class:?]
	at xaero.common.minimap.write.MinimapWriter.onRender(MinimapWriter.java:415) [MinimapWriter.class:?]
	at xaero.common.events.FMLEventHandler.handleRenderTickEvent(FMLEventHandler.java:85) [FMLEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3661_FMLEventHandler_handleRenderTickEvent_RenderTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:355) [FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1117) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[17:46:09] [Client thread/INFO] [xaero.common.MinimapLogs]: Exception when loading tconstruct:tooltables texture, using material colour.
[17:46:09] [Client thread/INFO] [xaero.common.MinimapLogs]: Didn't pass the unlisted property check.
[17:46:09] [Client thread/INFO] [xaero.common.MinimapLogs]: Exception when loading wizardry:mana_fluid texture, using material colour.
[17:46:09] [Client thread/INFO] [xaero.common.MinimapLogs]: Didn't pass the unlisted property check.
[17:46:09] [Client thread/INFO] [xaero.common.MinimapLogs]: Exception when loading thermalexpansion:cache texture, using material colour.
[17:46:09] [Client thread/INFO] [xaero.common.MinimapLogs]: Didn't pass the unlisted property check.
[17:46:09] [Client thread/INFO] [xaero.common.MinimapLogs]: Exception when loading enderutilities:barrel texture, using material colour.
[17:46:09] [Client thread/INFO] [xaero.common.MinimapLogs]: Didn't pass the unlisted property check.
[17:46:09] [Client thread/INFO] [xaero.common.MinimapLogs]: Exception when loading architecturecraft:sawbench texture, using material colour.
[17:46:09] [Client thread/INFO] [xaero.common.MinimapLogs]: Didn't pass the unlisted property check.
[17:46:09] [Client thread/INFO] [xaero.common.MinimapLogs]: Exception when loading thermalexpansion:device texture, using material colour.
[17:46:09] [Client thread/INFO] [xaero.common.MinimapLogs]: Didn't pass the unlisted property check.
[17:46:13] [Client thread/INFO] [xaero.map.WorldMap]: Exception when loading wizardry:mana_fluid texture, using material colour.
[17:46:13] [Client thread/INFO] [xaero.map.WorldMap]: Didn't pass the unlisted property check.
[17:46:13] [Client thread/INFO] [xaero.map.WorldMap]: Exception when loading gregtech:fluid.oil texture, using material colour.
[17:46:13] [Client thread/INFO] [xaero.map.WorldMap]: Didn't pass the unlisted property check.
[17:46:13] [Client thread/INFO] [xaero.map.WorldMap]: Exception when loading gregtech:fluid.oil texture, using material colour.
[17:46:13] [Client thread/INFO] [xaero.map.WorldMap]: Didn't pass the unlisted property check.
[17:46:13] [Client thread/INFO] [xaero.map.WorldMap]: Exception when loading gregtech:fluid.oil texture, using material colour.
[17:46:13] [Client thread/INFO] [xaero.map.WorldMap]: Didn't pass the unlisted property check.
[17:46:13] [Client thread/INFO] [xaero.map.WorldMap]: Exception when loading gregtech:fluid.oil texture, using material colour.
[17:46:13] [Client thread/INFO] [xaero.map.WorldMap]: Didn't pass the unlisted property check.
[17:46:13] [Client thread/INFO] [xaero.map.WorldMap]: Exception when loading gregtech:fluid.oil texture, using material colour.
[17:46:13] [Client thread/INFO] [xaero.map.WorldMap]: Didn't pass the unlisted property check.
[17:46:13] [Client thread/INFO] [xaero.map.WorldMap]: Exception when loading gregtech:fluid.oil texture, using material colour.
[17:46:13] [Client thread/INFO] [xaero.map.WorldMap]: Didn't pass the unlisted property check.
[17:46:13] [Client thread/INFO] [xaero.map.WorldMap]: Exception when loading gregtech:fluid.oil texture, using material colour.
[17:46:13] [Client thread/INFO] [xaero.map.WorldMap]: Didn't pass the unlisted property check.
[17:46:13] [Client thread/INFO] [xaero.map.WorldMap]: Exception when loading gregtech:fluid.oil texture, using material colour.
[17:46:13] [Client thread/INFO] [xaero.map.WorldMap]: Didn't pass the unlisted property check.
[17:46:14] [Client thread/INFO] [xaero.map.WorldMap]: Exception when loading wizardry:mana_fluid texture, using material colour.
[17:46:14] [Client thread/INFO] [xaero.map.WorldMap]: Didn't pass the unlisted property check.
[17:46:14] [Client thread/INFO] [xaero.map.WorldMap]: Exception when loading botania:specialflower texture, using material colour.
[17:46:14] [Client thread/INFO] [xaero.map.WorldMap]: Didn't pass the unlisted property check.
[17:46:20] [Client thread/INFO] [xaero.map.WorldMap]: Exception when loading wizardry:mana_fluid texture, using material colour.
[17:46:20] [Client thread/INFO] [xaero.map.WorldMap]: Didn't pass the unlisted property check.
[17:46:20] [Client thread/INFO] [xaero.map.WorldMap]: Exception when loading wizardry:mana_fluid texture, using material colour.
[17:46:20] [Client thread/INFO] [xaero.map.WorldMap]: Didn't pass the unlisted property check.
[17:46:20] [Client thread/INFO] [xaero.map.WorldMap]: Exception when loading wizardry:mana_fluid texture, using material colour.
[17:46:20] [Client thread/INFO] [xaero.map.WorldMap]: Didn't pass the unlisted property check.
[17:46:20] [Client thread/INFO] [xaero.map.WorldMap]: Exception when loading wizardry:mana_fluid texture, using material colour.
[17:46:20] [Client thread/INFO] [xaero.map.WorldMap]: Didn't pass the unlisted property check.
[17:46:22] [Client thread/INFO] [xaero.map.WorldMap]: Exception when loading astralsorcery:blockfaketree texture, using material colour.
[17:46:22] [Client thread/INFO] [xaero.map.WorldMap]: Black texture 16
[17:46:23] [Client thread/INFO] [xaero.map.WorldMap]: Exception when loading astralsorcery:fluidblockliquidstarlight texture, using material colour.
[17:46:23] [Client thread/INFO] [xaero.map.WorldMap]: Didn't pass the unlisted property check.
[17:46:23] [Client thread/INFO] [xaero.map.WorldMap]: Exception when loading gregtech:machine texture, using material colour.
[17:46:23] [Client thread/INFO] [xaero.map.WorldMap]: Didn't pass the unlisted property check.
[17:46:23] [Client thread/INFO] [xaero.map.WorldMap]: Exception when loading mekanism:transmitter texture, using material colour.
[17:46:23] [Client thread/INFO] [xaero.map.WorldMap]: Didn't pass the unlisted property check.
[17:46:23] [Client thread/INFO] [xaero.map.WorldMap]: Block file not found: gregtech:cable
[17:46:23] [Client thread/INFO] [xaero.map.WorldMap]: Exception when loading roost:roost texture, using material colour.
[17:46:23] [Client thread/INFO] [xaero.map.WorldMap]: Didn't pass the unlisted property check.
[17:46:23] [Client thread/INFO] [xaero.map.WorldMap]: Exception when loading thermalexpansion:device texture, using material colour.
[17:46:23] [Client thread/INFO] [xaero.map.WorldMap]: Didn't pass the unlisted property check.
[17:46:25] [Client thread/INFO] [xaero.map.WorldMap]: Exception when loading enderutilities:barrel texture, using material colour.
[17:46:25] [Client thread/INFO] [xaero.map.WorldMap]: Didn't pass the unlisted property check.
[17:47:09] [Server thread/WARN] [minecraft/EntityTrackerEntry]: Fetching addPacket for removed entity
[17:47:12] [Client thread/INFO] [xaero.common.MinimapLogs]: Block file not found: gregtech:cable
attack on collide reset
attack on collide reset
[17:51:16] [Client thread/WARN] [minecraft/NetHandlerPlayClient]: Received passengers for unknown entity
attack on collide reset
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000000747b7f8a, pid=11764, tid=0x00000000000019f4
#
# JRE version: Java(TM) SE Runtime Environment (8.0_311-b11) (build 1.8.0_311-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.311-b11 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# V  [jvm.dll+0xb7f8a]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\Jacob\Desktop\MultiMC\instances\1.12.2\.minecraft\hs_err_pid11764.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 1 (0x1).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
MultiMC: Log upload triggered at: 24 Feb 2023 17:54:24 -0700

### Steps to reproduce

crash not related to my actions

### Expected behaviour

unrelated map mod crash

**Comment by Gaz492** [comment]
Did this continue to happen when going back into your world or was it a one-off crash?

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.

We may have something up our sleeves, some may call it a remaster, keep an eye out on our social media platforms for more information.
