### ISSUE TITLE
Random Crash when exploring the End

### ISSUE THREAD

**Issue by SamelCamel** [FTBTeam/FTB-Modpack-Issues#2815]
### Modpack

FTB Inferno

### Modpack version

1.6.1

### Log Files

[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10925119/console.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10925120/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10925121/latest.log)

### Describe the bug

When exploring the End, at certain points, the game will suddenly halt, as if it's experiencing a ton of server lag. Every tip says "Waiting for Server." The client itself runs perfectly fine, it's just the server that stops. I am also playing on a singleplayer game. This seems to happen when loading specific chunks, as it seems to happen at specific locations. The only way to exit the game is by forcibly killing the instance, as clicking Save and Exit just stays stuck on the screen that says "Saving world". I am not able to figure out what is specifically causing this, as none of the logs mention anything abnormal. No exception or error is thrown. 

### Steps to reproduce

1. Enter the End
2. Enter any of the portals that take you outside of the main island (I have also tried just flying instead of taking the portal)
3. Explore around, whether walking or flying. I personally used the Leap spell from Ars Nouveau, and I also tried not using that just in case.
4. In certain areas, the game will permanently hang.

### Expected behaviour

Ideally, the game should run as normal

### Additional information

I have tried allocating more RAM to both the game server and client, to no avail. 

Also note that in these logs, I always hit Save and Exit, before killing the instance. If you want a log that is just me killing the instance as soon as the bug occurs, let me know.

**Comment by Saereth** [comment]
unfortunately your logs dont really show anything out of the ordinary. If you can zip up your world instance and drop me google drive/drop box link I'll load it up and see if I can reproduce it on my end

**Comment by SamelCamel** [comment]
Here's the world instance. After testing some more, I found out it's not necessarily at certain locations, but the bug does occur after attempting to load too many new chunks. I have a hard time avoiding this because I need to cross large gaps in the End, and I guess when doing so, the game is forced to load new chunks too quickly. 

https://drive.google.com/file/d/1xG5_89mm03DZn-z15SRuQTjI0pCWhBVD/view?usp=sharing

**Comment by SamelCamel** [comment]
@Saereth

**Comment by SamelCamel** [comment]
I also found someone on Reddit who is experiencing the same issue, just in the Nether instead of the End. This isn't in Inferno, and I can't find a specific fix, but googling "minecraft ftb waiting for server" pulls up quite a few results.

https://www.reddit.com/r/feedthebeast/comments/nwdlf2/waiting_for_server_on_singleplayer/

**Comment by Articdive** [comment]
I get the same issue, my logs (crash reports) seem to show something more similar to a thread deadlock. But I have the exact same effects and issues as you do.

**Comment by poleshe** [comment]
@Saereth
Hi!

This also happens to us. It happens in the moment a chunk containing an End Citadel is loaded, the servers stops processing ticks and FTB crashes.

If you remove max server tick time, the server just hangs indefinitely, even when all players have left the servers.

No fix found unfortunately as the logs do not output anything.

Thanks,

**Comment by Jabber267** [comment]
Hi

Can confirm our server also hangs then crashes in The End.

It specifically happens when an End City is being loaded in. 
Checked around on google and the fix mentioned to set Max Tick Time to -1, which only makes the server hang indefinitely without crashing and kicking the players. Cannot rejoin either and have to force close the server.

**Comment by ATezier** [comment]
Hello, 

I have the issue. I even added the mod chunk pregenerator to load lots of chunk in the End before going there.
Unfortunately, it didn't work.

**Comment by DamondSword2247** [comment]
I've found that the L_Ender's Cataclysm's Ruined Citadel structure is a constant way to cause this issue. It might be able to randomly occur as well because I got slapped with this bug despite the closest one being over 1k blocks away. Makes getting end materials damn near impossible.

**Comment by m5m1th** [comment]
Also seeing this same issue. I tried cranking the tick watchdog to 10 mins, but it still eventually crashes. I loaded the world up in single player and everything stays interactive, but all ticking has stopped with nothing really useful in the logs. I didn't go in the end until after I upgraded to 1.6.1. I've seen it freeze both near a citadel and what appears to be a vanilla end building and airship. Anything I can do to help track it down?

**Comment by m5m1th** [comment]
I tried loading that same world in 1.5.0 and didn't have any freezes or crashes, so really looks like a regression in 1.6.1.

**Comment by poleshe** [comment]
@Saereth Tagging for visibility! :)

**Comment by m5m1th** [comment]
I also checked against 1.6.0 and it works there, so that should narrow down the potential changes quite a bit.

**Comment by Absylicus** [comment]
we checked some stuff and it looks like there are some problems with the architectury mod maybe?!?
Here is some log:

java.lang.Error: ServerHangWatchdog detected that a single server tick took 120.00 seconds (should be max 0.05)                                                                                                                                        at jdk.internal.misc.Unsafe.park(Native Method) ~[?:?] {}
        at java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source) ~[?:?] {}
        at net.minecraft.util.thread.BlockableEventLoop.m_5667_(BlockableEventLoop.java:152) ~[server-1.18.2-20220404.173914-srg.jar%23289!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:
accesstransformer:B}
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:142) ~[server-1.18.2-20220404.173914-srg.jar%23289!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl
:accesstransformer:B}
        at net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCache.java:129) ~[server-1.18.2-20220404.173914-srg.jar%23289!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:smoothchunk.m
ixins.json:ServerChunkCacheMixin,pl:mixin:A}
        at net.minecraft.world.level.Level.m_6522_(Level.java:169) ~[server-1.18.2-20220404.173914-srg.jar%23289!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin
,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:APP:itshallnottick.mixins.json:EntityTickMixin,pl:mixin:A}
        at net.minecraft.world.level.LevelReader.m_46819_(LevelReader.java:123) ~[server-1.18.2-20220404.173914-srg.jar%23289!/:?] {re:mixin,re:classloading}
        at net.minecraft.world.level.Level.m_6325_(Level.java:164) ~[server-1.18.2-20220404.173914-srg.jar%23289!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin
,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:APP:itshallnottick.mixins.json:EntityTickMixin,pl:mixin:A}
        at net.minecraft.world.level.Level.m_8055_(Level.java:390) ~[server-1.18.2-20220404.173914-srg.jar%23289!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin
,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:APP:itshallnottick.mixins.json:EntityTickMixin,pl:mixin:A}
        at net.minecraft.world.level.LevelReader.m_46859_(LevelReader.java:81) ~[server-1.18.2-20220404.173914-srg.jar%23289!/:?] {re:mixin,re:classloading}
        at net.minecraft.world.entity.Entity.m_20097_(Entity.java:724) ~[server-1.18.2-20220404.173914-srg.jar%23289!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:Entity
Mixin,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinEntity,pl:mixin:APP:mixins.shetiphiancore.json:SPC_ThinBlockHandler$_Entity,pl:mixin:APP:wyml.mixins.json:MixinEntity,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorEn
tity,pl:mixin:APP:mixins.artifacts.json:item.aquadashers.EntityMixin,pl:mixin:APP:mixins.artifacts.json:item.umbrella.EntityMixin,pl:mixin:APP:brutalbosses.mixins.json:EntityCapReader,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP
:expandability.mixins.json:fluidcollision.EntityMixin,pl:mixin:APP:expandability.mixins.json:swimming.EntityMixin,pl:mixin:APP:create.mixins.json:ContraptionDriverInteractMixin,pl:mixin:A}
        at ky.someone.mods.gag.block.NoSolicitorsSign.notBuyingYourStuff(NoSolicitorsSign.java:187) ~[gag-forge-1.2.1-build.10.jar%23153!/:?] {re:classloading,re:mixin}
        at ky.someone.mods.gag.GAG$$Lambda$8349/0x0000000802066800.add(Unknown Source) ~[?:?] {}
        at java.lang.invoke.LambdaForm$DMH/0x0000000800e3c400.invokeInterface(LambdaForm$DMH) ~[?:?] {}
        at java.lang.invoke.LambdaForm$MH/0x0000000803fb1800.invoke(LambdaForm$MH) ~[?:?] {}
        at java.lang.invoke.LambdaForm$MH/0x00000008017d0000.invoke(LambdaForm$MH) ~[?:?] {}
        at java.lang.invoke.LambdaForm$MH/0x0000000800f4d400.invokeExact_MT(LambdaForm$MH) ~[?:?] {}                                                                                                                                                   at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source) ~[?:?] {re:mixin}
        at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-4.11.89-forge.jar%2348!/:?] {re:classloading}                                                                                                         at dev.architectury.event.EventFactory$2.handleInvocation(EventFactory.java:81) ~[architectury-4.11.89-forge.jar%2348!/:?] {re:classloading}
        at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89) ~[guava-31.0.1-jre.jar%2322!/:?] {}
        at jdk.proxy3.$Proxy148.add(Unknown Source) ~[?:?] {}
