### ISSUE TITLE
Kube.js failing to let pack launch on Prism launcher

### ISSUE THREAD

**Issue by InnerLight07** [FTBTeam/FTB-Modpack-Issues#2906]
### Modpack

FTB Skies

### Modpack version

1.0.0

### Log Files

[19:06:52] [INFO ] Loaded script startup_scripts:global.js in 0.436 s
[19:06:52] [INFO ] Loaded script startup_scripts:commands.js in 0.054 s
[19:06:52] [INFO ] Loaded script startup_scripts:custom_blocks.js in 0.01 s
[19:06:52] [INFO ] Loaded script startup_scripts:custom_items.js in 0.013 s
[19:06:52] [INFO ] startup_scripts:eyeoflegend.js:8: Loaded Java class 'net.minecraft.world.entity.projectile.EyeOfEnder'
[19:06:52] [INFO ] startup_scripts:eyeoflegend.js:9: Loaded Java class 'net.minecraft.core.Registry'
[19:06:52] [INFO ] startup_scripts:eyeoflegend.js:10: Loaded Java class 'net.minecraft.tags.TagKey'
[19:06:52] [INFO ] Loaded script startup_scripts:eyeoflegend.js in 0.076 s
! [19:06:52] [ERR] #3: Error loading KubeJS script: startup_scripts:itemsfordimcreator.js': java.lang.RuntimeException: java.lang.ClassNotFoundException: dev.ftb.mods.ftbteamdimensions.event.DimensionCreatedEvent
[19:06:52] [ERR  ] java.lang.RuntimeException: java.lang.ClassNotFoundException: dev.ftb.mods.ftbteamdimensions.event.DimensionCreatedEvent
[19:06:52] [ERR  ] 	at TRANSFORMER/kubejs@1902.6.0-build.142/dev.latvian.mods.kubejs.forge.ForgeEventWrapper.onEvent(ForgeEventWrapper.java:21)
[19:06:52] [ERR  ] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:06:52] [ERR  ] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[19:06:52] [ERR  ] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:06:52] [ERR  ] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[19:06:52] [ERR  ] 	at TRANSFORMER/rhino@1902.2.2-build.264/dev.latvian.mods.rhino.MemberBox.invoke(MemberBox.java:160)
[19:06:52] [ERR  ] 	at TRANSFORMER/rhino@1902.2.2-build.264/dev.latvian.mods.rhino.NativeJavaMethod.call(NativeJavaMethod.java:463)
[19:06:52] [ERR  ] 	at TRANSFORMER/rhino@1902.2.2-build.264/dev.latvian.mods.rhino.Interpreter.interpretLoop(Interpreter.java:1086)
[19:06:52] [ERR  ] 	at TRANSFORMER/rhino@1902.2.2-build.264/dev.latvian.mods.rhino.Interpreter.interpret(Interpreter.java:423)
[19:06:52] [ERR  ] 	at TRANSFORMER/rhino@1902.2.2-build.264/dev.latvian.mods.rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[19:06:52] [ERR  ] 	at TRANSFORMER/rhino@1902.2.2-build.264/dev.latvian.mods.rhino.Context.doTopCall(Context.java:1197)
[19:06:52] [ERR  ] 	at TRANSFORMER/rhino@1902.2.2-build.264/dev.latvian.mods.rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:2619)
[19:06:52] [ERR  ] 	at TRANSFORMER/rhino@1902.2.2-build.264/dev.latvian.mods.rhino.InterpretedFunction.exec(InterpretedFunction.java:83)
[19:06:52] [ERR  ] 	at TRANSFORMER/rhino@1902.2.2-build.264/dev.latvian.mods.rhino.Context.evaluateString(Context.java:615)
[19:06:52] [ERR  ] 	at TRANSFORMER/kubejs@1902.6.0-build.142/dev.latvian.mods.kubejs.script.ScriptFile.load(ScriptFile.java:22)
[19:06:52] [ERR  ] 	at TRANSFORMER/kubejs@1902.6.0-build.142/dev.latvian.mods.kubejs.script.ScriptManager.load(ScriptManager.java:195)
[19:06:52] [ERR  ] 	at TRANSFORMER/kubejs@1902.6.0-build.142/dev.latvian.mods.kubejs.script.ScriptManager.reload(ScriptManager.java:74)
[19:06:52] [ERR  ] 	at TRANSFORMER/kubejs@1902.6.0-build.142/dev.latvian.mods.kubejs.KubeJS.<init>(KubeJS.java:134)
[19:06:52] [ERR  ] 	at TRANSFORMER/kubejs@1902.6.0-build.142/dev.latvian.mods.kubejs.forge.KubeJSForge.<init>(KubeJSForge.java:29)
[19:06:52] [ERR  ] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:06:52] [ERR  ] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[19:06:52] [ERR  ] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:06:52] [ERR  ] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[19:06:52] [ERR  ] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[19:06:52] [ERR  ] 	at LAYER PLUGIN/javafmllanguage@1.19.2-43.2.6/net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68)
[19:06:52] [ERR  ] 	at LAYER PLUGIN/fmlcore@1.19.2-43.2.6/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121)
[19:06:52] [ERR  ] 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[19:06:52] [ERR  ] 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[19:06:52] [ERR  ] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[19:06:52] [ERR  ] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[19:06:52] [ERR  ] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[19:06:52] [ERR  ] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[19:06:52] [ERR  ] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[19:06:52] [ERR  ] Caused by: java.lang.ClassNotFoundException: dev.ftb.mods.ftbteamdimensions.event.DimensionCreatedEvent
[19:06:52] [ERR  ] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[19:06:52] [ERR  ] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[19:06:52] [ERR  ] 	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
[19:06:52] [ERR  ] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[19:06:52] [ERR  ] 	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
[19:06:52] [ERR  ] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[19:06:52] [ERR  ] 	at java.base/java.lang.Class.forName0(Native Method)
[19:06:52] [ERR  ] 	at java.base/java.lang.Class.forName(Class.java:375)
[19:06:52] [ERR  ] 	at TRANSFORMER/kubejs@1902.6.0-build.142/dev.latvian.mods.kubejs.forge.ForgeEventWrapper.onEvent(ForgeEventWrapper.java:18)
[19:06:52] [ERR  ] 	... 32 more
[19:06:52] [INFO ] Loaded script startup_scripts:meshes.js in 0.026 s
[19:06:52] [INFO ] Loaded script startup_scripts:sdrp.js in 0.047 s
[19:06:52] [INFO ] Loaded 7/8 KubeJS startup scripts in 2.019 s

### Describe the bug

When Launching the modpack on Prism, I get the attached error in Kube.js 

### Steps to reproduce

Install pack via FTB install on Prism version 6.3
Launch pack
Wait for first launch, process hangs at the end and delivers that error

### Expected behaviour

I should get to the menu

**Comment by MichaelHillcox** [comment]
Does this happen in the FTB App?

**Comment by InnerLight07** [comment]
No, nor in multi MMC.

**Comment by Saereth** [comment]
Please provide your full latest.log. It looks like your installation is invalid/missing things but we'd need the log to verify that.

**Comment by InnerLight07** [comment]
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11162883/latest.log)
 Attached. I'm totally fine if it's just weirdness with my install, for the record, it just seems odd that it'd exhibit this behavior out of the box on a launcher that's worked for me elsewhere.

**Comment by thederpykrafter** [comment]
im also having the same issue

**Comment by admiral0** [comment]
Logs from kubejs attached. Confirming Prism Launcher on Linux.
[startup.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11243121/startup.txt)

**Comment by admiral0** [comment]
Works on FTB launcher, does not work in prism launcher. Differences:
```shell
◆ ~ ❯❯❯ diff good_modpack.txt bad_modpack.txt
```
```diff
181,182d180
< ./config/ftbpc-client.snbt
< ./config/ftbpc-common.snbt
230,231d227
< ./config/ftbsba-common.toml
< ./config/ftbteamdimensions-client.toml
241,242d236
< ./config/Hexerei-client.toml
< ./config/Hexerei-common.toml
284d277
< ./config/jade/jade.json
412d404
< ./config/moreoverlays.toml
426d417
< ./config/petrock-common.toml
437a429
> ./config/rftoolsstorage-client-1.toml.bak
509a502,505
> ./coremods
> ./crash-reports
> ./crash-reports/crash-2023-04-16_18.17.54-fml.txt
> ./crash-reports/crash-2023-04-16_20.24.20-fml.txt
589d584
< ./fancymenu_data/default_scale_set.fm
598,599c593
< ./folder.jpg
< ./instance.json
---
> ./icon.png
1180d1173
< ./log4jfixer.jar
1182c1175,1176
< ./logs/console.log
---
> ./logs/2023-04-16-1.log.gz
> ./logs/debug-1.log.gz
1189a1184,1185
> ./logs/minetogether/2023-04-16-1.log.gz
> ./logs/minetogether/debug-1.log.gz
1193d1188
< ./mods/accelerated-decay-forge-1.0.0+mc1.19.2.jar
1204d1198
< ./mods/antiblocksrechiseled-0.1.7.jar
1320d1313
< ./mods/ftb-pack-companion-2.0.3-build.8+mc1.19.2.jar
1323,1324d1315
< ./mods/ftb-skyblock-addons-1.0.0+mc1.19.2.jar
< ./mods/ftb-team-dimensions-1.0.1-build.3.jar
1335d1325
< ./mods/hexerei-0.3.0.jar
1361d1350
< ./mods/kube-utils-forge-1.0.2+mc1.19.2.jar
1386d1374
< ./mods/moreoverlays-1.21.5-mc1.19.2.jar
1404d1391
< ./mods/petrock-0.11.14.jar
1504a1492,1493
> ./screenshots
> ./server-resource-packs
1507c1496
< ./version.json
---
> ./texturepacks
```

**Comment by thederpykrafter** [comment]
Can someone address this before it goes stale?

**Comment by ad-nadroj** [comment]
Was having the same issue. It looks like Prism wasn't installing the modpack correctly. I fixed the issue by installing the modpack via FTB and then copied that into the instance created by Prism (overwriting all files). Modpack started perfectly after that

**Comment by InnerLight07** [comment]
I've used Prism extensively, and manually installed those mods as part of both the initial install and the reinstall I did before opening the issue. I've moved on from the pack, but it seems unlikely that was the sole cause of the initial issue.
