### ISSUE TITLE
NPE on wanderingtrader event spawn

### ISSUE THREAD

**Issue by ukmcplyr** [FTBTeam/FTB-Modpack-Issues#2933]
### Modpack

FTB Skies

### Modpack version

1.0.0

### Log Files

[latest.log](https://pste.ch/uqajojuzoq.sql)

### Describe the bug

Hit the following NPE in what looks like Apotheosis code a few times today on a server:

```

[05Apr2023 22:08:21.691] [Server thread/ERROR] [KubeJS Server/]: ! server_scripts:events/wanderingtrader.js:28: Error occurred while handling event 'EntityEvents.spawned': net.minecraft.ReportedException: Saving entity NBT
[05Apr2023 22:08:21.694] [Server thread/ERROR] [KubeJS Server/]: server_scripts:events/wanderingtrader.js:28: net.minecraft.ReportedException: Saving entity NBT
[05Apr2023 22:08:21.695] [Server thread/ERROR] [KubeJS Server/]: server_scripts:events/wanderingtrader.js:28: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.Entity.m_20240_(Entity.java:1546)
[05Apr2023 22:08:21.695] [Server thread/ERROR] [KubeJS Server/]: server_scripts:events/wanderingtrader.js:28: 	at TRANSFORMER/kubejs@1902.6.0-build.142/dev.latvian.mods.kubejs.core.EntityKJS.kjs$getFullNBT(EntityKJS.java:244)
[...]
[05Apr2023 22:08:21.698] [Server thread/ERROR] [KubeJS Server/]: server_scripts:events/wanderingtrader.js:28: Caused by: java.lang.NullPointerException: Cannot invoke "shadows.apotheosis.adventure.loot.LootRarity.ordinal()" because "rarity" is null
[05Apr2023 22:08:21.698] [Server thread/ERROR] [KubeJS Server/]: server_scripts:events/wanderingtrader.js:28: 	at TRANSFORMER/apotheosis@6.1.5/shadows.apotheosis.adventure.affix.trades.AffixTrade.m_213663_(AffixTrade.java:37)
```

The trader spawns okay but is unresponsive and no trade UI pops up.

Passive mobs haven't been spawning anywhere near as often as they did earlier in the day though I don't know if that's related.

### Steps to reproduce

On a server:
1. Wait for a wandering trader to spawn
2. Try and access its UI

### Expected behaviour

Functional wandering trader

**Comment by Saereth** [comment]
Apotheosis bug, I've reported it to the mod dev, waiting for a fix
