### ISSUE TITLE
Player will lag and when they DC, server will spam logs with Network Dispatcher Exception 

### ISSUE THREAD

**Issue by tankirules** [FTBTeam/FTB-Modpack-Issues#2974]
### Modpack

FTB Interactions

### Modpack version

2.12.1

### Log Files

https://drive.google.com/file/d/1If6Qr1N-cv9mfePUcVqdHiZvzxos6ocu/view?usp=sharing

### Describe the bug

(This might sound convoluted)
Once, every day, a player will not receive information from the server. On their screen, they will appear to be lagging, however, the server, and other players, can see their typing - but not themselves (this can happen to different players). Once they disconnect, the server will start freezing for everyone, while spamming this error message in the logs, multiple times in a second.

[01:06:09] [Netty Server IO #3/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote host
    at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_302]
    at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:55) ~[?:1.8.0_302]
    at sun.nio.ch.IOUtil.write(IOUtil.java:148) ~[?:1.8.0_302]
    at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:503) ~[?:1.8.0_302]
    at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[minecraft_server.1.12.2.jar:?]
    at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [minecraft_server.1.12.2.jar:?]
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [minecraft_server.1.12.2.jar:?]
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [minecraft_server.1.12.2.jar:?]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [minecraft_server.1.12.2.jar:?]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [minecraft_server.1.12.2.jar:?]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [minecraft_server.1.12.2.jar:?]
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [minecraft_server.1.12.2.jar:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]

This literally makes the logs multiple gigabytes big. There is almost no information online pertaining to this error. Other than this daily occurrence, everyone can play and connect on the server just fine.

### Steps to reproduce

I am honestly unsure how to reproduce this. All I know is, once a day, this issue occurs, and to different players as well. But, I find that it normally occurs when players have not been on the server for a while (12 hours or less).

### Expected behaviour

This error should not occur

### Additional information

Server is running on win 10.

**Comment by Gaz492** [comment]
A little late getting back to you, but do you happen to have the modpack logs from the player that runs into this issues?
The client log may give us more information as to whats going on here.
