### ISSUE TITLE
FTB Skies 1.0.5 Crashes on startup

### ISSUE THREAD

**Issue by DarkHelmet2023** [FTBTeam/FTB-Modpack-Issues#3086]
### Modpack

FTB Skies

### Modpack version

1.0.5

### Log Files

---- Minecraft Crash Report ----
// My bad.

Time: 2023-04-13 15:04:39
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.m_5962_()" because the return value of "org.cyclops.everlastingabilities.core.helper.WorldHelpers.getActiveLevel()" is null
	at org.cyclops.everlastingabilities.api.capability.ItemStackMutableAbilityStore.getRegistry(ItemStackMutableAbilityStore.java:34) ~[EverlastingAbilities-1.19.2-2.0.0.jar%23550!/:2.0.0] {re:classloading}
	at org.cyclops.everlastingabilities.api.capability.ItemStackMutableAbilityStore.getInnerStore(ItemStackMutableAbilityStore.java:44) ~[EverlastingAbilities-1.19.2-2.0.0.jar%23550!/:2.0.0] {re:classloading}
	at org.cyclops.everlastingabilities.api.capability.ItemStackMutableAbilityStore.getAbilities(ItemStackMutableAbilityStore.java:94) ~[EverlastingAbilities-1.19.2-2.0.0.jar%23550!/:2.0.0] {re:classloading}
	at org.cyclops.everlastingabilities.EverlastingAbilities.lambda$onLivingDeath$4(EverlastingAbilities.java:298) ~[EverlastingAbilities-1.19.2-2.0.0.jar%23550!/:2.0.0] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150) ~[forge-1.19.2-43.2.6-universal.jar%23754!/:?] {re:mixin,re:classloading}
	at org.cyclops.everlastingabilities.EverlastingAbilities.onLivingDeath(EverlastingAbilities.java:268) ~[EverlastingAbilities-1.19.2-2.0.0.jar%23550!/:2.0.0] {re:classloading}
	at org.cyclops.everlastingabilities.__EverlastingAbilities_onLivingDeath_LivingDeathEvent.invoke(.dynamic) ~[EverlastingAbilities-1.19.2-2.0.0.jar%23550!/:2.0.0] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:354) ~[forge-1.19.2-43.2.6-universal.jar%23754!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.hammerlib.json:ForgeHooksMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_6667_(LivingEntity.java:1277) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LivingEntityMixin,pl:mixin:APP:ad_astra_giselle_addon.mixin.common.json:minecraft.LivingEntityMixin,pl:mixin:APP:maxhealthfix.common.mixins.json:MixinLivingEntity,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:LivingEntityInvoker,pl:mixin:APP:supplementaries-common.mixins.json:LivingEntityMixin,pl:mixin:APP:botania_xplat.mixins.json:LivingEntityAccessor,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:mixins.cofhcore.json:LivingEntityMixin,pl:mixin:APP:ars_nouveau.mixins.json:elytra.MixinLivingEntity,pl:mixin:APP:ars_nouveau.mixins.json:perks.PerkLivingEntity,pl:mixin:APP:responsiveshields.mixin.json:MixinTicksConst,pl:mixin:APP:ad_astra-common.mixins.json:LivingEntityMixin,pl:mixin:APP:ad_astra-common.mixins.json:gravity.LivingEntityGravityMixin,pl:mixin:APP:tetra.mixins.json:LivingEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:entity.MixinLivingEntity,pl:mixin:APP:spirit.common.mixins.json:LivingEntityMixin,pl:mixin:APP:voidtotem.mixins.json:LivingEntityMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinLivingEntity,pl:mixin:APP:hexplat.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:quark.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:charmofundying.mixins.json:MixinLivingEntity,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:expandability-common.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:scena.mixins.json:common.LivingEntityEquipmentSlotMixin,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1155) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LivingEntityMixin,pl:mixin:APP:ad_astra_giselle_addon.mixin.common.json:minecraft.LivingEntityMixin,pl:mixin:APP:maxhealthfix.common.mixins.json:MixinLivingEntity,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:LivingEntityInvoker,pl:mixin:APP:supplementaries-common.mixins.json:LivingEntityMixin,pl:mixin:APP:botania_xplat.mixins.json:LivingEntityAccessor,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:mixins.cofhcore.json:LivingEntityMixin,pl:mixin:APP:ars_nouveau.mixins.json:elytra.MixinLivingEntity,pl:mixin:APP:ars_nouveau.mixins.json:perks.PerkLivingEntity,pl:mixin:APP:responsiveshields.mixin.json:MixinTicksConst,pl:mixin:APP:ad_astra-common.mixins.json:LivingEntityMixin,pl:mixin:APP:ad_astra-common.mixins.json:gravity.LivingEntityGravityMixin,pl:mixin:APP:tetra.mixins.json:LivingEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:entity.MixinLivingEntity,pl:mixin:APP:spirit.common.mixins.json:LivingEntityMixin,pl:mixin:APP:voidtotem.mixins.json:LivingEntityMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinLivingEntity,pl:mixin:APP:hexplat.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:quark.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:charmofundying.mixins.json:MixinLivingEntity,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:expandability-common.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:scena.mixins.json:common.LivingEntityEquipmentSlotMixin,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:A}
	at mob_grinding_utils.items.ItemImaginaryInvisibleNotReallyThereSword.m_7579_(ItemImaginaryInvisibleNotReallyThereSword.java:26) ~[mob_grinding_utils-1.19.2-0.4.48.jar%23636!/:1.19.2-0.4.48] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41640_(ItemStack.java:392) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:kubejs-common.mixins.json:ItemStackMixin,pl:mixin:APP:mixins.hammerlib.json:ItemStackMixin,pl:mixin:APP:apotheosis.mixins.json:ItemStackMixin,pl:mixin:APP:tetra.mixins.json:MixinItemStack,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:ae2wtlib.mixins.json:Restock,pl:mixin:APP:itemfilters-common.mixins.json:ItemStackMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinItemStack,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:APP:ars_instrumentum.mixins.json:GlyphCostMixin,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.m_5706_(Player.java:1218) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apotheosis.mixins.json:PlayerMixin,pl:mixin:APP:darkutils.mixins.json:MixinPlayer,pl:mixin:APP:darkutils.mixins.json:AccessorPlayer,pl:mixin:APP:supplementaries.mixins.json:PlayerProjectileMixin,pl:mixin:APP:botania_xplat.mixins.json:PlayerMixin,pl:mixin:APP:endertrigon.mixins.json:MixinPlayer,pl:mixin:APP:ars_nouveau.mixins.json:elytra.ElytraPlayerMixin,pl:mixin:APP:ad_astra-common.mixins.json:PlayerMixin,pl:mixin:APP:tetra.mixins.json:MixinPlayerEntity,pl:mixin:APP:elementalcraft.mixins.json:MixinPlayer,pl:mixin:APP:expandability-common.mixins.json:swimming.PlayerMixin,pl:mixin:APP:kubejs-common.mixins.json:PlayerMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayer.m_5706_(ServerPlayer.java:1368) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ServerPlayerMixin,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerPlayerMixin,pl:mixin:APP:ftbteamdimensions.mixins.json:ServerPlayerAccess,pl:mixin:APP:ftbteamdimensions.mixins.json:ServerPlayerMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.ANServerPlayerMixin,pl:mixin:APP:ftbpc.mixins.json:features.bedtime.ServerPlayerMixin,pl:mixin:A}
	at mob_grinding_utils.tile.TileEntitySaw.activateBlock(TileEntitySaw.java:98) ~[mob_grinding_utils-1.19.2-0.4.48.jar%23636!/:1.19.2-0.4.48] {re:classloading}
	at mob_grinding_utils.tile.TileEntitySaw.serverTick(TileEntitySaw.java:63) ~[mob_grinding_utils-1.19.2-0.4.48.jar%23636!/:1.19.2-0.4.48] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(MixinLevel.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:beefix:Level,re:classloading,pl:accesstransformer:B,xf:fml:beefix:Level,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:ftbteamdimensions.mixins.json:LevelAccess,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin,pl:mixin:APP:mixins.integrateddynamics.json:MixinLevel,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:ftbteamdimensions.mixins.json:ServerLevelAccess,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.cyclops.everlastingabilities.api.capability.ItemStackMutableAbilityStore.getRegistry(ItemStackMutableAbilityStore.java:34) ~[EverlastingAbilities-1.19.2-2.0.0.jar%23550!/:2.0.0] {re:classloading}
	at org.cyclops.everlastingabilities.api.capability.ItemStackMutableAbilityStore.getInnerStore(ItemStackMutableAbilityStore.java:44) ~[EverlastingAbilities-1.19.2-2.0.0.jar%23550!/:2.0.0] {re:classloading}
	at org.cyclops.everlastingabilities.api.capability.ItemStackMutableAbilityStore.getAbilities(ItemStackMutableAbilityStore.java:94) ~[EverlastingAbilities-1.19.2-2.0.0.jar%23550!/:2.0.0] {re:classloading}
	at org.cyclops.everlastingabilities.EverlastingAbilities.lambda$onLivingDeath$4(EverlastingAbilities.java:298) ~[EverlastingAbilities-1.19.2-2.0.0.jar%23550!/:2.0.0] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150) ~[forge-1.19.2-43.2.6-universal.jar%23754!/:?] {re:mixin,re:classloading}
	at org.cyclops.everlastingabilities.EverlastingAbilities.onLivingDeath(EverlastingAbilities.java:268) ~[EverlastingAbilities-1.19.2-2.0.0.jar%23550!/:2.0.0] {re:classloading}
	at org.cyclops.everlastingabilities.__EverlastingAbilities_onLivingDeath_LivingDeathEvent.invoke(.dynamic) ~[EverlastingAbilities-1.19.2-2.0.0.jar%23550!/:2.0.0] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:354) ~[forge-1.19.2-43.2.6-universal.jar%23754!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.hammerlib.json:ForgeHooksMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_6667_(LivingEntity.java:1277) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LivingEntityMixin,pl:mixin:APP:ad_astra_giselle_addon.mixin.common.json:minecraft.LivingEntityMixin,pl:mixin:APP:maxhealthfix.common.mixins.json:MixinLivingEntity,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:LivingEntityInvoker,pl:mixin:APP:supplementaries-common.mixins.json:LivingEntityMixin,pl:mixin:APP:botania_xplat.mixins.json:LivingEntityAccessor,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:mixins.cofhcore.json:LivingEntityMixin,pl:mixin:APP:ars_nouveau.mixins.json:elytra.MixinLivingEntity,pl:mixin:APP:ars_nouveau.mixins.json:perks.PerkLivingEntity,pl:mixin:APP:responsiveshields.mixin.json:MixinTicksConst,pl:mixin:APP:ad_astra-common.mixins.json:LivingEntityMixin,pl:mixin:APP:ad_astra-common.mixins.json:gravity.LivingEntityGravityMixin,pl:mixin:APP:tetra.mixins.json:LivingEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:entity.MixinLivingEntity,pl:mixin:APP:spirit.common.mixins.json:LivingEntityMixin,pl:mixin:APP:voidtotem.mixins.json:LivingEntityMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinLivingEntity,pl:mixin:APP:hexplat.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:quark.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:charmofundying.mixins.json:MixinLivingEntity,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:expandability-common.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:scena.mixins.json:common.LivingEntityEquipmentSlotMixin,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1155) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LivingEntityMixin,pl:mixin:APP:ad_astra_giselle_addon.mixin.common.json:minecraft.LivingEntityMixin,pl:mixin:APP:maxhealthfix.common.mixins.json:MixinLivingEntity,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:LivingEntityInvoker,pl:mixin:APP:supplementaries-common.mixins.json:LivingEntityMixin,pl:mixin:APP:botania_xplat.mixins.json:LivingEntityAccessor,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:mixins.cofhcore.json:LivingEntityMixin,pl:mixin:APP:ars_nouveau.mixins.json:elytra.MixinLivingEntity,pl:mixin:APP:ars_nouveau.mixins.json:perks.PerkLivingEntity,pl:mixin:APP:responsiveshields.mixin.json:MixinTicksConst,pl:mixin:APP:ad_astra-common.mixins.json:LivingEntityMixin,pl:mixin:APP:ad_astra-common.mixins.json:gravity.LivingEntityGravityMixin,pl:mixin:APP:tetra.mixins.json:LivingEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:entity.MixinLivingEntity,pl:mixin:APP:spirit.common.mixins.json:LivingEntityMixin,pl:mixin:APP:voidtotem.mixins.json:LivingEntityMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinLivingEntity,pl:mixin:APP:hexplat.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:quark.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:charmofundying.mixins.json:MixinLivingEntity,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:expandability-common.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:scena.mixins.json:common.LivingEntityEquipmentSlotMixin,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:A}
	at mob_grinding_utils.items.ItemImaginaryInvisibleNotReallyThereSword.m_7579_(ItemImaginaryInvisibleNotReallyThereSword.java:26) ~[mob_grinding_utils-1.19.2-0.4.48.jar%23636!/:1.19.2-0.4.48] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41640_(ItemStack.java:392) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:kubejs-common.mixins.json:ItemStackMixin,pl:mixin:APP:mixins.hammerlib.json:ItemStackMixin,pl:mixin:APP:apotheosis.mixins.json:ItemStackMixin,pl:mixin:APP:tetra.mixins.json:MixinItemStack,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:ae2wtlib.mixins.json:Restock,pl:mixin:APP:itemfilters-common.mixins.json:ItemStackMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinItemStack,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:APP:ars_instrumentum.mixins.json:GlyphCostMixin,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.m_5706_(Player.java:1218) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apotheosis.mixins.json:PlayerMixin,pl:mixin:APP:darkutils.mixins.json:MixinPlayer,pl:mixin:APP:darkutils.mixins.json:AccessorPlayer,pl:mixin:APP:supplementaries.mixins.json:PlayerProjectileMixin,pl:mixin:APP:botania_xplat.mixins.json:PlayerMixin,pl:mixin:APP:endertrigon.mixins.json:MixinPlayer,pl:mixin:APP:ars_nouveau.mixins.json:elytra.ElytraPlayerMixin,pl:mixin:APP:ad_astra-common.mixins.json:PlayerMixin,pl:mixin:APP:tetra.mixins.json:MixinPlayerEntity,pl:mixin:APP:elementalcraft.mixins.json:MixinPlayer,pl:mixin:APP:expandability-common.mixins.json:swimming.PlayerMixin,pl:mixin:APP:kubejs-common.mixins.json:PlayerMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayer.m_5706_(ServerPlayer.java:1368) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ServerPlayerMixin,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerPlayerMixin,pl:mixin:APP:ftbteamdimensions.mixins.json:ServerPlayerAccess,pl:mixin:APP:ftbteamdimensions.mixins.json:ServerPlayerMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.ANServerPlayerMixin,pl:mixin:APP:ftbpc.mixins.json:features.bedtime.ServerPlayerMixin,pl:mixin:A}
	at mob_grinding_utils.tile.TileEntitySaw.activateBlock(TileEntitySaw.java:98) ~[mob_grinding_utils-1.19.2-0.4.48.jar%23636!/:1.19.2-0.4.48] {re:classloading}
	at mob_grinding_utils.tile.TileEntitySaw.serverTick(TileEntitySaw.java:63) ~[mob_grinding_utils-1.19.2-0.4.48.jar%23636!/:1.19.2-0.4.48] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(MixinLevel.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:beefix:Level,re:classloading,pl:accesstransformer:B,xf:fml:beefix:Level,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:ftbteamdimensions.mixins.json:LevelAccess,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin,pl:mixin:APP:mixins.integrateddynamics.json:MixinLevel,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:ftbteamdimensions.mixins.json:ServerLevelAccess,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
-- Block entity being ticked --
Details:
	Name: mob_grinding_utils:saw // mob_grinding_utils.tile.TileEntitySaw

### Describe the bug

Start game, gets to 100% crashes shortly after getting to 100%. 

### Steps to reproduce

1. Get the newest update
2. Launch the game
3. wait for crash at 100%

### Expected behaviour

Game starts after getting to 100% loading. Retry fails as well.

**Comment by DarkHelmet2023** [comment]
This did fix my issue thank you for the quick fix.
