### ISSUE TITLE
INFERNO - INVALID PLAYER DATA

### ISSUE THREAD

**Issue by Exovi** [FTBTeam/FTB-Modpack-Issues#3107]
### Modpack

FTB Inferno

### Modpack version

1.7

### Describe the bug

Updated pack to latest version. Wanted to make a new world. Created a singleplayer world. Generated successfully... but when I try to connect, I am kicked with a "Connection Lost - Invalid Player Data" error.

The world is there, shows up in Singleplayer menu. But I can't join.

I have tried making several new worlds, and a complete fresh re-install of Inferno (deleted original instance). No luck. Another user has the same issue on Discord

### Steps to reproduce

1. Complete fresh install of Inferno
2. Launch singleplayer
3. Create World
4. ... get kicked
5. Submit bug report

### Expected behaviour

Ability to connect to singleplayer world

### Screenshots

![Screenshot 2023-04-14 144710](https://user-images.githubusercontent.com/10617209/232146153-2437b711-7c45-460d-a8ad-c91c8cda0339.png)

**Comment by Thepowerisreal** [comment]
I am having the same issues. If I create a world in an older version such as 1.2.1, I can load that world fine in the 1.7.0 version. However I can not create a new world in 1.7.0

Below is a copy of the latest.log that has the problem that I believe is related to FTB Teams:

[17:49:58] [Server thread/ERROR]: Couldn't place player in world
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
	at dev.ftb.mods.ftbteams.data.TeamManager.getPlayerTeam(TeamManager.java:112) ~[ftb-teams-forge-1802.2.10-build.96.jar%23178!/:1802.2.10-build.96]
	at dev.ftb.mods.ftbteams.data.TeamManager.createParty(TeamManager.java:399) ~[ftb-teams-forge-1802.2.10-build.96.jar%23178!/:1802.2.10-build.96]
	at dev.ftb.mods.ftbteams.data.TeamManager.createParty(TeamManager.java:390) ~[ftb-teams-forge-1802.2.10-build.96.jar%23178!/:1802.2.10-build.96]
	at dev.ftb.mods.ftbteamislands.Events.onTeamCreated(Events.java:68) ~[ftb-team-islands-forge-1801-2.4-build.28.jar%23177!/:1801-2.4-build.28]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-4.11.90-forge.jar%2370!/:?]
	at dev.architectury.event.EventFactory$4.handleInvocation(EventFactory.java:125) ~[architectury-4.11.90-forge.jar%2370!/:?]
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89) ~[guava-31.0.1-jre.jar%2329!/:?]
	at jdk.proxy3.$Proxy101.accept(Unknown Source) ~[?:?]
	at dev.ftb.mods.ftbteams.data.Team.onCreated(Team.java:70) ~[ftb-teams-forge-1802.2.10-build.96.jar%23178!/:1802.2.10-build.96]
	at dev.ftb.mods.ftbteams.data.TeamManager.createPlayerTeam(TeamManager.java:280) ~[ftb-teams-forge-1802.2.10-build.96.jar%23178!/:1802.2.10-build.96]
	at dev.ftb.mods.ftbteams.data.TeamManager.playerLoggedIn(TeamManager.java:293) ~[ftb-teams-forge-1802.2.10-build.96.jar%23178!/:1802.2.10-build.96]
	at dev.ftb.mods.ftbteams.FTBTeams.playerLoggedIn(FTBTeams.java:82) ~[ftb-teams-forge-1802.2.10-build.96.jar%23178!/:1802.2.10-build.96]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-4.11.90-forge.jar%2370!/:?]
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62) ~[architectury-4.11.90-forge.jar%2370!/:?]
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89) ~[guava-31.0.1-jre.jar%2329!/:?]
	at jdk.proxy3.$Proxy188.join(Unknown Source) ~[?:?]
	at dev.architectury.event.forge.EventHandlerImplCommon.event(EventHandlerImplCommon.java:112) ~[architectury-4.11.90-forge.jar%2370!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler_859_EventHandlerImplCommon_event_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:833) ~[forge-1.18.2-40.1.93-universal.jar%23325!/:?]
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:238) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:138) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:125) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10050_(ServerLoginPacketListenerImpl.java:69) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:241) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[17:49:58] [Render thread/WARN]: ESM: Muffled list not found; Creating empty Muffled list
[17:49:58] [Render thread/WARN]: ESM: Anchor list not found; Creating empty Anchor list
[17:49:58] [Server thread/INFO]: TrueBrisken lost connection: Invalid player data
[17:49:58] [Server thread/INFO]: TrueBrisken left the game
[17:49:58] [Render thread/INFO]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggedInEvent
[17:49:58] [Render thread/INFO]: JEI StartEventObserver transitioning state from DISABLED to ENABLED
[17:49:58] [Server thread/INFO]: Stopping singleplayer server as player logged out
[17:49:58] [Server thread/INFO]: Stopping server
[17:49:58] [Server thread/INFO]: Saving players
[17:49:58] [Server thread/INFO]: Saving worlds
[17:49:59] [Render thread/INFO]: Released client Flux Networks cache
[17:49:59] [Render thread/INFO]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggedOutEvent
[17:49:59] [Render thread/INFO]: JEI StartEventObserver transitioning state from ENABLED to DISABLED
[17:49:59] [Render thread/INFO]: Removed all colony views
[17:50:00] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Test]'/minecraft:overworld
[17:50:00] [Server thread/INFO]: Saved active rites successfully
[17:50:01] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Test]'/bonsaitrees3:growtown
[17:50:01] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Test]'/minecraft:the_nether
[17:50:01] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Test]'/witherstormmod:bowels
[17:50:01] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Test]'/minecraft:the_end
[17:50:01] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Test]'/bloodmagic:dungeon
[17:50:01] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Test]'/ae2:spatial_storage
[17:50:01] [Server thread/INFO]: ThreadedAnvilChunkStorage (Test): All chunks are saved
[17:50:01] [Server thread/INFO]: ThreadedAnvilChunkStorage (growtown): All chunks are saved
[17:50:01] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[17:50:01] [Server thread/INFO]: ThreadedAnvilChunkStorage (bowels): All chunks are saved
[17:50:01] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[17:50:01] [Server thread/INFO]: ThreadedAnvilChunkStorage (dungeon): All chunks are saved
[17:50:01] [Server thread/INFO]: ThreadedAnvilChunkStorage (spatial_storage): All chunks are saved
[17:50:01] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[17:50:05] [Server thread/INFO]: Shutting down scheduler thread
[17:50:05] [Server thread/INFO]: Scheduler ftbbackups2_$_NON_CLUSTERED shutting down.
[17:50:05] [Server thread/INFO]: Scheduler ftbbackups2_$_NON_CLUSTERED paused.
[17:50:05] [Server thread/INFO]: Scheduler ftbbackups2_$_NON_CLUSTERED shutdown complete.
[17:50:05] [Server thread/INFO]: Shutting down the config watcher executor
[17:50:05] [Server thread/INFO]: Shutting down backup cleaning executor
[17:50:05] [Server thread/INFO]: Shutting down backup executor
[17:50:05] [Server thread/INFO]: =========Checking everything is shut down============
[17:50:05] [Server thread/INFO]: Scheduler Shutdown:true
[17:50:05] [Server thread/INFO]: Config watcher Shutdown:true
[17:50:05] [Server thread/INFO]: Cleaner watcher Shutdown:true
[17:50:05] [Server thread/INFO]: Backup Executor Shutdown:true

**Comment by afolk2** [comment]
Any information on this? I'm also experiencing this issue.
Since it might not be apparent, it returns back to the multiplayer server list as opposed to single-player world selection as one would expect

**Comment by Exovi** [comment]
> Any information on this? I'm also experiencing this issue. Since it might not be apparent, it returns back to the multiplayer server list as opposed to single-player world selection as one would expect

Someone found that downgrading to an earlier version, creating world, joining world, then updating modpack fixes it. 
Allows you to join the world with the current version. 

Something in the update broke it

**Comment by Saereth** [comment]
Downgrading, making a wold and then updating resolves this, I've downgraded teams for the next update

**Comment by Riathel** [comment]
It looks like this bug is back in 1.9.0

**Comment by edukstro** [comment]
Same error here
