### ISSUE TITLE
Crashes server 

### ISSUE THREAD

**Issue by theeranan** [FTBTeam/FTB-Modpack-Issues#3166]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Log Files

[14:57:48] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:906) ~[server-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) [?:?] {}
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/Lists
        at ironfurnaces.blocks.furnaces.BlockIronFurnaceBase.getComparatorInputOverride(BlockIronFurnaceBase.java:296) ~[ironfurnaces-1.18.2-3.3.3.jar%23139!/:3.3.3] {re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
        at ironfurnaces.blocks.furnaces.BlockIronFurnaceBase.calculateOutput(BlockIronFurnaceBase.java:370) ~[ironfurnaces-1.18.2-3.3.3.jar%23139!/:3.3.3] {re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
        at ironfurnaces.blocks.furnaces.BlockIronFurnaceBase.m_6376_(BlockIronFurnaceBase.java:410) ~[ironfurnaces-1.18.2-3.3.3.jar%23139!/:3.3.3] {re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60775_(BlockBehaviour.java:560) ~[server-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:random_tick_block,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:libx:random_tick_block,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:A}
        at ironfurnaces.tileentity.furnaces.BlockIronFurnaceTileBase.tick(BlockIronFurnaceTileBase.java:572) ~[ironfurnaces-1.18.2-3.3.3.jar%23139!/:3.3.3] {re:classloading,pl:rei_plugin_compatibilities:B}      
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[server-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
        at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[server-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
        at net.minecraft.world.level.Level.m_46463_(Level.java:476) ~[server-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:A}
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:327) ~[server-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:MixinServerLevel,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[server-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        ... 5 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.Lists
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
        at ironfurnaces.blocks.furnaces.BlockIronFurnaceBase.getComparatorInputOverride(BlockIronFurnaceBase.java:296) ~[ironfurnaces-1.18.2-3.3.3.jar%23139!/:3.3.3] {re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
        at ironfurnaces.blocks.furnaces.BlockIronFurnaceBase.calculateOutput(BlockIronFurnaceBase.java:370) ~[ironfurnaces-1.18.2-3.3.3.jar%23139!/:3.3.3] {re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
        at ironfurnaces.blocks.furnaces.BlockIronFurnaceBase.m_6376_(BlockIronFurnaceBase.java:410) ~[ironfurnaces-1.18.2-3.3.3.jar%23139!/:3.3.3] {re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60775_(BlockBehaviour.java:560) ~[server-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:random_tick_block,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:libx:random_tick_block,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:A}
        at ironfurnaces.tileentity.furnaces.BlockIronFurnaceTileBase.tick(BlockIronFurnaceTileBase.java:572) ~[ironfurnaces-1.18.2-3.3.3.jar%23139!/:3.3.3] {re:classloading,pl:rei_plugin_compatibilities:B}      
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[server-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
        at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[server-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
        at net.minecraft.world.level.Level.m_46463_(Level.java:476) ~[server-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:A}
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:327) ~[server-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:MixinServerLevel,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[server-1.18.2-20220404.173914-srg.jar%23261!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        ... 5 more

[14:57:48] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 99f4edf8-8993-4e30-bd26-beaaef4b3b26

### Describe the bug

[crash-2023-04-18_14.57.48-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11259358/crash-2023-04-18_14.57.48-server.txt)

### Steps to reproduce

Server crashing after I'm set ironfurnace to comparator mode

### Expected behaviour

Crash

### Screenshots

![1](https://user-images.githubusercontent.com/16732363/232711207-2414d558-1732-4bde-bf5a-f4a5e644feeb.png)

**Comment by UnRealDinnerbone** [comment]
Bug in the Iron Furnace mod https://github.com/Qelifern/IronFurnaces/issues/158

**Comment by UnRealDinnerbone** [comment]
Closing this issue as it seems that author is not going to fix it
