### ISSUE TITLE
FTB-Direwolf20 1.8.0 Beta serverinstall linux multiple ERRORS on starting Server

### ISSUE THREAD

**Issue by phil2sat** [FTBTeam/FTB-Modpack-Issues#3218]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.8.0

### Log Files

[log.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11307473/log.txt)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11307618/debug.log)

openjdk 17.0.6 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)

Distro:          Debian GNU/Linux 11 (bullseye)
Architecture:    x86_64
Kernel:          6.2.9
Hostname:        ftb-server
tmux:            tmux 3.1c
Avg Load:        0.96, 1.04, 1.03
Free Memory:     7.9GB
Free Disk:       13G
Game Server IP: 0.0.0.0:25565
Internet IP:    x.x.x.x:25565
Start parameters: java -javaagent:log4jfix/Log4jPatcher-1.0.0.jar -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -Xmx6144M -Xms4096M @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.19.2-43.2.6/unix_args.txt -jar ./minecraft_server.1.19.2.jar nogui

starting the Server under Debian 11 with Adoptium 17.0.6 and shipped 17.0.2 does exact the same

### Describe the bug

These i guess are just cosmetical:
```
[06:42:41] [main/ERROR] [mixin/]: Mixin config javd-common.mixins.json does not specify "minVersion" property
[06:42:41] [main/ERROR] [mixin/]: Mixin config javd.mixins.json does not specify "minVersion" property
[06:42:41] [main/ERROR] [mixin/]: Mixin config blockshot.mixins.json does not specify "minVersion" property
[06:42:41] [main/ERROR] [mixin/]: Mixin config jamd-common.mixins.json does not specify "minVersion" property
[06:42:41] [main/ERROR] [mixin/]: Mixin config jamd.mixins.json does not specify "minVersion" property
[06:42:41] [main/ERROR] [mixin/]: Mixin config accelerateddecay.mixins.json does not specify "minVersion" property
[06:42:42] [main/ERROR] [mixin/]: Mixin config flatbedrock-common.mixins.json does not specify "minVersion" property
[06:42:42] [main/ERROR] [mixin/]: Mixin config minetogether-common.mixins.json does not specify "minVersion" property
[06:42:42] [main/ERROR] [mixin/]: Mixin config minetogether-forge.mixins.json does not specify "minVersion" property
```
Dont start a gui if DEDICATED_SERVER
```
[06:42:44] [main/ERROR] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/gui/screens/inventory/AbstractContainerScreen for invalid dist DEDICATED_SERVER
[06:42:44] [main/ERROR] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/particle/ParticleEngine for invalid dist DEDICATED_SERVER
```
Maybe remove from Serverinstall:
```
[06:43:00] [modloading-worker-0/ERROR] [toastcontrol/]: Running on a dedicated server, disabling mod.
```
Here im out:
```
[06:42:59] [modloading-worker-0/ERROR] [KubeJS/]: Failed to load plugin dev.ftb.mods.ftbchunks.integration.kubejs.FTBChunksKubeJSPlugin from source ftbchunks: java.lang.ClassNotFoundException: dev.ftb.mods.ftbchunks.integration.kubejs.FTBChunksKubeJSPlugin
[06:43:01] [modloading-worker-0/ERROR] [minecraft/MultiPackResourceManager]: Failed to get filter section from pack server-1.19.2-20220805.130853-srg.jar
[06:43:01] [modloading-worker-0/ERROR] [minecraft/MultiPackResourceManager]: Failed to get filter section from pack kubejs
[06:43:02] [modloading-worker-0/ERROR] [th.ja.da.DataCollector/]: Tag upright_on_belt in namespace create has no type
[06:43:03] [modloading-worker-0/ERROR] [th.ja.cu.CustomModule/]: Unable to read custom json
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
        at com.google.gson.Gson.fromJson(Gson.java:975) ~[gson-2.8.9.jar%2370!/:?] {re:mixin}
        at com.google.gson.Gson.fromJson(Gson.java:901) ~[gson-2.8.9.jar%2370!/:?] {re:mixin}
        at thelm.jaopca.custom.CustomModule.setCustomFormConfigFile(CustomModule.java:57) ~[JAOPCA-1.19.2-4.2.7.13.jar%23508!/:4.2.7.13] {re:classloading}
        at thelm.jaopca.config.ConfigHandler.setupCustomFormConfig(ConfigHandler.java:182) ~[JAOPCA-1.19.2-4.2.7.13.jar%23508!/:4.2.7.13] {re:classloading}
        at thelm.jaopca.events.CommonEventHandler.onConstruct(CommonEventHandler.java:54) ~[JAOPCA-1.19.2-4.2.7.13.jar%23508!/:4.2.7.13] {re:mixin,re:classloading}
        at thelm.jaopca.events.__CommonEventHandler_onConstruct_FMLConstructModEvent.invoke(.dynamic) ~[JAOPCA-1.19.2-4.2.7.13.jar%23508!/:4.2.7.13] {re:classloading,pl:eventbus:B}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19.2-43.2.6.jar%23665!/:?] {}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.19.2-43.2.6.jar%23664!/:?] {re:mixin}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {re:mixin,re:computing_frames}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {re:mixin,re:computing_frames}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {re:mixin}
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
        at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:349) ~[gson-2.8.9.jar%2370!/:?] {}
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70) ~[gson-2.8.9.jar%2370!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%2370!/:?] {re:mixin}
        ... 17 more
[06:43:54] [Worker-Main2/ERROR] [minecraft/TagLoader]: Couldn't load tag [bambooeverything:dry_bamboo_raft (from BambooEverything-forge-2.2.4-build.33+mc1.19.2.jar)] as it is missing following references: bambooeverything:dry_bamboo_raft (from BambooEverything-forge-2.2.4-build.33+mc1.19.2.jar)
[06:43:54] [Worker-Main2/ERROR] [minecraft/TagLoader]: Couldn't load tag [#refinedstorage:parts/items/65536k (from rebornstorage-1.19.2-5.0.3.jar), #refinedstorage:parts/items/262144k (from rebornstorage-1.19.2-5.0.3.jar), #refinedstorage:parts/items/1048576k (from rebornstorage-1.19.2-5.0.3.jar)] as it is missing following references: #refinedstorage:parts/items/65536k (from rebornstorage-1.19.2-5.0.3.jar),
        #refinedstorage:parts/items/262144k (from rebornstorage-1.19.2-5.0.3.jar),
        #refinedstorage:parts/items/1048576k (from rebornstorage-1.19.2-5.0.3.jar)
[06:43:54] [Worker-Main2/ERROR] [minecraft/TagLoader]: Couldn't load tag [#refinedstorage:disks/items/65536k (from rebornstorage-1.19.2-5.0.3.jar), #refinedstorage:disks/items/262144k (from rebornstorage-1.19.2-5.0.3.jar), #refinedstorage:disks/items/1048576k (from rebornstorage-1.19.2-5.0.3.jar)] as it is missing following references: #refinedstorage:disks/items/65536k (from rebornstorage-1.19.2-5.0.3.jar),
        #refinedstorage:disks/items/262144k (from rebornstorage-1.19.2-5.0.3.jar),
        #refinedstorage:disks/items/1048576k (from rebornstorage-1.19.2-5.0.3.jar)
[06:43:54] [Worker-Main2/ERROR] [minecraft/TagLoader]: Couldn't load tag [#refinedstorage:disks/items (from ExtraStorage-1.19.2-3.0.1.jar), #refinedstorage:disks/items (from rebornstorage-1.19.2-5.0.3.jar)] as it is missing following references: #refinedstorage:disks/items (from ExtraStorage-1.19.2-3.0.1.jar),
        #refinedstorage:disks/items (from rebornstorage-1.19.2-5.0.3.jar)
[06:43:54] [Worker-Main2/ERROR] [minecraft/TagLoader]: Couldn't load tag [#refinedstorage:parts/items (from ExtraStorage-1.19.2-3.0.1.jar), #refinedstorage:parts/items (from rebornstorage-1.19.2-5.0.3.jar)] as it is missing following references: #refinedstorage:parts/items (from ExtraStorage-1.19.2-3.0.1.jar),
        #refinedstorage:parts/items (from rebornstorage-1.19.2-5.0.3.jar)
[06:44:02] [main/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement delightful:recipes/cutting/cactus: Missing advancement, expected to find a JsonObject
[06:44:02] [main/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement delightful:recipes/cutting/salmonberry_pie: Missing advancement, expected to find a JsonObject
[06:44:02] [main/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement megacells:recipes/megacells.tab/cells/portable/portable_mana_cell_16m: Unknown item id 'megacells:mega_mana_cell_housing'
[06:44:02] [main/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement megacells:recipes/megacells.tab/cells/standard/mana_storage_cell_64m_with_housing: Unknown item id 'megacells:mega_mana_cell_housing'
[06:44:02] [main/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement megacells:recipes/megacells.tab/cells/standard/mana_storage_cell_4m_with_housing: Unknown item id 'megacells:mega_mana_cell_housing'
[06:44:02] [main/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement delightful:recipes/cutting/cantaloupe: Missing advancement, expected to find a JsonObject
[06:44:02] [main/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement megacells:recipes/megacells.tab/cells/standard/mana_storage_cell_16m_with_housing: Unknown item id 'megacells:mega_mana_cell_housing'
[06:44:02] [main/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement delightful:recipes/cutting/mini_melon: Missing advancement, expected to find a JsonObject
[06:44:02] [main/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement megacells:recipes/megacells.tab/cells/standard/mana_storage_cell_256m_with_housing: Unknown item id 'megacells:mega_mana_cell_housing'
[06:44:02] [main/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement delightful:recipes/cutting/pumpkin_pie: Missing advancement, expected to find a JsonObject
[06:44:02] [main/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement megacells:recipes/megacells.tab/cells/standard/mana_storage_cell_1m_with_housing: Unknown item id 'megacells:mega_mana_cell_housing'
[06:44:02] [main/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement delightful:recipes/cutting/source_berry_pie: Missing advancement, expected to find a JsonObject
[06:44:02] [main/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement megacells:recipes/megacells.tab/cells/portable/portable_mana_cell_64m: Unknown item id 'megacells:mega_mana_cell_housing'
[06:44:02] [main/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement megacells:recipes/megacells.tab/cells/portable/portable_mana_cell_4m: Unknown item id 'megacells:mega_mana_cell_housing'
[06:44:02] [main/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement megacells:recipes/megacells.tab/cells/portable/portable_mana_cell_1m: Unknown item id 'megacells:mega_mana_cell_housing'
[06:44:02] [main/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement megacells:recipes/megacells.tab/cells/portable/portable_mana_cell_256m: Unknown item id 'megacells:mega_mana_cell_housing'
[06:44:02] [main/ERROR] [Apotheosis : Enchantment/]: Failed parsing enchanting_stats file apotheosis:white_candle.
[06:44:02] [main/ERROR] [Apotheosis : Enchantment/]: Underlying Exception:
java.lang.IllegalArgumentException: Improper arguments to BlockStats - only one of "blocks", "tag", and "block" may be provided!
        at shadows.apotheosis.ench.table.EnchantingStatManager$BlockStats.<init>(EnchantingStatManager.java:204) ~[Apotheosis-1.19.2-6.1.5.jar%23392!/:6.1.5] {re:classloading}
        at com.mojang.datafixers.util.Function4.lambda$curry2$2(Function4.java:14) ~[datafixerupper-5.0.28.jar%2375!/:?] {}
        at com.mojang.serialization.DataResult$Instance.ap2(DataResult.java:315) ~[datafixerupper-5.0.28.jar%2375!/:?] {}
        at com.mojang.datafixers.kinds.Applicative.ap4(Applicative.java:84) ~[datafixerupper-5.0.28.jar%2375!/:?] {}
        at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$7.decode(RecordCodecBuilder.java:404) ~[datafixerupper-5.0.28.jar%2375!/:?] {}
        at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[datafixerupper-5.0.28.jar%2375!/:?] {}
        at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[datafixerupper-5.0.28.jar%2375!/:?] {}
        at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-5.0.28.jar%2375!/:?] {re:mixin}
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar%2375!/:?] {}
        at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-5.0.28.jar%2375!/:?] {re:mixin}
        at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-5.0.28.jar%2375!/:?] {}
        at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[datafixerupper-5.0.28.jar%2375!/:?] {}
        at shadows.placebo.json.PSerializer.lambda$fromCodec$7(PSerializer.java:149) ~[Placebo-1.19.2-7.1.7.jar%23561!/:7.1.7] {re:classloading}
        at shadows.placebo.json.PSerializer.read(PSerializer.java:61) ~[Placebo-1.19.2-7.1.7.jar%23561!/:7.1.7] {re:classloading}
        at shadows.placebo.json.PlaceboJsonReloadListener.lambda$apply$0(PlaceboJsonReloadListener.java:101) ~[Placebo-1.19.2-7.1.7.jar%23561!/:7.1.7] {re:classloading}
        at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?] {re:mixin}
        at shadows.placebo.json.PlaceboJsonReloadListener.apply(PlaceboJsonReloadListener.java:89) ~[Placebo-1.19.2-7.1.7.jar%23561!/:7.1.7] {re:classloading}
        at shadows.placebo.json.PlaceboJsonReloadListener.m_5787_(PlaceboJsonReloadListener.java:50) ~[Placebo-1.19.2-7.1.7.jar%23561!/:7.1.7] {re:classloading}
        at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[server-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:A}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[server-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:classloading}
        at net.minecraft.Util.m_214652_(Util.java:781) ~[server-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:UtilMixin,pl:mixin:APP:yungsbridges.mixins.json:SuppressLogMixin,pl:mixin:APP:mixin.imdlib-whisperwoods.json:UtilMixin,pl:mixin:APP:ftbchunks-common.mixins.json:UtilMixin,pl:mixin:APP:smoothboot.mixins.json:UtilMixin,pl:mixin:A}
        at net.minecraft.Util.m_214679_(Util.java:770) ~[server-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:UtilMixin,pl:mixin:APP:yungsbridges.mixins.json:SuppressLogMixin,pl:mixin:APP:mixin.imdlib-whisperwoods.json:UtilMixin,pl:mixin:APP:ftbchunks-common.mixins.json:UtilMixin,pl:mixin:APP:smoothboot.mixins.json:UtilMixin,pl:mixin:A}
        at net.minecraft.server.Main.main(Main.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:classloading,re:mixin,pl:mixin:A}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.2.6.jar%2367!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

```

### Steps to reproduce

Fresh install via server install script
run server via start.sh or in my case with lgsm, no matter its the same errors popping up
watch for red messages

Thanks in advance

### Expected behaviour

Start a running Server without ERRORS

**Comment by Saereth** [comment]
those particular errors are fine to ignore, I've added toast control to the client only list now ftbchunks error should be gone now with the next update, apotheosis errors can be ignored per the mode dev
mixin errors are meaningless as well
