### ISSUE TITLE
Refined Storage interactions with Draws

### ISSUE THREAD

**Issue by kazzam333** [FTBTeam/FTB-Modpack-Issues#3237]
### Modpack

FTB Skies

### Modpack version

1.0.6

java.lang.NullPointerException: Cannot invoke "net.minecraftforge.items.IItemHandler.getSlots()" because "handler" is null
	at com.buuz135.functionalstorage.inventory.ControllerInventoryHandler.invalidateSlots(ControllerInventoryHandler.java:60) ~[functionalstorage-1.19.2-1.1.3.jar%23581!/:1.19.2-1.1.3] {re:classloading}
	at com.buuz135.functionalstorage.block.tile.DrawerControllerTile$ConnectedDrawers.rebuild(DrawerControllerTile.java:262) ~[functionalstorage-1.19.2-1.1.3.jar%23581!/:1.19.2-1.1.3] {re:classloading}
	at com.buuz135.functionalstorage.block.tile.DrawerControllerTile.serverTick(DrawerControllerTile.java:82) ~[functionalstorage-1.19.2-1.1.3.jar%23581!/:1.19.2-1.1.3] {re:classloading}
	at com.buuz135.functionalstorage.block.tile.DrawerControllerTile.serverTick(DrawerControllerTile.java:41) ~[functionalstorage-1.19.2-1.1.3.jar%23581!/:1.19.2-1.1.3] {re:classloading}
	at com.hrznstudio.titanium.block.BasicTileBlock.lambda$getTicker$3(BasicTileBlock.java:77) ~[titanium-1.19.2-3.7.3-27.jar%23731!/:3.7.3] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(MixinLevel.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:beefix:Level,re:classloading,pl:accesstransformer:B,xf:fml:beefix:Level,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:ftbteamdimensions.mixins.json:LevelAccess,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin,pl:mixin:APP:mixins.integrateddynamics.json:MixinLevel,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:ftbteamdimensions.mixins.json:ServerLevelAccess,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23749!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:?] {}

_No response_

### Describe the bug

I got a refined storage set up, hooked up to a draw controller with a external storage bus, looked in the refined storage and couldn't pull anything out from the draw storage, also noticed that i couldn't pull anything out that was stored on disk's in the storage system. As long as the draw controller was hooked up I couldn't pull anything, disconnected the connection to the draw controller and could pull out of the refined storage, logged out of the world to go back later, but now every time i go to play that save the game crashes.

### Steps to reproduce

1. hook up a draw controller to a refined storage system
2. see if you can pull out of the draws
3. see if you can pull out of items on disks
4. log out of the world, shut the game down and go back to the game 
5. see if the game crashes if you log into that save

### Expected behaviour

the game will crash

**Comment by johnll56** [comment]
You can attach the external storage to a drawer extension for now (connect the extension to the main controller)

**Comment by kazzam333** [comment]
> You can attach the external storage to a drawer extension for now (connect the extension to the main controller)

If the draw controller is attached to the refined storage system using an external storage, you can't get anything out, not even things that are stored on the disks. I can't even load the world now, it just crashes the game.

**Comment by johnll56** [comment]
> > You can attach the external storage to a drawer extension for now (connect the extension to the main controller)
> 
> If the draw controller is attached to the refined storage system using an external storage, you can't get anything out, not even things that are stored on the disks. I can't even load the world now, it just crashes the game.

Yes i know. I'm suggesting you connect them by crafting a "controller extension" (different block to the drawer controller) and putting the external storage on that, if you're able to load your world again. At least it works in my world

**Comment by Saereth** [comment]
this is a known issue with the mod, using the controller extension is the work around for now.
