### ISSUE TITLE
Crash when linking Collector Crystal to Prism Lens

### ISSUE THREAD

**Issue by iComputerfreak** [FTBTeam/FTB-Modpack-Issues#3556]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.1.0

### Log Files

```
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at hellfirepvp.astralsorcery.common.crystal.CrystalCalculations.calculate(CrystalCalculations.java:36) ~[astralsorcery:1.16.4-1.14.1] {re:classloading}
	at hellfirepvp.astralsorcery.common.crystal.CrystalCalculations.getThroughputMultiplier(CrystalCalculations.java:103) ~[astralsorcery:1.16.4-1.14.1] {re:classloading}
	at hellfirepvp.astralsorcery.common.starlight.network.TransmissionChain.recBuildChain(TransmissionChain.java:108) ~[astralsorcery:1.16.4-1.14.1] {re:classloading}
	at hellfirepvp.astralsorcery.common.starlight.network.TransmissionChain.recBuildChain(TransmissionChain.java:136) ~[astralsorcery:1.16.4-1.14.1] {re:classloading}
	at hellfirepvp.astralsorcery.common.starlight.network.TransmissionChain.recBuildChain(TransmissionChain.java:136) ~[astralsorcery:1.16.4-1.14.1] {re:classloading}
	at hellfirepvp.astralsorcery.common.starlight.network.TransmissionChain.buildFromSource(TransmissionChain.java:74) ~[astralsorcery:1.16.4-1.14.1] {re:classloading}
	at hellfirepvp.astralsorcery.common.starlight.network.TransmissionChain.buildNetworkChain(TransmissionChain.java:58) ~[astralsorcery:1.16.4-1.14.1] {re:classloading}
	at hellfirepvp.astralsorcery.common.starlight.network.TransmissionWorldHandler.buildNetworkChain(TransmissionWorldHandler.java:134) ~[astralsorcery:1.16.4-1.14.1] {re:classloading}
	at hellfirepvp.astralsorcery.common.starlight.network.TransmissionWorldHandler.tick(TransmissionWorldHandler.java:75) ~[astralsorcery:1.16.4-1.14.1] {re:classloading}
	at hellfirepvp.astralsorcery.common.starlight.network.StarlightTransmissionHandler.tick(StarlightTransmissionHandler.java:47) ~[astralsorcery:1.16.4-1.14.1] {re:classloading}
	at hellfirepvp.observerlib.common.util.tick.TickManager.worldTick(TickManager.java:63) ~[observerlib:1.16.5-1.5.3] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPreWorldTick(BasicEventHooks.java:81) ~[forge:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:848) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:?] {}
```

### Describe the bug

When placing the Astral Sorcery Celestial Collector Crystal that is given as a quest reward and then linking it to a Crystal Prism, the server crashes with the given error. When I try to start the server again, it just crashes again with the same error.

Might be related to https://github.com/HellFirePvP/AstralSorcery/issues/1920.

Sadly this means that all the progress since my last backup is gone, as I did not find any way to delete the crystal or prism block without starting the server (I even tried editing the astral sorcery jar contents, but forge verifies the checksum and the astral sorcery souce code sadly does not contain a gradle wrapper or any instructions on how to compile it).

If anyone has any ideas on how to fix this problem, please do tell :)

### Steps to reproduce

1. Claim the Celestial Collector Crystal from the "A Huge Table" quest, craft one or cheat one in
2. Place it in the world
3. Link the crystal to a Crystal Prism using the Linking Tool
4. The server crashes

### Expected behaviour

The prism should redirect the starlight, not crash the server

**Comment by iComputerfreak** [comment]
After some more testing, the crash also occurs when crafting a celestial collector crystal manually or cheating one in via JEI. As soon as I link the crystal to the Crystal Prism, the server crashes.

Someone else also reported this bug on the Astral Sorcery github regarding another modpack. So I guess it is probably an Astral Sorcery bug.
https://github.com/HellFirePvP/AstralSorcery/issues/1957
