### ISSUE TITLE
Server crash + unusable after single right-click on computer

### ISSUE THREAD

**Issue by kyokeen** [FTBTeam/FTB-Modpack-Issues#3868]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.5.0

### Log Files

[crash-report.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12528211/crash-report.txt)

```
java.lang.NoClassDefFoundError: dan200/computercraft/core/asm/PeripheralMethod
	at de.srendi.advancedperipherals.lib.peripherals.IPeripheralPlugin.getMethods(IPeripheralPlugin.java:12) ~[AdvancedPeripherals-1.20.1-0.7.31a.jar%23303!/:0.7.31a] {re:classloading,pl:rei_plugin_compatibilities:B}
	at de.srendi.advancedperipherals.lib.peripherals.BasePeripheral.lambda$buildPlugins$1(BasePeripheral.java:53) ~[AdvancedPeripherals-1.20.1-0.7.31a.jar%23303!/:0.7.31a] {re:classloading,pl:rei_plugin_compatibilities:B}
	at java.util.HashMap$Values.forEach(Unknown Source) ~[?:?] {}
	at de.srendi.advancedperipherals.lib.peripherals.BasePeripheral.buildPlugins(BasePeripheral.java:51) ~[AdvancedPeripherals-1.20.1-0.7.31a.jar%23303!/:0.7.31a] {re:classloading,pl:rei_plugin_compatibilities:B}
	at de.srendi.advancedperipherals.lib.peripherals.BasePeripheral.getMethodNames(BasePeripheral.java:140) ~[AdvancedPeripherals-1.20.1-0.7.31a.jar%23303!/:0.7.31a] {re:classloading,pl:rei_plugin_compatibilities:B}
	at dan200.computercraft.core.asm.PeripheralMethodSupplier.lambda$create$5(PeripheralMethodSupplier.java:36) ~[cc-tweaked-1.20.1-forge-1.108.0.jar%23323!/:1.108.0] {re:classloading,pl:rei_plugin_compatibilities:B}
	at dan200.computercraft.core.asm.MethodSupplierImpl.forEachSelfMethod(MethodSupplierImpl.java:60) ~[cc-tweaked-1.20.1-forge-1.108.0.jar%23323!/:1.108.0] {re:classloading,pl:rei_plugin_compatibilities:B}
	at dan200.computercraft.core.methods.MethodSupplier.getSelfMethods(MethodSupplier.java:34) ~[cc-tweaked-1.20.1-forge-1.108.0.jar%23323!/:1.108.0] {re:classloading,pl:rei_plugin_compatibilities:B}
	at dan200.computercraft.core.apis.PeripheralAPI$PeripheralWrapper.<init>(PeripheralAPI.java:46) ~[cc-tweaked-1.20.1-forge-1.108.0.jar%23323!/:1.108.0] {re:classloading,pl:rei_plugin_compatibilities:B}
	at dan200.computercraft.core.apis.PeripheralAPI.onPeripheralChanged(PeripheralAPI.java:202) ~[cc-tweaked-1.20.1-forge-1.108.0.jar%23323!/:1.108.0] {re:classloading,pl:rei_plugin_compatibilities:B}
	at dan200.computercraft.core.computer.Environment.setPeripheral(Environment.java:275) ~[cc-tweaked-1.20.1-forge-1.108.0.jar%23323!/:1.108.0] {re:classloading,pl:rei_plugin_compatibilities:B}
	at dan200.computercraft.shared.computer.core.ServerComputer.setPeripheral(ServerComputer.java:219) ~[cc-tweaked-1.20.1-forge-1.108.0.jar%23323!/:1.108.0] {re:classloading,pl:rei_plugin_compatibilities:B}
	at dan200.computercraft.shared.computer.blocks.AbstractComputerBlockEntity.refreshPeripheral(AbstractComputerBlockEntity.java:222) ~[cc-tweaked-1.20.1-forge-1.108.0.jar%23323!/:1.108.0] {re:classloading,pl:rei_plugin_compatibilities:B}
	at dan200.computercraft.shared.computer.blocks.AbstractComputerBlockEntity.updateInputsImmediately(AbstractComputerBlockEntity.java:243) ~[cc-tweaked-1.20.1-forge-1.108.0.jar%23323!/:1.108.0] {re:classloading,pl:rei_plugin_compatibilities:B}
	at dan200.computercraft.shared.computer.blocks.AbstractComputerBlockEntity.createServerComputer(AbstractComputerBlockEntity.java:331) ~[cc-tweaked-1.20.1-forge-1.108.0.jar%23323!/:1.108.0] {re:classloading,pl:rei_plugin_compatibilities:B}
	at dan200.computercraft.shared.computer.blocks.AbstractComputerBlockEntity.serverTick(AbstractComputerBlockEntity.java:125) ~[cc-tweaked-1.20.1-forge-1.108.0.jar%23323!/:1.108.0] {re:classloading,pl:rei_plugin_compatibilities:B}
	at dan200.computercraft.shared.computer.blocks.AbstractComputerBlock.lambda$new$0(AbstractComputerBlock.java:47) ~[cc-tweaked-1.20.1-forge-1.108.0.jar%23323!/:1.108.0] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689) ~[server-1.20.1-20230612.114412-srg.jar%23491!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782) ~[server-1.20.1-20230612.114412-srg.jar%23491!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.world.level.Level.m_46463_(Level.java:468) ~[server-1.20.1-20230612.114412-srg.jar%23491!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351) ~[server-1.20.1-20230612.114412-srg.jar%23491!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:modulargolems.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23491!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:273) ~[server-1.20.1-20230612.114412-srg.jar%23491!/:?] {re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23491!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23491!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23491!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) ~[?:?] {}
Caused by: java.lang.ClassNotFoundException: dan200.computercraft.core.asm.PeripheralMethod
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
	... 27 more
```

### Describe the bug

[crash-report-1.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12528208/crash-report.txt)
[crash-2023-09-05_23.08.12-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12528222/crash-2023-09-05_23.08.12-server.txt)
While playing, I encountered a computer situated in a village and tried interacting with it (first time doing this on a server that;s 4 days old). Upon interacting with it, the server threw NoClassDefFoundError. Looking around cc-tweaked code, found that [PeripheralMethod class](https://github.com/cc-tweaked/CC-Tweaked/blob/mc-1.20.x/projects/core/src/main/java/dan200/computercraft/core/methods/PeripheralMethod.java) is in core package `methods` not `asm`... I would assume this was the cause of the error. 

### Steps to reproduce

1. Find computer (player X)
2. Right click on it to interact

Behavior: 
- server crashed
- server can be restarted, but when player X tries to reconnect server crashes with the same exception
- player Y was able to connect and join the server, but caused the same server crash when loading the chunk where player X/the computer was

### Expected behaviour

no server crash

### Additional information

We tried updating cc-tweaks to the latest version cc-tweaked-1.20.1-forge-1.108.0 from https://legacy.curseforge.com/minecraft/mc-mods/cc-tweaked (copy-paste jarfile) but to no avail.

**Comment by opietrice** [comment]
Also experiencing this issue, too.  Same experience with cc: tweak in a village which corrupted the entire chunk.  If any player enters it, the server will crash. To mitigate, edited player files to change their location away from the chunk.

**Comment by kyokeen** [comment]
@opietrice how did you manage to edit player location? I'm very new to FTB and modded minecraft. Thank you for your reply.

**Comment by opietrice** [comment]
@kyokeen I used a program called NTBExplorer.  You need to open the player UUID file in world/playerdata/<player UUID>.dat file.  You'll see a parameter about a quarter of the way down for position called pos with 3 values.  You can edit the x, y, z coordinates and overwrite the file.  Try to avoid placing players in walls, though.

**Comment by kyokeen** [comment]
Confirm this was fixed by moving the player outside the zone. Thanks for the help, I can't wait for the underlying issue to be fixed..

**Comment by MPDR200011** [comment]
I'm having the same issue. I've tried editing the position with NBTExplorer, but the game crashes immediately after joining the world anyways, and when I reopen NBTExplorer the position value is reset back to the original position.

**Comment by Zalgo2462** [comment]
Experiencing the same issue here. Ended up reverting to a backup.

**Comment by FusseI** [comment]
Unfortunately, this is also the case with my server :/

**Comment by dirtyredz** [comment]
Same issue, Here

**Comment by SirTony** [comment]
Recently ran into this issue myself in a single player world.

You need to edit both the `(UUID).dat` file as @opietrice mentions, but *also* the `level.dat` file which also stores the player location. At the bottom of the player data are the X, Y, and Z coords for the spawn point. I just set my location in both files to the spawn point and the game was playable again.

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.

Keep an eye on our social media as we may have something unstable coming out soon.
