### ISSUE TITLE
Mythical Mounts

### ISSUE THREAD

**Issue by Skyebb98** [FTBTeam/FTB-Modpack-Issues#3885]
### Modpack

FTB Presents AbePack

### Modpack version

1.19.2

### Describe the bug

When you go to open the book to the mystical mounts one it says: error building entry mythicalmounts:creatures/geckotoa 

### Steps to reproduce

1. Click on the book
2. Go to the mythical mounts section
3. Open that section
4. Shows loading error 

### Expected behaviour

To be able to read about the mythical mounts 

### Screenshots

![IMG_8475](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/144862109/4d3bdd3a-6795-4571-a5f5-89328c7d6733)

**Comment by Hanoverfist** [comment]
Tested this on our servers. Fresh 1.04 install of client and server. Everything is working as intended for me. All categories showed in the book and worked properly. Tested both the version included in the Akashic Tome and a book from Creative.

Suspect you have a bad install. Get a clean, fresh reinstall and see if the problem goes away. If not, check the log for the actual error.

**Comment by craigo7** [comment]
I am also having the exact same issue and tried the fix suggested here but still having the same issue. i tried to reach out on discord but i have had no response. any help would be really appreciated.

**Comment by mb9023** [comment]
I have a fresh FTB app install and have this issue. I've also deleted it and reinstalled it.

Log has this

`[26Sep2023 10:03:36.204] [Render thread/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 147 advancements
[26Sep2023 10:03:36.209] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/categories/gear.json
[26Sep2023 10:03:36.209] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/categories/creatures.json
[26Sep2023 10:03:36.210] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/categories/care.json
[26Sep2023 10:03:36.210] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/categories/about.json
[26Sep2023 10:03:36.211] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/entries/gear/summoning_staff.json
[26Sep2023 10:03:36.212] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/entries/gear/riding_gear.json
[26Sep2023 10:03:36.213] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/entries/gear/inventory.json
[26Sep2023 10:03:36.213] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/entries/gear/armor.json
[26Sep2023 10:03:36.213] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/entries/creatures/zar_ptak.json
[26Sep2023 10:03:36.213] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/entries/creatures/riding_lizard.json
[26Sep2023 10:03:36.214] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/entries/creatures/nudibranch.json
[26Sep2023 10:03:36.214] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/entries/creatures/nightmare.json
[26Sep2023 10:03:36.214] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/entries/creatures/nether_bat.json
[26Sep2023 10:03:36.214] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/entries/creatures/moth.json
[26Sep2023 10:03:36.214] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/entries/creatures/griffon.json
[26Sep2023 10:03:36.214] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/entries/creatures/geckotoa.json
[26Sep2023 10:03:36.214] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/entries/creatures/dragon.json
[26Sep2023 10:03:36.214] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/entries/creatures/dire_wolf.json
[26Sep2023 10:03:36.214] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/entries/creatures/courier_bird.json
[26Sep2023 10:03:36.214] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/entries/creatures/colelytra.json
[26Sep2023 10:03:36.214] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/entries/creatures/archelon.json
[26Sep2023 10:03:36.215] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/entries/creatures/acencia.json
[26Sep2023 10:03:36.215] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/entries/care/taming.json
[26Sep2023 10:03:36.215] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/entries/care/stabling.json
[26Sep2023 10:03:36.215] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/entries/care/riding_techniques.json
[26Sep2023 10:03:36.215] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/entries/care/mount_commands.json
[26Sep2023 10:03:36.215] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/entries/care/healing.json
[26Sep2023 10:03:36.215] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/entries/care/breeding.json
[26Sep2023 10:03:36.215] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/entries/about/about.json
[26Sep2023 10:03:36.215] [Render thread/DEBUG] [patchouli/]: Loading data/mythicmounts/patchouli_books/mythical_mounts/en_us/templates/server_page.json
[26Sep2023 10:03:36.229] [Render thread/ERROR] [patchouli/]: Error compiling book mythicmounts:mythical_mounts, using empty contents
java.lang.RuntimeException: Error building entry mythicmounts:creatures/geckotoa
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:98) ~[Patchouli-1.19.2-77.jar%23536!/:1.19.2-77]
	at java.util.HashMap$Values.forEach(Unknown Source) ~[?:?]
	at vazkii.patchouli.client.book.BookContentsBuilder.build(BookContentsBuilder.java:94) ~[Patchouli-1.19.2-77.jar%23536!/:1.19.2-77]
	at vazkii.patchouli.common.book.Book.reloadContents(Book.java:223) ~[Patchouli-1.19.2-77.jar%23536!/:1.19.2-77]
	at vazkii.patchouli.common.book.BookRegistry.reloadContents(BookRegistry.java:128) ~[Patchouli-1.19.2-77.jar%23536!/:1.19.2-77]
	at vazkii.patchouli.client.book.ClientBookRegistry.reload(ClientBookRegistry.java:63) ~[Patchouli-1.19.2-77.jar%23536!/:1.19.2-77]
	at vazkii.patchouli.client.base.ClientAdvancements.onClientPacket(ClientAdvancements.java:34) ~[Patchouli-1.19.2-77.jar%23536!/:1.19.2-77]
	at net.minecraft.client.multiplayer.ClientAdvancements.handler$cdd000$patchouli_onSync(ClientAdvancements.java:1017) ~[client-1.19.2-20220805.130853-srg.jar%23609!/:?]
	at net.minecraft.client.multiplayer.ClientAdvancements.m_104399_(ClientAdvancements.java:57) ~[client-1.19.2-20220805.130853-srg.jar%23609!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5498_(ClientPacketListener.java:1181) ~[client-1.19.2-20220805.130853-srg.jar%23609!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateAdvancementsPacket.m_5797_(ClientboundUpdateAdvancementsPacket.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23609!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateAdvancementsPacket.m_5797_(ClientboundUpdateAdvancementsPacket.java:16) ~[client-1.19.2-20220805.130853-srg.jar%23609!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.19.2-20220805.130853-srg.jar%23609!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23609!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23609!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23609!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.19.2-20220805.130853-srg.jar%23609!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1072) ~[client-1.19.2-20220805.130853-srg.jar%23609!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23609!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23609!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23609!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.23.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.RuntimeException: Error while loading entry mythicmounts:creatures/geckotoa page 2
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:249) ~[Patchouli-1.19.2-77.jar%23536!/:1.19.2-77]
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:96) ~[Patchouli-1.19.2-77.jar%23536!/:1.19.2-77]
	... 33 more
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 10, length 9
	at java.lang.String.checkBoundsBeginEnd(Unknown Source) ~[?:?]
	at java.lang.String.substring(Unknown Source) ~[?:?]
	at com.yahoo.chirpycricket.mythicmounts.client.integration.patchouli.EntityInfoProcessor.getBiomes(EntityInfoProcessor.java:91) ~[mythicmounts-19.2-7.2.1-forge.jar%23526!/:19.2-7.3-forge]
	at com.yahoo.chirpycricket.mythicmounts.client.integration.patchouli.EntityInfoProcessor.process(EntityInfoProcessor.java:42) ~[mythicmounts-19.2-7.2.1-forge.jar%23526!/:19.2-7.3-forge]
	at vazkii.patchouli.client.book.template.VariableAssigner.resolveStringVar(VariableAssigner.java:131) ~[Patchouli-1.19.2-77.jar%23536!/:1.19.2-77]
	at vazkii.patchouli.client.book.template.VariableAssigner.resolveStringFunctions(VariableAssigner.java:104) ~[Patchouli-1.19.2-77.jar%23536!/:1.19.2-77]
	at vazkii.patchouli.client.book.template.VariableAssigner.resolveString(VariableAssigner.java:80) ~[Patchouli-1.19.2-77.jar%23536!/:1.19.2-77]
	at vazkii.patchouli.client.book.template.VariableAssigner.lambda$assignVariableHolders$1(VariableAssigner.java:53) ~[Patchouli-1.19.2-77.jar%23536!/:1.19.2-77]
	at vazkii.patchouli.client.book.template.component.ComponentText.onVariablesAvailable(ComponentText.java:44) ~[Patchouli-1.19.2-77.jar%23536!/:1.19.2-77]
	at vazkii.patchouli.client.book.template.VariableAssigner.assignVariableHolders(VariableAssigner.java:48) ~[Patchouli-1.19.2-77.jar%23536!/:1.19.2-77]
	at vazkii.patchouli.client.book.template.TemplateComponent.compile(TemplateComponent.java:50) ~[Patchouli-1.19.2-77.jar%23536!/:1.19.2-77]
	at vazkii.patchouli.client.book.template.BookTemplate.compile(BookTemplate.java:114) ~[Patchouli-1.19.2-77.jar%23536!/:1.19.2-77]
	at vazkii.patchouli.client.book.page.PageTemplate.build(PageTemplate.java:28) ~[Patchouli-1.19.2-77.jar%23536!/:1.19.2-77]
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:246) ~[Patchouli-1.19.2-77.jar%23536!/:1.19.2-77]
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:96) ~[Patchouli-1.19.2-77.jar%23536!/:1.19.2-77]
	... 33 more`

**Comment by mb9023** [comment]
It seems this issue only happens on my singleplayer instance. I also lost my akashic tome after playing for a while and when I made a new one it doesn't work at all. I set up a server instance and do not have the same issues.

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
