### ISSUE TITLE
crash on guidebook open on certain items

### ISSUE THREAD

**Issue by nevaduh** [FTBTeam/FTB-Modpack-Issues#3917]
### Modpack

Other...

### Modpack version

1.0

### Log Files

`---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2023-09-29 07:39:10
Description: Tesselating block in world

java.lang.IllegalAccessError: 'boolean link.infra.indium.renderer.render.NonTerrainBlockRenderContext.hasTransform()'
	at net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(VanillaModelEncoder.java:54)
	at net.fabricmc.fabric.api.renderer.v1.model.FabricBakedModel.emitBlockQuads(FabricBakedModel.java:97)
	at appeng.client.render.cablebus.CableBusBakedModel.emitBlockQuads(CableBusBakedModel.java:173)
	at link.infra.indium.renderer.render.NonTerrainBlockRenderContext.render(NonTerrainBlockRenderContext.java:66)
	at net.minecraft.class_778.handler$cho000$indium$hookRender(class_778.java:553)
	at net.minecraft.class_778.method_3374(class_778.java)
	at net.minecraft.class_776.method_3355(class_776.java:60)
	at appeng.client.guidebook.scene.GuidebookLevelRenderer.lambda$renderBlocks$1(GuidebookLevelRenderer.java:171)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.LongPipeline$1$1.accept(LongPipeline.java:177)
	at it.unimi.dsi.fastutil.longs.LongOpenHashSet$SetSpliterator.forEachRemaining(LongOpenHashSet.java:678)
	at it.unimi.dsi.fastutil.longs.LongSpliterator.forEachRemaining(LongSpliterator.java:86)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at appeng.client.guidebook.scene.GuidebookLevelRenderer.renderBlocks(GuidebookLevelRenderer.java:148)
	at appeng.client.guidebook.scene.GuidebookLevelRenderer.lambda$renderContent$0(GuidebookLevelRenderer.java:110)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1191)
	at appeng.client.guidebook.scene.GuidebookLevelRenderer.renderContent(GuidebookLevelRenderer.java:109)
	at appeng.client.guidebook.scene.GuidebookLevelRenderer.render(GuidebookLevelRenderer.java:94)
	at appeng.client.guidebook.scene.GuidebookLevelRenderer.render(GuidebookLevelRenderer.java:54)
	at appeng.client.guidebook.scene.LytGuidebookScene$Viewport.render(LytGuidebookScene.java:322)
	at appeng.client.guidebook.document.block.LytBox.render(LytBox.java:87)
	at appeng.client.guidebook.document.block.LytBox.render(LytBox.java:87)
	at appeng.client.guidebook.document.block.LytDocument.render(LytDocument.java:110)
	at appeng.client.guidebook.screen.GuideScreen.method_25394(GuideScreen.java:234)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(VanillaModelEncoder.java:54)
	at net.fabricmc.fabric.api.renderer.v1.model.FabricBakedModel.emitBlockQuads(FabricBakedModel.java:97)
	at appeng.client.render.cablebus.CableBusBakedModel.emitBlockQuads(CableBusBakedModel.java:173)
	at link.infra.indium.renderer.render.NonTerrainBlockRenderContext.render(NonTerrainBlockRenderContext.java:66)
	at net.minecraft.class_778.handler$cho000$indium$hookRender(class_778.java:553)
	at net.minecraft.class_778.method_3374(class_778.java)
	at net.minecraft.class_776.method_3355(class_776.java:60)
	at appeng.client.guidebook.scene.GuidebookLevelRenderer.lambda$renderBlocks$1(GuidebookLevelRenderer.java:171)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.LongPipeline$1$1.accept(LongPipeline.java:177)
	at it.unimi.dsi.fastutil.longs.LongOpenHashSet$SetSpliterator.forEachRemaining(LongOpenHashSet.java:678)
	at it.unimi.dsi.fastutil.longs.LongSpliterator.forEachRemaining(LongSpliterator.java:86)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at appeng.client.guidebook.scene.GuidebookLevelRenderer.renderBlocks(GuidebookLevelRenderer.java:148)
	at appeng.client.guidebook.scene.GuidebookLevelRenderer.lambda$renderContent$0(GuidebookLevelRenderer.java:110)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1191)
	at appeng.client.guidebook.scene.GuidebookLevelRenderer.renderContent(GuidebookLevelRenderer.java:109)
	at appeng.client.guidebook.scene.GuidebookLevelRenderer.render(GuidebookLevelRenderer.java:94)
	at appeng.client.guidebook.scene.GuidebookLevelRenderer.render(GuidebookLevelRenderer.java:54)
	at appeng.client.guidebook.scene.LytGuidebookScene$Viewport.render(LytGuidebookScene.java:322)
	at appeng.client.guidebook.document.block.LytBox.render(LytBox.java:87)
	at appeng.client.guidebook.document.block.LytBox.render(LytBox.java:87)
	at appeng.client.guidebook.document.block.LytDocument.render(LytDocument.java:110)
	at appeng.client.guidebook.screen.GuideScreen.method_25394(GuideScreen.java:234)
	at net.minecraft.class_437.method_47413(class_437.java:110)

-- Block being tesselated --
Details:
	Block: CableBusBlock[cable_bus][light_level=0,waterlogged=false]
	Block location: World: (0,0,0), Section: (at 0,0,0 in 0,0,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
Stacktrace:
	at net.minecraft.class_776.method_3355(class_776.java:60)
	at appeng.client.guidebook.scene.GuidebookLevelRenderer.lambda$renderBlocks$1(GuidebookLevelRenderer.java:171)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.LongPipeline$1$1.accept(LongPipeline.java:177)
	at it.unimi.dsi.fastutil.longs.LongOpenHashSet$SetSpliterator.forEachRemaining(LongOpenHashSet.java:678)
	at it.unimi.dsi.fastutil.longs.LongSpliterator.forEachRemaining(LongSpliterator.java:86)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at appeng.client.guidebook.scene.GuidebookLevelRenderer.renderBlocks(GuidebookLevelRenderer.java:148)
	at appeng.client.guidebook.scene.GuidebookLevelRenderer.lambda$renderContent$0(GuidebookLevelRenderer.java:110)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1191)
	at appeng.client.guidebook.scene.GuidebookLevelRenderer.renderContent(GuidebookLevelRenderer.java:109)
	at appeng.client.guidebook.scene.GuidebookLevelRenderer.render(GuidebookLevelRenderer.java:94)
	at appeng.client.guidebook.scene.GuidebookLevelRenderer.render(GuidebookLevelRenderer.java:54)
	at appeng.client.guidebook.scene.LytGuidebookScene$Viewport.render(LytGuidebookScene.java:322)
	at appeng.client.guidebook.document.block.LytBox.render(LytBox.java:87)
	at appeng.client.guidebook.document.block.LytBox.render(LytBox.java:87)
	at appeng.client.guidebook.document.block.LytDocument.render(LytDocument.java:110)
	at appeng.client.guidebook.screen.GuideScreen.method_25394(GuideScreen.java:234)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Screen render details --
Details:
	Screen name: appeng.client.guidebook.screen.GuideScreen
	Mouse location: Scaled: (542, 93). Absolute: (1627.000000, 279.000000)
	Screen size: Scaled: (640, 337). Absolute: (1920, 1009). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Nevaduh'/5968, l='ClientLevel', x=-2358.96, y=142.00, z=-1141.58]]
	Chunk stats: 1024, 249
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,125,0), Section: (at 0,13,0 in 0,7,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 2836069 game time, 4043911 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/Vanilla Tweaks Resource Pack.zip, file/§4§l§o§kaaa§6§l§oCustomTotem§a1.19§4§l§o§kaaa

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 4738850128 bytes (4519 MiB) / 18622709760 bytes (17760 MiB) up to 18891145216 bytes (18016 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1660 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2182
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3699
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 79390.23
	Virtual memory used (MB): 70958.14
	Swap memory total (MB): 46748.34
	Swap memory used (MB): 3679.17
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx18016m -Xms256m -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionalstructures: Additional Structures 4.2.1
		ae2: Applied Energistics 2 15.0.11
			team_reborn_energy: Energy 3.0.0
		ae2wtlib: AE2WTLib 15.0.1-beta
		ambientsounds: AmbientSounds 5.2.22
		anxff: Fireflies 1.3.1
		architectury: Architectury 9.1.12
		axolotlitemfix: Axolotl Item Fix 1.1.7
		azurelibarmor: AzureLib Armor 1.0.3
		bclib: BCLib 3.0.13
			wunderlib: WunderLib 1.1.5
		bettercombat: Better Combat 1.7.3+1.20.1
		betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0.2
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.2
		betterend: Better End 4.0.10
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.3
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.2
		betternether: Better Nether 9.0.9
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0.2
		betterstats: Better Statistics Screen 2.10.3+1.20.1
			tcdcommons: TCD Commons API 2.10.2+1.20.1
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.2
		bookshelf: Bookshelf 20.0.4
		bsvsb: Better Sodium Video Settings Button 3.0.3
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		cat_jam: cat_jam 1.2.0
		chunksfadein: Chunks Fade In 1.0.4-1.20.1
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		climbladdersfast: ClimbLaddersFast 4.0-1.20.1
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 6.66
		combatroll: Combat Roll 1.2.1+1.20.1
		cosmetica: Cosmetica 1.2.5+hotfix
			com_github_cosmetica-cc_cosmeticadotjava: CosmeticaDotJava 1.11.2
			sulphate: Sulfate 1.1.1
		creativecore: CreativeCore 2.10.28
			net_minecraftforge_eventbus: eventbus 6.0.3
		cyclepaintings: Cycle Paintings 3.2
		dark-loading-screen: Dark Loading Screen 1.6.14
		deathbackup: Death Backup 3.0
		distanthorizons: Distant Horizons 2.0.0-a-dev
		do_a_barrel_roll: Do a Barrel Roll 3.3.3+1.20
			cicada: CICADA 0.4.4
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
		dungeon_difficulty: Dungeon Difficulty 2.0.5+1.20.1
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
		enchdesc: EnchantmentDescriptions 17.0.8
		enhancedvisuals: EnhancedVisuals 1.6.7
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1
		equipmentcompare: Equipment Compare 1.3.7
		expandeddelight: Expanded Delight 0.3.0.2
		explorify: Explorify v1.3.0-mc1.20u1.20.1
		fabric-api: Fabric API 0.89.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.0+0883a8d477
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.1+195226a777
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabricloader: Fabric Loader 0.14.22
		farmersdelight: Farmer's Delight 1.20.1-1.4.2
		firstperson: FirstpersonModel 2.2.3
		forcecrawl: Force Crawl 1.0.2
		fpsreducer: FPS Reducer 1.20-2.5
		fwaystones: Fabric Waystones 3.1.3+mc1.20
		geckolib: Geckolib 4.2.1
			com_eliotlash_mclib_mclib: mclib 20
		harvestwithease: Harvest with ease 7.0.0.2
		iceberg: Iceberg 1.1.15
		indium: Indium 1.0.25+mc1.20.1
		jade: Jade 11.5.1
		java: OpenJDK 64-Bit Server VM 17
		jewelry: Jewelry 1.1.0+1.20.1
		lambdynlights: LambDynamicLights 2.3.1+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 5.0.0+1.20
		letmedespawn: Let Me Despawn fabric-1.20-1.1.0
		levelz: LevelZ 1.4.11
		libz: LibZ 1.0.2
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.15.2
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.15.2
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.15.2
		litematica: Litematica 0.15.3
		logical_zoom: Logical Zoom 0.0.20
		magistuarmory: Epic Knights Mod 7.11
		malilib: MaLiLib 0.16.2
		mavapi: More Axolotl Variants API 1.0.5
		mavm: More Axolotl Variants Mod 1.2.4
		merequester: ME Requester 1.20.1-1.1.4
			midnightlib: MidnightLib 1.2.1
		minecraft: Minecraft 1.20.1
		moonlight: Moonlight 1.20-2.8.19
		mousetweaks: Mouse Tweaks 2.25
		mousewheelie: Mouse Wheelie 1.12.2+mc1.20.1
			amecsapi: Amecs API 1.5.1+mc1.20-pre1
			coat: Coat 1.0.0-beta.20+mc1.20-pre1
			tweed4_annotated: tweed4_annotated 1.3.1+mc1.20-pre1
			tweed4_base: tweed4_base 1.7.1+mc1.20-pre1
			tweed4_data: tweed4_data 1.2.1+mc1.20-pre1
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc1.20-pre1
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc1.20-pre1
			tweed4_tailor_lang_json_descriptions: tweed4_tailor_lang_json_descriptions 1.1.0+mc1.20-pre1
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.4+mc1.20-pre1
		owo: oωo 0.11.2+1.20
			blue_endless_jankson: jankson 1.2.2
		paladins: Paladins & Priests 1.0.1+1.20.1
		perfectplushies: Perfect Plushies 1.5.0
			forgeconfigapiport: Forge Config API Port 8.0.0
		pickupnotifier: Pick Up Notifier 8.0.0
		player-animator: Player Animator 1.0.2-rc1+1.20
		projectile_damage: Projectile Damage Attribute 3.2.2+1.20.1
		puzzleslib: Puzzles Lib 8.0.24
		randomium: Randomium 1.20-1.29
		roughlyenoughitems: Roughly Enough Items 12.0.659
			error_notifier: Error Notifier 1.0.9
		runes: Runes 0.9.10+1.20.1
		shouldersurfing: Shoulder Surfing Reloaded 2.5
		simplyswords: Simply Swords 1.51.1-1.20.1
		skinlayers: 3d Skin Layers 1.5.4-mc1.20.1
		sodium: Sodium 0.5.2
		sodium-extra: Sodium Extra 0.5.1+mc1.20.1-build.112
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		spell_engine: Spell Engine 0.9.31+1.20.1
		spell_power: Spell Power Attribute 0.9.17+1.20.1
		terralith: Terralith 2.4.5
		travelersbackpack: Traveler's Backpack 1.20.1-9.1.4
		travelerstitles: Traveler's Titles 1.20-Fabric-4.0.1
		trimeffects: Trim Effects 1.0.1-fabric
		trinkets: Trinkets 3.7.1
		vanityslots: Vanity Slots 1.2.9
		waveycapes: WaveyCapes 1.3.2
		wizards: Wizards 1.0.1+1.20.1
		yungsapi: YUNG's API 1.20-Fabric-4.0.1
			org_javassist_javassist: javassist 3.29.2-GA
	Launched Version: fabric-loader-0.14.22-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 536.99, NVIDIA Corporation
	Window size: 1920x1009
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/Vanilla Tweaks Resource Pack.zip, file/§4§l§o§kaaa§6§l§oCustomTotem§a1.19§4§l§o§kaaa (incompatible)
	Current Language: en_us
	CPU: 8x Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Nevaduh'/5968, l='ServerLevel[penial contortion]', x=-2358.96, y=142.00, z=-1141.58]]
	Data Packs: vanilla, fabric, file/anti creeper grief v1.1.4 (MC 1.20.x).zip, file/anti enderman grief v1.1.4 (MC 1.20.x).zip, file/anti ghast grief v1.1.4 (MC 1.20.x).zip, file/armor statues v2.8.5 (MC 1.20.x).zip, file/armored elytra v1.0.7 (MC 1.20.x).zip, file/back v1.3.4 (MC 1.20.x).zip, file/bat membranes v1.0.5 (MC 1.20.x).zip, file/classic fishing loot v1.1.4 (MC 1.20.x).zip, file/coordinates hud v1.2.4 (MC 1.20.x).zip, file/count mob deaths v1.1.4 (MC 1.20.x).zip, file/custom nether portals v2.3.7 (MC 1.20.x).zip, file/double shulker shells v1.3.4 (MC 1.20.x).zip, file/dragon drops v1.3.4 (MC 1.20.x).zip, file/durability ping v1.1.4 (MC 1.20.x).zip, file/graves v2.8.8 (MC 1.20.x).zip, file/homes v1.5.5 (MC 1.20.x).zip, file/larger phantoms v1.2.5 (MC 1.20.x).zip, file/more mob heads v2.12.1 (MC 1.20.x).zip, file/nether portal coords v1.1.4 (MC 1.20.x).zip, file/spawn v2.3.4 (MC 1.20.x).zip, file/timber v2.1.6 (MC 1.20.x).zip, file/track raw statistics v1.7.0 (MC 1.20.x).zip, file/track statistics v1.1.5 (MC 1.20.x).zip, file/unlock all recipes v2.0.5 (MC 1.20.x).zip, file/xp management v1.1.4 (MC 1.20.x).zip, file/VanillaTweaks_c768608_MC1.20.x.zip
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental`

### Describe the bug

sometimes, on specific items in rei, going into the guidebook will crash the game.
on some items its fine but on others it crashes the game saying something about rendering, i think it maybe the same block each time thats causing the crash but i have no real idea.

i am using LambDynamicLights, which ive been having problems with, and indium. based on the limited amount of knowledge i have on them they both mess with rendering, so they could be the problem, but i would have no idea which one  is causing rendering issues with ae2 blocks if it even is a problem on their side, but i have no idea, this could be a problem i would be experiencing with or without using them so to me better safe than sorry posting it here. plus, i heard there were some other problems 

### Steps to reproduce

1. find an ae2 item that uses the guidebook

2. press and hold 'G' to open the guidebook

3 a. if it opens correctly, thats sick, hype even. try another.
3 b. on an item that doesnt work the second you try to open the guidebook the game crashes, the items that are broken are 
       consistent

### Expected behaviour

for all items to open the guidebook, not some of them and not others.

### Screenshots

a SC wouldnt really help here so heres a video of me replicating it and showing that its only _some_ items that are crashing, its 93 mb so i have to upload it to youtube
https://youtu.be/gOb6rBirk5U

### Additional information

i do have a few rendering mods installed, LambDynamicLights, indium, and sodium to name a few. the crash log says that its a rendering problem and references "appeng.client.guidebook.screen.GuideScreen" which i would assume is the actual guidebook. 

if it is a problem with compatibility with my modlist i would have no idea about that and if its posted somewhere that its not compatible out the gate thats definitely on me, but i think that id still have this problem without them if you ask me, i dont have any real evidence for that thinking but i just got a feeling. and i really hope i dont have to try and mess with this modpack i made anymore because one little cable bus doesnt render correctly when i finally end up using it in game.

**Comment by nevaduh** [comment]
my bad i was really tired yesterday and somehow didnt realize this was for specifically FTB modpack issues, dont know how i didnt realize this sooner, sorry!

**Comment by caeserlettuce** [comment]
Did you figure out the cause of this issue? I'm getting the same error from indium in my modpack.
