### ISSUE TITLE
Problem with client - server setup

### ISSUE THREAD

**Issue by PavelKCZ** [FTBTeam/FTB-Modpack-Issues#3954]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0.1

### Describe the bug

Hello,

I freshly installed the FTB App and Direwolf20 1.20 modpack on my PC (Windows 10) and installation was without any problem.
When I tried to create a new world, it was also without any problem and Minecraft started without any problems.

After that, I installed a fresh installation of the Direwolf20 1.20 modpack server on a clean Raspberry Pi 4/8GB. Installation was also without any problem, server is running fine, no errors etc.

But when I try to connect from the PC client to the server (both machines are on the same home LAN), server see that I am connecting and immediately disconecting.
On the PC side, there is the error in debug.log:

[05Oct2023 22:53:22.347] [Netty Client IO #6/DEBUG] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Range value 1.0 is not within its bounds 100.0-10000.0
[05Oct2023 22:53:22.347] [Netty Client IO #6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key valve.rclPerOperation was corrected from 1 to its default, 100. 
[05Oct2023 22:53:22.348] [Netty Client IO #6/DEBUG] [net.minecraftforge.common.ForgeConfigSpec/CORE]: List on key augment_limits is deemed to need correction. It is null, not a list, or an empty list. Modders, consider defineListAllowEmpty?
[05Oct2023 22:53:22.348] [Netty Client IO #6/DEBUG] [net.minecraftforge.common.ForgeConfigSpec/CORE]: List on key augment_cost_overrides is deemed to need correction. It is null, not a list, or an empty list. Modders, consider defineListAllowEmpty?
[05Oct2023 22:53:22.348] [Netty Client IO #6/DEBUG] [net.minecraftforge.common.ForgeConfigSpec/CORE]: List on key invalid_combos is deemed to need correction. It is null, not a list, or an empty list. Modders, consider defineListAllowEmpty?
[05Oct2023 22:53:22.349] [Netty Client IO #6/INFO] [FluxNetworks/Energy]: Energy blacklist loaded: 1 block entries, 0 item entries
[05Oct2023 22:53:22.349] [Netty Client IO #6/DEBUG] [FluxNetworks/]: Server config loaded
[05Oct2023 22:53:22.420] [Render thread/DEBUG] [ironfurnaces.IronFurnaces/]: Loading config file C:\Users\PavelK\AppData\Local\.ftba\instances\fa843975-22b8-4c2b-aa5a-1c5416ead5ef\config\ironfurnaces-client.toml
[05Oct2023 22:53:22.420] [Render thread/DEBUG] [ironfurnaces.IronFurnaces/]: Built TOML config for C:\Users\PavelK\AppData\Local\.ftba\instances\fa843975-22b8-4c2b-aa5a-1c5416ead5ef\config\ironfurnaces-client.toml
[05Oct2023 22:53:22.421] [Render thread/DEBUG] [ironfurnaces.IronFurnaces/]: Loaded TOML config file C:\Users\PavelK\AppData\Local\.ftba\instances\fa843975-22b8-4c2b-aa5a-1c5416ead5ef\config\ironfurnaces-client.toml
[05Oct2023 22:53:22.421] [Render thread/DEBUG] [ironfurnaces.IronFurnaces/]: Loading config file C:\Users\PavelK\AppData\Local\.ftba\instances\fa843975-22b8-4c2b-aa5a-1c5416ead5ef\config\ironfurnaces.toml
[05Oct2023 22:53:22.421] [Render thread/DEBUG] [ironfurnaces.IronFurnaces/]: Built TOML config for C:\Users\PavelK\AppData\Local\.ftba\instances\fa843975-22b8-4c2b-aa5a-1c5416ead5ef\config\ironfurnaces.toml
[05Oct2023 22:53:22.421] [Render thread/DEBUG] [ironfurnaces.IronFurnaces/]: Loaded TOML config file C:\Users\PavelK\AppData\Local\.ftba\instances\fa843975-22b8-4c2b-aa5a-1c5416ead5ef\config\ironfurnaces.toml
[05Oct2023 22:53:22.422] [Render thread/DEBUG] [com.simibubi.create.Create/]: Prepared Redstone Network Space for minecraft:overworld
[05Oct2023 22:53:22.422] [Render thread/DEBUG] [com.simibubi.create.Create/]: Prepared Kinetic Network Space for minecraft:overworld
[05Oct2023 22:53:22.460] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggingIn
[05Oct2023 22:53:22.460] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver transitioning state from DISABLED to ENABLED
[05Oct2023 22:53:22.467] [Netty Client IO #6/WARN] [com.connectivity.Connectivity/]: Packet not registered: ClientboundDisconnectPacket
[05Oct2023 22:53:22.468] [Netty Client IO #6/WARN] [com.connectivity.Connectivity/]: Packet:ClientboundDisconnectPacket 
[05Oct2023 22:53:22.468] [Netty Client IO #6/WARN] [com.connectivity.Connectivity/]: Packet data:
{
  "f_132075_": {
    "f_237194_": {
      "f_237497_": "disconnect.genericReason",
      "f_237498_": [
        "Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: index: 20, length: 102 (expected: range(0, 62))"
      ],
      "f_237500_": []
    },
    "f_237195_": [],
    "f_237196_": {},
    "f_237197_": {}
  }
}
[05Oct2023 22:53:22.473] [Render thread/ERROR] [net.minecraft.util.thread.BlockableEventLoop/FATAL]: Error executing task on Client
java.util.NoSuchElementException: packet_handler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at net.minecraftforge.network.filters.NetworkFilters.lambda$injectIfNecessary$1(NetworkFilters.java:39) ~[forge-1.20.1-47.1.76-universal.jar%23721!/:?]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:292) ~[guava-31.1-jre.jar%23109!/:?]
	at net.minecraftforge.network.filters.NetworkFilters.injectIfNecessary(NetworkFilters.java:35) ~[forge-1.20.1-47.1.76-universal.jar%23721!/:?]
	at net.minecraftforge.network.NetworkHooks.sendMCRegistryPackets(NetworkHooks.java:110) ~[forge-1.20.1-47.1.76-universal.jar%23721!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5998_(ClientPacketListener.java:429) ~[client-1.20.1-20230612.114412-srg.jar%23716!/:?]
	at net.minecraft.network.protocol.game.ClientboundLoginPacket.m_5797_(ClientboundLoginPacket.java:95) ~[client-1.20.1-20230612.114412-srg.jar%23716!/:?]
	at net.minecraft.network.protocol.game.ClientboundLoginPacket.m_5797_(ClientboundLoginPacket.java:25) ~[client-1.20.1-20230612.114412-srg.jar%23716!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23716!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23716!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23716!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23716!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%23716!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%23716!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23716!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.1.76.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-47.1.47.jar:47.1]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114) ~[loader-47.1.47.jar:47.1]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-47.1.47.jar:47.1]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-47.1.47.jar:47.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
[05Oct2023 22:53:22.481] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggingOut
[05Oct2023 22:53:22.481] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver transitioning state from ENABLED to DISABLED
[05Oct2023 22:53:22.481] [Render thread/INFO] [FluxNetworks/]: Released client Flux Networks cache
[05Oct2023 22:53:22.481] [Render thread/DEBUG] [SpectreLib/CONFIG]: Unloading server configs

and client is not connected to the server.
 

### Steps to reproduce

Install FTB App and Direwolf20 1.20 modpack
Install FTB Direwolf20 1.20 modpack server package on clean machine (ideally Raspberry Pi 4)
Start the DW20 modpack
Try to select "Multiplayer" - "Direct Connection" - enter IP address of the server on local LAN
Client will try to connect to the server. Server will log that player "XYZPlayer" is connected, but immediately will log that player is disconnected.
Client will write the above mentioned error message.

### Expected behaviour

Client will connect to server and game will start

**Comment by PavelKCZ** [comment]
After erasing the Pi 4 SD card and new installation of everything on the server side, the problem disappeared.

So I suppose that this thread can be closed.
