### ISSUE TITLE
FTB University 1.3.0 Server - 

### ISSUE THREAD

**Issue by Dayuppy** [FTBTeam/FTB-Modpack-Issues#3967]
### Modpack

FTB University 1.19

### Modpack version

1.3.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12835800/latest.log)

### Describe the bug

1.2.0 worked perfectly fine. Updated to 1.3.0, exception occurs and will not continue. Tried completely new vanilla modpack install without updating from 1.2.0, same exception. Tried --safemode, same exception. Confirmed in #help-and-support channel in FTB Discord with another user, they too are experiencing the same issue.

### Steps to reproduce

1. Go to https://feed-the-beast.com/modpacks/server-files and download FTB University 1.19 1.3.0.
2. Run the installer in the directory you would like to install the server.
3. Run Start BATCH file.
4. See exception.

### Expected behaviour

Server to start without exception.

### Additional information

06Oct2023 18:01:30.280] [main/WARN] [net.minecraft.server.Main/]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:182) ~[server-1.19.2-20220805.130853-srg.jar%23587!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.2.21.jar%2367!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.2-43.2.21.jar%2367!/:1.0]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2354!/:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2354!/:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2354!/:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at nl.teamdiopside.seamless.forge.SeamlessForge.reloadOutlines(SeamlessForge.java:48) ~[seamless-2.1.0-forge-1.19.2.jar%23547!/:?]
	at nl.teamdiopside.seamless.forge.SeamlessForge$1.apply(SeamlessForge.java:33) ~[seamless-2.1.0-forge-1.19.2.jar%23547!/:?]
	at nl.teamdiopside.seamless.forge.SeamlessForge$1.m_5787_(SeamlessForge.java:30) ~[seamless-2.1.0-forge-1.19.2.jar%23547!/:?]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[server-1.19.2-20220805.130853-srg.jar%23587!/:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[server-1.19.2-20220805.130853-srg.jar%23587!/:?]
	at net.minecraft.Util.m_214652_(Util.java:781) ~[server-1.19.2-20220805.130853-srg.jar%23587!/:?]
	at net.minecraft.Util.m_214679_(Util.java:770) ~[server-1.19.2-20220805.130853-srg.jar%23587!/:?]
	at net.minecraft.server.Main.main(Main.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23587!/:?]
	... 13 more

**Comment by tlannigan** [comment]
Also have this exact same issue and error output. I downloaded the installer .exe, ran it, then ran start.bat to receive the same errors as the author.

**Comment by MichaelHillcox** [comment]
Please attach the full crash log

**Comment by Dayuppy** [comment]
> Please attach the full crash log

I already posted the latest.log file in the original post. Unless the GZ log archive is what you are needing: 
[2023-10-06-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12836003/2023-10-06-1.log.gz)

**Comment by MichaelHillcox** [comment]
Sorry, my mistake. Please remove this file from the server `seamless-2.1.0-forge-1.19.2.jar` this looks to be a client side only mod. I'll look into this more tomorrow.

**Comment by Dayuppy** [comment]
Thank you, I will give that a go later when everybody is asleep.

**Comment by aaronhowser1** [comment]
I'll push out a 1.3.1 with the fix. Sorry!
