### ISSUE TITLE
Tetra Server Crash

### ISSUE THREAD

**Issue by GHOSTLYxKNIGHT** [FTBTeam/FTB-Modpack-Issues#3980]
### Modpack

FTB Presents AbePack

### Modpack version

1.2.0

### Describe the bug

While using the Tetra Mod within the FTB Presents AbePack. If a player breaks a Placed Tetra block (IE. Tetra Forge, Tetra Schematics, Tetra shelving). The server crashes the moment the items hit the ground. This has occured with all above items listed and additional Tetra Items. But they must be placed as an entity first, finding the items within a chest does not crash.

### Steps to reproduce

Change Game mode to Creative
Spawn Tetra Forge or Workbench
Place entity
Log out
Log back in
Break the entity
Server crash 

### Expected behaviour

i expected the item to break and act as normal block loot.

### Additional information

this bug did not seem to occur in 1.1.1

**Comment by GHOSTLYxKNIGHT** [comment]
`---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 2023-10-12 12:03:09
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.2-43.2.23-universal.jar%23566!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.19.2-43.2.23-universal.jar%23566!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19.2-20220805.130853-srg.jar%23561!/:?] {re:classloading,re:mixin,pl:mixin:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.2.23.jar%2367!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:58) ~[forge-1.19.2-43.2.23-universal.jar%23566!/:?] {re:classloading}
-- MOD adaptive_performance_tweaks --
Details:
	Mod File: /home/container/mods/adaptive_performance_tweaks_1.19.2-6.8.0.jar
	Failure message: Mod adaptive_performance_tweaks requires adaptive_performance_tweaks_items 6.8.0 or above, and below 7.0.0
		Currently, adaptive_performance_tweaks_items is not installed
	Mod Version: 6.8.0
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE
Stacktrace:
	at net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:58) ~[forge-1.19.2-43.2.23-universal.jar%23566!/:?] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:56) ~[forge-1.19.2-43.2.23-universal.jar%23566!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.19.2-43.2.23-universal.jar%23566!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19.2-20220805.130853-srg.jar%23561!/:?] {re:classloading,re:mixin,pl:mixin:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.2.23.jar%2367!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


-- MOD adaptive_performance_tweaks --
Details:
	Mod File: /home/container/mods/adaptive_performance_tweaks_1.19.2-6.8.0.jar
	Failure message: Mod adaptive_performance_tweaks requires adaptive_performance_tweaks_spawn 6.8.0 or above, and below 7.0.0
		Currently, adaptive_performance_tweaks_spawn is not installed
	Mod Version: 6.8.0
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE

-- MOD adaptive_performance_tweaks --
Details:
	Mod File: /home/container/mods/adaptive_performance_tweaks_1.19.2-6.8.0.jar
	Failure message: Mod adaptive_performance_tweaks requires adaptive_performance_tweaks_player 6.8.0 or above, and below 7.0.0
		Currently, adaptive_performance_tweaks_player is not installed
	Mod Version: 6.8.0
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE

-- MOD adaptive_performance_tweaks --
Details:
	Mod File: /home/container/mods/adaptive_performance_tweaks_1.19.2-6.8.0.jar
	Failure message: Mod adaptive_performance_tweaks requires adaptive_performance_tweaks_gamerules 6.8.0 or above, and below 7.0.0
		Currently, adaptive_performance_tweaks_gamerules is not installed
	Mod Version: 6.8.0
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE

-- MOD adaptive_performance_tweaks --
Details:
	Mod File: /home/container/mods/adaptive_performance_tweaks_1.19.2-6.8.0.jar
	Failure message: Mod adaptive_performance_tweaks requires adaptive_performance_tweaks_core 6.8.0 or above, and below 7.0.0
		Currently, adaptive_performance_tweaks_core is not installed
	Mod Version: 6.8.0
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 5.4.0-163-generic
	Java Version: 17.0.8.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 599007696 bytes (571 MiB) / 1157627904 bytes (1104 MiB) up to 23941087232 bytes (22832 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600X 6-Core Processor
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 17017.70
	Virtual memory used (MB): 2808.11
	Swap memory total (MB): 1023.99
	Swap memory used (MB): 0.45
	JVM Flags: 2 total; -Xms128M -XX:MaxRAMPercentage=95.0
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.2.23.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.23.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.2.23.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.2.23.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.23.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
		kotlinforforge@3.12.0
		lowcodefml@null
		kotori_scala@2.13.10-build-10
	Mod List: 
		server-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |NONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.2.23-universal.jar                |Forge                         |forge `
		
		
		and
		
		`---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 2023-10-12 12:03:20
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.2-43.2.23-universal.jar%23566!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.19.2-43.2.23-universal.jar%23566!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19.2-20220805.130853-srg.jar%23561!/:?] {re:classloading,re:mixin,pl:mixin:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.2.23.jar%2367!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:58) ~[forge-1.19.2-43.2.23-universal.jar%23566!/:?] {re:classloading}
-- MOD adaptive_performance_tweaks --
Details:
	Mod File: /home/container/mods/adaptive_performance_tweaks_1.19.2-6.8.0.jar
	Failure message: Mod adaptive_performance_tweaks requires adaptive_performance_tweaks_items 6.8.0 or above, and below 7.0.0
		Currently, adaptive_performance_tweaks_items is not installed
	Mod Version: 6.8.0
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE
Stacktrace:
	at net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:58) ~[forge-1.19.2-43.2.23-universal.jar%23566!/:?] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:56) ~[forge-1.19.2-43.2.23-universal.jar%23566!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.19.2-43.2.23-universal.jar%23566!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19.2-20220805.130853-srg.jar%23561!/:?] {re:classloading,re:mixin,pl:mixin:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.2.23.jar%2367!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


-- MOD adaptive_performance_tweaks --
Details:
	Mod File: /home/container/mods/adaptive_performance_tweaks_1.19.2-6.8.0.jar
	Failure message: Mod adaptive_performance_tweaks requires adaptive_performance_tweaks_spawn 6.8.0 or above, and below 7.0.0
		Currently, adaptive_performance_tweaks_spawn is not installed
	Mod Version: 6.8.0
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE

-- MOD adaptive_performance_tweaks --
Details:
	Mod File: /home/container/mods/adaptive_performance_tweaks_1.19.2-6.8.0.jar
	Failure message: Mod adaptive_performance_tweaks requires adaptive_performance_tweaks_player 6.8.0 or above, and below 7.0.0
		Currently, adaptive_performance_tweaks_player is not installed
	Mod Version: 6.8.0
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE

-- MOD adaptive_performance_tweaks --
Details:
	Mod File: /home/container/mods/adaptive_performance_tweaks_1.19.2-6.8.0.jar
	Failure message: Mod adaptive_performance_tweaks requires adaptive_performance_tweaks_gamerules 6.8.0 or above, and below 7.0.0
		Currently, adaptive_performance_tweaks_gamerules is not installed
	Mod Version: 6.8.0
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE

-- MOD adaptive_performance_tweaks --
Details:
	Mod File: /home/container/mods/adaptive_performance_tweaks_1.19.2-6.8.0.jar
	Failure message: Mod adaptive_performance_tweaks requires adaptive_performance_tweaks_core 6.8.0 or above, and below 7.0.0
		Currently, adaptive_performance_tweaks_core is not installed
	Mod Version: 6.8.0
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 5.4.0-163-generic
	Java Version: 17.0.8.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 687560496 bytes (655 MiB) / 1258291200 bytes (1200 MiB) up to 23941087232 bytes (22832 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600X 6-Core Processor
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 17017.70
	Virtual memory used (MB): 2894.34
	Swap memory total (MB): 1023.99
	Swap memory used (MB): 0.45
	JVM Flags: 2 total; -Xms128M -XX:MaxRAMPercentage=95.0
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.2.23.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.23.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.2.23.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.2.23.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.23.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
		kotlinforforge@3.12.0
		lowcodefml@null
		kotori_scala@2.13.10-build-10
	Mod List: 
		server-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |NONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.2.23-universal.jar                |Forge                         |forge `
		
		
		and here is our Spark Profile
		
![Y7qXpc4542](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/19217201/0843aa75-67e5-42e4-aee5-6d43e63d5b93)
