### ISSUE TITLE
Client-side Functional Storage crash

### ISSUE THREAD

**Issue by ukmcplyr** [FTBTeam/FTB-Modpack-Issues#4018]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.1.0

### Log Files

- [latest.log](https://pste.ch/cufiqeqiru.md)
- [crash report](https://pste.ch/ponuziqavi.pl)

### Describe the bug

I've run into a client-side crash with Functional Storage when playing on a server.

At the time of the crash I had an RFTools Builder filling up a drawer system, in the standard JAMD mining dim, using a Laser IO node runing inserting at 64 items a tick.

I placed 3/5 compacting drawers from my inventory 1 block away from the active controller and on mousing over either of the remaining two drawers in my inventory, the client crashes:

```
[12Oct2023 01:04:09.341] [Render thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Index 3 out of bounds for length 2
        Index: 4
        Listeners:
                0: HIGH
                1: ASM: class dev.architectury.event.forge.EventHandlerImplClient eventRenderTooltipEvent(Lnet/minecraftforge/client/event/RenderTooltipEvent$Pre;)V
                2: NORMAL
                3: ASM: class com.hollingsworth.arsnouveau.client.events.ClientEvents TooltipEvent(Lnet/minecraftforge/client/event/RenderTooltipEvent$Pre;)V
                4: net.minecraftforge.eventbus.EventBus$$Lambda$1640/0x0000000801881380@4fce4218
                5: net.minecraftforge.eventbus.EventBus$$Lambda$1640/0x0000000801881380@1f02c7ba
java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 2
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
        at java.base/java.util.Objects.checkIndex(Unknown Source)
        at java.base/java.util.ArrayList.get(Unknown Source)
        at TRANSFORMER/functionalstorage@1.20.1-1.2.3/com.buuz135.functionalstorage.inventory.item.CompactingStackItemHandler.getStackInSlot(CompactingStackItemHandler.java:86)
```

I'm going to have to do some playerdata editing to get back to a playable state, I'll update this issue if there's any obviously bad NBT.

### Steps to reproduce

Unknown

### Expected behaviour

No crash

**Comment by ukmcplyr** [comment]
Updated to include reproduction steps.

**Comment by rjorgenson** [comment]
I am also experiencing this issue in All The Mods 8 Volcano Block. I broke a handful of loaded but not full compacting drawers to move them and now the client crashes whenever I open my inventory.

[crash-2023-10-14_08.34.45-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12906624/crash-2023-10-14_08.34.45-client.txt)

**Comment by rjorgenson** [comment]
@ukmcplyr I loaded up the Functional Storage that was released today (1.1.8 for 1.19.2) and it resolved this issue. I found the functional storage bug report here https://github.com/Buuz135/FunctionalStorage/issues/210 and the change that fixes this here https://github.com/Buuz135/FunctionalStorage/commit/2b7926a1221e000f869bcfed82633122b6eea0e6

**Comment by ukmcplyr** [comment]
Cheers for the pointer, can stop moving the buggers with cardboard boxes now :grin:

**Comment by DinnerBeef** [comment]
This issue has now been fixed! Please reopen this issue if you are still having problems.
