### ISSUE TITLE
Rftools tablet doesn't work in modpack

### ISSUE THREAD

**Issue by yuriondelagrion** [FTBTeam/FTB-Modpack-Issues#4068]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.2.0

### Log Files

<details>
<summary>Error log</summary>
<p>

at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
at MC-BOOTSTRAP/fml_loader@47.1.47/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108)
at MC-BOOTSTRAP/fml_loader@47.1.47/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24)
at MC-BOOTSTRAP/fml_loader@47.1.47/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114)
at MC-BOOTSTRAP/fml_loader@47.1.47/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:67)
at TRANSFORMER/forge@47.1.76/net.minecraftforge.network.PlayMessages$OpenContainer.lambda$handle$1(PlayMessages.java:290)
at java.base/java.util.Optional.ifPresent(Unknown Source)
at TRANSFORMER/forge@47.1.76/net.minecraftforge.network.PlayMessages$OpenContainer.lambda$handle$0(PlayMessages.java:291)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.inventory.MenuType.create(MenuType.java:61)
at TRANSFORMER/mcjtylib@1.20-8.0.3/mcjty.lib.container.GenericContainer.lambda$createRemoteContainerType$6(GenericContainer.java:526)
at TRANSFORMER/rftoolsstorage@1.20-5.0.1/mcjty.rftoolsstorage.modules.scanner.blocks.StorageScannerTileEntity.<init>(StorageScannerTileEntity.java:145)
at TRANSFORMER/rftoolsstorage@1.20-5.0.1/mcjty.rftoolsstorage.modules.scanner.blocks.StorageScannerTileEntity.<init>(StorageScannerTileEntity.java:139)
at TRANSFORMER/mcjtylib@1.20-8.0.3/mcjty.lib.tileentity.TickingTileEntity.<init>(TickingTileEntity.java:10)
at TRANSFORMER/mcjtylib@1.20-8.0.3/mcjty.lib.tileentity.GenericTileEntity.<init>(GenericTileEntity.java:70)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.entity.BlockEntity.<init>(BlockEntity.java:33)
at TRANSFORMER/forge@47.1.76/net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:51)
at TRANSFORMER/forge@47.1.76/net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:67)
at TRANSFORMER/forge@47.1.76/net.minecraftforge.common.capabilities.CapabilityProvider.doGatherCapabilities(CapabilityProvider.java:72)
at TRANSFORMER/forge@47.1.76/net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:628)
at TRANSFORMER/forge@47.1.76/net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:634)
at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
at TRANSFORMER/botarium@2.2.0/earth.terrarium.botarium.forge.BotariumForge.attachBlockCapabilities(BotariumForge.java:58)
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.state.BlockState.m_60734_()" because the return value of "net.minecraft.world.level.block.entity.BlockEntity.m_58900_()" is null
75: net.minecraftforge.eventbus.EventBus$$Lambda$1634/0x0000000801854910@7f05555e
74: ASM: mcjty.rftoolsutility.setup.ForgeEventHandlers@14484949 onEntityConstructing(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
73: net.minecraftforge.eventbus.EventBus$$Lambda$1634/0x0000000801854910@73448138
72: net.minecraftforge.eventbus.EventBus$$Lambda$1634/0x0000000801854910@6fc28423
71: net.minecraftforge.eventbus.EventBus$$Lambda$1634/0x0000000801854910@2ab4eb12
70: net.minecraftforge.eventbus.EventBus$$Lambda$1634/0x0000000801854910@231cf89
69: ASM: mcjty.lib.setup.ModSetup$EventHandler@6b6c7b6c onEntityConstructing(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
68: ASM: com.illusivesoulworks.comforts.common.CapabilitySleepData$CapabilityEvents@79a7ba3a onAttachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
67: ASM: class dan200.computercraft.shared.integration.MoreRedIntegration attachBlockCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
66: net.minecraftforge.eventbus.EventBus$$Lambda$1634/0x0000000801854910@50c98a61
65: ASM: mekanism.common.CommonPlayerTracker@48e00873 attachCaps(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
64: ASM: com.illusivesoulworks.polymorph.common.CommonEventsListener@20932a52 attachCapabilitiesStack(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
63: ASM: com.illusivesoulworks.polymorph.common.CommonEventsListener@20932a52 attachCapabilitiesPlayer(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
62: ASM: com.illusivesoulworks.polymorph.common.CommonEventsListener@20932a52 attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
61: ASM: org.cyclops.cyclopscore.modcompat.capabilities.CapabilityConstructorRegistry$TileEventListener@218419e3 onTileLoad(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
60: ASM: mcjty.theoneprobe.ForgeEventHandlers@4fbecaeb onEntityConstructing(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
59: net.minecraftforge.eventbus.EventBus$$Lambda$1634/0x0000000801854910@14fa392e
58: ASM: de.ellpeck.naturesaura.events.CommonEvents@3b105b21 onChunkCapsAttach(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
57: ASM: de.ellpeck.naturesaura.events.CommonEvents@3b105b21 onLevelCapsAttach(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
56: net.minecraftforge.eventbus.EventBus$$Lambda$1634/0x0000000801854910@1567b944
55: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@2156cfef attachStackCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
54: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@2156cfef attachEntitiesCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
53: ASM: com.blakebr0.ironjetpacks.compat.curios.CuriosCompat@48ae6d6b onAttachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
52: net.minecraftforge.eventbus.EventBus$$Lambda$1634/0x0000000801854910@6406c594
51: net.minecraftforge.eventbus.EventBus$$Lambda$1634/0x0000000801854910@5fc36686
50: ASM: class com.stal111.forbidden_arcanus.event.AttachCapabilitiesListener onWorldCapabilityAttachEvent(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
49: ASM: class com.stal111.forbidden_arcanus.event.AttachCapabilitiesListener onPlayerCapabilityAttachEvent(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
48: ASM: class dev.xkmc.modulargolems.events.ModifierEventListeners onAttachLevelCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
47: ASM: class sonar.fluxnetworks.register.EventHandler onAttachCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
46: ASM: class com.simibubi.create.foundation.events.CommonEvents attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
45: ASM: class net.blay09.mods.cookingforblockheads.compat.CompatCapabilityLoader attachTileEntityCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
44: ASM: class com.mystchonky.arsocultas.common.events.EventHandler attachItemCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
43: ASM: class tv.soaryn.xycraft.core.XyCoreClient$ForgeBus onAttachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
42: ASM: class tv.soaryn.xycraft.core.XyCoreCommon onAttachCapabilitiesToPlayer(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
41: net.minecraftforge.eventbus.EventBus$$Lambda$1634/0x0000000801854910@73ee5e58
40: net.minecraftforge.eventbus.EventBus$$Lambda$1634/0x0000000801854910@5e15f0a0
39: ASM: class dan200.computercraft.shared.ForgeCommonHooks onCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
38: ASM: class net.creeperhost.polylib.forge.ForgeEvents OnAttachCapabilitiesEvent(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
37: ASM: class com.hollingsworth.arsnouveau.setup.registry.CapabilityRegistry$EventHandler attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
36: net.minecraftforge.eventbus.EventBus$$Lambda$1634/0x0000000801854910@62cb26ac
35: net.minecraftforge.eventbus.EventBus$$Lambda$1634/0x0000000801854910@443d0784
34: ASM: org.cyclops.cyclopscore.modcompat.capabilities.CapabilityConstructorRegistry$EntityEventListener@722f1ca7 onEntityLoad(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
33: ASM: org.cyclops.cyclopscore.modcompat.capabilities.CapabilityConstructorRegistry$ItemStackEventListener@1d023303 onItemStackLoad(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
32: ASM: org.cyclops.cyclopscore.modcompat.capabilities.CapabilityConstructorRegistry$TileEventListener@10aa9469 onTileLoad(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
31: net.minecraftforge.eventbus.EventBus$$Lambda$1634/0x0000000801854910@6888bbc9
30: net.minecraftforge.eventbus.EventBus$$Lambda$1634/0x0000000801854910@3661506d
29: ASM: ru.yurannnzzz.moreredcccompat.MoreRedCCCompatMod@5b5153d attachCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
28: ASM: class com.aetherteam.aether.capability.AetherCapabilities$Registration attachEntityCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
27: net.minecraftforge.eventbus.EventBus$$Lambda$1634/0x0000000801854910@549e59c6
26: ASM: class com.aetherteam.aether.capability.AetherCapabilities$Registration attachWorldCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
25: ASM: class me.desht.pneumaticcraft.common.thirdparty.curios.Curios$CuriosCapabilityListener attachCurioInvTicker(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
24: ASM: class net.tropicraft.core.common.item.scuba.ScubaData onCapabilityAttach(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
23: ASM: me.desht.pneumaticcraft.common.thirdparty.mekanism.Mekanism@2e470635 attachHeatAdapters(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
22: ASM: me.desht.pneumaticcraft.common.thirdparty.mekanism.Mekanism@2e470635 attachRadiationShield(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
21: ASM: mods.railcraft.Railcraft@5c446c0d handleAttachItemStackCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
20: ASM: class me.desht.pneumaticcraft.common.thirdparty.computercraft.ComputerCraft attachPeripheralCap(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
19: ASM: mods.railcraft.Railcraft@5c446c0d handleAttachEntityCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
18: ASM: INSTANCE onEntityConstruction(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
17: net.minecraftforge.eventbus.EventBus$$Lambda$1634/0x0000000801854910@7c5a1864
16: net.minecraftforge.eventbus.EventBus$$Lambda$1634/0x0000000801854910@4c624ab2
15: ASM: class com.klikli_dev.occultism.handlers.CapabilityEventHandler onEntityConstructing(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
14: net.minecraftforge.eventbus.EventBus$$Lambda$1634/0x0000000801854910@27e8aea6
13: net.minecraftforge.eventbus.EventBus$$Lambda$1634/0x0000000801854910@4f3cea1b
12: ASM: class com.traverse.bhc.common.util.HealthModifier attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
11: ASM: class net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge onAttachTileCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
10: ASM: class dev.xkmc.l2library.init.events.BaseCapabilityEvents onAttachEntityCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
9: ASM: class com.supermartijn642.wormhole.PortalGroupCapability attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
8: ASM: class ironfurnaces.util.EventHandler playerEvent(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
7: net.minecraftforge.eventbus.EventBus$$Lambda$1634/0x0000000801854910@34508b19
6: ASM: class net.xalcon.torchmaster.common.logic.entityblocking.EntityBlockingEventHandler onWorldAttachCapabilityEvent(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
5: ASM: class net.gigabit101.shrink.events.PlayerEvents attachCaps(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
4: ASM: class com.matyrobbrt.antsportation.onetimejoin.OneTimeRewardListener onAttach(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
3: net.minecraftforge.eventbus.EventBus$$Lambda$1634/0x0000000801854910@3d6ac168
2: net.minecraftforge.eventbus.EventBus$$Lambda$1634/0x0000000801854910@65f1a9ab
1: net.minecraftforge.eventbus.EventBus$$Lambda$1634/0x0000000801854910@5e94a068
0: NORMAL
Listeners:
Index: 1
[14:24:34] [Render thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "net.minecraft.world.level.block.state.BlockState.m_60734_()" because the return value of "net.minecraft.world.level.block.entity.BlockEntity.m_58900_()" is null

</p>
</details>

### Describe the bug

Tablet from rftools doesn't work. I bound the screen module to the scanner, inserted into the tablet, pressed the right button and nothing shows up.

I tested the mod on its own and it works so the issue is in the pack itself not the mod.

### Steps to reproduce

craft the necessary items
bind the screen module to the storage scanner
insert it into the tablet
press right mouse button.

### Expected behaviour

When pressing the right button, a duplicate screen of storage scanner should show up, but it doesn't.

**Comment by Kyefer** [comment]
I am experiecing this issue as well.

I found an issue already open on the RFToolsStorage issue log.
https://github.com/McJtyMods/RFToolsStorage/issues/82

McJty came to the conclusion that this is a mod conflict, as the issue is with right-click behavior. I wonder if this is the case and which mod is causing the potential conflict.

**Comment by DinnerBeef** [comment]
It looks like the mod dev has resolved this issue.  The update should be in the latest version of the pack. Please reopen this issue if you are stilling have issues.
