### ISSUE TITLE
DW20 1.20 v1.3.0 client Crash *unplayable*

### ISSUE THREAD

**Issue by dalgrim** [FTBTeam/FTB-Modpack-Issues#4115]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.3.0

### Log Files

[25Oct2023 15:44:42.758] [Render thread/ERROR] [mezz.jei.library.load.PluginCaller/]: Caught an error from mod plugin: class dev.latvian.mods.kubejs.integration.forge.jei.JEIPlugin kubejs:jei
java.lang.IllegalArgumentException: ingredients must not be empty.
	at mezz.jei.common.util.ErrorUtil.checkNotEmpty(ErrorUtil.java:109) ~[jei-1.20.1-forge-15.2.0.27.jar%23580!/:15.2.0.27]
	at mezz.jei.library.ingredients.IngredientManager.addIngredientsAtRuntime(IngredientManager.java:79) ~[jei-1.20.1-forge-15.2.0.27.jar%23580!/:15.2.0.27]
	at dev.latvian.mods.kubejs.integration.forge.jei.AddJEIEventJS.afterPosted(AddJEIEventJS.java:44) ~[kubejs-forge-2001.6.3-build.77.jar%23587!/:2001.6.3-build.77]
	at dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:293) ~[kubejs-forge-2001.6.3-build.77.jar%23587!/:2001.6.3-build.77]
	at dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:225) ~[kubejs-forge-2001.6.3-build.77.jar%23587!/:2001.6.3-build.77]
	at dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:188) ~[kubejs-forge-2001.6.3-build.77.jar%23587!/:2001.6.3-build.77]
	at dev.latvian.mods.kubejs.integration.forge.jei.JEIPlugin.onRuntimeAvailable(JEIPlugin.java:63) ~[kubejs-forge-2001.6.3-build.77.jar%23587!/:2001.6.3-build.77]
	at mezz.jei.library.startup.JeiStarter.lambda$start$3(JeiStarter.java:175) ~[jei-1.20.1-forge-15.2.0.27.jar%23580!/:15.2.0.27]
	at mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:27) ~[jei-1.20.1-forge-15.2.0.27.jar%23580!/:15.2.0.27]
	at mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:175) ~[jei-1.20.1-forge-15.2.0.27.jar%23580!/:15.2.0.27]
	at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137) ~[jei-1.20.1-forge-15.2.0.27.jar%23580!/:15.2.0.27]
	at mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:100) ~[jei-1.20.1-forge-15.2.0.27.jar%23580!/:15.2.0.27]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2389!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2389!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2389!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2389!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5859_(ClientPacketListener.java:1451) ~[client-1.20.1-20230612.114412-srg.jar%23728!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:35) ~[client-1.20.1-20230612.114412-srg.jar%23728!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:11) ~[client-1.20.1-20230612.114412-srg.jar%23728!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23728!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23728!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23728!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23728!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%23728!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%23728!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23728!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.1.76.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-47.1.47.jar:47.1]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114) ~[loader-47.1.47.jar:47.1]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-47.1.47.jar:47.1]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-47.1.47.jar:47.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
[25Oct2023 15:44:42.760] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime took 221.6 ms
[25Oct2023 15:44:42.760] [Render thread/INFO] [mezz.jei.core.util.LoggedTimer/]: Starting JEI took 12.41 s
[25Oct2023 15:44:42.765] [Render thread/INFO] [Cucumber Library/]: Loaded cucumber-tags.json in 0 ms
[25Oct2023 15:44:42.766] [Render thread/INFO] [integrateddynamics/]: Loading infobook /data/integrateddynamics/info/on_the_dynamics_of_integration.xml
[25Oct2023 15:44:42.802] [Render thread/INFO] [cyclopscore/]: Loading infobook /data/cyclopscore/info/test.xml
[25Oct2023 15:44:44.151] [Render thread/WARN] [ModernFix/]: Time from main menu to in-game was 26.40417 seconds
[25Oct2023 15:44:44.152] [Render thread/WARN] [ModernFix/]: Total time to load game and open world was 83.142166 seconds
[25Oct2023 15:45:27.593] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggingOut
[25Oct2023 15:45:27.594] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver transitioning state from JEI_STARTED to DISABLED
[25Oct2023 15:45:27.594] [Render thread/INFO] [mezz.jei.library.startup.JeiStarter/]: Stopping JEI
[25Oct2023 15:45:27.594] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable...
[25Oct2023 15:45:27.594] [Render thread/INFO] [mezz.jei.forge.plugins.forge.ForgeGuiPlugin/]: Stopping JEI GUI
[25Oct2023 15:45:27.597] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable took 2.768 ms
[25Oct2023 15:45:27.597] [Render thread/INFO] [FluxNetworks/]: Released client Flux Networks cache
[25Oct2023 15:45:28.307] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: Rendering screen
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:978) ~[client-1.20.1-20230612.114412-srg.jar%23728!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23728!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23728!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.1.76.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-47.1.47.jar:47.1]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114) ~[loader-47.1.47.jar:47.1]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-47.1.47.jar:47.1]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-47.1.47.jar:47.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[?:?]
	at java.util.Objects.checkIndex(Unknown Source) ~[?:?]
	at java.util.ArrayList.get(Unknown Source) ~[?:?]
	at dev.shadowsoffire.apotheosis.adventure.loot.RarityRegistry.getMinRarity(RarityRegistry.java:69) ~[Apotheosis-1.20.1-7.0.5.jar%23458!/:7.0.5]
	at dev.shadowsoffire.apotheosis.adventure.affix.socket.SocketHelper.loadSocketAffix(SocketHelper.java:173) ~[Apotheosis-1.20.1-7.0.5.jar%23458!/:7.0.5]
	at dev.shadowsoffire.apotheosis.adventure.affix.AffixHelper.getAffixesImpl(AffixHelper.java:85) ~[Apotheosis-1.20.1-7.0.5.jar%23458!/:7.0.5]
	at dev.shadowsoffire.placebo.util.CachedObject.compute(CachedObject.java:88) ~[Placebo-1.20.1-8.3.7.jar%23638!/:8.3.7]
	at dev.shadowsoffire.placebo.util.CachedObject.get(CachedObject.java:62) ~[Placebo-1.20.1-8.3.7.jar%23638!/:8.3.7]
	at net.minecraft.world.item.ItemStack.getOrCreate(ItemStack.java:3588) ~[client-1.20.1-20230612.114412-srg.jar%23728!/:?]
	at dev.shadowsoffire.placebo.util.CachedObject$CachedObjectSource.getOrCreate(CachedObject.java:139) ~[Placebo-1.20.1-8.3.7.jar%23638!/:8.3.7]
	at dev.shadowsoffire.apotheosis.adventure.affix.AffixHelper.getAffixes(AffixHelper.java:79) ~[Apotheosis-1.20.1-7.0.5.jar%23458!/:7.0.5]
	at net.minecraft.world.item.enchantment.EnchantmentHelper.handler$zhl000$apoth_getDamageBonus(EnchantmentHelper.java:575) ~[client-1.20.1-20230612.114412-srg.jar%23728!/:?]
	at net.minecraft.world.item.enchantment.EnchantmentHelper.m_44833_(EnchantmentHelper.java:169) ~[client-1.20.1-20230612.114412-srg.jar%23728!/:?]
	at net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:686) ~[client-1.20.1-20230612.114412-srg.jar%23728!/:?]
	at net.minecraft.client.gui.screens.Screen.m_280152_(Screen.java:246) ~[client-1.20.1-20230612.114412-srg.jar%23728!/:?]
	at net.minecraft.client.gui.GuiGraphics.m_280153_(GuiGraphics.java:550) ~[client-1.20.1-20230612.114412-srg.jar%23728!/:?]
	at net.p3pp3rf1y.sophisticatedcore.client.gui.StorageScreenBase.m_280072_(StorageScreenBase.java:637) ~[sophisticatedcore-1.20.1-0.5.100.457.jar%23687!/:1.20.1-0.5.100.457]
	at net.p3pp3rf1y.sophisticatedcore.client.gui.StorageScreenBase.m_88315_(StorageScreenBase.java:375) ~[sophisticatedcore-1.20.1-0.5.100.457.jar%23687!/:1.20.1-0.5.100.457]
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23728!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:423) ~[forge-1.20.1-47.1.76-universal.jar%23733!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:416) ~[forge-1.20.1-47.1.76-universal.jar%23733!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965) ~[client-1.20.1-20230612.114412-srg.jar%23728!/:?]
	... 19 more
[25Oct2023 15:45:28.313] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID *removed*
[25Oct2023 15:45:28.318] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID *removed*
[25Oct2023 15:45:28.325] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID *removed*

### Describe the bug

Running dedicated server. When a client connects you will only be able to play for about 20 seconds. Then the client will crash with error.

### Steps to reproduce

1) connect to server
2) walk around about 15-20 seconds
3) crash

### Expected behaviour

Expected not to crash

### Additional information

Possibly related to the reported Apotheosis error as that mod is listed in the crashlog and I do have apotheosis items on my player.

**Comment by DinnerBeef** [comment]
Same as https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4109
