### ISSUE TITLE
FTB Presents Direwolf20 1.20: Damage Tick in the Nether Causes an IndexOutOfBoundsException

### ISSUE THREAD

**Issue by BonusDucksMkII** [FTBTeam/FTB-Modpack-Issues#4118]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.3.0

### Log Files

[crash-2023-10-25_14.48.59-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13170547/crash-2023-10-25_14.48.59-server.txt)

### Describe the bug

Going into the Nether and taking any form of damage while wearing certain types of armor will seemingly cause the integrated server to crash after a short delay.

### Steps to reproduce

1. Start a standard single-player world
2. Wear below mentioned (or maybe any) types of armor
3. Go to the Nether
4. Take any form of damage (blocks, mobs, etc.)

### Expected behaviour

Integrated server should crash, stopping the rest of the game process

### Additional information

Looking over the crash report, it looks like trying to change armor durability at all might be the cause, but I'm not sure. I tried testing the armor I was wearing when the crash first happened, and it's a tossup between a Compressed Iron helmet and leggings (from PneumaticCraft), a normal Iron Chestplate with the Apotheosis "Blessed" modifier, and a pair of Diamond Boots with the Apotheosis "Stalwart" modifier, but all of them seemed to cause it. This crash seemed to happen after the recent update to 1.3, but didn't happen before.

**Comment by jaysonsantos** [comment]
same here but on a fairly new world, here is the top of the exception on the same version
```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2023-10-25 21:18:31
Description: Ticking entity

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?] {}
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?] {}
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?] {}
        at java.util.Objects.checkIndex(Objects.java:361) ~[?:?] {re:mixin}
        at java.util.ArrayList.get(ArrayList.java:427) ~[?:?] {re:mixin}
        at dev.shadowsoffire.apotheosis.adventure.loot.RarityRegistry.getMinRarity(RarityRegistry.java:69) ~[Apotheosis-1.20.1-7.0.5.jar%23395!/:7.0.5] {re:classloading}
        at dev.shadowsoffire.apotheosis.adventure.affix.AffixHelper.getAffixesImpl(AffixHelper.java:90) ~[Apotheosis-1.20.1-7.0.5.jar%23395!/:7.0.5] {re:mixin,re:classloading}
        at dev.shadowsoffire.placebo.util.CachedObject.compute(CachedObject.java:88) ~[Placebo-1.20.1-8.3.7.jar%23567!/:8.3.7] {re:mixin,re:classloading}
        at dev.shadowsoffire.placebo.util.CachedObject.get(CachedObject.java:62) ~[Placebo-1.20.1-8.3.7.jar%23567!/:8.3.7] {re:mixin,re:classloading}
        at net.minecraft.world.item.ItemStack.getOrCreate(ItemStack.java:3588) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:kubejs-common.mixins.json:ItemStackMixin,pl:mixin:APP:mixins.hammerlib.json:ItemStackMixin,pl:mixin:APP:useitemonblockevent.mixins.json:ItemStackMixin,pl:mixin:APP:apotheosis.mixins.json:ItemStackMixin,pl:mixin:APP:attributeslib.mixins.json:ItemStackMixin,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:fastsuite.mixins.json:ItemStackMixin,pl:mixin:APP:forbidden_arcanus.mixins.json:ItemStackMixin,pl:mixin:A}
        at dev.shadowsoffire.placebo.util.CachedObject$CachedObjectSource.getOrCreate(CachedObject.java:139) ~[Placebo-1.20.1-8.3.7.jar%23567!/:8.3.7] {re:mixin,re:classloading}
        at dev.shadowsoffire.apotheosis.adventure.affix.AffixHelper.getAffixes(AffixHelper.java:79) ~[Apotheosis-1.20.1-7.0.5.jar%23395!/:7.0.5] {re:mixin,re:classloading}
        at net.minecraft.world.item.ItemStack.localvar$zfh000$swapDura(ItemStack.java:2604) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:kubejs-common.mixins.json:ItemStackMixin
```
```
- Entity being ticked --
Details:
        Entity Type: minecraft:zombie (net.minecraft.world.entity.monster.Zombie)
        Entity ID: 65
        Entity Name: Zombie
        Entity's Exact location: 871.05, 67.50, 93.74
        Entity's Block location: World: (871,67,93), Section: (at 7,3,13 in 54,4,5; chunk contains blocks 864,-64,80 to 879,319,95), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,-64,0 to 1023,319,511)
        Entity's Momentum: 0.00, -0.08, 0.00
        Entity's Passengers: []
        Entity's Vehicle: null
```

```
-- Affected level --
Details:
        All players: 1 total; [ServerPlayer['jaysonreis'/37, l='ServerLevel[world]', x=870.05, y=68.00, z=93.69]]
        Chunk stats: 3300
        Level dimension: minecraft:overworld
        Level spawn location: World: (352,63,128), Section: (at 0,15,0 in 22,3,8; chunk contains blocks 352,-64,128 to 367,319,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
        Level time: 1219623 game time, 1565125 day time
        Level name: world
        Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
        Level weather: Rain time: 1540 (now: true), thunder time: 97326 (now: false)
        Known server brands: forge
        Removed feature flags:
        Level was modded: true
        Level storage version: 0x04ABD - Anvil
```

report uuid be986e8c-3905-414b-8cd0-4b83db142498 if someone from ftb reads this

**Comment by DinnerBeef** [comment]
Same as https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4109
