### ISSUE TITLE
FTB Genesis Error

### ISSUE THREAD

**Issue by Pritch15** [FTBTeam/FTB-Modpack-Issues#4190]
### Modpack

Other...

### Modpack version

1.0

### Describe the bug

Crop stick information isn't working. Get error "error:ic2tile_provider" and you get no information about the farmland or plant that is growing

### Steps to reproduce

1. I made a world and played for a few hours, I quit the game and started it back up today and the crop information isn't working.

### Expected behaviour

Shows information about hydration, fertilization, growth etc.

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/150358763/3362432e-c343-41f2-93ce-c8d58dd85da6)

### Additional information

I don't see FTB Genesis in the packs I can make bugs about.

**Comment by atealein** [comment]
I can confirm this issue happens on and off for MacOS user - usually the trigger is at login, it either works or doesn't. There is a chance that re-login fixes it. Here is a latest.log where the issue happens, I logged out right after observing the plant so check the end of the log. 
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13312329/latest.log)

**Comment by Janitor53** [comment]
I have the same error. Details in the debug log:
```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:756) ~[?:?]
	at java.util.ArrayList.add(ArrayList.java:481) ~[?:?]
	at ic2.probeplugin.info.CropComponent.addInfo(CropComponent.java:122) ~[IC2Classic-1.19.2-2.0.7.1.jar%23526!/:1.19.2-2.0.7.1]
	at ic2.probeplugin.info.CropComponent.addInfo(CropComponent.java:38) ~[IC2Classic-1.19.2-2.0.7.1.jar%23526!/:1.19.2-2.0.7.1]
	at ic2.probeplugin.info.ITileInfoComponent.addTileInfo(ITileInfoComponent.java:33) ~[IC2Classic-1.19.2-2.0.7.1.jar%23526!/:1.19.2-2.0.7.1]
	at ic2.probeplugin.base.ProbeTileListener.addProbeInfo(ProbeTileListener.java:59) ~[IC2Classic-1.19.2-2.0.7.1.jar%23526!/:1.19.2-2.0.7.1]
	at mcjty.theoneprobe.network.PacketGetInfo.getProbeInfo(PacketGetInfo.java:137) ~[theoneprobe-1.19-6.2.2.jar%23636!/:1.19-6.2.2]
	at mcjty.theoneprobe.network.PacketGetInfo.lambda$handle$0(PacketGetInfo.java:100) ~[theoneprobe-1.19-6.2.2.jar%23636!/:1.19-6.2.2]
	at net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:68) ~[client-1.19.2-20220805.130853-srg.jar%23651!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.19.2-20220805.130853-srg.jar%23651!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23651!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23651!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) ~[client-1.19.2-20220805.130853-srg.jar%23651!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23651!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23651!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) ~[client-1.19.2-20220805.130853-srg.jar%23651!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[client-1.19.2-20220805.130853-srg.jar%23651!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.19.2-20220805.130853-srg.jar%23651!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:726) ~[client-1.19.2-20220805.130853-srg.jar%23651!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[client-1.19.2-20220805.130853-srg.jar%23651!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23651!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by wendictive** [comment]
have same issue .... relog hasent worked for me yet .... PC win 10

**Comment by Saereth** [comment]
the ic2c dev is aware of this and working on a fix

**Comment by Saereth** [comment]
this should now be fixed
