### ISSUE TITLE
[Bug]: Genesis: Lost souls doesn't ever mark as cleared, just continues to produce errors.

### ISSUE THREAD

**Issue by crzyblue** [FTBTeam/FTB-Modpack-Issues#4276]
### Modpack

FTB Genesis

### Modpack version

1.2.1

### Log Files

[18Nov2023 21:24:54.157] [Server thread/ERROR] [lostsouls/]: ForgeEventHandlers.onKill ERROR
java.lang.NumberFormatException: For input string: "de00cf14-4c64-484a-bf04-e840bb310a85"
	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:?]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:?]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:?]
	at mcjty.lostsouls.ForgeEventHandlers.onKill(ForgeEventHandlers.java:298) ~[lostsouls-1.19-3.0.1.jar%23473!/:1.19-3.0.1]
	at mcjty.lostsouls.__ForgeEventHandlers_onKill_LivingDeathEvent.invoke(.dynamic) ~[lostsouls-1.19-3.0.1.jar%23473!/:1.19-3.0.1]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:354) ~[forge-1.19.2-43.3.5-universal.jar%23572!/:?]
	at net.minecraft.world.entity.LivingEntity.m_6667_(LivingEntity.java:1277) ~[server-1.19.2-20220805.130853-srg.jar%23567!/:?]
	at net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1155) ~[server-1.19.2-20220805.130853-srg.jar%23567!/:?]
	at net.minecraft.world.entity.animal.Animal.m_6469_(Animal.java:75) ~[server-1.19.2-20220805.130853-srg.jar%23567!/:?]
	at com.github.alexthe666.alexsmobs.entity.EntityCockroach.m_6469_(EntityCockroach.java:135) ~[alexsmobs-1.21.1.jar%23339!/:1.21.1]
	at net.minecraft.world.entity.player.Player.m_5706_(Player.java:1154) ~[server-1.19.2-20220805.130853-srg.jar%23567!/:?]
	at net.minecraft.server.level.ServerPlayer.m_5706_(ServerPlayer.java:1368) ~[server-1.19.2-20220805.130853-srg.jar%23567!/:?]
	at com.exidex.swingthroughgrass.LeftClickEventHandler.onLeftClick(LeftClickEventHandler.java:47) ~[swingthroughgrass-1.19.2-1.10.0.jar%23547!/:1.19.2-1.10.0]
	at com.exidex.swingthroughgrass.__LeftClickEventHandler_onLeftClick_LeftClickBlock.invoke(.dynamic) ~[swingthroughgrass-1.19.2-1.10.0.jar%23547!/:1.19.2-1.10.0]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:868) ~[forge-1.19.2-43.3.5-universal.jar%23572!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_214168_(ServerPlayerGameMode.java:127) ~[server-1.19.2-20220805.130853-srg.jar%23567!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7502_(ServerGamePacketListenerImpl.java:1024) ~[server-1.19.2-20220805.130853-srg.jar%23567!/:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:42) ~[server-1.19.2-20220805.130853-srg.jar%23567!/:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:8) ~[server-1.19.2-20220805.130853-srg.jar%23567!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.19.2-20220805.130853-srg.jar%23567!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.19.2-20220805.130853-srg.jar%23567!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23567!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.19.2-20220805.130853-srg.jar%23567!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) ~[server-1.19.2-20220805.130853-srg.jar%23567!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23567!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23567!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) ~[server-1.19.2-20220805.130853-srg.jar%23567!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[server-1.19.2-20220805.130853-srg.jar%23567!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.19.2-20220805.130853-srg.jar%23567!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:726) ~[server-1.19.2-20220805.130853-srg.jar%23567!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[server-1.19.2-20220805.130853-srg.jar%23567!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23567!/:?]
	at java.lang.Thread.run(Unknown Source) [?:?]

### Describe the bug

Every time I kill a mob in a new city, the following error is rendered.

After further investigation, I have noticed that the GUID it is referencing above, is my Team ID from FTB Teams, and not my player GUID.

### Steps to reproduce

Find new lost city
Kill mob
notice error

### Expected behaviour

Haunted building to be cleared

**Comment by Saereth** [comment]
fixed by unlocking chests for now until mcjty can fix on his end
