### ISSUE TITLE
IC2 Cable crash

### ISSUE THREAD

**Issue by Micaxs** [FTBTeam/FTB-Modpack-Issues#4286]
### Modpack

FTB Genesis

### Modpack version

1.2.0

### Log Files

```
java.lang.NullPointerException: Cannot invoke "ic2.core.energy.EnergyNetLocal$Connectivity.get(boolean)" because the return value of "java.util.Map.get(Object)" is null
	at ic2.core.energy.EnergyNetLocal.getConnectivity(EnergyNetLocal.java:861) ~[IC2Classic-1.19.2-2.0.8.jar%23455!/:1.19.2-2.0.8] {re:classloading}
	at ic2.core.energy.EnergyNetLocal.discoverPaths(EnergyNetLocal.java:879) ~[IC2Classic-1.19.2-2.0.8.jar%23455!/:1.19.2-2.0.8] {re:classloading}
	at ic2.core.energy.EnergyNetGrid.updatePaths(EnergyNetGrid.java:242) ~[IC2Classic-1.19.2-2.0.8.jar%23455!/:1.19.2-2.0.8] {re:classloading}
	at ic2.core.energy.EnergyNetGrid.processChanges(EnergyNetGrid.java:206) ~[IC2Classic-1.19.2-2.0.8.jar%23455!/:1.19.2-2.0.8] {re:classloading}
	at ic2.core.energy.EnergyNetLocal.onTickStop(EnergyNetLocal.java:137) ~[IC2Classic-1.19.2-2.0.8.jar%23455!/:1.19.2-2.0.8] {re:classloading}
	at ic2.core.energy.EnergyNetGlobal.onWorldTickStop(EnergyNetGlobal.java:161) ~[IC2Classic-1.19.2-2.0.8.jar%23455!/:1.19.2-2.0.8] {re:classloading}
	at ic2.core.platform.events.IC2EventHandler.onWorldTickEvent(IC2EventHandler.java:449) ~[IC2Classic-1.19.2-2.0.8.jar%23455!/:1.19.2-2.0.8] {re:classloading,pl:runtimedistcleaner:A}
	at ic2.core.platform.events.__IC2EventHandler_onWorldTickEvent_LevelTickEvent.invoke(.dynamic) ~[IC2Classic-1.19.2-2.0.8.jar%23455!/:1.19.2-2.0.8] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactory.java:829) ~[forge-1.19.2-43.3.5-universal.jar%23586!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872) ~[server-1.19.2-20220805.130853-srg.jar%23581!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23581!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23581!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23581!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23581!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
```

### Describe the bug

Placed an IC2 copper cable on a batbox that had EU inside of it caused the server to crash.

### Steps to reproduce

1. Place batbox.
2. Charge batbox to max with EU
3. Connect copper cable to conent the batbox to supply additional power to the cable network to machine currently using eu
4. Observe crash.

### Expected behaviour

Not to crash when placing down a cable.

**Comment by Kibakus** [comment]
Hi, today I caught the same behavior, the server crashed when friends were playing on it.
traceback attached
```
[20Nov2023 21:14:58.088] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "ic2.core.energy.EnergyNetLocal$Connectivity.get(boolean)" because the return value of "java.util.Map.get(Object)" is null
	Index: 6
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda/0x000002d1656ac000@21fa734a
		2: net.minecraftforge.eventbus.EventBus$$Lambda/0x000002d1656ac000@60ed71ff
		3: ASM: class com.mrcrayfish.furniture.common.mail.PostOffice onTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		4: ASM: class net.mcreator.midnightmadness.procedures.SoulHarvestEventStartProcedure onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		5: ASM: class net.mcreator.midnightmadness.procedures.SoulHarvestEndProcedure onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		6: ASM: ic2.core.platform.events.IC2EventHandler@85c24d5 onWorldTickEvent(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		7: ASM: class com.ldtteam.structurize.event.EventSubscriber onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		8: net.minecraftforge.eventbus.EventBus$$Lambda/0x000002d1656ac000@179e195d
		9: ASM: class com.ldtteam.structurize.storage.ServerStructurePackLoader onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		10: ASM: class com.ldtteam.structurize.storage.ServerFutureProcessor onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		11: ASM: class cofh.thermal.cultivation.event.TCulCommonEvents handleTickEndEvent(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		12: ASM: class com.minecolonies.coremod.event.FMLEventHandler onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		13: ASM: vazkii.quark.content.tweaks.module.UtilityRecipesModule@382486e5 worldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		14: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@1e2e7b65 worldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		15: ASM: com.illusivesoulworks.polymorph.common.CommonEventsListener@171e1c4e levelTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		16: ASM: shadows.apotheosis.adventure.boss.BossEvents@7913546c tick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
java.lang.NullPointerException: Cannot invoke "ic2.core.energy.EnergyNetLocal$Connectivity.get(boolean)" because the return value of "java.util.Map.get(Object)" is null
	at TRANSFORMER/ic2@1.19.2-2.0.7.1/ic2.core.energy.EnergyNetLocal.getConnectivity(EnergyNetLocal.java:859)
	at TRANSFORMER/ic2@1.19.2-2.0.7.1/ic2.core.energy.EnergyNetLocal.discoverPaths(EnergyNetLocal.java:877)
	at TRANSFORMER/ic2@1.19.2-2.0.7.1/ic2.core.energy.EnergyNetGrid.updatePaths(EnergyNetGrid.java:242)
	at TRANSFORMER/ic2@1.19.2-2.0.7.1/ic2.core.energy.EnergyNetGrid.processChanges(EnergyNetGrid.java:206)
	at TRANSFORMER/ic2@1.19.2-2.0.7.1/ic2.core.energy.EnergyNetLocal.onTickStop(EnergyNetLocal.java:137)
	at TRANSFORMER/ic2@1.19.2-2.0.7.1/ic2.core.energy.EnergyNetGlobal.onWorldTickStop(EnergyNetGlobal.java:161)
	at TRANSFORMER/ic2@1.19.2-2.0.7.1/ic2.core.platform.events.IC2EventHandler.onWorldTickEvent(IC2EventHandler.java:449)
	at TRANSFORMER/ic2@1.19.2-2.0.7.1/ic2.core.platform.events.__IC2EventHandler_onWorldTickEvent_LevelTickEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.3.2/net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactory.java:829)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
	at java.base/java.lang.Thread.run(Thread.java:1583)

[20Nov2023 21:14:58.090] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot invoke "ic2.core.energy.EnergyNetLocal$Connectivity.get(boolean)" because the return value of "java.util.Map.get(Object)" is null
	at ic2.core.energy.EnergyNetLocal.getConnectivity(EnergyNetLocal.java:859) ~[IC2Classic-1.19.2-2.0.7.1.jar%23268!/:1.19.2-2.0.7.1]
	at ic2.core.energy.EnergyNetLocal.discoverPaths(EnergyNetLocal.java:877) ~[IC2Classic-1.19.2-2.0.7.1.jar%23268!/:1.19.2-2.0.7.1]
	at ic2.core.energy.EnergyNetGrid.updatePaths(EnergyNetGrid.java:242) ~[IC2Classic-1.19.2-2.0.7.1.jar%23268!/:1.19.2-2.0.7.1]
	at ic2.core.energy.EnergyNetGrid.processChanges(EnergyNetGrid.java:206) ~[IC2Classic-1.19.2-2.0.7.1.jar%23268!/:1.19.2-2.0.7.1]
	at ic2.core.energy.EnergyNetLocal.onTickStop(EnergyNetLocal.java:137) ~[IC2Classic-1.19.2-2.0.7.1.jar%23268!/:1.19.2-2.0.7.1]
	at ic2.core.energy.EnergyNetGlobal.onWorldTickStop(EnergyNetGlobal.java:161) ~[IC2Classic-1.19.2-2.0.7.1.jar%23268!/:1.19.2-2.0.7.1]
	at ic2.core.platform.events.IC2EventHandler.onWorldTickEvent(IC2EventHandler.java:449) ~[IC2Classic-1.19.2-2.0.7.1.jar%23268!/:1.19.2-2.0.7.1]
	at ic2.core.platform.events.__IC2EventHandler_onWorldTickEvent_LevelTickEvent.invoke(.dynamic) ~[IC2Classic-1.19.2-2.0.7.1.jar%23268!/:1.19.2-2.0.7.1]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactory.java:829) ~[forge-1.19.2-43.3.2-universal.jar%23346!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872) ~[server-1.19.2-20220805.130853-srg.jar%23341!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23341!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23341!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23341!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23341!/:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
[20Nov2023 21:14:58.420] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 0f84cdee-c15f-4232-91e6-5116036d2b20
```
