### ISSUE TITLE
Cable Tiers' Elite Exporter crash upon placement

### ISSUE THREAD

**Issue by volrathstormborn** [FTBTeam/FTB-Modpack-Issues#4327]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.7.0

### Log Files

[2023-11-23-1.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13452381/2023-11-23-1.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13452382/debug.log)
[crash-2023-11-23_02.32.08-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13452425/crash-2023-11-23_02.32.08-server.txt)
[crash-2023-11-23_02.33.11-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13452426/crash-2023-11-23_02.33.11-server.txt)

Also from the Client Logs after I restarted the server and tried to connect.  Issue with "Invalid Player Data" now allowing the connection:
  [23.11 02:47:57] [Server] [User Authenticator #2/INFO] [minecraft/ServerLoginPacketListenerImpl]: UUID of player VolrathStormborn is 18b742fd-e1e8-4453-abc2-ead98b9c87b3
[23.11 02:48:06] [Connect] VolrathStormborn, IP 47.205.181.87
[23.11 02:48:06] [Multicraft] VolrathStormborn ran command Message of the Day
[23.11 02:48:06] [Server] [Server thread/INFO] [minecraft/MinecraftServer]: VolrathStormborn joined the game
[23.11 02:48:06] [Server] [Server thread/ERROR] [minecraft/ServerLoginPacketListenerImpl]: Couldn't place player in world
[23.11 02:48:06] [Server] java.lang.ClassCastExceptionclass com.refinedmods.refinedstorage.apiimpl.network.node.ExporterNetworkNode cannot be cast to class com.ultramega.cabletiers.node.TieredExporterNetworkNode (com.refinedmods.refinedstorage.apiimpl.network.node.ExporterNetworkNode is in module refinedstorage@1.12.4 of loader 'TRANSFORMER' @3acc3ee; com.ultramega.cabletiers.node.TieredExporterNetworkNode is in module cabletiers@1.20.1-1.2 of loader 'TRANSFORMER' @3acc3ee)
[23.11 02:48:06] [Server] 	at com.ultramega.cabletiers.blockentity.TieredExporterBlockEntity.writeUpdate(TieredExporterBlockEntity.java:52) ~[cabletiers-1.20.1-1.2.jar%23418!/:1.20.1-1.{re:classloading}
[23.11 02:48:06] [Server] 	at com.refinedmods.refinedstorage.blockentity.BaseBlockEntity.m_5995_(BaseBlockEntity.java:35) ~[refinedstorage-1.12.4.jar%23584!/:?] {re:classloading}
[23.11 02:48:06] [Server] 	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData$BlockEntityInfo.m_195691_(ClientboundLevelChunkPacketData.java:152) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries.mixins.json:ChunkHolderMixin,pl:mixin:A}
[23.11 02:48:06] [Server] 	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.<init>(ClientboundLevelChunkPacketData.java:44) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
[23.11 02:48:06] [Server] 	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.<init>(ClientboundLevelChunkWithLightPacket.java:24) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:classloading}
[23.11 02:48:06] [Server] 	at net.minecraft.server.level.ChunkMap.m_183760_(ChunkMap.java:1261) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[23.11 02:48:06] [Server] 	at net.minecraft.server.level.ChunkMap.m_183754_(ChunkMap.java:892) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[23.11 02:48:06] [Server] 	at net.minecraft.server.level.ChunkMap.m_140192_(ChunkMap.java:1035) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[23.11 02:48:06] [Server] 	at net.minecraft.server.level.ChunkMap.m_140199_(ChunkMap.java:1158) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[23.11 02:48:06] [Server] 	at net.minecraft.server.level.ServerChunkCache.m_8463_(ServerChunkCache.java:465) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ChunkLoadDebug,pl:mixin:APP:smoothchunk.mixins.json:ServerChunkCacheMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_ticking.ServerChunkCacheMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.ServerChunkCacheMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerChunkCacheMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.chunk_deadlock.ServerChunkCache_CurrentLoadingMixin,pl:mixin:A}
[23.11 02:48:06] [Server] 	at net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1505) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.EntityCallbacksMixin,pl:mixin:A}
[23.11 02:48:06] [Server] 	at net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1488) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.EntityCallbacksMixin,pl:mixin:A}
[23.11 02:48:06] [Server] 	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157575_(PersistentEntitySectionManager.java:136) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.PersistentEntitySectionManagerAccessor,pl:mixin:A}
[23.11 02:48:06] [Server] 	at net.minecraft.world.level.entity.PersistentEntitySectionManager.addEntityWithoutEvent(PersistentEntitySectionManager.java:97) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.PersistentEntitySectionManagerAccessor,pl:mixin:A}
[23.11 02:48:06] [Server] 	at net.minecraft.world.level.entity.PersistentEntitySectionManager.addNewEntityWithoutEvent(PersistentEntitySectionManager.java:75) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.PersistentEntitySectionManagerAccessor,pl:mixin:A}
[23.11 02:48:06] [Server] 	at net.minecraft.server.level.ServerLevel.m_8853_(ServerLevel.java:850) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:libx:level_load,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:hyperbox.mixins.json:ServerLevelMixin,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:aether.mixins.json:common.accessor.ServerLevelAccessor,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:peripheralworks.mixins.json:ServerLevelMixin,pl:mixin:APP:modulargolems.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
[23.11 02:48:06] [Server] 	at net.minecraft.server.level.ServerLevel.m_8834_(ServerLevel.java:834) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:libx:level_load,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:hyperbox.mixins.json:ServerLevelMixin,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:aether.mixins.json:common.accessor.ServerLevelAccessor,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:peripheralworks.mixins.json:ServerLevelMixin,pl:mixin:APP:modulargolems.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
[23.11 02:48:06] [Server] 	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:215) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:mixin,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:PlayerListMixin,pl:mixin:APP:ftbessentials-common.mixins.json:PlayerListAccess,pl:mixin:APP:ars_nouveau.mixins.json:camera.PlayerListMixin,pl:mixin:A}
[23.11 02:48:06] [Server] 	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:connectivity.mixins.json:ServerLoginNetHandlerMixin,pl:mixin:A}
[23.11 02:48:06] [Server] 	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:126) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:connectivity.mixins.json:ServerLoginNetHandlerMixin,pl:mixin:A}
[23.11 02:48:06] [Server] 	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:70) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:connectivity.mixins.json:ServerLoginNetHandlerMixin,pl:mixin:A}
[23.11 02:48:06] [Server] 	at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:mixin,re:classloading,pl:mixin:A}
[23.11 02:48:06] [Server] 	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:classloading,pl:accesstransformer:B}
[23.11 02:48:06] [Server] 	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
[23.11 02:48:06] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
[23.11 02:48:06] [Server] 	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
[23.11 02:48:06] [Server] 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
[23.11 02:48:06] [Server] 	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23657!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
[23.11 02:48:06] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
[23.11 02:48:07] [Disconnect] VolrathStormborn has disconnected, reasonInvalid player data
[23.11 02:48:07] [Server] [Server thread/INFO] [minecraft/MinecraftServer]: VolrathStormborn left the game
[23.11 02:48:07] [Server] [Server thread/WARN] [minecraft/Connection]: handleDisconnection() called twice

### Describe the bug

Crafted the Elite Exporter for use with a Cyclic Block Placer.  Upon sneak clicking the exporter onto the bottom of the placer it was an immediate crash.  The server automatically restarted itself so I restarted the client and attempted to connect, but was disconnected each time with the invalid player data from the pasted info above.

Server was restored from backup and I will not be using any items from Cable Tiers as I've had issues with them in ATM 8 as well.

### Steps to reproduce

Craft Elite Exporter
Place the item in the world and observe the crash
Server/Client restarts will no longer allow the player to connect due to invalid data

### Expected behaviour

Item should be placed in world, accessible, and functional

**Comment by DinnerBeef** [comment]
Unable to reproduce this, issue. Please reopen if you are still having issues with this.
