### ISSUE TITLE
Fresh Server Failing to Start

### ISSUE THREAD

**Issue by AzureDoom** [FTBTeam/FTB-Modpack-Issues#4374]
### Modpack

FTB Genesis

### Modpack version

1.3.2

### Log Files

https://gist.github.com/AzureDoom/43fbfcf07747952119682db0288a3e7c

### Describe the bug

Server is crashing due to Server Config Updater.

### Steps to reproduce

1. Install Server Files using installer
2. Try and start server.

### Expected behaviour

Server starts

**Comment by Myoki42** [comment]
Same here

**Comment by jlp1528** [comment]
Please include crash logs even if OP already has. More logs help corroborate reports and track down the problem, or multiple problems as is sometimes the case.

**Comment by Myoki42** [comment]
Here it is:

[crash-2023-12-01_11.45.28-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13524957/crash-2023-12-01_11.45.28-server.txt)

**Comment by Myoki42** [comment]
The last lines in your app log screen (and everything stops, only kill instance works):

[12:01:30] [Server thread/INFO] [ne.mi.fm.co.ConfigFileTypeHandler/CONFIG]: Loading default config file from path D:\Games\FTBA\instances\61ae94f5-523d-4108-9637-02886195f5ef\defaultconfigs\mcjtylib-server.toml
[12:01:30] [Server thread/INFO] [ne.mi.fm.co.ConfigFileTypeHandler/CONFIG]: Loading default config file from path D:\Games\FTBA\instances\61ae94f5-523d-4108-9637-02886195f5ef\defaultconfigs\rftoolsbase-server.toml
[12:01:30] [Server thread/INFO] [ne.mi.fm.co.ConfigFileTypeHandler/CONFIG]: Loading default config file from path D:\Games\FTBA\instances\61ae94f5-523d-4108-9637-02886195f5ef\defaultconfigs\productivebees-server.toml
[12:01:30] [Server thread/INFO] [ne.mi.fm.co.ConfigFileTypeHandler/CONFIG]: Loading default config file from path D:\Games\FTBA\instances\61ae94f5-523d-4108-9637-02886195f5ef\defaultconfigs\xnet-server.toml
[12:01:30] [Server thread/INFO] [ne.mi.fm.co.ConfigFileTypeHandler/CONFIG]: Loading default config file from path D:\Games\FTBA\instances\61ae94f5-523d-4108-9637-02886195f5ef\defaultconfigs\rftoolsstorage-server.toml
[12:01:30] [Server thread/INFO] [ne.mi.fm.co.ConfigFileTypeHandler/CONFIG]: Loading default config file from path D:\Games\FTBA\instances\61ae94f5-523d-4108-9637-02886195f5ef\defaultconfigs\rftoolsdim-server.toml
[12:01:30] [Server thread/INFO] [ne.mi.fm.co.ConfigFileTypeHandler/CONFIG]: Loading default config file from path D:\Games\FTBA\instances\61ae94f5-523d-4108-9637-02886195f5ef\defaultconfigs\rftoolsbuilder-server.toml
[12:01:30] [Server thread/INFO] [ne.mi.fm.co.ConfigFileTypeHandler/CONFIG]: Loading default config file from path D:\Games\FTBA\instances\61ae94f5-523d-4108-9637-02886195f5ef\defaultconfigs\matc-server.toml
[12:01:30] [Server thread/INFO] [ne.mi.fm.co.ConfigFileTypeHandler/CONFIG]: Loading default config file from path D:\Games\FTBA\instances\61ae94f5-523d-4108-9637-02886195f5ef\defaultconfigs\sebastrnlib-server.toml
[12:01:30] [Server thread/INFO] [ne.mi.fm.co.ConfigFileTypeHandler/CONFIG]: Loading default config file from path D:\Games\FTBA\instances\61ae94f5-523d-4108-9637-02886195f5ef\defaultconfigs\immersiveengineering-server.toml
[12:01:30] [Server thread/INFO] [ne.mi.fm.co.ConfigFileTypeHandler/CONFIG]: Loading default config file from path D:\Games\FTBA\instances\61ae94f5-523d-4108-9637-02886195f5ef\defaultconfigs\rftoolsutility-server.toml
[12:01:30] [Server thread/INFO] [Puzzles Lib/]: Loading server config for barteringstation
[12:01:30] [Server thread/INFO] [ne.mi.fm.co.ConfigFileTypeHandler/CONFIG]: Loading default config file from path D:\Games\FTBA\instances\61ae94f5-523d-4108-9637-02886195f5ef\defaultconfigs\engineersdecor-server.toml
[12:01:30] [Server thread/INFO] [wi.en.ModEngineersDecor/]: Config lab furnace speed:130.0%, efficiency:100.0%, boost: 24rf/t.
[12:01:30] [Server thread/INFO] [wi.en.ModEngineersDecor/]: Config lab furnace accepted heaters: immersiveengineering:furnace_heater.
[12:01:30] [Server thread/INFO] [spark/]: Starting background profiler...
[12:01:30] [Server thread/INFO] [spark/]: The async-profiler engine is not supported for your os/arch (windows10/amd64), so the built-in Java engine will be used instead.
[12:01:31] [Server thread/WARN] [co.da.se.ServerConfigUpdater/]: No ServerConfig for MODIDelectrodynamics found!
[12:01:31] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: begin 0, end -1, length 0
Index: 10
Listeners:
0: HIGH
1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
2: NORMAL
3: net.minecraftforge.eventbus.EventBus$$Lambda$1543/0x00000008017de910@e72f258
4: net.minecraftforge.eventbus.EventBus$$Lambda$1543/0x00000008017de910@3eb20bfd
5: ASM: me.lucko.spark.forge.ForgeSparkMod@200ccbc serverInit(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
6: net.minecraftforge.eventbus.EventBus$$Lambda$1543/0x00000008017de910@3a79d365
7: net.minecraftforge.eventbus.EventBus$$Lambda$1543/0x00000008017de910@15abf528
8: net.minecraftforge.eventbus.EventBus$$Lambda$1543/0x00000008017de910@cd235f7
9: net.minecraftforge.eventbus.EventBus$$Lambda$1543/0x00000008017de910@22113a73
10: ASM: com.darkere.serverconfigupdater.ServerConfigUpdater@354c0b3a onServerStarting(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
11: ASM: class com.mactso.harderfarther.Main$ForgeEvents onServerAbout(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
at java.base/java.lang.String.substring(Unknown Source)
at TRANSFORMER/serverconfigupdater@3.2/com.darkere.serverconfigupdater.ServerConfigUpdater.LogConfigsToReset(ServerConfigUpdater.java:105)
at TRANSFORMER/serverconfigupdater@3.2/com.darkere.serverconfigupdater.ServerConfigUpdater.onServerStarting(ServerConfigUpdater.java:70)
at TRANSFORMER/serverconfigupdater@3.2/com.darkere.serverconfigupdater.__ServerConfigUpdater_onServerStarting_ServerAboutToStartEvent.invoke(.dynamic)
at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
at TRANSFORMER/forge@43.3.5/net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:92)
at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:61)
at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:625)
at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
at java.base/java.lang.Thread.run(Unknown Source)
[12:01:31] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 0
at java.lang.String.checkBoundsBeginEnd(Unknown Source) ~[?:?] {re:mixin}
at java.lang.String.substring(Unknown Source) ~[?:?] {re:mixin}
at com.darkere.serverconfigupdater.ServerConfigUpdater.LogConfigsToReset(ServerConfigUpdater.java:105) ~[serverconfigupdater-3.2.jar%23612!/:3.2] {re:classloading}
at com.darkere.serverconfigupdater.ServerConfigUpdater.onServerStarting(ServerConfigUpdater.java:70) ~[serverconfigupdater-3.2.jar%23612!/:3.2] {re:classloading}
at com.darkere.serverconfigupdater.__ServerConfigUpdater_onServerStarting_ServerAboutToStartEvent.invoke(.dynamic) ~[serverconfigupdater-3.2.jar%23612!/:3.2] {re:classloading,pl:eventbus:B}
at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2385!/:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?] {}
at net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:92) ~[forge-1.19.2-43.3.5-universal.jar%23654!/:?] {re:classloading}
at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:61) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:625) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
at java.lang.Thread.run(Unknown Source) [?:?] {re:mixin}
[12:01:31] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID b59d57dd-209e-4df2-b91c-ce3b3e1d0448
[12:01:31] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 436779b8-9863-4ee4-9293-7e46f3f1c952
[12:01:31] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: D:\Games\FTBA\instances\61ae94f5-523d-4108-9637-02886195f5ef\crash-reports\crash-2023-12-01_12.01.31-server.txt
[12:01:31] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[12:01:31] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[12:01:31] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[12:01:31] [Server thread/ERROR] [minecraft/MinecraftServer]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.ServerLevel.m_6857_()" because "serverlevel2" is null
at net.minecraft.server.MinecraftServer.m_129885_(MinecraftServer.java:502) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
at net.minecraft.server.MinecraftServer.m_7041_(MinecraftServer.java:575) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
at net.minecraft.client.server.IntegratedServer.m_7041_(IntegratedServer.java:173) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:682) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23649!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
at java.lang.Thread.run(Unknown Source) [?:?] {re:mixin}
[12:01:31] [Server thread/INFO] [Framework/]: Unloading server configs...

**Comment by jlp1528** [comment]
> Here it is:
> 
> [crash-2023-12-01_11.45.28-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13524957/crash-2023-12-01_11.45.28-server.txt)
> 
> The crash more like a freeze at me, i have to kill the instance.

The command line does not close on its own, which could look like a freeze, but a crash log is still prepared and saved in the "crash-reports" folder.

I can confirm the same crash.
[crash-2023-12-01_05.08.23-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13525406/crash-2023-12-01_05.08.23-server.txt)

**Comment by Myoki42** [comment]
Ehm, i really dont know why i did not try that LOL :)
Sry, and thank you :)

**Comment by jlp1528** [comment]
> Ehm, i really dont know why i did not try that LOL :) Sry, and thank you :)

So that actually worked for you too? Cool.

It should still be fixed!
