### ISSUE TITLE
FTB Inferno: Crash if you use Inmersive Enguineer´s Blueprint Brench

### ISSUE THREAD

**Issue by Devilcer** [FTBTeam/FTB-Modpack-Issues#4448]
### Modpack

FTB Inferno

### Modpack version

1.10.0

### Log Files

[10Dec2023 13:22:08.890] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: Rendering Block Entity
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112278_(BlockEntityRenderDispatcher.java:105) ~[client-1.18.2-20220404.173914-srg.jar%23321!/:?]
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112267_(BlockEntityRenderDispatcher.java:73) ~[client-1.18.2-20220404.173914-srg.jar%23321!/:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:297) ~[embeddium-0.2.12+mc1.18.2.jar%23134!/:?]
	at net.minecraft.client.renderer.LevelRenderer.handler$zgb000$onRenderTileEntities(LevelRenderer.java:5715) ~[client-1.18.2-20220404.173914-srg.jar%23321!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1260) ~[client-1.18.2-20220404.173914-srg.jar%23321!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1061) ~[client-1.18.2-20220404.173914-srg.jar%23321!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:835) ~[client-1.18.2-20220404.173914-srg.jar%23321!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046) ~[client-1.18.2-20220404.173914-srg.jar%23321!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23321!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23321!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.7.jar%2318!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
Caused by: java.lang.IllegalStateException: Not filled all elements of the vertex
	at com.mojang.blaze3d.vertex.BufferBuilder.m_5752_(BufferBuilder.java:249) ~[client-1.18.2-20220404.173914-srg.jar%23321!/:?]
	at blusunrize.immersiveengineering.client.utils.TransformingVertexBuilder.m_5752_(TransformingVertexBuilder.java:135) ~[ImmersiveEngineering-1.18.2-8.4.0-161.jar%23189!/:?]
	at blusunrize.immersiveengineering.client.render.tile.BlueprintRenderer.lambda$makeQuadLinePainter$0(BlueprintRenderer.java:210) ~[ImmersiveEngineering-1.18.2-8.4.0-161.jar%23189!/:?]
	at blusunrize.immersiveengineering.client.render.tile.BlueprintRenderer$BlueprintLines.draw(BlueprintRenderer.java:256) ~[ImmersiveEngineering-1.18.2-8.4.0-161.jar%23189!/:?]
	at blusunrize.immersiveengineering.client.render.tile.ModWorkbenchRenderer.lambda$buildVBO$0(ModWorkbenchRenderer.java:159) ~[ImmersiveEngineering-1.18.2-8.4.0-161.jar%23189!/:?]
	at blusunrize.immersiveengineering.client.utils.VertexBufferHolder.renderToBuilder(VertexBufferHolder.java:130) ~[ImmersiveEngineering-1.18.2-8.4.0-161.jar%23189!/:?]
	at blusunrize.immersiveengineering.client.utils.VertexBufferHolder.render(VertexBufferHolder.java:116) ~[ImmersiveEngineering-1.18.2-8.4.0-161.jar%23189!/:?]
	at blusunrize.immersiveengineering.api.client.IVertexBufferHolder.render(IVertexBufferHolder.java:58) ~[ImmersiveEngineering-1.18.2-8.4.0-161.jar%23189!/:?]
	at blusunrize.immersiveengineering.client.render.tile.ModWorkbenchRenderer.render(ModWorkbenchRenderer.java:61) ~[ImmersiveEngineering-1.18.2-8.4.0-161.jar%23189!/:?]
	at blusunrize.immersiveengineering.client.render.tile.ModWorkbenchRenderer.m_6922_(ModWorkbenchRenderer.java:31) ~[ImmersiveEngineering-1.18.2-8.4.0-161.jar%23189!/:?]
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112284_(BlockEntityRenderDispatcher.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23321!/:?]
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112297_(BlockEntityRenderDispatcher.java:73) ~[client-1.18.2-20220404.173914-srg.jar%23321!/:?]
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112278_(BlockEntityRenderDispatcher.java:98) ~[client-1.18.2-20220404.173914-srg.jar%23321!/:?]
	... 22 more
[10Dec2023 13:22:08.895] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 8d2fe0a7-2226-46b6-b6c1-234a3035c313
[10Dec2023 13:22:08.898] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID ff869b87-57a1-4916-b88a-acc0312157c4
[10Dec2023 13:22:09.402] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID c210f920-e22b-4362-b417-82ef0b1a16c5

### Describe the bug

After put the blueprint, the game inmediatly crash. Is imposible load the save again after it.

### Steps to reproduce

- Place a Enginer´s Workbrench
- Take the Enguiners Blueprint: Crafting Components
- Place the Blueprint in the Brench
- Crash

### Expected behaviour

Normally, by placing the drawing, it would allow to create the components

### Additional information

Looking at the error log, there seems to be an exception with ImmersiveEnguineering, caused by trying to render the elements for crafting in the brench. May is the AE2 processors patch?

**Comment by joeyjumper94** [comment]
any fix yet?

**Comment by thegwangster** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4514
Downgrading the immersive engineering mod works apparently

**Comment by Drackmord** [comment]
Go to config, open immersiveenginering-client, set enableVBO = true

**Comment by Devilcer** [comment]
Apparently, it solved the problem. Thanks
