### ISSUE TITLE
Instance crash

### ISSUE THREAD

**Issue by Thomaste9** [FTBTeam/FTB-Modpack-Issues#4564]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.19.2

### Log Files

[debug-5.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13932661/debug-5.log.gz)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13932662/latest.log)

### Describe the bug

Cant play the game. I dont know whats happening. Tell me what to delete or add to fix this.

### Steps to reproduce

Open FTB app
press play
instance runs then crashes

### Expected behaviour

Open FTB app, play game

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/156606242/1bef333a-6909-4e17-b743-0863d2c36d76)

### Additional information

[AUTH][INFO] Starting authentication flow finished successfully
[AUTH][INFO] Contacting Xbox Live started
[AUTH][INFO] Contacting Xbox Live finished successfully
[AUTH][INFO] Authenticating with Xbox Services started
[AUTH][INFO] Authenticating with Xbox Services finished successfully
[AUTH][INFO] Logging in with Xbox Live started
[AUTH][INFO] Logging in with Xbox Live finished successfully
[AUTH][INFO] Getting Minecraft Profile started
[AUTH][INFO] Verifying ownership started
[AUTH][INFO] Getting Minecraft Profile finished successfully
[AUTH][INFO] Verifying ownership finished successfully
[FTB APP][INFO] Pre-Start Tasks
[FTB APP][INFO] Validate Java Runtime
[FTB APP][INFO] Validate assets
[FTB APP][INFO] Validate libraries
[FTB APP][INFO] Validate client
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/pattern/MessagePatternConverter
[Log4jPatcher] [WARN] Unable to find noLookups:Z field in org/apache/logging/log4j/core/pattern/MessagePatternConverter
[Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/lookup/JndiLookup
2024-01-14 13:17:56,598 main WARN Advanced terminal features are not available in this environment
[13:17:56] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, MLG_Sniper_Tom, --version, 1.19.2-forge-43.2.14, --gameDir, C:\Users\Thomas\AppData\Local\.ftba\instances\5957f699-44a0-4656-a39e-0640b72ac38d, --assetsDir, C:\Users\Thomas\AppData\Local\.ftba\bin\assets, --assetIndex, 1.19, --uuid, e844d825-15db-4b68-a484-cacfe9870808, --accessToken, ????????, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, msa, --versionType, release, --width, 1720, --height, 840, --launchTarget, forgeclient, --fml.forgeVersion, 43.2.14, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[13:17:56] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.2 by Eclipse Adoptium; OS Windows 10 arch amd64 version 10.0
[13:17:58] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Thomas/AppData/Local/.ftba/bin/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2397!/ Service=ModLauncher Env=CLIENT
Exception in thread "main" java.lang.RuntimeException: Failed to load FML config from C:\Users\Thomas\AppData\Local\.ftba\instances\5957f699-44a0-4656-a39e-0640b72ac38d\config\fml.toml
at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.14/net.minecraftforge.fml.loading.FMLConfig.loadFrom(FMLConfig.java:50)
at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.14/net.minecraftforge.fml.loading.FMLConfig.load(FMLConfig.java:63)
at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.14/net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:65)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:92)
at java.base/java.util.HashMap$Values.forEach(Unknown Source)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:92)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:51)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:87)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: com.electronwill.nightconfig.core.io.ParsingException: Not enough data available
at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22)
at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ReaderInput.directReadChar(ReaderInput.java:36)
at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.AbstractInput.readChar(AbstractInput.java:49)
at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.AbstractInput.readCharsUntil(AbstractInput.java:123)
at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:166)
at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:145)
at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55)
at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44)
at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37)
at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113)
at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219)
at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202)
at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73)
at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.AutoreloadFileConfig.load(AutoreloadFileConfig.java:41)
at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85)
at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.14/net.minecraftforge.fml.loading.FMLConfig.loadFrom(FMLConfig.java:46)

**Comment by Thomaste9** [comment]
It is not fixed
