### ISSUE TITLE
stoneblock 2 instance crash

### ISSUE THREAD

**Issue by 101thunder101** [FTBTeam/FTB-Modpack-Issues#4568]
### Modpack

FTB Genesis

### Modpack version

1.22.0

### Log Files

[02:10:48] [MineTogether invite check thread/WARN] [minetogether]: An error occurred while fetching https://api.creeper.host/serverlist/friendinvites. Will hide repeated errors.
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1570) ~[?:1.8.0_312]
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1400) ~[?:1.8.0_312]
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1300) ~[?:1.8.0_312]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:435) ~[?:1.8.0_312]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[?:1.8.0_312]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:846) ~[?:1.8.0_312]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678) ~[?:1.8.0_312]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1590) ~[?:1.8.0_312]
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92) ~[?:1.8.0_312]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1487) ~[?:1.8.0_312]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1485) ~[?:1.8.0_312]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_312]
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784) ~[?:1.8.0_312]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1484) ~[?:1.8.0_312]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268) ~[?:1.8.0_312]
	at net.creeperhost.minetogether.common.WebUtils.methodWebResponse(WebUtils.java:135) ~[WebUtils.class:?]
	at net.creeperhost.minetogether.common.WebUtils.putWebResponse(WebUtils.java:173) ~[WebUtils.class:?]
	at net.creeperhost.minetogether.paul.Callbacks.getInvite(Callbacks.java:296) ~[Callbacks.class:?]
	at net.creeperhost.minetogether.EventHandler.lambda$onClientTick$4(EventHandler.java:843) ~[EventHandler.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:167) ~[?:1.8.0_312]
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:109) ~[?:1.8.0_312]
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1392) ~[?:1.8.0_312]
	... 18 more
[02:10:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:131]: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
[02:10:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:131]: 	at sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1570)
[02:10:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:131]: 	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1400)
[02:10:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:131]: 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1300)
[02:10:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:131]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:435)
[02:10:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:131]: 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
[02:10:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:131]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
[02:10:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:131]: 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1337)
[02:10:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:131]: 	at sun.net.www.protocol.http.HttpURLConnection.access$100(HttpURLConnection.java:92)
[02:10:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:131]: 	at sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1304)
[02:10:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:131]: 	at sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1302)
[02:10:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:131]: 	at java.security.AccessController.doPrivileged(Native Method)
[02:10:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:131]: 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784)
[02:10:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:131]: 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1301)
[02:10:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:131]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:264)
[02:10:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:131]: 	at net.creeperhost.minetogether.common.WebUtils.methodWebResponse(WebUtils.java:124)
[02:10:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:131]: 	at net.creeperhost.minetogether.common.WebUtils.putWebResponse(WebUtils.java:173)
[02:10:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:131]: 	at net.creeperhost.minetogether.paul.Callbacks.getInvite(Callbacks.java:296)
[02:10:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:131]: 	at net.creeperhost.minetogether.EventHandler.lambda$onClientTick$4(EventHandler.java:843)
[02:10:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:131]: 	at java.lang.Thread.run(Thread.java:748)
[02:10:59] [MineTogether invite check thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: Caused by: java.io.EOFException: SSL peer shut down incorrectly
[02:10:59] [MineTogether invite check thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:167)
[02:10:59] [MineTogether invite check thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:109)
[02:10:59] [MineTogether invite check thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1392)
[02:10:59] [MineTogether invite check thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	... 17 more
[03:30:33] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.EventHandler:lambda$onClientTick$4:863]: java.lang.ClassCastException: com.google.gson.JsonPrimitive cannot be cast to com.google.gson.JsonArray
[03:30:33] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.EventHandler:lambda$onClientTick$4:863]: 	at com.google.gson.JsonObject.getAsJsonArray(JsonObject.java:181)
[03:30:33] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.EventHandler:lambda$onClientTick$4:863]: 	at net.creeperhost.minetogether.paul.Callbacks.getInvite(Callbacks.java:304)
[03:30:33] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.EventHandler:lambda$onClientTick$4:863]: 	at net.creeperhost.minetogether.EventHandler.lambda$onClientTick$4(EventHandler.java:843)
[03:30:33] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.EventHandler:lambda$onClientTick$4:863]: 	at java.lang.Thread.run(Thread.java:748)
[06:09:11] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.EventHandler:lambda$onClientTick$4:863]: java.lang.ClassCastException: com.google.gson.JsonPrimitive cannot be cast to com.google.gson.JsonArray
[06:09:11] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.EventHandler:lambda$onClientTick$4:863]: 	at com.google.gson.JsonObject.getAsJsonArray(JsonObject.java:181)
[06:09:11] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.EventHandler:lambda$onClientTick$4:863]: 	at net.creeperhost.minetogether.paul.Callbacks.getInvite(Callbacks.java:304)
[06:09:11] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.EventHandler:lambda$onClientTick$4:863]: 	at net.creeperhost.minetogether.EventHandler.lambda$onClientTick$4(EventHandler.java:843)
[06:09:11] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.EventHandler:lambda$onClientTick$4:863]: 	at java.lang.Thread.run(Thread.java:748)
[06:52:25] [ReAuth-VersionChecker/INFO] [ReAuth]: Looking for Updates
[06:52:26] [ReAuth-VersionChecker/INFO] [ReAuth]: Looking for Updates - Finished
[06:52:26] [Session-Validator/INFO] [ReAuth]: Session validation successful
[06:52:26] [Client thread/INFO] [net.minecraft.client.Minecraft]: Stopping!
[06:52:26] [Client thread/INFO] [net.minecraft.client.audio.SoundManager]: SoundSystem shutting down...
[06:52:26] [Client thread/WARN] [net.minecraft.client.audio.SoundManager]: Author: Paul Lamb, www.paulscode.com
[06:52:27] [CraftPresence-ShutDown-Handler/INFO] [craftpresence]: Shutting down CraftPresence...
[06:52:27] [nioEventLoopGroup-2-1/WARN] [net.creeperhost.minetogether.chat.ChatHandler]: Attempting to reconnect chat

### Describe the bug

the instance crashes while trying to boot up

### Steps to reproduce

every time i try to start the instance

### Expected behaviour

instance loads into minecraft client

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/156686031/4c8ee03c-464c-477d-9ba3-2692537adec2)

**Comment by Gaz492** [comment]
Can you confirm that this is still an issue for you?
I have not been able to reproduce this issue.
