### ISSUE TITLE
FTB Vanilla+ doesn't starts

### ISSUE THREAD

**Issue by vanyaplay645** [FTBTeam/FTB-Modpack-Issues#4627]
### Modpack

FTB Vanilla+

### Modpack version

1.1.0

### Log Files

[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at java.util.zip.ZipFile.<init>(ZipFile.java:157)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at java.util.zip.ZipFile.<init>(ZipFile.java:171)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at codechicken.core.launch.DepLoader$DepLoadInst.scanDepInfo(DepLoader.java:503)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at codechicken.core.launch.DepLoader$DepLoadInst.scanDepInfos(DepLoader.java:497)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:445)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at codechicken.core.launch.DepLoader.load(DepLoader.java:584)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at codechicken.core.launch.CodeChickenCorePlugin.<init>(CodeChickenCorePlugin.java:47)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at java.lang.Class.newInstance(Class.java:442)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:458)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[15:58:45] [main/INFO] [STDERR]: [codechicken.core.launch.DepLoader$DepLoadInst:scanDepInfo:510]: Failed to load dependencies.info from ForgeMultipart-1.7.10-1.2.0.345-universal.jar as JSON
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.util.zip.ZipException: error in opening zip file
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at java.util.zip.ZipFile.open(Native Method)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at java.util.zip.ZipFile.<init>(ZipFile.java:228)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at java.util.zip.ZipFile.<init>(ZipFile.java:157)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at java.util.zip.ZipFile.<init>(ZipFile.java:171)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at codechicken.core.launch.DepLoader$DepLoadInst.scanDepInfo(DepLoader.java:503)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at codechicken.core.launch.DepLoader$DepLoadInst.scanDepInfos(DepLoader.java:497)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:445)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at codechicken.core.launch.DepLoader.load(DepLoader.java:584)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at codechicken.core.launch.CodeChickenCorePlugin.<init>(CodeChickenCorePlugin.java:47)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at java.lang.Class.newInstance(Class.java:442)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:458)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[15:58:45] [main/ERROR] [FML]: Unable to read the jar file CodeChickenLib-1.7.10-1.1.3.138-universal.jar - ignoring
java.util.zip.ZipException: error in opening zip file
at java.util.zip.ZipFile.open(Native Method) ~[?:?]
at java.util.zip.ZipFile.<init>(ZipFile.java:228) ~[?:?]
at java.util.zip.ZipFile.<init>(ZipFile.java:157) ~[?:?]
at java.util.jar.JarFile.<init>(JarFile.java:171) ~[?:?]
at java.util.jar.JarFile.<init>(JarFile.java:135) ~[?:?]
at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:265) [forge-1.7.10-10.13.4.1448-1.7.10.jar:?]
at codechicken.nei.asm.NEICorePlugin.<init>(NEICorePlugin.java:18) ~[NotEnoughItems-1.7.10-1.0.5.118-universal.jar:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:?]
at java.lang.Class.newInstance(Class.java:442) ~[?:?]
at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:458) ~[forge-1.7.10-10.13.4.1448-1.7.10.jar:?]
at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346) ~[forge-1.7.10-10.13.4.1448-1.7.10.jar:?]
at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214) ~[forge-1.7.10-10.13.4.1448-1.7.10.jar:?]
at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1448-1.7.10.jar:?]
at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1448-1.7.10.jar:?]
at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1448-1.7.10.jar:?]
at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1448-1.7.10.jar:?]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.ClassNotFoundException: codechicken.lib.asm.ASMInit
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:?]
... 15 more
Caused by: java.lang.NullPointerException
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:?]
... 15 more
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.NoClassDefFoundError: codechicken/lib/asm/ASMInit
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at codechicken.nei.asm.NEICorePlugin.<init>(NEICorePlugin.java:18)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at java.lang.Class.newInstance(Class.java:442)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:458)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: java.lang.ClassNotFoundException: codechicken.lib.asm.ASMInit
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: ... 15 more
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: java.lang.NullPointerException
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[15:58:45] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: ... 17 more

### Describe the bug

Does not start

### Steps to reproduce

1. Click "Play"

### Expected behaviour

The game is running

**Comment by vanyaplay645** [comment]
It worked! I added a new version of CodeChikenCore and removed the old one. As a result, it turned out that in the "mods" folder itself there is nothing related to CodeChiken, and in the "1.7.10" subfolder there are CodeChikenCore 1.7.10-1.0.7.48 and CodeChikenLib 1.7.10-1.1.3.141 with the rest of the mods. Everything is working!
