### ISSUE TITLE
Pack crash seems to be identical to issue fixed in dw20 1.20 pack regarding Tropicraft tree growth. null pointer ... because "fruitLeaves" 

### ISSUE THREAD

**Issue by AWDoBaun** [FTBTeam/FTB-Modpack-Issues#4717]
### Modpack

FTB Skies Expert

### Modpack version

1.0.3

### Describe the bug

https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4072

---- Minecraft Crash Report ----
// Don't do that.

Time: 2024-02-21 11:40:24
Description: Exception ticking world

java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "fruitLeaves" is null
	at net.tropicraft.core.common.block.TropicraftTrees.lambda$createFruit$3(TropicraftTrees.java:96) ~[Tropicraft-9.5.1.jar%23824!/:9.5.1] {re:classloading}
	at net.tropicraft.core.common.block.TropicraftTrees$1.m_213817_(TropicraftTrees.java:134) ~[Tropicraft-9.5.1.jar%23824!/:9.5.1] {re:classloading}
	at net.minecraft.world.level.block.SaplingBlock.m_222000_(SaplingBlock.java:45) ~[client-1.19.2-20220805.130853-srg.jar%23833!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.block.SaplingBlock.m_213898_(SaplingBlock.java:36) ~[client-1.19.2-20220805.130853-srg.jar%23833!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_222972_(BlockBehaviour.java:698) ~[client-1.19.2-20220805.130853-srg.jar%23833!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.BlockStateBaseMixin,pl:mixin:APP:mixins.oculus.json:MixinBlockStateBehavior,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.reduce_blockstate_cache_rebuilds.BlockStateBaseMixin,pl:mixin:APP:supplementaries-common.mixins.json:BlockBehaviourPlanterMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8714_(ServerLevel.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23833!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:ftbteamdimensions.mixins.json:ServerLevelAccess,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:360) ~[client-1.19.2-20220805.130853-srg.jar%23833!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ChunkLoadDebug,pl:mixin:APP:smoothchunk.mixins.json:ServerChunkCacheMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerChunkCacheMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.chunk_deadlock.ServerChunkCache_CurrentLoadingMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:310) ~[client-1.19.2-20220805.130853-srg.jar%23833!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ChunkLoadDebug,pl:mixin:APP:smoothchunk.mixins.json:ServerChunkCacheMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerChunkCacheMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.chunk_deadlock.ServerChunkCache_CurrentLoadingMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:285) ~[client-1.19.2-20220805.130853-srg.jar%23833!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:ftbteamdimensions.mixins.json:ServerLevelAccess,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23833!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23833!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23833!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23833!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23833!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:?] {re:mixin}

### Steps to reproduce

Place sapling in world, wait for it to try to grow.

I placed two saplings on my island, one grew into a papaya, the other has not grown yet and I believe is causing the crash:
Grapefruit Sapling ( tropicraft:grapefruit_sapling ) 

### Expected behaviour

No crashy

**Comment by Saereth** [comment]
https://github.com/Tropicraft/Tropicraft/issues/576

**Comment by Gaz492** [comment]
This looks to have been fixed in the latest version of the pack.
