### ISSUE TITLE
Tropicraft causing crashes in FTB Skies Expert

### ISSUE THREAD

**Issue by isochronous** [FTBTeam/FTB-Modpack-Issues#4843]
### Modpack

FTB Skies Expert

### Modpack version

1.2.2

### Log Files

Just crash logs: 
https://gist.github.com/isochronous/0e94ad84277df38b9d8b0020f4955cb3
https://gist.github.com/isochronous/26dc68cc9d5bbfac13a118694a9b8ec4

Full log:
https://gist.github.com/isochronous/9dce76be7d23264e27f29b8bd4adfb69

### Describe the bug

I planted one of each of the Tropicraft fruit tree (papaya, lemon, lime, orange, etc).  At some point one of those trees completely crashes the game to desktop.
```
java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "fruitLeaves" is null
	at net.tropicraft.core.common.block.TropicraftTrees.lambda$createFruit$3(TropicraftTrees.java:96) ~[Tropicraft-9.5.1.jar%23824!/:9.5.1] {re:classloading}
	at net.tropicraft.core.common.block.TropicraftTrees$1.m_213817_(TropicraftTrees.java:134) ~[Tropicraft-9.5.1.jar%23824!/:9.5.1] {re:classloading}
	at net.minecraft.world.level.block.SaplingBlock.m_222000_(SaplingBlock.java:45) ~[client-1.19.2-20220805.130853-srg.jar%23833!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.block.SaplingBlock.m_213898_(SaplingBlock.java:36) ~[client-1.19.2-20220805.130853-srg.jar%23833!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_222972_(BlockBehaviour.java:698) ~[client-1.19.2-20220805.130853-srg.jar%23833!/:?]
```

### Steps to reproduce

1. Purchase tropicraft fruit saplings from market
2. Plant saplings.
3. Wait until a certain random tick, I guess?
4. Game crashes to desktop

### Expected behaviour

Game should not crash

**Comment by Saereth** [comment]
Duplicate issue, we're waiting for a fix from the dev
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4717
