### ISSUE TITLE
[Bug]: An update error has occured

### ISSUE THREAD

**Issue by Krishibbleton** [FTBTeam/FTB-Modpack-Issues#487]
### Modpack

ftb infinity

### Modpack version

1.7.10-10.13.4.1641

### Log Files
[17:59:17] [main/INFO] [STDOUT]: [net.creeperhost.creeperlauncher.CreeperLauncher:main:78]: c2a207862801c2e15e8d36b03812c5adc7382b19b96440f7f738ea9d7241e12f
[17:59:17] [main/INFO] [Instances]: Reloading instances..
[17:59:17] [main/INFO] [Instances]: Skipping Cloud instance reload.
[17:59:17] [main/INFO] [Instances]: Loaded 0 out of 0 instances in 8ms(8913800ns).
[17:59:17] [main/INFO] [Instances]: Finished instance reload in 15ms(15549700ns)
[17:59:17] [main/INFO] [FTB Subprocess]: Overwolf integration mode
[17:59:17] [WebSocketSelector-27/INFO] [Websockets API]: Server started successfully - 202112101445-bdf8bdbaca-release
[17:59:17] [main/INFO] [Instances]: Reloading instances..
[17:59:17] [main/INFO] [Instances]: Skipping Cloud instance reload.
[17:59:17] [main/INFO] [Instances]: Loaded 0 out of 0 instances in 336700ns.
[17:59:17] [main/INFO] [Instances]: Finished instance reload in 4664000ns
[17:59:18] [WebSocketSelector-27/INFO] [Websockets API]: closed null with exit code 1000 additional info: 
[17:59:18] [WebSocketWorker-19/INFO] [Websockets API]: Front end connected: /127.0.0.1:56789 - sending our socket and secret and relaunching websocket
[17:59:18] [WebSocketSelector-38/INFO] [Websockets API]: Server started successfully - 202112101445-bdf8bdbaca-release
[17:59:18] [WebSocketWorker-30/INFO] [Websockets API]: Front end connected: /127.0.0.1:56796
[17:59:48] [ForkJoinPool-1-worker-5/INFO] [Modpack Installer Task]: Getting pack from api.
[17:59:51] [ForkJoinPool-1-worker-3/INFO] [Modpack Installer Task]: FTB Infinity Evolved 1.7 23 99
[17:59:51] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.os.Platform]: Installing Minecraft Launcher.
[17:59:51] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.os.Platform]: Downloading launcher from https://launcher.mojang.com/download/Minecraft.exe to C:\Users\Kristofer's\AppData\Local\.ftba\bin\launcherCache\Minecraft.exe
[17:59:51] [ForkJoinPool-1-worker-3/INFO] [DownloadAction]: Not Modified. Skipping 'https://launcher.mojang.com/download/Minecraft.exe'.
[17:59:51] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.os.Platform]: Downloaded launcher in 299ms(299267600ns), action taken false.
[17:59:51] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.os.Platform]: Unpacking launcher.
[17:59:51] [ForkJoinPool-1-worker-3/INFO] [Modpack Installer Task]: Preparing instance folder for C:\Users\Kristofer's\OneDrive\Desktop\FTB\fe0fa44f-2be4-4ec1-84f5-6df995df6953
[17:59:52] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.minecraft.modloader.forge.ForgeUniversalModLoader]: Minecraft version: 1.7.10 Forge version: 10.13.4.1614
[17:59:52] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.util.ForgeUtils]: FAILED, Using alternative mirror https://maven.creeperhost.net/net/minecraftforge/forge/1.7.10-10.13.4.1614/forge-1.7.10-10.13.4.1614-universal.jar
[17:59:52] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.util.ForgeUtils]: SUCCESS, Downloading forge from: https://maven.creeperhost.net/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
[17:59:52] [pool-3-thread-1/WARN] [net.creeperhost.creeperlauncher.api.DownloadableFile]: 1.7.10-forge1.7.10-10.13.4.1614 already exists.
[17:59:53] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.minecraft.modloader.forge.ForgeUniversalModLoader]: Completed download of 1.7.10-forge1.7.10-10.13.4.1614
[17:59:53] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.util.ForgeUtils]: Attempting to update forge json
[17:59:53] [ForkJoinPool-1-worker-3/INFO] [Modpack Installer Task]: Attempting to downloaded required files
[17:59:55] [pool-3-thread-2/WARN] [net.creeperhost.creeperlauncher.api.DownloadableFile]: BiblioWoods[Forestry][v1.7].jar size expected does not match remote file size. File size updated.
[17:59:55] [pool-3-thread-1/WARN] [net.creeperhost.creeperlauncher.api.DownloadableFile]: BiblioWoods[Natura][v1.5].jar size expected does not match remote file size. File size updated.
[18:00:29] [pool-3-thread-1/WARN] [net.creeperhost.creeperlauncher.api.DownloadableFile]: CarpentersBlocksCachedResources.zip size expected does not match remote file size. File size updated.
[18:00:30] [pool-3-thread-2/WARN] [net.creeperhost.creeperlauncher.api.DownloadableFile]: lwjgl-platform-2.9.1.jar error 404: Not Found!
[18:00:30] [pool-3-thread-2/ERROR] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]: Unable to download lwjgl-platform-2.9.1.jar
java.io.FileNotFoundException: File does not exist at URL.
	at net.creeperhost.creeperlauncher.api.DownloadableFile.prepare(DownloadableFile.java:122) ~[launcher-202112101445-bdf8bdbaca-release-all.jar:?]
	at net.creeperhost.creeperlauncher.install.tasks.DownloadTask.lambda$execute$1(DownloadTask.java:55) ~[launcher-202112101445-bdf8bdbaca-release-all.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
[18:00:30] [pool-3-thread-1/WARN] [net.creeperhost.creeperlauncher.api.DownloadableFile]: jinput-platform-2.0.5.jar error 404: Not Found!
[18:00:30] [pool-3-thread-1/ERROR] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]: Unable to download jinput-platform-2.0.5.jar
java.io.FileNotFoundException: File does not exist at URL.
	at net.creeperhost.creeperlauncher.api.DownloadableFile.prepare(DownloadableFile.java:122) ~[launcher-202112101445-bdf8bdbaca-release-all.jar:?]
	at net.creeperhost.creeperlauncher.install.tasks.DownloadTask.lambda$execute$1(DownloadTask.java:55) ~[launcher-202112101445-bdf8bdbaca-release-all.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
[18:00:30] [pool-3-thread-2/WARN] [net.creeperhost.creeperlauncher.api.DownloadableFile]: twitch-platform-5.16.jar error 404: Not Found!
[18:00:30] [pool-3-thread-2/ERROR] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]: Unable to download twitch-platform-5.16.jar
java.io.FileNotFoundException: File does not exist at URL.
	at net.creeperhost.creeperlauncher.api.DownloadableFile.prepare(DownloadableFile.java:122) ~[launcher-202112101445-bdf8bdbaca-release-all.jar:?]
	at net.creeperhost.creeperlauncher.install.tasks.DownloadTask.lambda$execute$1(DownloadTask.java:55) ~[launcher-202112101445-bdf8bdbaca-release-all.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
[18:00:30] [pool-3-thread-1/WARN] [net.creeperhost.creeperlauncher.api.DownloadableFile]: twitch-external-platform-4.5.jar error 404: Not Found!
[18:00:30] [pool-3-thread-1/ERROR] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]: Unable to download twitch-external-platform-4.5.jar
java.io.FileNotFoundException: File does not exist at URL.
	at net.creeperhost.creeperlauncher.api.DownloadableFile.prepare(DownloadableFile.java:122) ~[launcher-202112101445-bdf8bdbaca-release-all.jar:?]
	at net.creeperhost.creeperlauncher.install.tasks.DownloadTask.lambda$execute$1(DownloadTask.java:55) ~[launcher-202112101445-bdf8bdbaca-release-all.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
[18:00:30] [ForkJoinPool.commonPool-worker-3/INFO] [net.creeperhost.creeperlauncher.pack.LocalInstance]: Checking for Launch Mod for instance fe0fa44f-2be4-4ec1-84f5-6df995df6953}(FTB Infinity Evolved 1.7)..
[18:00:31] [ForkJoinPool.commonPool-worker-7/INFO] [Instances]: Reloading instances..
[18:00:31] [ForkJoinPool.commonPool-worker-7/INFO] [Instances]: Skipping Cloud instance reload.
[18:00:31] [ForkJoinPool.commonPool-worker-7/INFO] [Modpack Installer Task]: Getting pack from api.
[18:00:31] [ForkJoinPool.commonPool-worker-7/INFO] [Instances]: Loaded 1 out of 1 instances in 16ms(16063100ns).
[18:00:31] [ForkJoinPool.commonPool-worker-7/INFO] [Instances]: Finished instance reload in 17ms(17196699ns)
[18:00:32] [ForkJoinPool.commonPool-worker-3/INFO] [net.creeperhost.creeperlauncher.pack.LocalInstance]: Didn't find Launch Mod for instance fe0fa44f-2be4-4ec1-84f5-6df995df6953(FTB Infinity Evolved 1.7) in 1582ms(1582585500ns).
[18:01:00] [ForkJoinPool-1-worker-5/INFO] [Modpack Installer Task]: Getting pack from api.
[18:01:01] [ForkJoinPool-1-worker-5/INFO] [net.creeperhost.creeperlauncher.pack.LocalInstance]: Checking for Launch Mod for instance fe0fa44f-2be4-4ec1-84f5-6df995df6953}(FTB Infinity Evolved 1.7)..
[18:01:02] [ForkJoinPool-1-worker-5/INFO] [net.creeperhost.creeperlauncher.pack.LocalInstance]: Didn't find Launch Mod for instance fe0fa44f-2be4-4ec1-84f5-6df995df6953(FTB Infinity Evolved 1.7) in 1047ms(1047036901ns).
[18:01:02] [ForkJoinPool-1-worker-5/WARN] [net.creeperhost.creeperlauncher.pack.LocalInstance]: Log4jPatcher not found, Attempting to download
[18:01:02] [ForkJoinPool-1-worker-5/INFO] [net.creeperhost.creeperlauncher.pack.LocalInstance]: Log4jPatcher successfully downloaded to C:\Users\Kristofer's\OneDrive\Desktop\FTB\fe0fa44f-2be4-4ec1-84f5-6df995df6953\Log4jPatcher-1.0.0.jar
[18:01:02] [ForkJoinPool-1-worker-5/INFO] [net.creeperhost.creeperlauncher.pack.LocalInstance]: Checking for Launch Mod for instance fe0fa44f-2be4-4ec1-84f5-6df995df6953}(FTB Infinity Evolved 1.7)..
[18:01:03] [ForkJoinPool-1-worker-5/INFO] [net.creeperhost.creeperlauncher.pack.LocalInstance]: Found Launch Mod for instance fe0fa44f-2be4-4ec1-84f5-6df995df6953(FTB Infinity Evolved 1.7) in 581ms(581048100ns).
[18:01:03] [ForkJoinPool.commonPool-worker-3/INFO] [FTB Subprocess]: Starting mod socket on port 50839
[18:01:03] [ForkJoinPool-1-worker-5/INFO] [net.creeperhost.creeperlauncher.pack.LocalInstance]: Starting launcher at C:\Users\Kristofer's\AppData\Local\.ftba\bin
[18:01:03] [ForkJoinPool.commonPool-worker-5/INFO] [Minecraft Launcher 0]: https://launchermeta.mojang.com/v1/products/launcher/d03cf0cf95cce259fa9ea3ab54b65bd28bb0ae82/windows-x86.json
[18:01:05] [ForkJoinPool-1-worker-5/ERROR] [net.creeperhost.creeperlauncher.pack.LocalInstance]: Unable to initialize MineTogether Connect!
[18:04:07] [WebSocketSelector-38/INFO] [Websockets API]: closed null with exit code 1001 additional info: 

### Describe the bug

Trying to launch game from FTB app, loads minecraft launcher and crashes with
![ftbwtf](https://user-images.githubusercontent.com/96396597/146694488-74cbd540-69b6-43a8-9c7a-6870ae687cff.PNG)

I have deleted the file manually a hand full of times, it just makes a new file and gives the same error.
 

### Steps to reproduce

launch game

### Expected behaviour

the game to launch normally lol

### Screenshots

![ftbwtf](https://user-images.githubusercontent.com/96396597/146694499-935bdee9-4784-4f9f-b026-ae3cb7161be0.PNG)

**Comment by Raidobw2** [comment]
Have you tried to move it out of OneDrive? Files change so much on the game cycle when Minecraft starts that's it's generally not a good idea. What you want to backup is your world every now and then, not the entire mod files and config, since you can redownload those anytime. Let me know after moving it if it works!

**Comment by Raidobw2** [comment]
Have not received a response in multiple days, will assume fixed. If it persists, come on the FTB Discord support channels.
