### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by AimZAmZoum** [FTBTeam/FTB-Modpack-Issues#492]
### Modpack

FTB OCEAN BLOCK

### Modpack version

1.11.0

### Log Files

[18:27:39 INFO]: Minecraft Launcher 1.6.93 (through bootstrap 100) started on windows...
[18:27:39 INFO]: Current time is Dec 21, 2021 6:27:39 PM
[18:27:39 INFO]: System.getProperty('os.name') == 'Windows Vista'
[18:27:39 INFO]: System.getProperty('os.version') == '6.0'
[18:27:39 INFO]: System.getProperty('os.arch') == 'amd64'
[18:27:39 INFO]: System.getProperty('java.version') == '1.8.0_51'
[18:27:39 INFO]: System.getProperty('java.vendor') == 'Oracle Corporation'
[18:27:39 INFO]: System.getProperty('sun.arch.data.model') == '64'
[18:27:39 INFO]: proxy == DIRECT
[18:27:40 INFO]: JFX is already initialized
[18:27:40 INFO]: Refreshing local version list...
[18:27:40 INFO]: Refreshing remote version list...
[18:27:41 INFO]: Refresh complete.
[18:27:41 ERROR]: Unexpected exception refreshing profile list
java.lang.NullPointerException
	at net.minecraft.launcher.Launcher$2.run(Launcher.java:184) [launcher.jar:1.6.93]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[18:27:41 ERROR]: Unhandled exception in executor com.mojang.launcher.updater.ExceptionalThreadPoolExecutor$ExceptionalFutureTask@639afb1e
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at com.mojang.launcher.updater.ExceptionalThreadPoolExecutor$ExceptionalFutureTask.done(ExceptionalThreadPoolExecutor.java:58) [launcher.jar:1.6.93]
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:384) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.setException(FutureTask.java:251) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:271) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at net.minecraft.launcher.profile.ProfileManager.saveProfiles(ProfileManager.java:51) ~[launcher.jar:1.6.93]
	at net.minecraft.launcher.SwingUserInterface.showLoginPrompt(SwingUserInterface.java:182) ~[launcher.jar:1.6.93]
	at net.minecraft.launcher.Launcher.ensureLoggedIn(Launcher.java:238) ~[launcher.jar:1.6.93]
	at net.minecraft.launcher.Launcher$2.run(Launcher.java:213) ~[launcher.jar:1.6.93]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	... 3 more
[18:27:41 FATAL]: Unhandled exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException
	at net.minecraft.launcher.ui.bottombar.ProfileSelectionPanel.populateProfiles(ProfileSelectionPanel.java:85) ~[launcher.jar:1.6.93]
	at net.minecraft.launcher.ui.bottombar.ProfileSelectionPanel$1.run(ProfileSelectionPanel.java:79) ~[launcher.jar:1.6.93]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[?:1.8.0_51]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756) ~[?:1.8.0_51]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_51]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_51]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_51]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_51]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) ~[?:1.8.0_51]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726) ~[?:1.8.0_51]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_51]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_51]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_51]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_51]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_51]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_51]

### Describe the bug

when i launch the modpack an old launcher start and i can't launch the game with and i can't manage to solve the problem

### Steps to reproduce

1. launche the modpack FTB oceanblock
2. the launcher start but it's the wrong

### Expected behaviour

to start the game

### Screenshots

![image_2021-12-21_182822](https://user-images.githubusercontent.com/76689431/146973003-5c00ee63-3703-477a-9ab0-8c88fcc08f72.png)

### Additional information

the screen is the launcher that i get when i launch the modpack

**Comment by AimZAmZoum** [comment]
![image_2021-12-21_184042](https://user-images.githubusercontent.com/76689431/146974513-80fa04b5-6c71-4705-885d-d8b9f33c2627.png)
after many tries this message popped and idk what i should do

**Comment by Raidobw2** [comment]
Use the FTB App https://feed-the-beast.com/app.
The old launcher looks broken, and don't use it. Use the launcher that came after that, it has the same functionalities:
![image](https://user-images.githubusercontent.com/17010632/147025305-ffda81e4-bd02-4454-a585-cc4a717024f8.png)
If you have other issues with the game, come see me in the FTB Discord in the support channel: https://ftb.team/discord
We use this Github for tracking issues with modpack primarily, and not game support!
