### ISSUE TITLE
Server install for Linux ARM includes client only mods

### ISSUE THREAD

**Issue by Nagapito** [FTBTeam/FTB-Modpack-Issues#5180]
### Modpack

FTB Skies Expert

### Modpack version

1.8.0

### Log Files

Time: 2024-05-03 10:44:53
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
        at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.2-43.3.8-universal.jar%23772!/:?] {re:classloading}
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.19.2-43.3.8-universal.jar%23772!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19.2-20220805.130853-srg.jar%23767!/:?] {re:classloading,re:mixin,pl:mixin:A}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.3.8.jar%2367!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Suspected Mod:
        Entity Model Features (entity_model_features), Version: 2.0.2
                Issue tracker URL: https://github.com/Traben-0/Entity_Texture_Features/issues
                at TRANSFORMER/entity_model_features@2.0.2/traben.entity_model_features.forge.EMFForge.<init>(EMFForge.java:37)
Stacktrace:
        at traben.entity_model_features.forge.EMFForge.<init>(EMFForge.java:37) ~[entity_model_features_forge_1.19.2-2.0.2.jar%23558!/:?] {re:classloading}
-- MOD entity_model_features --
Details:
        Mod File: /home/opc/FTB_Skies/mods/entity_model_features_forge_1.19.2-2.0.2.jar
        Failure message: Entity Model Features (entity_model_features) has failed to load correctly
                java.lang.UnsupportedOperationException: Attempting to load a clientside only mod [EMF] on the server, refusing
        Mod Version: 2.0.2
        Mod Issue URL: https://github.com/Traben-0/Entity_Texture_Features/issues
        Exception message: java.lang.UnsupportedOperationException: Attempting to load a clientside only mod [EMF] on the server, refusing
Stacktrace:
        at traben.entity_model_features.forge.EMFForge.<init>(EMFForge.java:37) ~[entity_model_features_forge_1.19.2-2.0.2.jar%23558!/:?] {re:classloading}
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
        at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.19.2-43.3.8.jar%23769!/:?] {}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:122) ~[fmlcore-1.19.2-43.3.8.jar%23768!/:?] {}
(...)

### Describe the bug

Not sure if this happens on other server installs but the Linux ARM installer for version 1.8.0 includes the new EMF and ETF mods, preventing the server to start.

### Steps to reproduce

Update Linux ARM server to version 1.8

### Expected behaviour

Server should start correctly after update

**Comment by Zonk1987** [comment]
Same for me Log ( https://mclo.gs/TbOBPNj )

**Comment by GalaxyOfZero** [comment]
ther are two clientside mods in it 
entity_texture_features  [crash-2024-05-03_12.09.13-fml.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/15198600/crash-2024-05-03_12.09.13-fml.txt)
entity_model_features [crash-2024-05-03_12.04.40-fml.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/15198608/crash-2024-05-03_12.04.40-fml.txt)

**Comment by Louise-Renwick** [comment]
same on the linux Intel/ARM install.   renaming the 2 offending jar files resolves the crash on startup.

**Comment by Firefox37** [comment]
Same issue happens in v1.8.1 Linux server installer.

To fix, you can rename or delete the 2 mods from mods folder.

**Comment by Zonk1987** [comment]
> Same issue happens in v1.8.1 Linux server installer.
> 
> To fix, you can rename or delete the 2 mods from mods folder.

For me as well

**Comment by Gaz492** [comment]
This should be resolved now, can you confirm if this is still an issue for you?

**Comment by Firefox37** [comment]
Just tested 1.8.1 installer on windows and linux. Both work correctly now.

**Comment by Gaz492** [comment]
Great to hear!
