### ISSUE TITLE
FTB Vanilla + launch

### ISSUE THREAD

**Issue by koubisdh** [FTBTeam/FTB-Modpack-Issues#5182]
### Modpack

FTB Vanilla+

### Modpack version

1.1.0

### Log Files

18:49:27.428
FML
main
The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
18:49:27.454
FML
main
An error occurred trying to configure the minecraft home at C:\Users\tbake\curseforge\minecraft\Instances\FTB Vanilla + for Forge Mod Loader
java.lang.NoClassDefFoundError: codechicken/lib/asm/ASMInit
	at codechicken.nei.asm.NEICorePlugin.<init>(NEICorePlugin.java:18)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:458)
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346)
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: codechicken.lib.asm.ASMInit
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 17 more

### Describe the bug

Hello, sorry for my engish im czech :)
When i go play FTB Vanilla + and launch in minecraft launcher after 10sec game didnt launch and massage : Crash Code 1

### Steps to reproduce

I DONT KNOW

### Expected behaviour

Game clearly launch without problem 

### Screenshots

![obrázek_2024-05-03_190518745](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/162782416/50033667-2de8-4574-93ef-ba8288548aa7)

### Additional information

i need a Help

**Comment by EndangeredNayla** [comment]
This is because ChickenBones's maven is down. You need to install Code Chicken Core manually.

**Comment by koubisdh** [comment]
How can i do that

**Comment by Gaz492** [comment]
This should be fixed now
