### ISSUE TITLE
IC2 Alloy Smelter no longer has steel recipe

### ISSUE THREAD

**Issue by Emenziot** [FTBTeam/FTB-Modpack-Issues#5208]
### Modpack

FTB Genesis

### Modpack version

1.5.0

### Describe the bug

The recipe for steel is not currently included in the Alloy smelter, making the "Steeling is not a crime" quest and all further progression impossible. 

### Steps to reproduce

1. Place down IC2 Alloy smelter
2. Attempt to add coal coke or iron

### Expected behaviour

Alloy smelter should accept ingredients for making steel.

**Comment by SgtKrazy** [comment]
Was just going to post this. Everything to make steel either requires steel or requires titanium which requires steel ever since 1.5.0 update.

**Comment by piedrrum** [comment]
It seems like parser is broken or json syntax is incorrect.
As for some other json ic2 recipes:

[01:05:41] [Render thread/ERROR] [IC2Classic/]: Recipe [ic2:steel_ingot] for Recipe List [mixing_furnace] wasn't able to load. Json Data: [{"input":[{"tag":"forge:coal_coke","size":1,"type":"ic2:tag"},{"item":"minecraft:iron_ingot","size":1,"type":"ic2:item"}],"output":{"xp":0.5,"outputs":[{"item":"mekanism:ingot_steel","count":1}],"type":"ic2:simple"}}]
[01:05:41] [Render thread/ERROR] [IC2Classic/CATCHING]: Catching
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
	at ic2.core.platform.recipes.misc.IngredientRegistry.readOutputGenerator(IngredientRegistry.java:326) ~[IC2Classic-1.19.2-2.0.9.2.jar%23532!/:1.19.2-2.0.9.2] {re:classloading}
	at ic2.api.recipes.ingridients.recipes.SimpleRecipeOutput.<init>(SimpleRecipeOutput.java:33) ~[IC2Classic-1.19.2-2.0.9.2.jar%23532!/:1.19.2-2.0.9.2] {re:classloading}
	at ic2.core.platform.recipes.misc.IngredientRegistry.readOutput(IngredientRegistry.java:313) ~[IC2Classic-1.19.2-2.0.9.2.jar%23532!/:1.19.2-2.0.9.2] {re:classloading}
	at ic2.core.block.machines.recipes.MultiMachineRecipeList.readRecipe(MultiMachineRecipeList.java:145) ~[IC2Classic-1.19.2-2.0.9.2.jar%23532!/:1.19.2-2.0.9.2] {re:classloading}
	at ic2.core.platform.recipes.misc.GlobalRecipes.readRecipes(GlobalRecipes.java:158) ~[IC2Classic-1.19.2-2.0.9.2.jar%23532!/:1.19.2-2.0.9.2] {re:classloading}
	at ic2.core.platform.recipes.misc.GlobalRecipes.loadDataPackRecipes(GlobalRecipes.java:149) ~[IC2Classic-1.19.2-2.0.9.2.jar%23532!/:1.19.2-2.0.9.2] {re:classloading}
	at ic2.core.platform.recipes.helpers.IC2RecipeLoader.apply(IC2RecipeLoader.java:44) ~[IC2Classic-1.19.2-2.0.9.2.jar%23532!/:1.19.2-2.0.9.2] {re:classloading}
	at ic2.core.platform.recipes.helpers.IC2RecipeLoader.m_5787_(IC2RecipeLoader.java:18) ~[IC2Classic-1.19.2-2.0.9.2.jar%23532!/:1.19.2-2.0.9.2] {re:classloading}
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:mixin,re:classloading,pl:mixin:APP:drippyloadingscreen.mixin.json:client.IMixinSimplePreparableReloadListener,pl:mixin:APP:moonlight.mixins.json:ConditionsHackMixin,pl:mixin:APP:jaopca.mixins.json:SimplePreparableReloadListenerMixin,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?] {}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin,pl:mixin:A}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_18701_(Minecraft.java:5419) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233096_(WorldOpenFlows.java:130) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:WorldOpenFlowsMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.WorldOpenFlowsMixin,pl:mixin:APP:yeetusexperimentus.mixins.json:WPFMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233122_(WorldOpenFlows.java:109) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:WorldOpenFlowsMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.WorldOpenFlowsMixin,pl:mixin:APP:yeetusexperimentus.mixins.json:WPFMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.doLoadLevel(WorldOpenFlows.java:148) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:WorldOpenFlowsMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.WorldOpenFlowsMixin,pl:mixin:APP:yeetusexperimentus.mixins.json:WPFMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233145_(WorldOpenFlows.java:136) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:WorldOpenFlowsMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.WorldOpenFlowsMixin,pl:mixin:APP:yeetusexperimentus.mixins.json:WPFMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233133_(WorldOpenFlows.java:58) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:WorldOpenFlowsMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.WorldOpenFlowsMixin,pl:mixin:APP:yeetusexperimentus.mixins.json:WPFMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101744_(WorldSelectionList.java:586) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_screen_skipped.WorldSelectionListMixin,pl:mixin:APP:yeetusexperimentus.mixins.json:WSLMixin,pl:mixin:APP:fancymenu.general.mixin.json:MixinWorldListEntry,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101704_(WorldSelectionList.java:448) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_screen_skipped.WorldSelectionListMixin,pl:mixin:APP:yeetusexperimentus.mixins.json:WSLMixin,pl:mixin:APP:fancymenu.general.mixin.json:MixinWorldListEntry,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_6375_(WorldSelectionList.java:378) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_screen_skipped.WorldSelectionListMixin,pl:mixin:APP:yeetusexperimentus.mixins.json:WSLMixin,pl:mixin:APP:fancymenu.general.mixin.json:MixinWorldListEntry,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.components.AbstractSelectionList.m_6375_(AbstractSelectionList.java:336) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MouseHandlerAccessor,pl:mixin:APP:supplementaries-common.mixins.json:MouseHandlerMixin,pl:mixin:APP:mixins.cofhcore.json:MouseHandlerMixin,pl:mixin:APP:konkrete.mixin.json:MixinMouseHandler,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ScreenMixin,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:APP:controlling.mixins.json:AccessScreen,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen,pl:mixin:APP:fmaudio.mixin.json:client.MixinScreen,pl:mixin:APP:iceberg.mixins.json:ScreenMixin,pl:mixin:APP:legendarytooltips.mixins.json:ScreenMixin,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:APP:fancymenu.general.mixin.json:MixinScreen,pl:mixin:APP:minetogether-common.mixins.json:chat.ScreenMixin,pl:mixin:APP:ae2.mixins.json:WrappedGenericStackTooltipModIdMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MouseHandlerAccessor,pl:mixin:APP:supplementaries-common.mixins.json:MouseHandlerMixin,pl:mixin:APP:mixins.cofhcore.json:MouseHandlerMixin,pl:mixin:APP:konkrete.mixin.json:MixinMouseHandler,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MouseHandlerAccessor,pl:mixin:APP:supplementaries-common.mixins.json:MouseHandlerMixin,pl:mixin:APP:mixins.cofhcore.json:MouseHandlerMixin,pl:mixin:APP:konkrete.mixin.json:MixinMouseHandler,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin,pl:mixin:A}
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MouseHandlerAccessor,pl:mixin:APP:supplementaries-common.mixins.json:MouseHandlerMixin,pl:mixin:APP:mixins.cofhcore.json:MouseHandlerMixin,pl:mixin:APP:konkrete.mixin.json:MixinMouseHandler,pl:mixin:A,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%23144!/:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23136!/:build 7] {}
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar%23144!/:build 7] {re:mixin}
	at com.mojang.blaze3d.systems.RenderSystem.m_69830_(RenderSystem.java:222) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.oculus.json:MixinGlStateManager,pl:mixin:APP:mixins.oculus.json:MixinRenderSystem,pl:mixin:APP:mixins.oculus.json:statelisteners.MixinRenderSystem,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.13.jar%23101!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

**Comment by ArtpokeBr** [comment]
IC2c changed the datapack recipe structure so took a bit to fix this but should be done now.

All tweaked and brand new IC2c recipes should be working now.
