### ISSUE TITLE
Crash on startup on FTB OceanBlock 1.16.0

### ISSUE THREAD

**Issue by RinkuStrange0** [FTBTeam/FTB-Modpack-Issues#5292]
### Modpack

FTB OceanBlock

### Modpack version

1.16.0

### Pack has been modified

- [ ] Yes

### Log Files

[AUTH][INFO] Starting authentication flow finished successfully
[AUTH][INFO] Contacting Xbox Live started 
[AUTH][INFO] Contacting Xbox Live finished successfully
[AUTH][INFO] Authenticating with Xbox Services started 
[AUTH][INFO] Authenticating with Xbox Services finished successfully
[AUTH][INFO] Logging in with Xbox Live started 
[AUTH][INFO] Logging in with Xbox Live finished successfully
[AUTH][INFO] Getting Minecraft Profile started 
[AUTH][INFO] Verifying ownership started 
[AUTH][INFO] Getting Minecraft Profile finished successfully
[AUTH][INFO] Verifying ownership finished successfully
[FTB APP][INFO] Pre-Start Tasks
[FTB APP][INFO] Validate Java Runtime
[FTB APP][INFO] Validate assets
[FTB APP][INFO] Validate libraries
[FTB APP][INFO] Validate client
[Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/lookup/JndiLookup
[Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/pattern/MessagePatternConverter
[Log4jPatcher] [WARN]  Unable to find noLookups:Z field in org/apache/logging/log4j/core/pattern/MessagePatternConverter
2024-06-09 10:51:14,191 main WARN Advanced terminal features are not available in this environment
[10:51:14] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, RinkuStrange, --version, 1.16.5-forge-36.2.39, --gameDir, C:\Users\scott\AppData\Local\.ftba\instances\ftb oceanblock, --assetsDir, C:\Users\scott\AppData\Local\.ftba\bin\assets, --assetIndex, 1.16, --uuid, 09d6359f-f0b5-4982-bb60-3fcf9c49b239, --accessToken, ????????, --userType, msa, --versionType, release, --width, 1720, --height, 840, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.39, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550]
[10:51:14] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 1.8.0_312 by Temurin
[10:51:14] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[10:51:14] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/scott/AppData/Local/.ftba/bin/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[LWJGL] GLFW_API_UNAVAILABLE error
[10:51:14] [main/INFO] [STDERR/]: [org.lwjgl.glfw.GLFWErrorCallback$1:invoke:105]: 	Description : WGL: The driver does not appear to support OpenGL
[10:51:14] [main/INFO] [STDERR/]: [org.lwjgl.glfw.GLFWErrorCallback$1:invoke:106]: 	Stacktrace  :
[10:51:14] [main/INFO] [STDERR/]: [org.lwjgl.glfw.GLFWErrorCallback$1:invoke:110]: org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714)
[10:51:14] [main/INFO] [STDERR/]: [org.lwjgl.glfw.GLFWErrorCallback$1:invoke:110]: org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897)
[10:51:14] [main/INFO] [STDERR/]: [org.lwjgl.glfw.GLFWErrorCallback$1:invoke:110]: net.minecraftforge.fml.loading.progress.ClientVisualization.initWindow(ClientVisualization.java:89)
[10:51:14] [main/INFO] [STDERR/]: [org.lwjgl.glfw.GLFWErrorCallback$1:invoke:110]: net.minecraftforge.fml.loading.progress.ClientVisualization.start(ClientVisualization.java:335)
[10:51:14] [main/INFO] [STDERR/]: [org.lwjgl.glfw.GLFWErrorCallback$1:invoke:110]: net.minecraftforge.fml.loading.progress.EarlyProgressVisualization.accept(EarlyProgressVisualization.java:29)
[10:51:14] [main/INFO] [STDERR/]: [org.lwjgl.glfw.GLFWErrorCallback$1:invoke:110]: net.minecraftforge.fml.loading.FMLLoader.setupLaunchHandler(FMLLoader.java:176)
[10:51:14] [main/INFO] [STDERR/]: [org.lwjgl.glfw.GLFWErrorCallback$1:invoke:110]: net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:80)
[10:51:14] [main/INFO] [STDERR/]: [org.lwjgl.glfw.GLFWErrorCallback$1:invoke:110]: cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
[10:51:14] [main/INFO] [STDERR/]: [org.lwjgl.glfw.GLFWErrorCallback$1:invoke:110]: cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)
[10:51:14] [main/INFO] [STDERR/]: [org.lwjgl.glfw.GLFWErrorCallback$1:invoke:110]: java.util.HashMap$Values.forEach(HashMap.java:982)
[10:51:14] [main/INFO] [STDERR/]: [org.lwjgl.glfw.GLFWErrorCallback$1:invoke:110]: cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)
[10:51:14] [main/INFO] [STDERR/]: [org.lwjgl.glfw.GLFWErrorCallback$1:invoke:110]: cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
[10:51:14] [main/INFO] [STDERR/]: [org.lwjgl.glfw.GLFWErrorCallback$1:invoke:110]: cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
[10:51:14] [main/INFO] [STDERR/]: [org.lwjgl.glfw.GLFWErrorCallback$1:invoke:110]: cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[10:51:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: Failed to create the GLFW window
[10:51:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.progress.ClientVisualization.initWindow(ClientVisualization.java:91)
[10:51:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.progress.ClientVisualization.start(ClientVisualization.java:335)
[10:51:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.progress.EarlyProgressVisualization.accept(EarlyProgressVisualization.java:29)
[10:51:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLLoader.setupLaunchHandler(FMLLoader.java:176)
[10:51:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:80)
[10:51:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
[10:51:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)
[10:51:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap$Values.forEach(HashMap.java:982)
[10:51:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)
[10:51:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
[10:51:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
[10:51:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

### Describe the bug

I can't launch the modpack, the game closes in a loop as soon as I try to launch it and I didn't have this problem yesterday

### Steps to reproduce

I don't know

### Expected behaviour

launch the game and play in peace

### Screenshots

![image_2024-06-09_110643046](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/172176621/e7b6bcb9-fa45-4b34-a1e9-3462af975717)

### Additional information

I was playing quietly, my pc shut down, I turned it on and since then I can't play modpack anymore

**Comment by Gaz492** [comment]
When you say your PC shutdown, did it do this without you telling it to?
Is it only this modpack that the issue is happening on or does it happen to all modpacks/vanilla minecraft?

Would you also be able to post what your computer specifications are, specifically your CPU and GPU?
