### ISSUE TITLE
[Server] Amadron tablet place order is not working

### ISSUE THREAD

**Issue by Apolomir** [FTBTeam/FTB-Modpack-Issues#5316]
### Modpack

FTB NeoTech

### Modpack version

1.1.0

### Pack has been modified

- [ ] Yes

### Describe the bug

Can't progress the quest in pneumatic craft on server - Amadron tablet "place order" button is gray when linked to chest with 8 emeralds inside.

### Steps to reproduce

1. Join some server
2. Link amadron tablet to chest with 8 emeralds
3. Open amadron tablet and request 1 PCB Blueprint
4. Order request button is gray

### Expected behaviour

I should be able to request PCB Blueprint in amadron tablet

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/60337783/980447b9-2ab2-4554-b7fb-7e9d81896627)

**Comment by Saereth** [comment]
I can't reproduce this, its working fine on our server. Are you right clicking to select the order? I've seen some people left clicking and that doesnt actually select it

**Comment by weaz12** [comment]
This is also not working on our server.....Tablet is synced with chest and tank.....emeralds in chest......Place Order remains grayed out regardless of the type of order.

**Comment by Apolomir** [comment]
> I can't reproduce this, its working fine on our server. Are you right clicking to select the order? I've seen some people left clicking and that doesnt actually select it

Yes, on screenshot you can see that I selected 1 item. I tried on Linux server and also on local Windows server. It’s not working on both. In single player it works fine.

**Comment by Apolomir** [comment]
Just to clarify… I’m using server without any modifications… Server is running using start.sh script

**Comment by Apolomir** [comment]
On 1.1.0 issue seems still present

**Comment by Apolomir** [comment]
I also checked client logs and see that messages every time Im chenging quantity of item that I want to order

```
[08:03:45] [Render thread/ERROR] [minecraft/BlockableEventLoop]: Error executing task on Client
java.util.concurrent.CompletionException: java.lang.IndexOutOfBoundsException: Index 40 out of bounds for length 33
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:146) ~[client-1.20.4-20231207.154220-srg.jar%23707!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[client-1.20.4-20231207.154220-srg.jar%23707!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:120) ~[client-1.20.4-20231207.154220-srg.jar%23707!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:109) ~[client-1.20.4-20231207.154220-srg.jar%23707!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1223) ~[client-1.20.4-20231207.154220-srg.jar%23707!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.modernui-neoforge.json:MixinMinecraft from mod modernui,pl:mixin:APP:mffs.mixins.json:MinecraftMixin from mod mffs,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-neoforge.mixins.json:feature.measure_time.MinecraftMixin_Forge from mod modernfix,pl:mixin:APP:resourcepackoverrides.common.mixins.json:client.MinecraftMixin from mod resourcepackoverrides,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:emojiful.mixins.json:MinecraftEmojifulMixin from mod emojiful,pl:mixin:APP:resourcefulconfig.mixins.json:client.MinecraftMixin from mod resourcefulconfig,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin from mod mining_helmet,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin from mod fallingleaves,pl:mixin:APP:drippyloadingscreen.mixins.json:client.IMixinMinecraft from mod drippyloadingscreen,pl:mixin:APP:emi.mixins.json:MinecraftClientMixin from mod emi,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess from mod immersiveengineering,pl:mixin:APP:ding.mixins.json:MinecraftMixin from mod ding,pl:mixin:APP:immediatelyfast-common.mixins.json:core.MixinMinecraftClient from mod immediatelyfast,pl:mixin:APP:extrasounds.mixins.json:hotbar.MinecraftClientMixin from mod extrasounds,pl:mixin:APP:extrasounds.mixins.json:inventory.MinecraftClientMixin from mod extrasounds,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft from mod bookshelf,pl:mixin:APP:konkrete.mixins.json:client.MixinMinecraft from mod konkrete,pl:mixin:APP:entity_model_features-common.mixins.json:MixinResourceReload from mod entity_model_features,pl:mixin:APP:entity_model_features-common.mixins.json:accessor.MinecraftClientAccessor from mod entity_model_features,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinMinecraftClient from mod entity_texture_features,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinResourceReload from mod entity_texture_features,pl:mixin:APP:bridgingmod.mixins.json:MinecraftClientMixin from mod bridgingmod,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:blockshot.mixins.json:MixinMinecraft from mod blockshot,pl:mixin:APP:kubejs-common.mixins.json:MinecraftClientMixin from mod kubejs,pl:mixin:APP:combatnouveau.common.mixins.json:client.MinecraftMixin from mod combatnouveau,pl:mixin:APP:travelerstitles.mixins.json:MinecraftClientTickMixin from mod travelerstitles,pl:mixin:APP:just_enough_beacons.mixins.json:test.TestMixin from mod just_enough_beacons,pl:mixin:APP:just_enough_beacons-common.mixins.json:test.TestMixin from mod just_enough_beacons,pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod ae2,pl:mixin:APP:armorposer.neoforge.mixins.json:MinecraftMixin from mod armorposer,pl:mixin:APP:fancymenu.mixins.json:client.IMixinMinecraft from mod fancymenu,pl:mixin:APP:fancymenu.mixins.json:client.MixinMinecraft from mod fancymenu,pl:mixin:APP:betterf3.mixins.json:ClientAccessor from mod betterf3,pl:mixin:APP:sound_physics_remastered.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin from mod embeddium,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.run(Minecraft.java:818) ~[client-1.20.4-20231207.154220-srg.jar%23707!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.modernui-neoforge.json:MixinMinecraft from mod modernui,pl:mixin:APP:mffs.mixins.json:MinecraftMixin from mod mffs,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-neoforge.mixins.json:feature.measure_time.MinecraftMixin_Forge from mod modernfix,pl:mixin:APP:resourcepackoverrides.common.mixins.json:client.MinecraftMixin from mod resourcepackoverrides,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:emojiful.mixins.json:MinecraftEmojifulMixin from mod emojiful,pl:mixin:APP:resourcefulconfig.mixins.json:client.MinecraftMixin from mod resourcefulconfig,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin from mod mining_helmet,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin from mod fallingleaves,pl:mixin:APP:drippyloadingscreen.mixins.json:client.IMixinMinecraft from mod drippyloadingscreen,pl:mixin:APP:emi.mixins.json:MinecraftClientMixin from mod emi,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess from mod immersiveengineering,pl:mixin:APP:ding.mixins.json:MinecraftMixin from mod ding,pl:mixin:APP:immediatelyfast-common.mixins.json:core.MixinMinecraftClient from mod immediatelyfast,pl:mixin:APP:extrasounds.mixins.json:hotbar.MinecraftClientMixin from mod extrasounds,pl:mixin:APP:extrasounds.mixins.json:inventory.MinecraftClientMixin from mod extrasounds,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft from mod bookshelf,pl:mixin:APP:konkrete.mixins.json:client.MixinMinecraft from mod konkrete,pl:mixin:APP:entity_model_features-common.mixins.json:MixinResourceReload from mod entity_model_features,pl:mixin:APP:entity_model_features-common.mixins.json:accessor.MinecraftClientAccessor from mod entity_model_features,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinMinecraftClient from mod entity_texture_features,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinResourceReload from mod entity_texture_features,pl:mixin:APP:bridgingmod.mixins.json:MinecraftClientMixin from mod bridgingmod,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:blockshot.mixins.json:MixinMinecraft from mod blockshot,pl:mixin:APP:kubejs-common.mixins.json:MinecraftClientMixin from mod kubejs,pl:mixin:APP:combatnouveau.common.mixins.json:client.MinecraftMixin from mod combatnouveau,pl:mixin:APP:travelerstitles.mixins.json:MinecraftClientTickMixin from mod travelerstitles,pl:mixin:APP:just_enough_beacons.mixins.json:test.TestMixin from mod just_enough_beacons,pl:mixin:APP:just_enough_beacons-common.mixins.json:test.TestMixin from mod just_enough_beacons,pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod ae2,pl:mixin:APP:armorposer.neoforge.mixins.json:MinecraftMixin from mod armorposer,pl:mixin:APP:fancymenu.mixins.json:client.IMixinMinecraft from mod fancymenu,pl:mixin:APP:fancymenu.mixins.json:client.MixinMinecraft from mod fancymenu,pl:mixin:APP:betterf3.mixins.json:ClientAccessor from mod betterf3,pl:mixin:APP:sound_physics_remastered.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin from mod embeddium,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:244) ~[neoforge-20.4.237.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-2.0.17.jar:2.0] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-2.0.17.jar:2.0] {}
	at net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-2.0.17.jar:2.0] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-2.0.17.jar:2.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
```

**Comment by Saereth** [comment]
this is a mod issue with PNC, I've passed it onto desht to have a look at.

**Comment by Apolomir** [comment]
@Saereth yes, now it works. Many thanks !!! :)
