### ISSUE TITLE
server crashing for others and myself 

### ISSUE THREAD

**Issue by morgan20144** [FTBTeam/FTB-Modpack-Issues#5321]
### Modpack

FTB NeoTech

### Modpack version

1.5.0

### Pack has been modified

- [ ] Yes

### Describe the bug

I have very limited knowledge on why this is happening and what's causing it as it doesn't give much information, other than in the code. When I try to load into the game, the server is working perfectly fine, with friends already playing on the server with no issues, I try to load the game and it comes up with loading terrain then the page dims in colour and proceeds to say connection to server has been lost, connection refused: no further information.. 

\the only part that's confusing, is why its then booting everyone on that server off, and disabling it for a while. any help would be massively appreciated, thank you.  

Script Below:

[17:44:11] [Server Connector #1/ERROR] [minecraft/ConnectScreen]: Couldn't connect to server
[17:32:45] [Worker-Main-3/ERROR] [ne.mi.re.PathPackResources/]: Invalid path textures/enderio:block/overlay: Invalid segment 'enderio:block' in path 'textures/enderio:block/overlay'
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: eu6188947.g-portal.game./45.85.250.175:32965
[17:32:45] [Worker-Main-3/ERROR] [ne.mi.re.PathPackResources/]: Invalid path textures/enderio:block/overlay: Invalid segment 'enderio:block' in path 'textures/enderio:block/overlay'
Caused by: java.net.ConnectException: Connection refused: no further information
[17:32:45] [Worker-Main-3/ERROR] [ne.mi.re.PathPackResources/]: Invalid path textures/enderio:block/overlay: Invalid segment 'enderio:block' in path 'textures/enderio:block/overlay'
	at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?] {}
[17:32:45] [Worker-Main-3/ERROR] [ne.mi.re.PathPackResources/]: Invalid path textures/enderio:block/overlay: Invalid segment 'enderio:block' in path 'textures/enderio:block/overlay'
	at sun.nio.ch.Net.pollConnectNow(Unknown Source) ~[?:?] {}
[17:32:45] [Worker-Main-3/ERROR] [ne.mi.re.PathPackResources/]: Invalid path textures/enderio:block/overlay: Invalid segment 'enderio:block' in path 'textures/enderio:block/overlay'
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source) ~[?:?] {}
[17:32:45] [Worker-Main-3/ERROR] [ne.mi.re.PathPackResources/]: Invalid path textures/enderio:block/overlay: Invalid segment 'enderio:block' in path 'textures/enderio:block/overlay'
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final] {}
[17:32:45] [Worker-Main-3/ERROR] [ne.mi.re.PathPackResources/]: Invalid path textures/enderio:block/overlay: Invalid segment 'enderio:block' in path 'textures/enderio:block/overlay'
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final] {}
[17:32:45] [Worker-Main-3/ERROR] [ne.mi.re.PathPackResources/]: Invalid path textures/enderio:block/overlay: Invalid segment 'enderio:block' in path 'textures/enderio:block/overlay'
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final] {}
[17:32:45] [Worker-Main-3/ERROR] [ne.mi.re.PathPackResources/]: Invalid path textures/enderio:block/overlay: Invalid segment 'enderio:block' in path 'textures/enderio:block/overlay'
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final] {}
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final] {}
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final] {}
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar%23123!/:4.1.82.Final] {}
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar%23123!/:4.1.82.Final] {}
	at java.lang.Thread.run(Unknown Source) ~[?:?] {}

### Steps to reproduce

i have no idea on what steps to take to avoid it 

### Expected behaviour

for it to load into the game with no problems and evreryone else still being on the server 

### Additional information

looking at the script it seems to be one mod called [ ENDER-IO ]

**Comment by Gaz492** [comment]
Would you be able to upload the latest.log and debug.log from your client after you attempt to connect to the server?
https://docs.feed-the-beast.com/docs/app/Instances/instance-logs#locating-normal-game-logs

The latest.log and debug.log from the server may also be helpful to see whats happening there as well.

**Comment by morgan20144** [comment]
Hello thereThank you for the reply, we managed to figure it out, it’s was a “glitched chunk” i think that’s what they call it. where a certain mod doesn’t load in a area and cause the player to get stuck in a area. we managed to “/teleport” me away from the infected chunk before i fully loaded into the game and it worked.I do appreciate the reply though, thank you.All the best Sent from my iPhoneOn 17 Jun 2024, at 20:37, Gareth Williams ***@***.***> wrote:﻿
Would you be able to upload the latest.log and debug.log from your client after you attempt to connect to the server?
https://docs.feed-the-beast.com/docs/app/Instances/instance-logs#locating-normal-game-logs
The latest.log and debug.log from the server may also be helpful to see whats happening there as well.
