### ISSUE TITLE
Minetogether mod not working world visible but constant pinging 

### ISSUE THREAD

**Issue by DisguisedNewt1** [FTBTeam/FTB-Modpack-Issues#5357]
### Modpack

FTB NeoTech

### Modpack version

1.1.0

### Pack has been modified

- [ ] Yes

### Describe the bug

when the server is opened for friends to join it wont stop pinging and will not allow to join. attempted this exact scenario on a seperate network and different devices and still the same results

### Steps to reproduce

1.download and install a fresh Neotech instance from the FTB app
2.Load game and start new singleplayer world
3.press escape and open to freinds 
4. server opened for friends to join but server constantly Pinging

### Expected behaviour

expected friends to be able to join the server

### Additional information

 [Netty Server IO #2/WARN] [io.ne.ch.DefaultChannelPipeline/]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.attr(io.netty.util.AttributeKey)" because "this.channel" is null
	at net.minecraft.network.Connection.setListener(Connection.java:212) ~[client-1.20.4-20231207.154220-srg.jar%23707!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.creeperhost.minetogether.connect.netty.NettyClient.link(NettyClient.java:198) ~[minetogether-neoforge-1.20.4-6.2.6.jar%23604!/:?] {re:classloading}
	at net.creeperhost.minetogether.connect.netty.NettyClient$1.handleServerLink(NettyClient.java:92) ~[minetogether-neoforge-1.20.4-6.2.6.jar%23604!/:?] {re:classloading}
	at net.creeperhost.minetogether.connect.lib.netty.packet.CServerLink.handle(CServerLink.java:30) ~[minetogether-neoforge-1.20.4-6.2.6.jar%23604!/:?] {re:classloading}
	at net.creeperhost.minetogether.connect.lib.netty.packet.CServerLink.handle(CServerLink.java:11) ~[minetogether-neoforge-1.20.4-6.2.6.jar%23604!/:?] {re:classloading}
	at net.creeperhost.minetogether.connect.netty.NettyClient$ProxyConnection.channelRead0(NettyClient.java:377) ~[minetogether-neoforge-1.20.4-6.2.6.jar%23604!/:?] {re:classloading}
	at net.creeperhost.minetogether.connect.netty.NettyClient$ProxyConnection.channelRead0(NettyClient.java:351) ~[minetogether-neoforge-1.20.4-6.2.6.jar%23604!/:?] {re:classloading}
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.97.Final.jar%23157!/:4.1.97.Final] {re:mixin,re:computing_frames}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar%23157!/:4.1.97.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23157!/:4.1.97.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar%23157!/:4.1.97.Final] {}
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.97.Final.jar%23151!/:4.1.97.Final] {}
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.97.Final.jar%23151!/:4.1.97.Final] {}
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) ~[netty-codec-4.1.97.Final.jar%23151!/:4.1.97.Final] {}

**Comment by M7mdrd1** [comment]
same issue... any progress?

**Comment by DisguisedNewt1** [comment]
Hi no progress unfortunately, i believe that its an issue with the version of the mod, minecraft or mod incompatibility, i did download the server files and host a server going through the portforwarding process and got a server running that way, if your pc can handle hosting and playing id recommend this way

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs

**Comment by DisguisedNewt1** [comment]
[2024-06-20-1.log.gz](https://github.com/user-attachments/files/15924085/2024-06-20-1.log.gz)
[2024-06-20-2.log.gz](https://github.com/user-attachments/files/15924087/2024-06-20-2.log.gz)
[2024-06-21-1.log.gz](https://github.com/user-attachments/files/15924088/2024-06-21-1.log.gz)
[debug-1.log.gz](https://github.com/user-attachments/files/15924089/debug-1.log.gz)
[debug-2.log.gz](https://github.com/user-attachments/files/15924090/debug-2.log.gz)
[debug-3.log.gz](https://github.com/user-attachments/files/15924092/debug-3.log.gz)

**Comment by DisguisedNewt1** [comment]
im sure thats going to be a lot of information to sift through and i have played since the error so theres probably quite a bit on there since, the last attempt to connect was around 21:30 - 21:50 20/06/2024 hope thats helpful

**Comment by Saereth** [comment]
Better place for MT specific support in the future is https://github.com/CreeperHost/mineTogether/
that being said, I've spoke with the devs and was told its likely fixed but the new version wont be out till next week

**Comment by M7mdrd1** [comment]
> Hi no progress unfortunately, i believe that its an issue with the version of the mod, minecraft or mod incompatibility, i did download the server files and host a server going through the portforwarding process and got a server running that way, if your pc can handle hosting and playing id recommend this way

I went with your advice, I was bit unlucky but I think my computer handle it, thanks
