### ISSUE TITLE
Sophisticated Backpacks makes the game crash when

### ISSUE THREAD

**Issue by H3kk4** [FTBTeam/FTB-Modpack-Issues#5436]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

Yes

### Log Files

[04Jul2024 20:41:24.023] [pool-13-thread-1/INFO] [com.sunekaer.sdrp.discord.RPClient/]: Sent state to discord: {"assets":{"small_image":"overworld","small_text":"Overworld","large_image":"logo","large_text":"Pack Logo"},"instance":false,"buttons":[{"label":"Download FTB NeoTech","url":"https://feed-the-beast.com/modpacks/123-ftb-neotech?tab=about"},{"label":"Download the FTB App","url":"https://go.ftb.team/app"}],"timestamps":{"start":1720116198},"state":"In Overworld"}
[04Jul2024 20:42:21.649] [Render thread/INFO] [de.keksuccino.fancymenu.customization.layer.ScreenCustomizationLayerHandler/]: [FANCYMENU] ScreenCustomizationLayer registered: net.neoforged.neoforge.client.gui.ModListScreen
[04Jul2024 20:43:02.405] [Render thread/ERROR] [net.minecraft.util.thread.BlockableEventLoop/FATAL]: Error executing task on Client
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "net.p3pp3rf1y.sophisticatedcore.client.gui.StorageScreenBase.getMenu()" because "this.storageScreen" is null
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:146) ~[client-1.20.4-20231207.154220-srg.jar%23697!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[client-1.20.4-20231207.154220-srg.jar%23697!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:120) ~[client-1.20.4-20231207.154220-srg.jar%23697!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:109) ~[client-1.20.4-20231207.154220-srg.jar%23697!/:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1223) ~[client-1.20.4-20231207.154220-srg.jar%23697!/:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:818) ~[client-1.20.4-20231207.154220-srg.jar%23697!/:?]
	at net.minecraft.client.main.Main.main(Main.java:244) ~[neoforge-20.4.237.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-2.0.17.jar:2.0]
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-2.0.17.jar:2.0]
	at net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-2.0.17.jar:2.0]
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-2.0.17.jar:2.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.p3pp3rf1y.sophisticatedcore.client.gui.StorageScreenBase.getMenu()" because "this.storageScreen" is null
	at net.p3pp3rf1y.sophisticatedcore.compat.craftingtweaks.CraftingUpgradeTweakUIPart.onCraftingSlotsDisplayed(CraftingUpgradeTweakUIPart.java:66) ~[sophisticatedcore-1.20.4-0.6.21.608.jar%23651!/:1.20.4-0.6.21.608]
	at net.p3pp3rf1y.sophisticatedcore.upgrades.crafting.CraftingUpgradeTab.moveSlotsToTab(CraftingUpgradeTab.java:254) ~[sophisticatedcore-1.20.4-0.6.21.608.jar%23651!/:1.20.4-0.6.21.608]
	at net.p3pp3rf1y.sophisticatedcore.client.gui.UpgradeSettingsTab.onTabOpen(UpgradeSettingsTab.java:33) ~[sophisticatedcore-1.20.4-0.6.21.608.jar%23651!/:1.20.4-0.6.21.608]
	at net.p3pp3rf1y.sophisticatedcore.client.gui.SettingsTabBase.setOpen(SettingsTabBase.java:110) ~[sophisticatedcore-1.20.4-0.6.21.608.jar%23651!/:1.20.4-0.6.21.608]
	at net.p3pp3rf1y.sophisticatedcore.client.gui.UpgradeSettingsTab.setOpen(UpgradeSettingsTab.java:45) ~[sophisticatedcore-1.20.4-0.6.21.608.jar%23651!/:1.20.4-0.6.21.608]
	at net.p3pp3rf1y.sophisticatedcore.client.gui.UpgradeSettingsTab.onAfterInit(UpgradeSettingsTab.java:50) ~[sophisticatedcore-1.20.4-0.6.21.608.jar%23651!/:1.20.4-0.6.21.608]
	at net.p3pp3rf1y.sophisticatedcore.client.gui.UpgradeSettingsTabControl.<init>(UpgradeSettingsTabControl.java:16) ~[sophisticatedcore-1.20.4-0.6.21.608.jar%23651!/:1.20.4-0.6.21.608]
	at net.p3pp3rf1y.sophisticatedcore.client.gui.StorageScreenBase.<init>(StorageScreenBase.java:69) ~[sophisticatedcore-1.20.4-0.6.21.608.jar%23651!/:1.20.4-0.6.21.608]
	at net.p3pp3rf1y.sophisticatedbackpacks.client.gui.BackpackScreen.<init>(BackpackScreen.java:21) ~[sophisticatedbackpacks-1.20.4-3.20.6.1051.jar%23650!/:1.20.4-3.20.6.1051]
	at net.p3pp3rf1y.sophisticatedbackpacks.client.gui.BackpackScreen.constructScreen(BackpackScreen.java:17) ~[sophisticatedbackpacks-1.20.4-3.20.6.1051.jar%23650!/:1.20.4-3.20.6.1051]
	at net.neoforged.neoforge.network.handlers.ClientPayloadHandler.lambda$createMenuScreen$7(ClientPayloadHandler.java:138) ~[neoforge-20.4.237-universal.jar%23698!/:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at net.neoforged.neoforge.network.handlers.ClientPayloadHandler.createMenuScreen(ClientPayloadHandler.java:137) ~[neoforge-20.4.237-universal.jar%23698!/:?]
	at net.neoforged.neoforge.network.handlers.ClientPayloadHandler.lambda$handle$5(ClientPayloadHandler.java:125) ~[neoforge-20.4.237-universal.jar%23698!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[client-1.20.4-20231207.154220-srg.jar%23697!/:?]
	... 24 more
[04Jul2024 20:43:02.420] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: H3kk4 lost connection: Disconnected
[04Jul2024 20:43:02.420] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: H3kk4 left the game
[04Jul2024 20:43:02.453] [Render thread/INFO] [EMI/]: [EMI] Disconnecting from server, EMI data cleared
[04Jul2024 20:43:02.454] [Thread-301/INFO] [EMI/]: [EMI] Clearing data
[04Jul2024 20:43:02.461] [Render thread/INFO] [mezz.jei.neoforge.startup.StartEventObserver/]: JEI StartEventObserver received class net.neoforged.neoforge.client.event.ClientPlayerNetworkEvent$LoggingOut
[04Jul2024 20:43:02.461] [Render thread/INFO] [mezz.jei.neoforge.startup.StartEventObserver/]: JEI StartEventObserver transitioning state from JEI_STARTED to LISTENING
[04Jul2024 20:43:02.462] [Render thread/INFO] [mezz.jei.library.startup.JeiStarter/]: Stopping JEI
[04Jul2024 20:43:02.463] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable...
[04Jul2024 20:43:02.465] [Render thread/INFO] [mezz.jei.neoforge.plugins.neoforge.NeoForgeGuiPlugin/]: Stopping JEI GUI
[04Jul2024 20:43:02.470] [Server thread/INFO] [net.minecraft.server.network.ServerCommonPacketListenerImpl/]: Stopping singleplayer server as player logged out
[04Jul2024 20:43:02.471] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable took 7.143 ms
[04Jul2024 20:43:02.485] [Server thread/INFO] [net.creeperhost.ftbbackups.FTBBackups/]: Shutdown Complete
[04Jul2024 20:43:02.495] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[04Jul2024 20:43:02.496] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[04Jul2024 20:43:02.496] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[04Jul2024 20:43:02.578] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[NeoTech]'/minecraft:overworld
[04Jul2024 20:43:02.663] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[NeoTech]'/minecraft:the_nether
[04Jul2024 20:43:02.668] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[NeoTech]'/minecraft:the_end
[04Jul2024 20:43:02.673] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[NeoTech]'/javd:void
[04Jul2024 20:43:02.678] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[NeoTech]'/undergarden:undergarden
[04Jul2024 20:43:02.684] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[NeoTech]'/ae2:spatial_storage
[04Jul2024 20:43:02.729] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (NeoTech): All chunks are saved
[04Jul2024 20:43:02.729] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[04Jul2024 20:43:02.729] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[04Jul2024 20:43:02.729] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (void): All chunks are saved
[04Jul2024 20:43:02.729] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (undergarden): All chunks are saved
[04Jul2024 20:43:02.729] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (spatial_storage): All chunks are saved
[04Jul2024 20:43:02.729] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage: All dimensions are saved
[04Jul2024 20:43:02.798] [Server thread/INFO] [net.creeperhost.equivalentexchange.EquivalentExchange/]: Cleaning up players alchemical bags
[04Jul2024 20:43:02.798] [Server thread/INFO] [net.creeperhost.equivalentexchange.EquivalentExchange/]: Cleaning up players stored emc
[04Jul2024 20:43:02.798] [Server thread/INFO] [net.creeperhost.equivalentexchange.EquivalentExchange/]: Cleaning up players knowledge
[04Jul2024 20:43:02.809] [Server thread/INFO] [Puzzles Lib/]: Unloading server config for easyanvils
[04Jul2024 20:43:02.812] [Server thread/INFO] [Puzzles Lib/]: Unloading server config for universalbonemeal
[04Jul2024 20:43:02.825] [Server thread/INFO] [Puzzles Lib/]: Unloading server config for hangglider
[04Jul2024 20:43:02.829] [Server thread/INFO] [Puzzles Lib/]: Unloading server config for easymagic
[04Jul2024 20:43:02.830] [Server thread/INFO] [Puzzles Lib/]: Unloading server config for combatnouveau
[04Jul2024 20:43:02.833] [Server thread/INFO] [Puzzles Lib/]: Unloading server config for magnumtorch
[04Jul2024 20:43:02.839] [Render thread/INFO] [ChunkBuilder/]: Stopping worker threads
[04Jul2024 20:43:02.859] [Render thread/INFO] [Entity Texture Features/]: emissive suffixes loaded: {_e}.
[04Jul2024 20:43:02.860] [Render thread/WARN] [net.minecraft.client.multiplayer.ClientCommonPacketListenerImpl/]: Client disconnected with reason: Failed to open a screen with advanced data: java.lang.NullPointerException: Cannot invoke "net.p3pp3rf1y.sophisticatedcore.client.gui.StorageScreenBase.getMenu()" because "this.storageScreen" is null
[04Jul2024 20:43:24.020] [pool-13-thread-1/INFO] [com.sunekaer.sdrp.discord.RPClient/]: Sent state to discord: {"assets":{"small_image":"overworld","small_text":"Overworld","large_image":"logo","large_text":"Pack Logo"},"instance":false,"buttons":[{"label":"Download FTB NeoTech","url":"https://feed-the-beast.com/modpacks/123-ftb-neotech?tab=about"},{"label":"Download the FTB App","url":"https://go.ftb.team/app"}],"timestamps":{"start":1720116198},"state":"In Overworld"}

### Describe the bug

Everything has been working perfectly for a week, but now when i try to open a diamond backpack from sophisticated backpacks, it crashes. I tried to place it on the ground and right click on it to open it in a different way but it doesn't change anything.

### Steps to reproduce

1. Try to open the backpack, whatever the way you do it
2. See the error : Failed to open a screen with advanced data: java.lang.NullPointerException: Cannot invoke "net.p3pp3rf1y.sophisticatedcore.client.gui.StorageScreenBase.getMenu()" because "this.storageScreen" is null

### Expected behaviour

Have access to the backpack inventory

### Screenshots

![image_2024-07-04_205324189](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/78410927/761465d1-9e6f-4765-9c18-d29ac990a8d8)

### Additional information

It worked perfectly earlier in the day, so i don't understand what's going on.

**Comment by Quazaka** [comment]
I can add to this. 
I am playing with a friend of mine, i crafted the backpack for both of us, upgrade to diamond, and placed a crafting upgrade in both. When he tried to open the backpack he crashed and DC'ed from the game. I removed the crafting upgrade and he could then open the backpack and insert it himself and it worked fine.

**Comment by Steampunk00** [comment]
I know this is a bit of a necro but do you have any information or remember how this big was fixed? I'm facing an identical bug in the 1.20 craftoria mod pack so I'm looking for solutions. 
Thanks!

**Comment by GamingGoombah** [comment]
Also been having similar issued for the past few days in craftoria 1.21 
![image](https://github.com/user-attachments/assets/0baef53d-0047-4860-a68d-01604f1c2c80)
Don't know if this will help. It also seems to happen at complete random? I'll be able to play one time for a good few hours before this happens, or maybe it'll randomly happen after 10 minutes.

I know that Craftoria isn't your folks modpack, but seeing how similar the issue is here, I thought that I might aswell ask.

**Comment by DDzwiedziu** [comment]
> Also been having similar issued for the past few days in craftoria 1.21 ![image](https://private-user-images.githubusercontent.com/122757150/377545017-0baef53d-0047-4860-a68d-01604f1c2c80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMjA4NzUsIm5iZiI6MTczMDMyMDU3NSwicGF0aCI6Ii8xMjI3NTcxNTAvMzc3NTQ1MDE3LTBiYWVmNTNkLTAwNDctNDg2MC1hNjhkLTAxNjA0ZjFjMmM4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQyMDM2MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDNmOWRlY2FkMjJlMTBlZmEwMWFhNzA4MzkxNjIwNjU5YTAyZGQ0Y2U5MzJiYzI3OGFjZTE5YmUzNjJlMjc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.teW3Vh9x1El5U3G4XHAd6TPPbfKlyr3kL1w9HfsUTrE) Don't know if this will help. It also seems to happen at complete random? I'll be able to play one time for a good few hours before this happens, or maybe it'll randomly happen after 10 minutes.
> 
> I know that Craftoria isn't your folks modpack, but seeing how similar the issue is here, I thought that I might aswell ask.

I've also had it in Craftoria out of the blue, fixed it by switching NeoForge 21.1.72 to 21.1.73.

**Comment by FusionGecko** [comment]
SOLO IN GAME WORK AROUND: 
Shift Right Click to place backpack on top of a hopper. Items will get pulled out safely. Craft new backpack (sorry).

yes im getting the same crash/forced out of server ( "this.storageScreen" is null ) error message on Craftoria 1.9.0 Neoforge 21.1.79.   I didn't put anything new or weird in the backpack but it WAS soon after i started using the crafting table upgrade more often so maybe it is tied to that like someone else said.

I'll be throwing my old pack in lava.
