### ISSUE TITLE
Server crash when using Camouflage with the Pipe Config Card

### ISSUE THREAD

**Issue by smushis** [FTBTeam/FTB-Modpack-Issues#5535]
### Modpack

FTB NeoTech

### Modpack version

1.5.1

### Has the pack been modified

No

### Log Files

https://pste.ch/siwukijeqi.coffeescript

### Describe the bug

The server is crashing when using camouflage on pipes with the pipe config card from Modern Industrialization.
This issue appeared on Neotech 1.5.

### Steps to reproduce

1. Use Camouflage on any MI pipes.

### Expected behaviour

The pipes should be covered with the camouflage

**Comment by usynelig** [comment]
The server also crashes when using the pipe config card with a shift right click on a block to update the camouflage settings.

**Comment by N8-Yue** [comment]
Have the same issue, this is the following error `[20:32:17] [Server thread/ERROR] [ne.ne.fm.co.as.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
[20:32:17] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.ExceptionInInitializerError: null
        at aztech.modern_industrialization.items.ConfigCardItem.setCamouflage(ConfigCardItem.java:91) ~[Modern-Industrialization-2.0.25-all.jar%23538!/:?] {re:classloading}
        at aztech.modern_industrialization.items.ConfigCardItem.useOn(ConfigCardItem.java:79) ~[Modern-Industrialization-2.0.25-all.jar%23538!/:?] {re:classloading}
        at net.neoforged.neoforge.common.CommonHooks.onPlaceItemIntoWorld(CommonHooks.java:515) ~[neoforge-20.4.237-universal.jar%23631!/:?] {re:mixin,re:classloading,pl:mixin:APP:lootjs.mixins.json:forge.CommonHooksMixin from mod lootjs,pl:mixin:A}
        at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:290) ~[server-1.20.4-20231207.154220-srg.jar%23630!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apothic_enchanting.mixins.json:ItemStackMixin from mod apothic_enchanting,pl:mixin:APP:veinmining.mixins.json:ItemStackMixin from mod veinmining,pl:mixin:APP:mixins.transmog.common.json:ItemStackMixin from mod transmog,pl:mixin:APP:placebo.mixins.json:ItemStackMixin from mod placebo,pl:mixin:APP:apothic_attributes.mixins.json:ItemStackMixin from mod apothic_attributes,pl:mixin:APP:kubejs-common.mixins.json:ItemStackMixin from mod kubejs,pl:mixin:APP:tarotcards.mixins.json:ItemStackMixin from mod tarotcards,pl:mixin:A}
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:363) ~[server-1.20.4-20231207.154220-srg.jar%23630!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1131) ~[server-1.20.4-20231207.154220-srg.jar%23630!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:servercore.common.mixins.json:features.misc.ServerGamePacketListenerImplMixin from mod servercore,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ServerPlayNetHandlerAccess from mod immersiveengineering,pl:mixin:APP:hangglider.common.mixins.json:accessor.ServerGamePacketListenerImplAccessor from mod hangglider,pl:mixin:A}
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:34) ~[server-1.20.4-20231207.154220-srg.jar%23630!/:?] {re:classloading}
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:8) ~[server-1.20.4-20231207.154220-srg.jar%23630!/:?] {re:classloading}
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:24) ~[server-1.20.4-20231207.154220-srg.jar%23630!/:?] {re:classloading}
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.4-20231207.154220-srg.jar%23630!/:?] {re:classloading}
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:146) ~[server-1.20.4-20231207.154220-srg.jar%23630!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[server-1.20.4-20231207.154220-srg.jar%23630!/:?] {re:mixin,re:computing_frames,re:classloading}
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:810) ~[server-1.20.4-20231207.154220-srg.jar%23630!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:162) ~[server-1.20.4-20231207.154220-srg.jar%23630!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:120) ~[server-1.20.4-20231207.154220-srg.jar%23630!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:793) ~[server-1.20.4-20231207.154220-srg.jar%23630!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:787) ~[server-1.20.4-20231207.154220-srg.jar%23630!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:130) ~[server-1.20.4-20231207.154220-srg.jar%23630!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:774) ~[server-1.20.4-20231207.154220-srg.jar%23630!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:704) ~[server-1.20.4-20231207.154220-srg.jar%23630!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:255) ~[server-1.20.4-20231207.154220-srg.jar%23630!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:1583) ~[?:?] {re:mixin}
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
        at net.neoforged.fml.common.asm.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[loader-2.0.17.jar%2362!/:2.0] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:169) ~[securejarhandler-2.1.24.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:275) ~[securejarhandler-2.1.24.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:288) ~[securejarhandler-2.1.24.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:275) ~[securejarhandler-2.1.24.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:191) ~[securejarhandler-2.1.24.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
        at net.swedz.mi_tweaks.compat.mi.MITweaksMIHookListener.tooltips(MITweaksMIHookListener.java:33) ~[mi-tweaks-1.0.1+1.20.4.jar%23534!/:?] {re:classloading}
        at net.swedz.tesseract.neoforge.compat.mi.hook.MIHooks.triggerHookListeners(MIHooks.java:96) ~[tesseract-neoforge-1.0.4+1.20.4.jar%23601!/:?] {re:classloading,re:mixin}
        at aztech.modern_industrialization.MITooltips.handler$bfi001$tesseract_api$clinit(MITooltips.java:578) ~[Modern-Industrialization-2.0.25-all.jar%23538!/:?] {re:mixin,re:classloading,pl:mixin:APP:tesseract_api_mi.mixins.json:hook.listener.TooltipsHookMixin from mod tesseract_api,pl:mixin:A}
        at aztech.modern_industrialization.MITooltips.<clinit>(MITooltips.java:438) ~[Modern-Industrialization-2.0.25-all.jar%23538!/:?] {re:mixin,re:classloading,pl:mixin:APP:tesseract_api_mi.mixins.json:hook.listener.TooltipsHookMixin from mod tesseract_api,pl:mixin:A}
        ... 22 more`
