### ISSUE TITLE
Keybinds Reset

### ISSUE THREAD

**Issue by Blugypsy** [FTBTeam/FTB-Modpack-Issues#5631]
### Modpack

FTB Unstable 1.21

### Modpack version

1.0.1

### Has the pack been modified

No

### Describe the bug

Keybinds reset every time i close and reopen the pack 

### Steps to reproduce

Launch Pack 
Load into world
change keybind 
close the game
reopen game 

### Expected behaviour

keybind doesnt reset

**Comment by Blugypsy** [comment]
is this issue something that can be fixed?

**Comment by ArtpokeBr** [comment]
Not sure if this was something with a mod in specific, but so far I'am not being affected by this issue here in dev

**Comment by ArtpokeBr** [comment]
I will mark it as fixed then, but please, make sure to reopen it if still persists after the next update.

**Comment by Zeropainter2386** [comment]
This issue is still found present in version 1.2.0

**Comment by rfields99** [comment]
This is still happening for me as well in version 1.3.0 
It is very annoying and I cannot find a solution

**Comment by g1xb17** [comment]
Still an issue obviously. What seems to be the case here is on startup the configuration is reset.

```
[06Apr2025 19:59:01.621] [Render thread/INFO] [defaultoptions/]: Loaded default options for keymappings
[06Apr2025 19:59:01.622] [Render thread/INFO] [defaultoptions/]: Found 0 default keys and 0 known keys
[06Apr2025 19:59:01.622] [Render thread/ERROR] [net.minecraft.client.Options/]: Failed to save options
java.io.FileNotFoundException: C:\Users\g1xb17\AppData\Local\.ftba\instances\ftb unstable 121\options.txt (Access is denied)
	at java.base/java.io.FileOutputStream.open0(Native Method) ~[?:?]
	at java.base/java.io.FileOutputStream.open(Unknown Source) ~[?:?]
	at java.base/java.io.FileOutputStream.<init>(Unknown Source) ~[?:?]
	at java.base/java.io.FileOutputStream.<init>(Unknown Source) ~[?:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Options.save(Options.java:1412) ~[client-1.21-20240613.152323-srg.jar%23427!/:?]
	at TRANSFORMER/defaultoptions@21.1.1/net.blay09.mods.defaultoptions.keys.KeyMappingDefaultsHandler.saveCurrentOptions(KeyMappingDefaultsHandler.java:47) ~[defaultoptions-neoforge-1.21.1-21.1.1.jar%23479!/:21.1.1]
	at TRANSFORMER/defaultoptions@21.1.1/net.blay09.mods.defaultoptions.keys.KeyMappingDefaultsHandler.loadDefaults(KeyMappingDefaultsHandler.java:142) ~[defaultoptions-neoforge-1.21.1-21.1.1.jar%23479!/:21.1.1]
	at TRANSFORMER/defaultoptions@21.1.1/net.blay09.mods.defaultoptions.DefaultOptionsInitializer.loadDefaults(DefaultOptionsInitializer.java:30) ~[defaultoptions-neoforge-1.21.1-21.1.1.jar%23479!/:21.1.1]
	at TRANSFORMER/defaultoptions@21.1.1/net.blay09.mods.defaultoptions.DefaultOptionsInitializer.postLoad(DefaultOptionsInitializer.java:22) ~[defaultoptions-neoforge-1.21.1-21.1.1.jar%23479!/:21.1.1]
	at TRANSFORMER/balm@21.0.20/net.blay09.mods.balm.neoforge.event.NeoForgeBalmEvents.fireEventHandler(NeoForgeBalmEvents.java:50) ~[balm-neoforge-1.21.1-21.0.20.jar%23448!/:21.0.20]
	at TRANSFORMER/balm@21.0.20/net.blay09.mods.balm.neoforge.event.NeoForgeBalmEvents.lambda$fireEventHandlers$0(NeoForgeBalmEvents.java:44) ~[balm-neoforge-1.21.1-21.0.20.jar%23448!/:21.0.20]
	at java.base/java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at TRANSFORMER/balm@21.0.20/net.blay09.mods.balm.neoforge.event.NeoForgeBalmEvents.fireEventHandlers(NeoForgeBalmEvents.java:44) ~[balm-neoforge-1.21.1-21.0.20.jar%23448!/:21.0.20]
	at TRANSFORMER/balm@21.0.20/net.blay09.mods.balm.neoforge.event.NeoForgeBalmEvents.fireEvent(NeoForgeBalmEvents.java:76) ~[balm-neoforge-1.21.1-21.0.20.jar%23448!/:21.0.20]
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.handler$zeo000$balm$run(Minecraft.java:6499) ~[client-1.21-20240613.152323-srg.jar%23427!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.run(Minecraft.java) ~[client-1.21-20240613.152323-srg.jar%23427!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21-20240613.152323-srg.jar%23427!/:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.23.jar%23122!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.23.jar%23122!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.23.jar%23122!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.23.jar%23122!/:4.0]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23104!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23104!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23104!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23104!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23104!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23104!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23104!/:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?]
```

So, For people wondering what they can do to fix this, decide what your keys are and then go to options.txt file in the "ftb unstable 121" folder and set it to read only in windows

![Image](https://github.com/user-attachments/assets/2ff0b1bf-f804-4512-987b-0253d632b15a)

this will temporary address this terrible problem. I also would like to note that turning read-only off on the options.txt file will most likely allow you to adjust the configuration later. But, after you should probably turn it back on. I didn't try turning it on and off while the game is running but, It doesnt matter a whole lot because this is already inconvenient and this is better than nothing.
