### ISSUE TITLE
F.A.M 1.3.0 Hard Crash

### ISSUE THREAD

**Issue by Cruors** [FTBTeam/FTB-Modpack-Issues#5658]
### Modpack

FTB Presents F.A.M

### Modpack version

1.3.0

### Has the pack been modified

No

### Log Files

[hs_err_pid32180.log](https://github.com/user-attachments/files/16694430/hs_err_pid32180.log)
[hs_err_pid26728.log](https://github.com/user-attachments/files/16694432/hs_err_pid26728.log)

### Describe the bug

The game hard crashes, opened up to Lan and it hard crashed immediately, the 2nd time we loaded in and walked abit then I hard crashed again.

### Steps to reproduce

it just happened by itself randomly after a short wait

### Expected behaviour

The game to work?

### Additional information

haven't tried older versions on new laptop but the older versions did work on my old laptop.

**Comment by Gaz492** [comment]
Could you try disabling the mod embeddium and seeing if this issue continues to happen?

**Comment by Cruors** [comment]
Game wont launch anymore says we need Rubidium because oculus failed to load says it requires it for good performance

**Comment by Cruors** [comment]
tried with Rubidium and got instant crash the second my wife tries and joins 
[hs_err_pid23716.log](https://github.com/user-attachments/files/16786998/hs_err_pid23716.log)

**Comment by Cruors** [comment]
Bump

**Comment by Cruors** [comment]
any help?

**Comment by Cruors** [comment]
@Gaz492

**Comment by Gaz492** [comment]
Sorry, If you try it without both rubidium/embedium and occulus does the issue still happen?

If it does would you be able to post a new log?

**Comment by Cruors** [comment]
sorry about the late reply @Gaz492 i got sick and just recovered

fails to start at all, not sure where to find log for that.

Caused by: java.lang.UnsupportedOperationException: A mod tried to access the state neighbor table directly. Please report this at https://github.com/malte0811/FerriteCore/issues. As a temporary workaround you can enable "populateNeighborTable" in the FerriteCore config
	at TRANSFORMER/ferritecore@5.0.3/malte0811.ferritecore.fastmap.table.CrashNeighborTable.crashOnAccess(CrashNeighborTable.java:101)
	at TRANSFORMER/ferritecore@5.0.3/malte0811.ferritecore.fastmap.table.CrashNeighborTable.rowKeySet(CrashNeighborTable.java:77)
	at TRANSFORMER/canary@0.3.3/com.abdelaziz.canary.common.state.FastImmutableTable.<init>(FastImmutableTable.java:36)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.state.StateHolder.handler$bdk000$postCreateWithTable(StateHolder.java:531)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.state.StateHolder.m_61133_(StateHolder.java:1052)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.state.StateDefinition.<init>(StateDefinition.java:68)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.state.StateDefinition$Builder.m_61101_(StateDefinition.java:157)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.Block.<init>(Block.java:176)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.AirBlock.<init>(AirBlock.java:12)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:39)
	... 19 more

**Comment by Cruors** [comment]
@Gaz492

**Comment by Gaz492** [comment]
Sorry for the delay, could you try disabling `populateNeighbourTable` again then also disable the rubidium, embeddium, canary and oculus mod then check to see if the issue still happens?
