### ISSUE TITLE
EMC Value on Server only saving on a cron and doesn't save before logging out

### ISSUE THREAD

**Issue by chrisjgray** [FTBTeam/FTB-Modpack-Issues#5659]
### Modpack

FTB NeoTech

### Modpack version

1.7.0

### Has the pack been modified

No

### Log Files

[21Aug2024 13:40:07.127] [Server thread/INFO] [net.creeperhost.equivalentexchange.EquivalentExchange/]: Loading bags for player FritzMeistr
[21Aug2024 13:40:07.129] [Server thread/INFO] [net.creeperhost.equivalentexchange.EquivalentExchange/]: Loading saved emc for team c08d58ca-34ec-4ae7-a4b4-8bf951522e97
[21Aug2024 13:40:07.134] [Server thread/INFO] [net.creeperhost.equivalentexchange.EquivalentExchange/]: Loaded value 65934.0 for player FritzMeistr
[21Aug2024 13:40:07.134] [Server thread/INFO] [net.creeperhost.equivalentexchange.EquivalentExchange/]: Loading knowledge for team c08d58ca-34ec-4ae7-a4b4-8bf951522e97
[21Aug2024 13:40:07.208] [Server thread/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: Tried to send supermartijn642configlib:sync_packet packet to a client that does not support it. Not sending the packet.
[21Aug2024 13:40:07.208] [Server thread/WARN] [net.neoforged.neoforge.network.registration.NetworkRegistry/]: Tried to send supermartijn642configlib:sync_packet packet to a client that does not support it. Not sending the packet.
[21Aug2024 13:40:07.245] [Server thread/DEBUG] [snownee.jade.Jade/]: Syncing config to FritzMeistr (2a59e0b2-81b2-4482-a025-02c02428a2c1)
[21Aug2024 13:40:07.251] [Server thread/INFO] [actuallyadditions/]: Sending Player Data to player literal{FritzMeistr} with UUID 2a59e0b2-81b2-4482-a025-02c02428a2c1.
[21Aug2024 13:40:07.297] [ForkJoinPool.commonPool-worker-1/INFO] [net.creeperhost.equivalentexchange.EquivalentExchange/]: Loading alchemicalBagInventory inventory for FritzMeistr
[21Aug2024 13:40:07.627] [Server thread/DEBUG] [mixin/]: Mixing features.breeding_cap.tasks.AnimalMakeLoveMixin from servercore.common.mixins.json into net.minecraft.world.entity.ai.behavior.AnimalMakeLove
[21Aug2024 13:40:07.628] [Server thread/DEBUG] [mixin/]: servercore.common.mixins.json:features.breeding_cap.tasks.AnimalMakeLoveMixin from mod servercore: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_16 supports class version 60)
[21Aug2024 13:40:08.239] [Server thread/DEBUG] [Curios API/]: Loaded top.theillusivec4.curios.platform.NeoForgeCurios@1339204c for service interface top.theillusivec4.curios.platform.services.ICuriosPlatform
[21Aug2024 13:40:08.284] [Server thread/DEBUG] [shiroroku.tarotcards.TarotCards/]: Adding Tarot Modifier: tarotcards:the_sun - AttributeModifier{amount=0.25, operation=MULTIPLY_BASE, name='Tarot Card', id=1d6d9271-51a6-3d38-abce-fbe1d65252da}
[21Aug2024 13:40:09.241] [Server thread/DEBUG] [ModernFix/]: Using cached upgraded version of terralith:underground/old_refinery
[21Aug2024 13:40:24.155] [Server thread/DEBUG] [harvest_with_ease/]: Loaded it.crystalnest.harvest_with_ease.platform.NeoForgePlatformHelper@29266c1e for service interface it.crystalnest.harvest_with_ease.platform.services.PlatformHelper
[21Aug2024 13:40:24.158] [Server thread/DEBUG] [harvest_with_ease/]: Loaded it.crystalnest.harvest_with_ease.api.event.NeoForgeEventHelper@340fe85b for service interface it.crystalnest.harvest_with_ease.platform.services.EventHelper
[21Aug2024 13:40:24.158] [Server thread/DEBUG] [harvest_with_ease/]: Loaded it.crystalnest.harvest_with_ease.platform.NeoForgeHarvestHelper@40434092 for service interface it.crystalnest.harvest_with_ease.platform.services.HarvestHelper
[21Aug2024 13:40:34.825] [ftbbackups2_QuartzSchedulerThread/DEBUG] [net.creeperhost.ftbbackups.repack.org.quartz.core.QuartzSchedulerThread/]: batch acquisition of 0 triggers
[21Aug2024 13:41:02.999] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: FritzMeistr lost connection: Disconnected
[21Aug2024 13:41:02.999] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: FritzMeistr left the game
[21Aug2024 13:41:04.354] [ftbbackups2_QuartzSchedulerThread/DEBUG] [net.creeperhost.ftbbackups.repack.org.quartz.core.QuartzSchedulerThread/]: batch acquisition of 0 triggers
[21Aug2024 13:41:21.887] [User Authenticator #2/INFO] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: UUID of player FritzMeistr is 2a59e0b2-81b2-4482-a025-02c02428a2c1
[21Aug2024 13:41:21.906] [Netty Server IO #3/DEBUG] [net.neoforged.neoforge.network.filters.NetworkFilters/]: Injected net.neoforged.neoforge.network.filters.GenericPacketSplitter@54b73261 into net.minecraft.network.Connection@11b5a693
[21Aug2024 13:41:22.212] [Server thread/INFO] [net.minecraft.server.players.PlayerList/]: FritzMeistr[/[2601:647:8400:8c20:5d3d:43bc:be3a:7592]:62332] logged in with entity id 259 at (-351.1506724892083, 144.0, 1039.3470401922987)
[21Aug2024 13:41:22.213] [Server thread/DEBUG] [ModernFix/]: Sending ID correction packet to client with 89 classes
[21Aug2024 13:41:22.236] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: FritzMeistr joined the game
[21Aug2024 13:41:22.250] [Server thread/DEBUG] [FTB Teams/]: player 2a59e0b2-81b2-4482-a025-02c02428a2c1 logged in, player team = FritzMeistr#2a59e0b2
[21Aug2024 13:41:22.250] [Server thread/DEBUG] [FTB Teams/]: syncing player team data, all = false
[21Aug2024 13:41:22.264] [Server thread/DEBUG] [FTB Teams/]: updating team presence
[21Aug2024 13:41:22.264] [Server thread/DEBUG] [FTB Teams/]: sending team login event for 2a59e0b2-81b2-4482-a025-02c02428a2c1...
[21Aug2024 13:41:22.264] [Server thread/DEBUG] [FTB Chunks/]: handling player team login: player = 2a59e0b2-81b2-4482-a025-02c02428a2c1, team = c08d58ca-34ec-4ae7-a4b4-8bf951522e97
[21Aug2024 13:41:22.264] [Server thread/DEBUG] [FTB Chunks/]: server config and team data sent to 2a59e0b2-81b2-4482-a025-02c02428a2c1
[21Aug2024 13:41:22.264] [Server thread/DEBUG] [FTB Chunks/]: claimed chunk data sent to 2a59e0b2-81b2-4482-a025-02c02428a2c1
[21Aug2024 13:41:22.264] [Server thread/DEBUG] [FTB Chunks/]: visible player list sent to 2a59e0b2-81b2-4482-a025-02c02428a2c1
[21Aug2024 13:41:22.269] [Server thread/DEBUG] [FTB Quests/]: Wrote 168002 bytes, 2230 objects
[21Aug2024 13:41:22.273] [Server thread/DEBUG] [FTB Teams/]: team login event for 2a59e0b2-81b2-4482-a025-02c02428a2c1 sent
[21Aug2024 13:41:22.274] [Server thread/INFO] [net.creeperhost.equivalentexchange.EquivalentExchange/]: Loading bags for player FritzMeistr
[21Aug2024 13:41:22.274] [Server thread/INFO] [net.creeperhost.equivalentexchange.EquivalentExchange/]: Loading saved emc for team c08d58ca-34ec-4ae7-a4b4-8bf951522e97
[21Aug2024 13:41:22.274] [Server thread/INFO] [net.creeperhost.equivalentexchange.EquivalentExchange/]: Loaded value 65934.0 for player FritzMeistr

### Describe the bug

When I store items with EMC value in my Transmutation Table, I see the values get updated and can utilize the EMC to get items out of the table. When I logout and log back in, the EMC value resets back to a static value every time, 65934.0. 

### Steps to reproduce

1. Login
2. Store Emerald in EMC Table
3. Logout
4. Login (see reset value of 65934 value loaded in logs)

### Expected behaviour

Keep prior EMC value stored.

### Screenshots

![after](https://github.com/user-attachments/assets/def8e06d-3e72-4ad9-bebd-f1064899201a)
![before](https://github.com/user-attachments/assets/157ea82c-0101-4824-b8b8-7d093ff9119e)

### Additional information

Not sure how relevant, but I do see the emc value stored within the NBT value in ftbteams\emc\<id>_emc.dat

**Comment by chrisjgray** [comment]
I also get this error when adding a new item to the EMC table:
`[14:07:38] [Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundContainerClickPacket@4616aa56, suppressing error
net.minecraft.ReportedException: Container click
        at net.minecraft.world.inventory.AbstractContainerMenu.clicked(AbstractContainerMenu.java:299) ~[server-1.20.4-20231207.154220-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ContainerAccess from mod immersiveengineering,pl:mixin:A}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:1617) ~[server-1.20.4-20231207.154220-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:servercore.common.mixins.json:features.misc.ServerGamePacketListenerImplMixin from mod servercore,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ServerPlayNetHandlerAccess from mod immersiveengineering,pl:mixin:APP:hangglider.common.mixins.json:accessor.ServerGamePacketListenerImplAccessor from mod hangglider,pl:mixin:A}
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[server-1.20.4-20231207.154220-srg.jar%23692!/:?] {re:classloading}
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[server-1.20.4-20231207.154220-srg.jar%23692!/:?] {re:classloading}
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:24) ~[server-1.20.4-20231207.154220-srg.jar%23692!/:?] {re:classloading}
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.4-20231207.154220-srg.jar%23692!/:?] {re:classloading}
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:146) ~[server-1.20.4-20231207.154220-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[server-1.20.4-20231207.154220-srg.jar%23692!/:?] {re:mixin,re:computing_frames,re:classloading}
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:810) ~[server-1.20.4-20231207.154220-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:162) ~[server-1.20.4-20231207.154220-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:120) ~[server-1.20.4-20231207.154220-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:793) ~[server-1.20.4-20231207.154220-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:787) ~[server-1.20.4-20231207.154220-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:130) ~[server-1.20.4-20231207.154220-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:774) ~[server-1.20.4-20231207.154220-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:704) ~[server-1.20.4-20231207.154220-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:255) ~[server-1.20.4-20231207.154220-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at java.lang.Thread.run(Unknown Source) ~[?:?] {re:mixin}
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.ServerPlayer.getDisplayName()" because "serverPlayer" is null
        at net.creeperhost.equivalentexchange.compat.CompatHandler.lambda$init$4(CompatHandler.java:64) ~[equivalentexchange-1.20.4-1.0.11-neoforge.jar%23494!/:?] {re:classloading}
        at java.util.HashMap$KeySet.forEach(Unknown Source) ~[?:?] {}
        at java.util.Collections$UnmodifiableCollection.forEach(Unknown Source) ~[?:?] {}
        at net.creeperhost.equivalentexchange.compat.CompatHandler.lambda$init$5(CompatHandler.java:61) ~[equivalentexchange-1.20.4-1.0.11-neoforge.jar%23494!/:?] {re:classloading}
        at net.creeperhost.equivalentexchange.compat.teams.TeamsKnowledgeHandler.addKnowledge(TeamsKnowledgeHandler.java:92) ~[equivalentexchange-1.20.4-1.0.11-neoforge.jar%23494!/:?] {re:classloading}
        at net.creeperhost.equivalentexchange.inventory.TransmutationInventory.setItem(TransmutationInventory.java:144) ~[equivalentexchange-1.20.4-1.0.11-neoforge.jar%23494!/:?] {re:classloading}
        at net.minecraft.world.inventory.Slot.set(Slot.java:66) ~[server-1.20.4-20231207.154220-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.neoforge.mixins.json:SlotAccessor from mod balm,pl:mixin:A}
        at net.minecraft.world.inventory.Slot.setByPlayer(Slot.java:62) ~[server-1.20.4-20231207.154220-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.neoforge.mixins.json:SlotAccessor from mod balm,pl:mixin:A}
        at net.minecraft.world.inventory.Slot.setByPlayer(Slot.java:58) ~[server-1.20.4-20231207.154220-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.neoforge.mixins.json:SlotAccessor from mod balm,pl:mixin:A}
        at net.minecraft.world.inventory.Slot.safeInsert(Slot.java:166) ~[server-1.20.4-20231207.154220-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.neoforge.mixins.json:SlotAccessor from mod balm,pl:mixin:A}
        at net.minecraft.world.inventory.AbstractContainerMenu.doClick(AbstractContainerMenu.java:411) ~[server-1.20.4-20231207.154220-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ContainerAccess from mod immersiveengineering,pl:mixin:A}
        at net.minecraft.world.inventory.AbstractContainerMenu.doClick(AbstractContainerMenu.java:334) ~[server-1.20.4-20231207.154220-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ContainerAccess from mod immersiveengineering,pl:mixin:A}
        at net.minecraft.world.inventory.AbstractContainerMenu.clicked(AbstractContainerMenu.java:289) ~[server-1.20.4-20231207.154220-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ContainerAccess from mod immersiveengineering,pl:mixin:A}
        ... 17 more`

**Comment by chrisjgray** [comment]
I can't tell when it triggers but I can only get it to keep if I monitor the server logs and wait for this event to occur in the logs:
`[21Aug2024 14:08:41.542] [Server thread/INFO] [net.creeperhost.equivalentexchange.EquivalentExchange/]: Saving bag inventory for FritzMeistr
[21Aug2024 14:08:41.544] [Server thread/INFO] [net.creeperhost.equivalentexchange.EquivalentExchange/]: Saving stored emc for team c08d58ca-34ec-4ae7-a4b4-8bf951522e97
[21Aug2024 14:08:41.545] [Server thread/INFO] [net.creeperhost.equivalentexchange.EquivalentExchange/]: Saving value 15800.0 to .\world\.\ftbteams\emc\c08d58ca-34ec-4ae7-a4b4-8bf951522e97_emc.dat
[21Aug2024 14:08:41.545] [Server thread/INFO] [net.creeperhost.equivalentexchange.EquivalentExchange/]: Saving knowledge for team c08d58ca-34ec-4ae7-a4b4-8bf951522e97
[21Aug2024 14:08:41.546] [Server thread/INFO] [net.creeperhost.equivalentexchange.EquivalentExchange/]: Saving bag inventory for FritzMeistr`

Otherwise I can buy/sell whatever, and it won't save the values.
