### ISSUE TITLE
[Bug]: java.lang.NullPointerException: KubeJS has not been initialized, this won't happen unless some OTHER mod failed to load first! Check your latest.log!

### ISSUE THREAD

**Issue by RoughCactus69** [FTBTeam/FTB-Modpack-Issues#567]
### Modpack

OceanBlock

### Modpack version

1.11.0

### Log Files

at java.util.Objects.requireNonNull([Objects.java:228](https://Objects.java:228)) \~\[?:1.8.0\_51\] {}

at dev.latvian.kubejs.script.data.KubeJSResourcePack.<init>([KubeJSResourcePack.java:45](https://KubeJSResourcePack.java:45)) \~\[?:1605.3.19-build.229\] {re:mixin,re:classloading}

at dev.latvian.kubejs.client.KubeJSClientResourcePack.<init>([KubeJSClientResourcePack.java:25](https://KubeJSClientResourcePack.java:25)) \~\[?:1605.3.19-build.229\] {re:mixin,re:classloading}

at dev.latvian.kubejs.client.KubeJSClientResourcePack.inject([KubeJSClientResourcePack.java:20](https://KubeJSClientResourcePack.java:20)) \~\[?:1605.3.19-build.229\] {re:mixin,re:classloading}

at net.minecraft.client.Minecraft.redirect$ban000$loadPacksKJS([Minecraft.java:3521](https://Minecraft.java:3521)) \~\[?:?\] {re:mixin,pl:accesstransformer:B,xf:fml:traylauncher:loadingHookCoremod,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:traylauncher:loadingHookCoremod,pl:mixin:A,pl:runtimedistcleaner:A}

at net.minecraft.client.Minecraft.<init>([Minecraft.java:502](https://Minecraft.java:502)) \[?:?\] {re:mixin,pl:accesstransformer:B,xf:fml:traylauncher:loadingHookCoremod,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:traylauncher:loadingHookCoremod,pl:mixin:A,pl:runtimedistcleaner:A}

at net.minecraft.client.main.Main.main([Main.java:149](https://Main.java:149)) \[?:?\] {re:classloading,pl:runtimedistcleaner:A}

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) \~\[?:1.8.0\_51\] {}

at sun.reflect.NativeMethodAccessorImpl.invoke([NativeMethodAccessorImpl.java:62](https://NativeMethodAccessorImpl.java:62)) \~\[?:1.8.0\_51\] {}

at sun.reflect.DelegatingMethodAccessorImpl.invoke([DelegatingMethodAccessorImpl.java:43](https://DelegatingMethodAccessorImpl.java:43)) \~\[?:1.8.0\_51\] {}

at java.lang.reflect.Method.invoke([Method.java:497](https://Method.java:497)) \~\[?:1.8.0\_51\] {}

at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0([FMLClientLaunchProvider.java:51](https://FMLClientLaunchProvider.java:51)) \[forge-1.16.5-36.2.20.jar:36.2\] {}

at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$509/1901272535.call(Unknown Source) \[forge-1.16.5-36.2.20.jar:36.2\] {}

at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch([LaunchServiceHandlerDecorator.java:37](https://LaunchServiceHandlerDecorator.java:37)) \[modlauncher-8.0.9.jar:?\] {}

at cpw.mods.modlauncher.LaunchServiceHandler.launch([LaunchServiceHandler.java:54](https://LaunchServiceHandler.java:54)) \[modlauncher-8.0.9.jar:?\] {}

at cpw.mods.modlauncher.LaunchServiceHandler.launch([LaunchServiceHandler.java:72](https://LaunchServiceHandler.java:72)) \[modlauncher-8.0.9.jar:?\] {}

at [cpw.mods.modlauncher.Launcher.run](https://cpw.mods.modlauncher.Launcher.run)([Launcher.java:82](https://Launcher.java:82)) \[modlauncher-8.0.9.jar:?\] {}

### Describe the bug

Not exactly sure what the issue is, but I see a few other people have had this issue online.

### Steps to reproduce

Not sure.

### Expected behaviour

Not sure.

**Comment by RoughCactus69** [comment]
This was my girlfriend's issue, but I went ahead and posted it for her. Not sure how to fix it.

**Comment by Raidobw2** [comment]
Hi, sorry for the late reply, that looks like an installation problem. One of the files is probably missing/corrupted or empty.
The first thing to do would be to reinstall the modpack:
- First, delete the `.localCache` folder in the instances folder.
- Second, reinstall the modpack.

If that fails still, you could copy-paste your files to her computer with a USB key or a method of your choice.
Simply get those folders from your game:
`config`, `mods`, `kubejs`. The last one is the most important in this current case.
To get those folders on the FTB App, see the pictures below and click where the Hand icon is located:
![image](https://user-images.githubusercontent.com/17010632/150263107-2804ae29-283d-4302-af09-c302574c6e69.png)

![image](https://user-images.githubusercontent.com/17010632/150263124-e6cd54e8-a0c8-493e-baca-e7acac86e1dd.png)

![image](https://user-images.githubusercontent.com/17010632/150263127-fcf3e050-7a62-457e-97b0-ce7d635d9326.png)

![image](https://user-images.githubusercontent.com/17010632/150263137-c572046f-b13b-490a-8923-2541ab8a026f.png)

Do the same thing with her computer, where instead of copying the files you will paste them with overwrite.
Let me know if it persists and feel free to bring me more information, I have other tricks to get that working as well.
