### ISSUE TITLE
FTB Skies Expert generates client side null pointers continuously after 20 hours of play.

### ISSUE THREAD

**Issue by SyrusCan** [FTBTeam/FTB-Modpack-Issues#5686]
### Modpack

FTB Skies Expert

### Modpack version

1.9.0

### Has the pack been modified

No

### Describe the bug

Around 20 hour into the pack I start getting flooded with client errors that make the pack unplayable (serious block lag). I reset my player on the server after this happened the first time, and now re-occurring after another 20 hours of play.
 This error repeats several times per second:
 `[27Aug2024 13:53:04.595] [Render thread/ERROR] [net.minecraft.util.thread.BlockableEventLoop/FATAL]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.state.BlockState.m_60734_()" because "p_46606_" is null
	at net.minecraft.world.level.Level.m_6933_(MixinLevel.java:198) ~[client-1.19.2-20220805.130853-srg.jar%23859!/:?]
	at net.minecraft.client.multiplayer.ClientLevel.m_233653_(ClientLevel.java:134) ~[client-1.19.2-20220805.130853-srg.jar%23859!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_205522_(ClientPacketListener.java:635) ~[client-1.19.2-20220805.130853-srg.jar%23859!/:?]
	at net.minecraft.network.protocol.game.ClientboundSectionBlocksUpdatePacket.m_132992_(ClientboundSectionBlocksUpdatePacket.java:72) ~[client-1.19.2-20220805.130853-srg.jar%23859!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5771_(ClientPacketListener.java:634) ~[client-1.19.2-20220805.130853-srg.jar%23859!/:?]
	at net.minecraft.network.protocol.game.ClientboundSectionBlocksUpdatePacket.m_5797_(ClientboundSectionBlocksUpdatePacket.java:64) ~[client-1.19.2-20220805.130853-srg.jar%23859!/:?]
	at net.minecraft.network.protocol.game.ClientboundSectionBlocksUpdatePacket.m_5797_(ClientboundSectionBlocksUpdatePacket.java:14) ~[client-1.19.2-20220805.130853-srg.jar%23859!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.19.2-20220805.130853-srg.jar%23859!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23859!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23859!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23859!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.19.2-20220805.130853-srg.jar%23859!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1072) ~[client-1.19.2-20220805.130853-srg.jar%23859!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23859!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23859!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23859!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.4.2.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]`

### Steps to reproduce

Play 20 hours and advance in the pack?

### Expected behaviour

No null pointer exceptions and ability to play.

### Screenshots

![image](https://github.com/user-attachments/assets/88fad59f-f567-4c23-8596-845c3074b2f6)

**Comment by Gaz492** [comment]
Would you be able to send us the full debug.log from the logs folder (https://docs.feed-the-beast.com/docs/app/Instances/instance-logs) and also upload your world so we can look into this?

Unfortunately the log section you provided doesnt provide much information about whats causing it.

**Comment by SyrusCan** [comment]
[debug.log](https://github.com/user-attachments/files/16786722/debug.log)
https://drive.google.com/file/d/1XS1soL6nW_17CjhjrpP0QqNK0rumsidf/view?usp=sharing

World file is the latest backup of the server. Please let me know if you need any additional info.

**Comment by SyrusCan** [comment]
Another player on Discord was having the same issue and identified this mod as a fix:
https://github.com/TropheusJ/block_limit_fix

It worked for me as well, but did cause some networking issues. I found the fix here:

> For anyone else having this issue, the fix is to go into Windows Control Panel, Networks and Sharing Center, click on "Change adapter settings", select the adapter you have connected to the internet (in my case it was "Ethernet") and click on "properties" and then just uncheck the box labeled "Internet Protocol Version 6 (TCP/IPv6)".

It would be helpful to include the above mod in the core modpack.

Thanks!
