### ISSUE TITLE
Linux Server crashes on startup

### ISSUE THREAD

**Issue by Mojo741m** [FTBTeam/FTB-Modpack-Issues#5750]
### Modpack

FTB Unstable 1.21

### Modpack version

1.2.0

### Launcher

Server

### Has the pack been modified

No

### Log Files

[18:51:10] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.neoforged.fml.ModLoadingException: Loading errors encountered:
        - Health Indicator TXF (healthindicatortxf) has failed to load correctly
          java.lang.ExceptionInInitializerError: null
        - Entity Model Features (entity_model_features) has failed to load correctly
          java.lang.UnsupportedOperationException: Attempting to load a clientside only mod [EMF] on the server, refusing

        at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.ModLoader.waitForFuture(ModLoader.java:281) ~[loader-4.0.23.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.ModLoader.dispatchParallelTask(ModLoader.java:244) ~[loader-4.0.23.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.ModLoader.constructMods(ModLoader.java:152) ~[loader-4.0.23.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:142) ~[loader-4.0.23.jar%2360!/:4.0] {}
        at TRANSFORMER/neoforge@21.0.167/net.neoforged.neoforge.internal.CommonModLoader.begin(CommonModLoader.java:49) ~[neoforge-21.0.167-universal.jar%23352!/:?] {re:classloading}
        at TRANSFORMER/neoforge@21.0.167/net.neoforged.neoforge.server.loading.ServerModLoader.load(ServerModLoader.java:34) ~[neoforge-21.0.167-universal.jar%23352!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.Main.main(Main.java:124) ~[server-1.21-20240613.152323-srg.jar%23351!/:?] {re:classloading}
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?] {}
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
        at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.23.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:128) ~[loader-4.0.23.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonServerLaunchHandler.runService(CommonServerLaunchHandler.java:32) ~[loader-4.0.23.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.23.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%2362!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%2362!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%2362!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%2362!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%2362!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%2362!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%2362!/:?] {}
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}

### Describe the bug

During startup of the start.sh on Ubuntu Server it crashes.

After deleting Health Indicator TXF and Entity Model Features .jar server starts without problems.

### Steps to reproduce

1. Install Serverfile with ./serverinstall_124_12458
2. sh start.sh after installation
3. Accept EULA
4. sh start.sh again
5. Crash occurs

### Expected behaviour

Working server

**Comment by Gaz492** [comment]
This should be fixed now
