### ISSUE TITLE
FTB Unstable 1.21 Linux server fails to start

### ISSUE THREAD

**Issue by lovick** [FTBTeam/FTB-Modpack-Issues#5758]
### Modpack

FTB Unstable 1.21

### Modpack version

1.2.0

### Launcher

Server

### Has the pack been modified

No

### Log Files

[08:56:03] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.neoforged.fml.ModLoadingException: Loading errors encountered:
        - Extreme Sound Muffler (extremesoundmuffler) has failed to load correctly
          java.lang.IllegalArgumentException: class com.leobeliik.extremesoundmuffler.SoundMufflerNeoForge has no @SubscribeEvent methods, but register was called anyway.
          The event bus only recognizes listener methods that have the @SubscribeEvent annotation.

        at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.ModLoader.waitForFuture(ModLoader.java:281) ~[loader-4.0.23.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.ModLoader.dispatchParallelTask(ModLoader.java:244) ~[loader-4.0.23.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.ModLoader.constructMods(ModLoader.java:152) ~[loader-4.0.23.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:142) ~[loader-4.0.23.jar%2360!/:4.0] {}
        at TRANSFORMER/neoforge@21.0.167/net.neoforged.neoforge.internal.CommonModLoader.begin(CommonModLoader.java:49) ~[neoforge-21.0.167-universal.jar%23353!/:?] {re:classloading}
        at TRANSFORMER/neoforge@21.0.167/net.neoforged.neoforge.server.loading.ServerModLoader.load(ServerModLoader.java:34) ~[neoforge-21.0.167-universal.jar%23353!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.Main.main(Main.java:124) ~[server-1.21-20240613.152323-srg.jar%23352!/:?] {re:classloading}
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?] {}
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
        at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.23.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:128) ~[loader-4.0.23.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonServerLaunchHandler.runService(CommonServerLaunchHandler.java:32) ~[loader-4.0.23.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.23.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%2362!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%2362!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%2362!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%2362!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%2362!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%2362!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%2362!/:?] {}
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}

### Describe the bug

After installing the server, attempting to start the server leads to a crash. Confirmed with a fresh install as well as an upgrade to an existing install.

### Steps to reproduce

1. Install the Linux Server
2. Start the server

### Expected behaviour

Started server available to connect to

### Additional information

Slightly different error from issue #5750, as this error only popped up after that one was resolved.

**Comment by stevenliuxd** [comment]
Hey there! I ran into this exact issue. I did some digging and sources state that Extreme Sound Muffler is a client-side mod, so I deleted it from my server mods folder and it has been working for me since. Give that a shot and let me know!

**Comment by TheWolfNations** [comment]
Can confirm @stevenliuxd diagnosis is correct. Extreme Sound Muffler is a client-side mod, once removed the server starts fine

**Comment by Gaz492** [comment]
This looks to have been fixed, let us know if you run into any further issues.
