### ISSUE TITLE
[Bug]:  line 13:0 token recognition error at: '`' server files for ocean block 

### ISSUE THREAD

**Issue by JewelsArt** [FTBTeam/FTB-Modpack-Issues#578]
### Modpack

FTB OceanBlock

### Modpack version

1.10

### Log Files

"Do you agree to the Mojang EULA available at https://account.mojang.com/documents/minecraft_eula ?"
[y/n]
[Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/lookup/JndiLookup
[Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/pattern/MessagePatternConverter
[Log4jPatcher] [WARN]  Unable to find noLookups:Z field in org/apache/logging/log4j/core/pattern/MessagePatternConverter
2022-01-22 11:38:43,933 main WARN Advanced terminal features are not available in this environment
[11:38:44] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.20, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui]
[11:38:44] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_321 by Oracle Corporation
[11:38:44] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[11:38:44] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/timot/Desktop/Nouveau%20dossier%20(3)/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
[11:38:45] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 13:0 token recognition error at: '`'
Init CreativeCore coremods ...
[11:38:46] [main/ERROR] [mixin/]: Mixin config minetogether.mixins.json does not specify "minVersion" property
Exception in thread "main" [11:38:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
[11:38:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
[11:38:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
[11:38:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[11:38:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[11:38:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.ClassLoader.loadClass(Unknown Source)
[11:38:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.Class.forName0(Native Method)
[11:38:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.Class.forName(Unknown Source)
[11:38:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:67)
[11:38:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:70)
[11:38:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:59)
[11:38:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:196)
[11:38:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
[11:38:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
[11:38:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:195)
[11:38:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
[11:38:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.util.HashMap.forEach(Unknown Source)
[11:38:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
[11:38:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[11:38:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[11:38:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[11:38:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[11:38:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[11:38:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[11:38:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
Appuyez sur une touche pour continuer...

### Describe the bug

I had no issue installing server files from all the other modpacks, but i just can't seem to grasp the issue with OceanBlock's modpack, each time i run the start.bat file, it just runs theses codes, then shutdowns the server. 

### Steps to reproduce

1. https://feed-the-beast.com/modpack/ftb_oceanblock server files are here 
2. i download all the files
3. starter the start.bat

### Expected behaviour

werver doesn't work.

**Comment by nwageler** [comment]
I had same issue with Oceanblock 1.9.0 after updating Java to 1.8.0_321.  I found that reverting Java back to 1.8.0_311 resolved this.

**Comment by Raidobw2** [comment]
Yup, that is indeed one of the solutions. Java 8 Update 321 is causing issues, you have a few options:
Use Java 11 to start the server. You can get it from multiple sources, here's some of them:
Microsoft OpenJDK: https://docs.microsoft.com/en-us/java/openjdk/download#openjdk-11
Adoptium OpenJDK: https://adoptium.net/?variant=openjdk11&jvmVariant=hotspot

When you install it, make sure to take note where it will be installed. For example with Adoptium the files are at `C:\Program Files\Eclipse Adoptium`.
I then simply open the jdk folder for the version I want inside that location: `jdk-11.0.14.9-hotspot`.
Then I open the `bin` folder.
My path looks like this, and I simply append "\java.exe" to it on Windows for example.
`C:\Program Files\Eclipse Adoptium\jdk-11.0.14.9-hotspot\bin` + `\java.exe`
-> `C:\Program Files\Eclipse Adoptium\jdk-11.0.14.9-hotspot\bin\java.exe`.

Then I'll go into my server installation and Edit the start script. I'll edit `start.bat` on Windows for example.
My current script looks like:
![image](https://user-images.githubusercontent.com/17010632/150669636-9a14a132-b06e-48c9-978e-a3f9921934f1.png)

And I'll replace the `java.exe` with the path from earlier. It will look like this after. It is important to put that file path into some quotes, since the path contains a space.
![image](https://user-images.githubusercontent.com/17010632/150669690-4a17d912-c88e-4f80-8f08-e598fefb36ce.png)

Then save the file and double click the start script to start your server, and it should work well!

It is still possible to use Java 8 but since the old Java8u311 got archived and isn't as available as the Java 11 is, it's harder to get.
But if you want it you can get it from the Adoptium link above or from Oracle's archive for example https://www.oracle.com/in/java/technologies/javase/javase8u211-later-archive-downloads.html.

You can refer to any other Java version in the future by following the same pattern I've written here. You install a version, refer directly to it in the start script and that's it. Java versions change between Minecraft versions sometimes so this is knowledge you can reuse later.
Please close the issue if this resolved it for you, and cheers.

**Comment by quietust** [comment]
It should also be possible to use Java 8u51 which is bundled with Minecraft itself - I played through the entire pack with that version and never had any problems.
