### ISSUE TITLE
[Bug]: Java 8 update 321 causing game to crash  - update 30-1-2022 adoptium java works fine incl tested create A&B, no issues.

### ISSUE THREAD

**Issue by gzcwnk** [FTBTeam/FTB-Modpack-Issues#585]
### Modpack

FTB Endeavour

### Modpack version

1.8.0

### Log Files

https://paste.ee/p/3tqOk

### Describe the bug

Upgarded java and now FTB Endeavour 1.8.0 crashes.

[18:06:05] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.HashMap.forEach(Unknown Source)
[18:06:05] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
[18:06:05] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[18:06:05] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[18:06:05] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[18:06:05] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[18:06:05] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 13 more
[18:06:05] [main/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:37]: Exiting with -1
Process exited with code -1.

### Steps to reproduce

Update java
Try and start game

### Expected behaviour

game runs

**Comment by gzcwnk** [comment]
1.7.0 has the same issue.

**Comment by gzcwnk** [comment]
In fact enigmatica6 also

**Comment by Raidobw2** [comment]
Hi, Java 8 update 321 has issues allowing players to play the game, it's become incompatible. I'd recommend you use Java8u311 or Java8u312.
The simplest way currently would be to get the `jdk8u312-b07` from Adoptium. You can uninstall the other Java 8. https://adoptium.net/archive.html?variant=openjdk8&jvmVariant=hotspot
![image](https://user-images.githubusercontent.com/17010632/151111699-1a2d4549-3f3f-479c-9ac9-9aaaf8521beb.png)
Cheers and please close the issue if that solved it.

**Comment by bahaynes** [comment]
Seeing this on Oceanblock 1.11.0 as well.

**Comment by gzcwnk** [comment]
> Seeing this on Oceanblock 1.11.0 as well.

Its a java thing not a mod thing, follow as above and get adoptium 312, then no issues with two different modded games so far.
