### ISSUE TITLE
LogisticsPipes crafting request fails

### ISSUE THREAD

**Issue by mofumofluffy** [FTBTeam/FTB-Modpack-Issues#5932]
### Modpack

FTB Interactions Remastered

### Modpack version

1.3.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

---- Minecraft Crash Report ----

Time: 2024-10-10 03:51:38 JST
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: dummyInventory
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1817)
    at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NoSuchFieldError: dummyInventory
    at org.dv.minecraft.logisticsbridge.module.ModuleCrafterExt.addCrafting(ModuleCrafterExt.java:107)
    at logisticspipes.pipes.PipeLogisticsChassis.addCrafting(PipeLogisticsChassis.java:732)
    at logisticspipes.request.RequestTreeNode.getCrafters(RequestTreeNode.java:127)
    at logisticspipes.request.RequestTreeNode.checkCrafting(RequestTreeNode.java:413)
    at logisticspipes.request.RequestTreeNode.<init>(RequestTreeNode.java:82)
    at logisticspipes.request.RequestTreeNode.<init>(RequestTreeNode.java:57)
    at logisticspipes.request.RequestTree.<init>(RequestTree.java:44)
    at logisticspipes.request.RequestTree.request(RequestTree.java:179)
    at logisticspipes.request.RequestTree.request(RequestTree.java:204)
    at logisticspipes.request.RequestHandler.request(RequestHandler.java:50)
    at logisticspipes.network.packets.orderer.RequestSubmitPacket.processPacket(RequestSubmitPacket.java:31)
    at logisticspipes.network.PacketInboundHandler.inThreadProcessPacket(PacketInboundHandler.java:35)
    at logisticspipes.network.PacketInboundHandler.lambda$channelRead0$0(PacketInboundHandler.java:29)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 5 more

No Mixin Metadata is found in the Stacktrace.

### Describe the bug

Could not make order using recipe placed on Crafting Manager (added by LogisticsBridge)

### Steps to reproduce

1. Set recipe on Crafting Module
2. Insert to Crafting Manager
3. Set Result/Satellite Pipe appropriately
4. Send crafting request
5. No any action

### Expected behaviour

Message which either reject or accept request

### Screenshots

![2024-10-10_04 25 25](https://github.com/user-attachments/assets/9cae158f-6290-4d61-ae61-df49ab22bbc0)

### Additional information

Provider is placed in Void World and Machine placed in Compact Machine's dimension.
Both are chunk-loaded and connected through Logistics Inventory System Connector and surely connected, as interdimensional request (which just pull stock) works fine.
Crafting using Crafting Logistics Pipe works fine.
Crafting using Crafting Module inside Chassis (Mk1) works fine.

Recipe is Microprocessor (LV Best circuit) which send solder to extractor and other to assembler.
Upper machine is HV Circuit Assembler, other one is MV Extractor

**Comment by Delfayne** [comment]
Crafting Managers are currently known to be defective

**Comment by rlnt** [comment]
This is already being tracked here. https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5874
