### ISSUE TITLE
Middle-clicking the inventory of Industrial Foregoing machines causes all items in the block to delete. Including upgrades.

### ISSUE THREAD

**Issue by ipaqmaster** [FTBTeam/FTB-Modpack-Issues#5997]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.3.0

### Launcher

Prism

### Has the pack been modified

No

### Describe the bug

Middle clicking the inventory of a Mob Crusher results in it entirely deleting its held inventory, plus its installed upgrades. I was able to reproduce this twice by testing the case again after recreating those upgrades.

### Steps to reproduce

1. Put down a Mob Crusher
2. Put in an `Addon: Speed Tier 2` upgrade and a `Addon: Range Tier 12` upgrade
3. Let it kill something for an item to be placed in its storage inventory.
4. Middle-click the inventory and all items plus upgrade modules disappear.
5. Breaking the block does not reveal them. They get deleted during the sort.

### Expected behaviour

Either nothing to happen or inventory of the block to become sorted.

**Comment by Gaz492** [comment]
Notes for pack dev, just need to add the container to the inventory sorter blacklist in the inventorysorter-server.toml config
![](!skip)

**Comment by Raidobw2** [comment]
Inventory Sorter or some mod will spit an error when trying to run `/invsorter showlast`, but the blacklist will work.

This will fix it in the file Gaz mentioned:
```toml
#Inventory sorter blacklists
[blacklists]
	#Container blacklist
	containerBlacklist = ["titanium:addon_container"]
	#Slot type blacklist
	slotBlacklist = []

```

Client soft crash:

<details>

  <summary>Stacktrace</summary>

```

[09Nov2024 17:12:55.356] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: [NMX_R3GEN: Last container sorted: {0}]
[09Nov2024 17:12:55.360] [Netty Server IO #1/ERROR] [net.minecraft.network.Connection/]: Exception caught in connection
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:system_chat'
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:55) ~[client-1.21.1-20240808.144430-srg.jar%23447!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:14) ~[client-1.21.1-20240808.144430-srg.jar%23447!/:?]
	at TRANSFORMER/neoforge@21.1.74/net.neoforged.neoforge.network.filters.GenericPacketSplitter.encode(GenericPacketSplitter.java:104) ~[neoforge-21.1.74-universal.jar%23448!/:?]
	at TRANSFORMER/neoforge@21.1.74/net.neoforged.neoforge.network.filters.GenericPacketSplitter.encode(GenericPacketSplitter.java:39) ~[neoforge-21.1.74-universal.jar%23448!/:?]
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar%23114!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar%23120!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar%23120!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar%23120!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar%23120!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar%23114!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar%23120!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar%23120!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar%23120!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar%23120!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar%23120!/:4.1.97.Final]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection$2.write(Connection.java:528) ~[client-1.21.1-20240808.144430-srg.jar%23447!/:?]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar%23120!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar%23120!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar%23120!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar%23120!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar%23120!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar%23120!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar%23120!/:4.1.97.Final]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.doSendPacket(Connection.java:364) ~[client-1.21.1-20240808.144430-srg.jar%23447!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.lambda$sendPacket$12(Connection.java:359) ~[client-1.21.1-20240808.144430-srg.jar%23447!/:?]
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar%23115!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar%23115!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar%23115!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar%23120!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar%23115!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar%23115!/:4.1.97.Final]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: io.netty.handler.codec.EncoderException: Failed to encode: This value needs to be parsed as component translation{key='inventorysorter.commands.inventorysorter.showlast.message', args=[titanium:addon_container]}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.ByteBufCodecs$19.lambda$encode$1(ByteBufCodecs.java:311) ~[client-1.21.1-20240808.144430-srg.jar%23447!/:?]
	at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar%23106!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.ByteBufCodecs$19.encode(ByteBufCodecs.java:311) ~[client-1.21.1-20240808.144430-srg.jar%23447!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.ByteBufCodecs$19.encode(ByteBufCodecs.java:301) ~[client-1.21.1-20240808.144430-srg.jar%23447!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$8.encode(StreamCodec.java:156) ~[client-1.21.1-20240808.144430-srg.jar%23447!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:97) ~[client-1.21.1-20240808.144430-srg.jar%23447!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:87) ~[client-1.21.1-20240808.144430-srg.jar%23447!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:53) ~[client-1.21.1-20240808.144430-srg.jar%23447!/:?]
	... 31 more
[09Nov2024 17:12:55.400] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: NMX_R3GEN lost connection: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:system_chat'
[09Nov2024 17:12:55.401] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: NMX_R3GEN left the game

```

</details>

**Comment by Shadowfire86** [comment]
This applies to multiple Industrial Foregoing machines. Still happening on 1.4.1 on Laser Drill as well.

**Comment by ipaqmaster** [comment]
Yeah. I had been meaning to update the title to reflect that

**Comment by ArtpokeBr** [comment]
Doesn't seem to be happening anymore, and also just to make sure I've added the blacklist that @Raidobw2 mentioned :)
