### ISSUE TITLE
ftb-presents-direwolf20-11 v1.4.0 crashes on dedicated Linux box with ferritcore mixin

### ISSUE THREAD

**Issue by sandalle** [FTBTeam/FTB-Modpack-Issues#6110]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.4.0

### Launcher

Server

### Has the pack been modified

No

### Log Files

https://pste.ch/togatixika.md

### Describe the bug

After updating my server (and saying "y" to any cleanup/overwrites from the installer), I get this crash.
```
[07Nov2024 11:12:25.669] [main/FATAL] [mixin/]: Mixin apply for mod ferritecore failed ferritecore.fastmap.mixin.json:FastMapStateHolderMixin from mod ferritecore -> net.minecraft.world.level.block.state.StateHolder: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/world/level/block/state/StateHolder::getNeighborFromFastMap with priority 1000 cannot inject into net/minecraft/world/level/block/state/StateHolder::setValue(Lnet/minecraft/world/level/block/state/properties/Property;Ljava/lang/Comparable;)Ljava/lang/Object; merged by ca.spottedleaf.moonrise.mixin.blockstate_propertyaccess.StateHolderMixin with priority 1000 [INJECT_PREPARE Applicator Phase -> ferritecore.fastmap.mixin.json:FastMapStateHolderMixin from mod ferritecore -> Prepare Injections -> redirect$bof000$ferritecore$getNeighborFromFastMap(Lcom/google/common/collect/Table;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; -> Prepare ->  -> { target: setValue(Lnet/minecraft/world/level/block/state/properties/Property;Ljava/lang/Comparable;)Ljava/lang/Object; }]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/world/level/block/state/StateHolder::getNeighborFromFastMap with priority 1000 cannot inject into net/minecraft/world/level/block/state/StateHolder::setValue(Lnet/minecraft/world/level/block/state/properties/Property;Ljava/lang/Comparable;)Ljava/lang/Object; merged by ca.spottedleaf.moonrise.mixin.blockstate_propertyaccess.StateHolderMixin with priority 1000 [INJECT_PREPARE Applicator Phase -> ferritecore.fastmap.mixin.json:FastMapStateHolderMixin from mod ferritecore -> Prepare Injections -> redirect$bof000$ferritecore$getNeighborFromFastMap(Lcom/google/common/collect/Table;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; -> Prepare ->  -> { target: setValue(Lnet/minecraft/world/level/block/state/properties/Property;Ljava/lang/Comparable;)Ljava/lang/Object; }]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:312) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar%2375!/:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:248) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar%2375!/:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:475) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar%2375!/:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1407) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar%2375!/:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:731) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar%2375!/:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:315) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar%2375!/:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar%2375!/:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar%2375!/:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar%2375!/:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar%2375!/:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar%2375!/:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar%2375!/:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar%2375!/:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-11.0.4.jar%2362!/:11.0.4+main.d2e20e43]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:94) ~[modlauncher-11.0.4.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-11.0.4.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:57) ~[modlauncher-11.0.4.jar%2362!/:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:190) ~[securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:311) ~[securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:214) ~[securejarhandler-3.0.8.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source) ~[?:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:196) ~[securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:311) ~[securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:214) ~[securejarhandler-3.0.8.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.Bootstrap.bootStrap(Bootstrap.java:45) ~[server-1.21.1-20240808.144430-srg.jar%23376!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.Main.main(Main.java:120) ~[server-1.21.1-20240808.144430-srg.jar%23376!/:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.31.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:128) ~[loader-4.0.31.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonServerLaunchHandler.runService(CommonServerLaunchHandler.java:32) ~[loader-4.0.31.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.31.jar%2360!/:4.0]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%2362!/:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?]
```

### Steps to reproduce

1. Have a working 1.3.0 install
2. Download and run https://api.feed-the-beast.com/v1/modpacks/public/modpack/126/12591/server/linux to update
3. Answer 'y' to all prompts
4. Try and start the server

### Expected behaviour

Server should start without a crash

### Additional information

OS: Linux Mint 21.3 Virginia x86_64

**Comment by Gaz492** [comment]
Could you try deleting the config folder then run the server installer again?
It looks like one of the configs did not get updated correctly.

**Comment by sandalle** [comment]
Removed config/ folder and re-ran the setup script:
```
Where would you like to install the server? [current directory]
Path . already exists - still want to install? (y/n) [y]
Continuing will install FTB Presents Direwolf20 1.21 version 1.4.0 as an update. Do you wish to continue? (y/n) [y]                                                           
...
2024/11/07 12:05:24  This install has 0 files changed, 0 new files and 0 deleted files
There are [] failed checksums on already existing files. This may be as a result of manual config changes. Do you wish to overwrite them with the files from the update? (y/n) [y]
...
2024/11/07 12:07:52  [816/821] Error downloading https://dist.modpacks.ch/modpacks/7/FTB%20Presents%20Direwolf20%201.21-1.4.0/kubejs/server_scripts/189bc6fa2101d02aa8449f999a628dce253dd2ab: Checksums did not match for kubejs/server_
scripts/additions.js.
Expected: 189bc6fa2101d02aa8449f999a628dce253dd2ab
Got: f1acf54d1f70ff10e477f740318bea7b4e02f93c
*sha1.digest
The server installed successfully
You can delete this installer file now if you wish
2024/11/07 12:08:59 Downloaded 818 successful, 1 failed, 0 incomplete.
Some downloads failed. Would you like to continue anyway? (y/n) [y] n
```
Re-ran it again, sometimes I get checksum failures on downloaded files, I'm not sure why, so I just re-run the installer until it reports no errors, and didn't see the checksum failure this time:
```
The server installed successfully
You can delete this installer file now if you wish
2024/11/07 12:12:05 Downloaded 131 successful, 0 failed, 0 incomplete.
2024/11/07 12:12:06  Installed!
minecraft@tendriculous:~/servers/ftb-
```

Some of the configs (such as for Waystones) are missing until I run the server at least once. These are the config files that don't exist after installation until the world has been created and run:
```
$ diff -q config.orig config | grep Only
Only in config: market_categories
Only in config: market_presets
Only in config: waystones-common.toml
```

After getting a clean config/ folder, my server is able to start and users can connect, thanks! :)

**Comment by dalgrim** [comment]
I have this same issue. This is not a one-off for the OP. 
Same failed download issue, and same server start failure on ferritecore mixin.

Downgrading to 130 allows it to start. someone needs to review the upgrade serverinstall script.
