### ISSUE TITLE
java.lang.NullPointerException when Adding Improved Coke Oven to the Calculator

### ISSUE THREAD

**Issue by MaMilaCan** [FTBTeam/FTB-Modpack-Issues#6281]
### Modpack

FTB Interactions Remastered

### Modpack version

1.1.0 -> 1.10.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

https://mclo.gs/wLXRyRa

---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// Hey, that tickles! Hehehe!
Time: 2024-11-27 20:04:10 CET
Description: Rendering screen
java.lang.NullPointerException: Rendering screen
    at me.towdium.jecalculation.utils.Utilities.getModName(Utilities.java:84)
    at me.towdium.jecalculation.data.label.labels.LItemStack.getToolTip(LItemStack.java:195)
    at me.towdium.jecalculation.gui.widgets.WLabel.onTooltip(WLabel.java:77)
    at me.towdium.jecalculation.gui.widgets.WContainer.lambda$onTooltip$4(WContainer.java:75)
    at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
    at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
    at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
    at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
    at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:516)
    at me.towdium.jecalculation.gui.widgets.WContainer.onTooltip(WContainer.java:75)
    at me.towdium.jecalculation.gui.JecaGui.drawScreen(JecaGui.java:252)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1124)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:5614)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
No Mixin Metadata is found in the Stacktrace.

[12:30:07] [Client thread/WARN] [AE2:C]: item was null for paint_ball ( paint_ball.brown )!
[12:30:07] [Client thread/ERROR] [FML]: Parsing error loading recipe appliedenergistics2:tools/paintballs_brown
com.google.gson.JsonSyntaxException: Got a null item for paint_ball ( paint_ball.brown ). This should never happen!
	at appeng.recipes.factories.recipes.PartRecipeFactory.getPart(PartRecipeFactory.java:88) ~[PartRecipeFactory.class:?]
	at appeng.recipes.factories.recipes.PartRecipeFactory.getResult(PartRecipeFactory.java:70) ~[PartRecipeFactory.class:?]
	at appeng.recipes.factories.recipes.PartRecipeFactory.getResult(PartRecipeFactory.java:63) ~[PartRecipeFactory.class:?]
	at appeng.recipes.factories.recipes.PartRecipeFactory.shapedFactory(PartRecipeFactory.java:155) ~[PartRecipeFactory.class:?]
	at appeng.recipes.factories.recipes.PartRecipeFactory.parse(PartRecipeFactory.java:54) ~[PartRecipeFactory.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:416) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:723) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:833) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:688) ~[CraftingHelper.class:?]
	at java.util.ArrayList.forEach(ArrayList.java:1259) [?:1.8.0_392]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:633) [CraftingHelper.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.init(Minecraft.java:535) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:5601) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_392]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_392]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_392]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_392]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[12:30:07] [Client thread/WARN] [AE2:C]: item was null for paint_ball ( paint_ball.magenta )!
[12:30:07] [Client thread/ERROR] [FML]: Parsing error loading recipe appliedenergistics2:tools/paintballs_magenta
com.google.gson.JsonSyntaxException: Got a null item for paint_ball ( paint_ball.magenta ). This should never happen!
	at appeng.recipes.factories.recipes.PartRecipeFactory.getPart(PartRecipeFactory.java:88) ~[PartRecipeFactory.class:?]
	at appeng.recipes.factories.recipes.PartRecipeFactory.getResult(PartRecipeFactory.java:70) ~[PartRecipeFactory.class:?]
	at appeng.recipes.factories.recipes.PartRecipeFactory.getResult(PartRecipeFactory.java:63) ~[PartRecipeFactory.class:?]
	at appeng.recipes.factories.recipes.PartRecipeFactory.shapedFactory(PartRecipeFactory.java:155) ~[PartRecipeFactory.class:?]
	at appeng.recipes.factories.recipes.PartRecipeFactory.parse(PartRecipeFactory.java:54) ~[PartRecipeFactory.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:416) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:723) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:833) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:688) ~[CraftingHelper.class:?]
	at java.util.ArrayList.forEach(ArrayList.java:1259) [?:1.8.0_392]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:633) [CraftingHelper.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747) [Loader.class:?]

### Describe the bug

Open a newly crafted Calculator and search in NEI for "coke" and drag and drop the "Improved Coke Oven" into the top field of the Calculator -> Crash

### Steps to reproduce

- Open a newly crafted Calculator 
- search in NEI for "coke"
- drag and drop the "Improved Coke Oven" into the top field of the Calculator -
- Crash

### Expected behaviour

The Calculator can calculate the Items for the Improved Coke oven

**Comment by ArtpokeBr** [comment]
Just to be sure, you are in 1.10.0 and not in 1.1.0 right?

**Comment by MaMilaCan** [comment]
I just found that the Calculator has a warning in the tooltip
I guess we can close this now.


![grafik](https://github.com/user-attachments/assets/c37050ed-f4e3-4491-9999-40f0f4160e63)
