### ISSUE TITLE
Ars Nouveau Storage Lectern Crash

### ISSUE THREAD

**Issue by balu100** [FTBTeam/FTB-Modpack-Issues#6282]
### Modpack

FTB Skies Expert

### Modpack version

1.10.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

https://pastebin.com/21bdfNDN

### Describe the bug

I've been constantly crashing when shift-taking items from the lectern. The weird part is that it's not happening every time, only about every third time.

### Steps to reproduce

Take stacks of items(specific?) from the Ars Nouveau Lectern

### Expected behaviour

do not crash

**Comment by balu100** [comment]
Additional info: It happens semi-constantly when taking out all items. For example, if there are 65 items and you shift-click to take them, it won't crash. However, if you try to take, let's say, 36 items, it will.

**Comment by nikoflame** [comment]
This is happening to me, too. Here are many crash reports I've encountered
[crash-2024-12-03_12.26.51-client.txt](https://github.com/user-attachments/files/17999995/crash-2024-12-03_12.26.51-client.txt)
[crash-2024-12-03_12.47.04-client.txt](https://github.com/user-attachments/files/17999996/crash-2024-12-03_12.47.04-client.txt)
[crash-2024-12-03_13.20.02-client.txt](https://github.com/user-attachments/files/17999997/crash-2024-12-03_13.20.02-client.txt)
[crash-2024-12-03_13.30.01-client.txt](https://github.com/user-attachments/files/17999998/crash-2024-12-03_13.30.01-client.txt)
[crash-2024-12-03_13.36.27-client.txt](https://github.com/user-attachments/files/17999999/crash-2024-12-03_13.36.27-client.txt)
[crash-2024-12-03_14.08.36-client.txt](https://github.com/user-attachments/files/18000000/crash-2024-12-03_14.08.36-client.txt)
[crash-2024-12-03_14.18.15-client.txt](https://github.com/user-attachments/files/18000001/crash-2024-12-03_14.18.15-client.txt)

**Comment by badookey** [comment]
I found some success by modifying 'flower_doubling.json' (for me this is C:\Users\XXX\AppData\Local\.ftba\instances\ftb skies expert\config\flower_doubling) and modifying "show_Doubling_Chance_Tolltips" and "show_Fertilizer_Multiplyer_on_Tooltips" to false.

My entire file looks like
```
{
  "#Doubling_Chance": "Set the Doubling Chance for each list.",
  "show_Doubling_Chance_Tolltips": false,
  "#show_Fertilizers": "Shows which items count as fertilizer in the flower Tooltips.",
  "show_Fertilizers": true,
  "flower_List_1_Doubling_Chance": 100,
  "flower_List_2_Doubling_Chance": 66,
  "flower_List_3_Doubling_Chance": 33,
  "flower_List_4_Doubling_Chance": 0.01,
  "#Fertilizer_Multi": "Tells how often something is doubled.",
  "show_Fertilizer_Multiplyer_on_Tooltips": false,
  "fertilizer_multi": 1
}
```

**Comment by JayTee36** [comment]
I've found that this will only occur if you shift click the last remaining item(s)  from a Lectern ie. anything less than a stack. I'm not sure about non-stacking/NBT items though.

**Comment by badookey** [comment]
> I found some success by modifying 'flower_doubling.json' (for me this is C:\Users\XXX\AppData\Local.ftba\instances\ftb skies expert\config\flower_doubling) and modifying "show_Doubling_Chance_Tolltips" and "show_Fertilizer_Multiplyer_on_Tooltips" to false.


Can confirm that I did not encounter the bug again after these changes until today updating FTB skies from v1.10.0 to v1.11.0. The update seems to re-write changed config, but I just enacted the same changes and it seems gone again now.

> I've found that this will only occur if you shift click the last remaining item(s) from a Lectern ie. anything less than a stack. I'm not sure about non-stacking/NBT items though.
> 
>     * edit - Same issue for NBT items as well.

I suspect it's because ars' lectern displays an item with '0' in it's stack when you shift click the last remaining item, and reading the crash logs it says the flowerdoubling plugin is trying to write a tooltip but has an index out of bounds exception

```
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?] {}
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[?:?] {}
	at jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[?:?] {}
	at java.util.Objects.checkIndex(Unknown Source) ~[?:?] {re:mixin}
	at java.util.ArrayList.get(Unknown Source) ~[?:?] {re:mixin}
	at com.blackdragonfire.flowerdoubling.procedures.ItemTooltipsProcedure.execute(ItemTooltipsProcedure.java:145) ~[flower_doubling_1.19.2-1.2.0.jar%23654!/:?] {re:classloading}
```

I'm fairly confident that disabling these tooltips will resolve this issue for anyone else
