### ISSUE TITLE
[net.creeperhost.creeperlauncher.install.tasks.DownloadTask]: Trying to download from https://piston-data.mojang.com/v1/objects/30c73b1c5da787909b2f73340419fdf13b9def88/client.jar..

### ISSUE THREAD

**Issue by flybytech-prog** [FTBTeam/FTB-Modpack-Issues#6321]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.5.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

[11:36:10] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.api.handlers.instances.LaunchInstanceHandler]: Preparing instance for launch...
[11:36:10] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.pack.Instance]: Resetting launcher..
[11:36:10] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.pack.Instance]: Polling version manifest.
[11:36:10] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.data.modpack.ModpackManifest]: Querying Modpack version manifest: https://api.feed-the-beast.com/v1/modpacks/public/modpack/126
[11:36:10] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.data.modpack.ModpackVersionManifest]: Querying Modpack version manifest: https://api.feed-the-beast.com/v1/modpacks/public/modpack/126/100001
[11:36:11] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.pack.Instance]: Scanning instance.
[11:36:11] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.pack.Instance]: Adding start/shutdown tasks..
[11:36:11] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.pack.Instance]: Handing off to launcher..
[11:36:11] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.pack.InstanceLauncher]: Attempting to launch instance FTB Presents Direwolf20 1.21(6909efc4-e1ae-4ae8-b6a2-e2483741bbd1)
[11:36:11] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.pack.InstanceLauncher]: Setting phase: INITIALIZING
[11:36:11] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]: Downloading file C:\Users\Soul\AppData\Local\.ftba\bin\support-meta.json..
[11:36:11] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]: Trying to download from https://api.feed-the-beast.com/v1/modpacks/public/helpers/meta..
[11:36:11] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]:   File downloaded.
[11:36:11] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]: Downloading file E:\FTB\Instances\ftb presents direwolf20 121\log4jfixer.jar..
[11:36:11] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]:  File validated.
[11:36:11] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]: Downloading file E:\FTB\Instances\ftb presents direwolf20 121\serialization.jar..
[11:36:11] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]:  File validated.
[11:36:11] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]: Downloading file E:\FTB\Instances\ftb presents direwolf20 121\cfmalwarescanner.jar..
[11:36:11] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]:  File validated.
[11:36:11] [Instance Launcher 0/INFO] [net.covers1624.jdkutils.JdkInstallationManager]: Validating java installations.
[11:36:13] [Instance Launcher 0/INFO] [net.covers1624.jdkutils.JdkInstallationManager]: Recovered installation in C:\Users\Soul\AppData\Local\.ftba\bin\runtime\OpenJDK21U-jre_x64_windows_hotspot_21.0.4_7
[11:36:13] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.pack.InstanceLauncher]: Java home: C:\Users\Soul\AppData\Local\.ftba\bin\runtime\OpenJDK21U-jre_x64_windows_hotspot_21.0.4_7\jdk-21.0.4+7-jre
[11:36:13] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.pack.InstanceLauncher]: Java home: C:\Users\Soul\AppData\Local\.ftba\bin\runtime\OpenJDK21U-jre_x64_windows_hotspot_21.0.4_7\jdk-21.0.4+7-jre
[11:36:13] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.pack.InstanceLauncher]: Java home: file:///C:/Users/Soul/AppData/Local/.ftba/bin/runtime/OpenJDK21U-jre_x64_windows_hotspot_21.0.4_7/jdk-21.0.4+7-jre/
[11:36:13] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.pack.InstanceLauncher]: Java home: file:///C:/Users/Soul/AppData/Local/.ftba/bin/runtime/OpenJDK21U-jre_x64_windows_hotspot_21.0.4_7/jdk-21.0.4+7-jre/
[11:36:13] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.pack.InstanceLauncher]: Java executable: C:\Users\Soul\AppData\Local\.ftba\bin\runtime\OpenJDK21U-jre_x64_windows_hotspot_21.0.4_7\jdk-21.0.4+7-jre\bin\javaw.exe
[11:36:13] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.pack.InstanceLauncher]: Java executable: C:\Users\Soul\AppData\Local\.ftba\bin\runtime\OpenJDK21U-jre_x64_windows_hotspot_21.0.4_7\jdk-21.0.4+7-jre\bin\javaw.exe
[11:36:13] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.pack.InstanceLauncher]: Java executable: file:///C:/Users/Soul/AppData/Local/.ftba/bin/runtime/OpenJDK21U-jre_x64_windows_hotspot_21.0.4_7/jdk-21.0.4+7-jre/bin/javaw.exe
[11:36:13] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.pack.InstanceLauncher]: Java executable: file:///C:/Users/Soul/AppData/Local/.ftba/bin/runtime/OpenJDK21U-jre_x64_windows_hotspot_21.0.4_7/jdk-21.0.4+7-jre/bin/javaw.exe
[11:36:13] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]: Downloading file C:\Users\Soul\AppData\Local\.ftba\bin\versions\version_manifest.json..
[11:36:13] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]: Trying to download from https://launchermeta.mojang.com/mc/game/version_manifest.json..
[11:36:13] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]:   File passed ETag/OnlyIfModified checks.
[11:36:13] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]:   File downloaded.
[11:36:13] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.pack.InstanceLauncher]: Preparing manifest neoforge-21.1.80
[11:36:13] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.minecraft.jsons.VersionListManifest]: Version neoforge-21.1.80 not found on remote list, trying locally.
[11:36:13] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.pack.InstanceLauncher]: Preparing manifest 1.21.1
[11:36:13] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.minecraft.jsons.VersionManifest]: Updating version manifest for '1.21.1' from 'https://piston-meta.mojang.com/v1/packages/f31393a7358b95693640aaa27b81d1d9f2cd808c/1.21.1.json'.
[11:36:13] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]: Downloading file C:\Users\Soul\AppData\Local\.ftba\bin\versions\1.21.1\1.21.1.json..
[11:36:13] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]: Trying to download from https://piston-meta.mojang.com/v1/packages/f31393a7358b95693640aaa27b81d1d9f2cd808c/1.21.1.json..
[11:36:14] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]:   File passed ETag/OnlyIfModified checks.
[11:36:14] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]:   File downloaded.
[11:36:14] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.pack.InstanceLauncher]: Updating assets..
[11:36:14] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.minecraft.jsons.AssetIndexManifest]: Updating AssetIndex Manifest for '17' from 'https://piston-meta.mojang.com/v1/packages/7cedb23305a218c4d1a58d27e7ad8a86ee495d48/17.json'.
[11:36:15] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.pack.InstanceLauncher]: Validating minecraft libraries...
[11:36:15] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.pack.InstanceLauncher]: Libraries validated!
[11:36:15] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.pack.InstanceLauncher]: Validating client download for 1.21.1
[11:36:15] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]: Downloading file C:\Users\Soul\AppData\Local\.ftba\bin\versions\neoforge-21.1.80\neoforge-21.1.80.jar..
[11:36:15] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]: Trying to download from https://piston-data.mojang.com/v1/objects/30c73b1c5da787909b2f73340419fdf13b9def88/client.jar..
[11:36:15] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]: Trying to download from https://piston-data.mojang.com/v1/objects/30c73b1c5da787909b2f73340419fdf13b9def88/client.jar..
[11:36:16] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]: Trying to download from https://piston-data.mojang.com/v1/objects/30c73b1c5da787909b2f73340419fdf13b9def88/client.jar..
[11:36:16] [Instance Launcher 0/WARN] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]: Download failed 3 times. Trying HTTP/1.1
[11:36:16] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]: Trying to download from https://piston-data.mojang.com/v1/objects/30c73b1c5da787909b2f73340419fdf13b9def88/client.jar..
[11:36:16] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]: Trying to download from https://piston-data.mojang.com/v1/objects/30c73b1c5da787909b2f73340419fdf13b9def88/client.jar..
[11:36:16] [Instance Launcher 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]: Trying to download from https://piston-data.mojang.com/v1/objects/30c73b1c5da787909b2f73340419fdf13b9def88/client.jar..
[11:36:17] [Instance Launcher 0/ERROR] [net.creeperhost.creeperlauncher.api.handlers.instances.LaunchInstanceHandler]: Failed to launch instance.
net.creeperhost.creeperlauncher.pack.InstanceLaunchException: Failed to prepare instance 'FTB Presents Direwolf20 1.21'(6909efc4-e1ae-4ae8-b6a2-e2483741bbd1).
	at net.creeperhost.creeperlauncher.pack.InstanceLauncher.prepareProcess(InstanceLauncher.java:515) ~[launcher-3bad3a9a29-all.jar:?]
	at net.creeperhost.creeperlauncher.pack.InstanceLauncher.launch(InstanceLauncher.java:153) ~[launcher-3bad3a9a29-all.jar:?]
	at net.creeperhost.creeperlauncher.pack.Instance.play(Instance.java:429) ~[launcher-3bad3a9a29-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.instances.LaunchInstanceHandler.lambda$handle$0(LaunchInstanceHandler.java:56) ~[launcher-3bad3a9a29-all.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: net.creeperhost.creeperlauncher.install.tasks.DownloadFailedException: Download failed.
Tried URL: 'https://piston-data.mojang.com/v1/objects/30c73b1c5da787909b2f73340419fdf13b9def88/client.jar' 6 times.
Try 0: java.io.IOException: FRAME_SIZE_ERROR: 6648417
  	at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:107)
  	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:618)
  	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
  	at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
  	at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
  	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
  	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  	at java.base/java.lang.Thread.run(Unknown Source)
  
Try 1: java.io.IOException: FRAME_SIZE_ERROR: 6648417
  	at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:107)
  	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:618)
  	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
  	at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
  	at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
  	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
  	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  	at java.base/java.lang.Thread.run(Unknown Source)
  
Try 2: java.io.IOException: FRAME_SIZE_ERROR: 6648417
  	at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:107)
  	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:618)
  	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
  	at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
  	at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
  	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
  	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  	at java.base/java.lang.Thread.run(Unknown Source)
  
Try 3: java.net.ProtocolException: Unexpected status line: eraft.pngPK   
  	at okhttp3.internal.http.StatusLine$Companion.parse(StatusLine.kt:80)
  	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
  	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
  	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at net.creeperhost.creeperlauncher.Constants.lambda$refreshHttpClient$1(Constants.java:115)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at net.covers1624.quack.net.okhttp.ThrottlerInterceptor.intercept(ThrottlerInterceptor.java:30)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at net.creeperhost.creeperlauncher.Constants.lambda$refreshHttpClient$0(Constants.java:113)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at net.covers1624.quack.net.okhttp.MultiHasherInterceptor.intercept(MultiHasherInterceptor.java:31)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
  	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
  	at net.creeperhost.creeperlauncher.install.tasks.DownloadTask.doRequest(DownloadTask.java:250)
  	at net.creeperhost.creeperlauncher.install.tasks.DownloadTask.execute(DownloadTask.java:144)
  	at net.creeperhost.creeperlauncher.pack.InstanceLauncher.validateClient(InstanceLauncher.java:597)
  	at net.creeperhost.creeperlauncher.pack.InstanceLauncher.prepareProcess(InstanceLauncher.java:381)
  	at net.creeperhost.creeperlauncher.pack.InstanceLauncher.launch(InstanceLauncher.java:153)
  	at net.creeperhost.creeperlauncher.pack.Instance.play(Instance.java:429)
  	at net.creeperhost.creeperlauncher.api.handlers.instances.LaunchInstanceHandler.lambda$handle$0(LaunchInstanceHandler.java:56)
  	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  	at java.base/java.lang.Thread.run(Unknown Source)
  
Try 4: java.net.ProtocolException: Unexpected status line: eraft.pngPK   
  	at okhttp3.internal.http.StatusLine$Companion.parse(StatusLine.kt:80)
  	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
  	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
  	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at net.creeperhost.creeperlauncher.Constants.lambda$refreshHttpClient$1(Constants.java:115)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at net.covers1624.quack.net.okhttp.ThrottlerInterceptor.intercept(ThrottlerInterceptor.java:30)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at net.creeperhost.creeperlauncher.Constants.lambda$refreshHttpClient$0(Constants.java:113)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at net.covers1624.quack.net.okhttp.MultiHasherInterceptor.intercept(MultiHasherInterceptor.java:31)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
  	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
  	at net.creeperhost.creeperlauncher.install.tasks.DownloadTask.doRequest(DownloadTask.java:250)
  	at net.creeperhost.creeperlauncher.install.tasks.DownloadTask.execute(DownloadTask.java:144)
  	at net.creeperhost.creeperlauncher.pack.InstanceLauncher.validateClient(InstanceLauncher.java:597)
  	at net.creeperhost.creeperlauncher.pack.InstanceLauncher.prepareProcess(InstanceLauncher.java:381)
  	at net.creeperhost.creeperlauncher.pack.InstanceLauncher.launch(InstanceLauncher.java:153)
  	at net.creeperhost.creeperlauncher.pack.Instance.play(Instance.java:429)
  	at net.creeperhost.creeperlauncher.api.handlers.instances.LaunchInstanceHandler.lambda$handle$0(LaunchInstanceHandler.java:56)
  	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  	at java.base/java.lang.Thread.run(Unknown Source)
  
Try 5: java.net.ProtocolException: Unexpected status line: eraft.pngPK   
  	at okhttp3.internal.http.StatusLine$Companion.parse(StatusLine.kt:80)
  	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
  	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
  	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at net.creeperhost.creeperlauncher.Constants.lambda$refreshHttpClient$1(Constants.java:115)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at net.covers1624.quack.net.okhttp.ThrottlerInterceptor.intercept(ThrottlerInterceptor.java:30)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at net.creeperhost.creeperlauncher.Constants.lambda$refreshHttpClient$0(Constants.java:113)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at net.covers1624.quack.net.okhttp.MultiHasherInterceptor.intercept(MultiHasherInterceptor.java:31)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
  	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
  	at net.creeperhost.creeperlauncher.install.tasks.DownloadTask.doRequest(DownloadTask.java:250)
  	at net.creeperhost.creeperlauncher.install.tasks.DownloadTask.execute(DownloadTask.java:144)
  	at net.creeperhost.creeperlauncher.pack.InstanceLauncher.validateClient(InstanceLauncher.java:597)
  	at net.creeperhost.creeperlauncher.pack.InstanceLauncher.prepareProcess(InstanceLauncher.java:381)
  	at net.creeperhost.creeperlauncher.pack.InstanceLauncher.launch(InstanceLauncher.java:153)
  	at net.creeperhost.creeperlauncher.pack.Instance.play(Instance.java:429)
  	at net.creeperhost.creeperlauncher.api.handlers.instances.LaunchInstanceHandler.lambda$handle$0(LaunchInstanceHandler.java:56)
  	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  	at java.base/java.lang.Thread.run(Unknown Source)
  

	at net.creeperhost.creeperlauncher.install.tasks.DownloadTask.execute(DownloadTask.java:168) ~[launcher-3bad3a9a29-all.jar:?]
	at net.creeperhost.creeperlauncher.pack.InstanceLauncher.validateClient(InstanceLauncher.java:597) ~[launcher-3bad3a9a29-all.jar:?]
	at net.creeperhost.creeperlauncher.pack.InstanceLauncher.prepareProcess(InstanceLauncher.java:381) ~[launcher-3bad3a9a29-all.jar:?]
	... 7 more
[11:38:29] [NanoHttpd Request Processor (#1)/INFO] [net.creeperhost.creeperlauncher.api.NanoHttpdWebsocketServer]: Connection to 127.0.0.1 closed null(null).
[11:38:29] [ForkJoinPool.commonPool-worker-3/INFO] [net.creeperhost.creeperlauncher.CreeperLauncher]: Cleaning up for shutdown
[11:38:29] [ForkJoinPool.commonPool-worker-3/INFO] [net.creeperhost.creeperlauncher.api.NanoHttpdWebsocketServer]: Gracefully stopping websocket.
[11:38:29] [ForkJoinPool.commonPool-worker-3/INFO] [net.creeperhost.creeperlauncher.api.NanoHttpdWebsocketServer]: Websocket stopped.
[11:38:29] [Thread-0/INFO] [net.creeperhost.creeperlauncher.CreeperLauncher]: Cleaning up for shutdown
[11:38:29] [Thread-0/INFO] [net.creeperhost.creeperlauncher.api.NanoHttpdWebsocketServer]: Gracefully stopping websocket.
[11:38:29] [Thread-0/INFO] [net.creeperhost.creeperlauncher.api.NanoHttpdWebsocketServer]: Websocket stopped.

### Describe the bug

Unable to launch Direwolf20 1.21 version 1.5. 
When launching it fails to download client.jar.

### Steps to reproduce

1. open FTB app
2. click on play button for Direwolf20 1.21 

### Expected behaviour

Error log is displayed with error above 

### Screenshots

![image](https://github.com/user-attachments/assets/000e5a59-d87f-4a46-9540-a97513280bd4)

**Comment by Saereth** [comment]
Mikey pushed an update to address this, should be sorted now

**Comment by Aroflamewing** [comment]
this is not solved, i'm still having this problem

**Comment by Aroflamewing** [comment]
This look familiar? I've been having this issue for weeks and you mark it as solved, fuckin really?
![error](https://github.com/user-attachments/assets/a49e4bab-2d6e-4564-83ea-293098d468a9)

**Comment by flybytech-prog** [comment]
> This look familiar? I've been having this issue for weeks and you mark it as solved, fuckin really? ![error](https://private-user-images.githubusercontent.com/192917218/398797606-a49e4bab-2d6e-4564-83ea-293098d468a9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4NDA1NTMsIm5iZiI6MTczNTg0MDI1MywicGF0aCI6Ii8xOTI5MTcyMTgvMzk4Nzk3NjA2LWE0OWU0YmFiLTJkNmUtNDU2NC04M2VhLTI5MzA5OGQ0NjhhOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMlQxNzUwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjJjM2NmNjZmYTVjZTViMWJiZmY0OWM5N2M3MjYzYjA1NjNhM2ExYzUwN2IyZDJjNTQ1ZmQ0MWUzZDRiNTc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ycR-Oa_fGenA2TkWXL0oMWxbkicoTMk548GWSfBfFvE)

If you are still having issues, try deleting the neoforge folders inside AppData\Local\.ftba\bin\versions. 

Even after they fixed it, it only started working for me once I deleted those neoforge folders and forced it to re-download.

**Comment by Aroflamewing** [comment]
Thank you, the folder purge worked.  I had tried repairing, uninstalling and restarting before reinstalling, doing the same with a full power off, all that crap countless times and no reply from devs.
