### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by AiMz911** [FTBTeam/FTB-Modpack-Issues#642]
### Modpack

FTB Oceanblock

### Modpack version

1.11.0

### Log Files

    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215685_b(AbstractBlock.java:545) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:losttrinkets.mixins.json:AbstractBlockStateMixin,pl:mixin:APP:roadrunner.mixins.json:ai.pathing.MixinAbstractBlockState,pl:mixin:APP:roadrunner.mixins.json:block.flatten_states.AbstractBlockStateMixin,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:AbstractBlockStateMixin,pl:mixin:A,pl:runtimedistcleaner:A}
    at me.jellysquid.mods.lithium.common.entity.movement.ChunkAwareBlockCollisionSweeper.getNextBlockCollision(ChunkAwareBlockCollisionSweeper.java:236) ~[roadrunner:1.3.0] {re:mixin,re:classloading}
    at me.jellysquid.mods.lithium.common.entity.movement.ChunkAwareBlockCollisionSweeper.getNextCollidedShape(ChunkAwareBlockCollisionSweeper.java:165) ~[roadrunner:1.3.0] {re:mixin,re:classloading}

### Describe the bug

when i join my server and takes a bit but after a few min the server will be closed and someone says It appears to be the Lithium mod ticking an entity.

### Steps to reproduce

i only wait a bit. my base is a bit large so idk :D

### Expected behaviour

idk i hope i can get help 

### Additional information

i ask my server hoster but there say i must report the bug from the modpack author

**Comment by Raidobw2** [comment]
Hello, would it be possible to attach the full crash report or log, preferably with a paste service such as https://paste.feed-the-beast.com/ ? Thank you
