### ISSUE TITLE
[Bug]: FTB Infinity evolved skyblock server crashes

### ISSUE THREAD

**Issue by Kakiking** [FTBTeam/FTB-Modpack-Issues#726]
### Modpack

FTB Infinity Evolved Skyblock

### Modpack version

latest version available

### Log Files

```
[kaki@Laptop ftb_infinity_evolved_skyblock]$ ./start.sh 
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 6 more
[kaki@Laptop ftb_infinity_evolved_skyblock]$ 
```

### Describe the bug

Server doesn't start.

### Steps to reproduce

1. Download the Server files
2. install the server
3. run start.sh
4. crash

### Expected behaviour

Server starting up.

### Additional information

OS: Manjaro Linux
Java Version: openjdk 17.0.3 2022-04-19

**Comment by Raidobw2** [comment]
Hi, please come to the FTB Discord for support, there's information you can use to solve this problem -> https://go.ftb.team/discord

This modpack will require fixing from us in the future since some mods are broken. The normal version is fine though.

If you join the FTB Discord and write `!olderjava` in the `#support` channel, you'll be given instructions by the Bot. That's the first error, which is you can never use Java 17 to start Minecraft 1.7.10. Java 17 didn't exist at the time.

I'll anticipate the next error, which is the broken mods. You'll have the fix written out for you in the `#infinity-evolved` channel, look in the pinned messages. Read carefully, there's a fix for client and server.

After that all should be fine and you'll be able to play. If you need more info I suggest asking in the `#support` channel, I'll give more attention to it in the next day in case you were to write something there or needed more help. If you manage to fix it with the information in the Discord (which you should), please close this issue and use the Discord for future support issues. Thanks!

**Comment by ProtazLV** [comment]
Hi! Where can I find the information thats referenced here. I want to host a FTB Infinity evolved skyblock expert mode local server.  The FTB discord doesnt have a #infinity-evolved channel anymore.
