### ISSUE TITLE
[Bug]: Brandon's Core, Extra Utilities 2

### ISSUE THREAD

**Issue by ChibiAsh** [FTBTeam/FTB-Modpack-Issues#730]
### Modpack

Stoneblock2

### Modpack version

1.22.0

### Log Files

[crash-2022-04-20_12.29.01-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8526145/crash-2022-04-20_12.29.01-client.txt)
[crash-2022-04-20_15.55.33-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8526146/crash-2022-04-20_15.55.33-client.txt)
[crash-2022-04-20_15.56.23-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8526147/crash-2022-04-20_15.56.23-client.txt)
[crash-2022-04-20_17.07.01-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8526148/crash-2022-04-20_17.07.01-client.txt)
[crash-2022-04-20_18.40.40-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8526149/crash-2022-04-20_18.40.40-client.txt)
[crash-2022-04-20_18.47.56-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8526150/crash-2022-04-20_18.47.56-client.txt)
[crash-2022-04-20_12.29.00-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8526151/crash-2022-04-20_12.29.00-client.txt)

### Describe the bug

Won't let me log into the server, crashed a while ago. Have since tried rejoining, restarting the modpack, restarting the app, next is uninstalling...

### Steps to reproduce

Clicking on my Private server running this. Won't load.

### Expected behaviour

I expected to log back into the server, instead I'm greeted with this error message

### Screenshots

![image](https://user-images.githubusercontent.com/55221238/164342821-b8753b7d-385d-4c28-abd4-92b97b1a8884.png)

**Comment by Raidobw2** [comment]
Hello, try reinstalling your client, it looks like it's missing some classes. Either it's a bug as it's stated in the crash log, or you're really missing those classes/mods.

Some builder wand from extra utilities is having an issue drawing ghost blocks I think. Try the "Diamond Wand" instead or other wands from Builder Wands mod
```
java.lang.RuntimeException: class com.brandon3055.draconicevolution.blocks.tileentity.TilePortalClient is missing a mapping! This is a bug!
    at net.minecraft.tileentity.TileEntity.writeInternal(TileEntity.java:78)
    at net.minecraft.tileentity.TileEntity.writeToNBT(TileEntity.java:69)
    at com.brandon3055.brandonscore.blocks.TileBCBase.writeToNBT(TileBCBase.java:232)
    at net.minecraftforge.common.util.BlockSnapshot.getTileNBT(BlockSnapshot.java:132)
    at net.minecraftforge.common.util.BlockSnapshot.<init>(BlockSnapshot.java:61)
    at net.minecraft.world.World.mayPlace(World.java:3176)
    at com.rwtema.extrautils2.compatibility.CompatHelper.canPlaceBlockHere(CompatHelper.java:51)
    at com.rwtema.extrautils2.items.ItemBuildersWand.checkAndAddBlocks(ItemBuildersWand.java:68)
    at com.rwtema.extrautils2.items.ItemSelectionWand.getPotentialBlocks(ItemSelectionWand.java:182)
    at com.rwtema.extrautils2.items.ItemSelectionWand.drawSelection(ItemSelectionWand.java:282)
```

If that doesn't work try moving your inventory outside of `world/playerdata` and try to join. Your inventory might be empty, in that case drop your player inventory file here and I'll fix it for you.

Let me know if something worked, even partially as long as you're able to join
