### ISSUE TITLE
[Bug]: FTB Direwolf dedicated server fails to start after 1.4.0 update

### ISSUE THREAD

**Issue by shindouj** [FTBTeam/FTB-Modpack-Issues#910]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.4.0

### Log Files

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 6/6/22, 9:52 PM
Description: Ticking block entity

java.lang.NoSuchMethodError: 'java.util.Collection com.hrznstudio.titanium.util.RecipeUtil.getRecipes(net.minecraft.world.level.Level, net.minecraft.world.item.crafting.RecipeType)'
	at com.buuz135.sushigocrafting.tile.machinery.FermentationBarrelTile.canStart(FermentationBarrelTile.java:78) ~[sushigocrafting-1.18.2-0.3.4.jar%23264!/:0.3.4] {re:classloading}
	at com.hrznstudio.titanium.component.progress.MultiProgressBarHandler.update(MultiProgressBarHandler.java:36) ~[titanium-1.18.2-3.5.5-37.jar%23276!/:3.5.5] {re:classloading}
	at com.hrznstudio.titanium.block.tile.ActiveTile.serverTick(ActiveTile.java:238) ~[titanium-1.18.2-3.5.5-37.jar%23276!/:3.5.5] {re:classloading,pl:runtimedistcleaner:A}
	at com.hrznstudio.titanium.block.tile.ActiveTile.serverTick(ActiveTile.java:76) ~[titanium-1.18.2-3.5.5-37.jar%23276!/:3.5.5] {re:classloading,pl:runtimedistcleaner:A}
	at com.hrznstudio.titanium.block.BasicTileBlock.lambda$getTicker$3(BasicTileBlock.java:80) ~[titanium-1.18.2-3.5.5-37.jar%23276!/:3.5.5] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[server-1.18.2-20220404.173914-srg.jar%23295!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[server-1.18.2-20220404.173914-srg.jar%23295!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:475) ~[server-1.18.2-20220404.173914-srg.jar%23295!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itshallnottick.mixins.json:EntityTickMixin,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:327) ~[server-1.18.2-20220404.173914-srg.jar%23295!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:botania_xplat.mixins.json:MixinServerLevel,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:wyml.mixins.json:AccessorServerLevel,pl:mixin:APP:wyml.mixins.json:MixinServerWorld,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[server-1.18.2-20220404.173914-srg.jar%23295!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:wyml.mixins.json:AccessorMinecraftServer,pl:mixin:APP:wyml.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23295!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23295!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:wyml.mixins.json:AccessorMinecraftServer,pl:mixin:APP:wyml.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23295!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:wyml.mixins.json:AccessorMinecraftServer,pl:mixin:APP:wyml.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23295!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:wyml.mixins.json:AccessorMinecraftServer,pl:mixin:APP:wyml.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}
```

### Describe the bug

After 1.4.0 upgrade server fails to start. This appears to be a regression within the Titanium mod, as rollbacking to previous known version (titanium-1.18.2-3.5.2-34.jar) causes the server to start correctly.

### Steps to reproduce

1. Install Direwolf20 1.18 1.3.1.
2. Start the server, generate the map.
3. Install Direwolf20 1.18 1.4.0.

### Expected behaviour

Server starts correctly.

### Additional information

Known Workaround: Rollback Titanium to version 3.5.2 (titanium-1.18.2-3.5.2-34.jar).

**Comment by JakeMoe** [comment]
I'm having this same error on my server.  Happened when I upgraded a copy of my 1.3.1 server, so I tried installing 1.4.0 fresh and copying world/, eula.txt, ops.json, server.properties, and whitelist.json to the fresh install, and had the same error.

```
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 6/6/22, 8:34 PM
Description: Ticking block entity

java.lang.NoSuchMethodError: 'java.util.Collection com.hrznstudio.titanium.util.RecipeUtil.getRecipes(net.minecraft.world.level.Level, net.minecraft.world.item.crafting.RecipeType)'
        at com.buuz135.sushigocrafting.tile.machinery.FermentationBarrelTile.canStart(FermentationBarrelTile.java:78) ~[sushigocrafting-1.18.2-0.3.4.jar%23262!/:0.3.4] {re:classloading}
        at com.hrznstudio.titanium.component.progress.MultiProgressBarHandler.update(MultiProgressBarHandler.java:36) ~[titanium-1.18.2-3.5.5-37.jar%23274!/:3.5.5] {re:classloading}
        at com.hrznstudio.titanium.block.tile.ActiveTile.serverTick(ActiveTile.java:238) ~[titanium-1.18.2-3.5.5-37.jar%23274!/:3.5.5] {re:classloading,pl:runtimedistcleaner:A}
        at com.hrznstudio.titanium.block.tile.ActiveTile.serverTick(ActiveTile.java:76) ~[titanium-1.18.2-3.5.5-37.jar%23274!/:3.5.5] {re:classloading,pl:runtimedistcleaner:A}
        at com.hrznstudio.titanium.block.BasicTileBlock.lambda$getTicker$3(BasicTileBlock.java:80) ~[titanium-1.18.2-3.5.5-37.jar%23274!/:3.5.5] {re:classloading}
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[server-1.18.2-20220404.173914-srg.jar%23293!/:?] {re:classloading}
        at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[server-1.18.2-20220404.173914-srg.jar%23293!/:?] {re:classloading}
        at net.minecraft.world.level.Level.m_46463_(Level.java:475) ~[server-1.18.2-20220404.173914-srg.jar%23293!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itshallnottick.mixins.json:EntityTickMixin,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:A}
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:327) ~[server-1.18.2-20220404.173914-srg.jar%23293!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:botania_xplat.mixins.json:MixinServerLevel,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:wyml.mixins.json:AccessorServerLevel,pl:mixin:APP:wyml.mixins.json:MixinServerWorld,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[server-1.18.2-20220404.173914-srg.jar%23293!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:wyml.mixins.json:AccessorMinecraftServer,pl:mixin:APP:wyml.mixins.json:MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23293!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23293!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:wyml.mixins.json:AccessorMinecraftServer,pl:mixin:APP:wyml.mixins.json:MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23293!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:wyml.mixins.json:AccessorMinecraftServer,pl:mixin:APP:wyml.mixins.json:MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23293!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:wyml.mixins.json:AccessorMinecraftServer,pl:mixin:APP:wyml.mixins.json:MixinMinecraftServer,pl:mixin:A}
        at java.lang.Thread.run(Unknown Source) [?:?] {}
```

**Comment by JakeMoe** [comment]
Looks like there's a bug report in the Titanium issue tracker: https://github.com/InnovativeOnlineIndustries/Titanium/issues/111
